element-hq/element-ios

- Vector/ViewController/RecentsViewController.m
The room notification "mute" button is displayed even if there is a "always notify" room rule.
> mute_room_notifications

- Vector/ViewController/MediaPickerViewController.m
- Vector/ViewController/MediaPickerViewController.xib
- Vector/Views/MediaAlbum/MediaAlbumTableCell.xib
- Enlarge the touch area of the 'Close' and 'Camera switch' button.
- Crop album thumbnail to fit the display box.
- Remove the thumbnail of 'Recently Deleted' album.
- Fix simultaneous asset selection. Only the first selected asset is considered.
- Fix multiple selfies capture. Only one selfie is captured at once.
> Media Picker: fix layout issues

- Vector.xcodeproj/project.pbxproj
- Vector/AppDelegate.h
- Vector/AppDelegate.m
- Vector/Vector.entitlements
- Vector/ViewController/DirectoryViewController.m
- Vector/ViewController/HomeViewController.h
- Vector/ViewController/HomeViewController.m
- Vector/ViewController/RoomViewController.m
Universal links are declared at:
https://vector.im/apple-app-site-association
The app currently supports a subset of possible vector.im links:
- links to room (id or room alias). ex: #/room/#freenode_#matrix:matrix.org
- links to permalinks. ex: #/room/!cURbafjkfsMDVwdRDQ:matrix.org/$1460364457773248cLoWe:matrix.org
Links not yet supported:
- 3PID invite to a room
- the next link in the registration process
- etc.
> Universal link: Enabled universal links declared at vector.im.

- Vector.xcodeproj/project.pbxproj
- Vector/AppDelegate.m
- Vector/Assets/en.lproj/Vector.strings
- Vector/Model/Room/RoomEmailInvitation.h
- Vector/Model/Room/RoomPreviewData.h
- Vector/Model/Room/RoomPreviewData.m
- Vector/ViewController/HomeViewController.h
- Vector/ViewController/HomeViewController.m
- Vector/ViewController/RoomViewController.h
- Vector/ViewController/RoomViewController.m
- Vector/Views/RoomTitle/PreviewRoomTitleView.h
- Vector/Views/RoomTitle/PreviewRoomTitleView.m
- Vector/Views/RoomTitle/RoomAvatarTitleView.m
[roomVC displayEmailInvitation] has been renamed to [roomVC displayRoomPreview] .
It display room preview from email invitation link or from a simple link to a room.
In the case of simple link, we try to get more info (room name, avatar, url) from the homeserver. There is **no preview on messages** yet.
> Connect the universal link management in AppDelegate to the preview or RoomVC 

- Vector/AppDelegate.h
- Vector/AppDelegate.m
- Vector/ViewController/RoomViewController.m
Use this method on in-app and from outside links.
> AppDelegate: Added fixURLWithSeveralHashKeys method to fix iOS NSURLs with several #

- Vector.xcodeproj/project.pbxproj
- Vector/Assets/en.lproj/Vector.strings
- Vector/Utils/Tools.h
- Vector/Utils/Tools.m
- Vector/ViewController/RoomMemberDetailsViewController.m
- Vector/ViewController/RoomParticipantsViewController.m
- Vector/Views/Contact/ContactTableViewCell.m
Changes:
- Members are sorted with the same algo as Vector web
- Use currently_active information 
- Remove (admin)
Note: Users presences are true only after logging in or resetting the cache. The issue is due to this lack in Matrix CS API: [Need a way to get all online users presences] (https://matrix.org/jira/browse/SPEC-397).
> Update room members list

- Vector/AppDelegate.h
- Vector/AppDelegate.m
- Vector/Utils/Tools.h
- Vector/Utils/Tools.m
- Vector/Vector.entitlements
- Vector/ViewController/RoomViewController.m
isUniversalLink and fixURLWithSeveralHashKeys methods have been moved from AppDelegate to  new Tools class.
This is Tools and only it that contains hardcoded "vector.im" and "www.vector.im" strings
> Manage www.vector.im urls as universal links

- Vector/Vector-Defaults.plist
- Vector/ViewController/AuthenticationViewController.m
Support automatic fallback to matrix.org HS for existing users.
> Authentication: Update the default login flow to the vector.im HS.

- Vector/ViewController/RoomViewController.m
- Vector/Views/RoomBubbleList/RoomOutgoingAttachmentBubbleCell.h
- Vector/Views/RoomBubbleList/RoomOutgoingAttachmentBubbleCell.m
- Vector/Views/RoomBubbleList/RoomOutgoingAttachmentWithoutSenderInfoBubbleCell.h
- Vector/Views/RoomBubbleList/RoomOutgoingAttachmentWithoutSenderInfoBubbleCell.m
#313 
This is done by showing a red-pink frame around the unsent media. Clicking on it display the action sheet to be able to resend it quickly.
> Improved images & videos sending failure UX

- Vector/ViewController/RoomViewController.m
Use the roomAliases field of RoomPreviewData. It contains either the aliases provided by MXPublicRoom or the aliases in the state of a room we are peeking in.
> Unable to join federated rooms #572

- Vector/Assets/en.lproj/Vector.strings
- Vector/ViewController/RoomViewController.m
- Vector/ViewController/SettingsViewController.m
This PR removes the following options from Settings > LABS:
- "Placing VoIP/Video calls" 
- "Conference Call"
The LABS section is now hidden because it is empty but the code to manage this section remains because there are new dangerous features to come.
> Make VoIP features enabled by default

- Vector/Utils/EventFormatter.m
> Until e2e is impl'd, encrypted msgs should be shown in the UI as unencryptable warning text 

- Vector/Categories/MXRoom+Vector.h
- Vector/Categories/MXRoom+Vector.m
- Vector/ViewController/RecentsViewController.m
- Vector/ViewController/RoomSettingsViewController.m
The web client defines 4 levels of notifications: 'All messages (loud)', 'All messages', 'Mentions only' and 'Mute'.
The ios client support only 2 modes: Mute / Unmute.
We update the client to map these 2 modes with the 4 new ones until a new design is defined to handle the 4 levels on mobile client:
- When a room is in 'Mute' or 'Mentions only mode', it is displayed as mute. Else it is unmute.
- When the user unmute a room, the room switches in 'All message mode'.
- When the user mute a room, the room switches in 'Mentions only' mode.
> Messages - Room notification modes.

- Vector/AppDelegate.m
#599
Maybe a bug in iOS 10 pre-releases. Use the workaround at http://stackoverflow.com/a/39419245 to make it work
> Tapping notifications doesn't take you to the right room in iOS 10

- Vector/Info.plist
I think this is all that is needed to fix issue #538. I can't test it because I am not a member of the Apple developer program but according to [this developer documentation](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html), we need to add this VoIP background mode so that the app can start on boot. According to the docs: `Apps with this key are automatically launched after system boot so that the app can reestablish VoIP services.`
> Allow Riot to autostart when phone boots, Fixes #538

- Vector/AppDelegate.m
- Vector/ViewController/ContactDetailsViewController.m
- Vector/ViewController/RoomMemberDetailsViewController.m
#715
Apply MatrixSDK changes (matrix-org/matrix-ios-sdk#158): Remove privateOneToOneRoomWithUserId: and privateOneToOneUsers (the developer must use the directRooms property instread).
> Converting existing rooms to/from DMs

- Vector/Assets/en.lproj/Vector.strings
- Vector/ViewController/RoomSettingsViewController.m
#723
- Prompt user before turning on the room encryption
- Check power level before displaying toggle button
> End-to-end encryption UI/UX

- Vector/AppDelegate.m
- Vector/ViewController/SettingsViewController.m
Once enabled, it is still not possible to disable it but do some cleaning in case of disabling in case we change our mind on this button.
> Crypto: Enable e2e by default

- Vector/Model/Search/FilesSearchCellData.m
Goes with https://github.com/matrix-org/matrix-ios-kit/pull/191
This might cause a file search view to use larger thumbnails than
it did previously, although I'm not actually sure this is wired up
anywhere. If it is, I'd rather find the place they're used and
switch it to use getThumbnailUrlForSize with the size it wants.
> Don't clobber thumbnail url on MXKAttachment

- Vector/ViewController/RoomViewController.m
Check whether the table view data source is set before laying out the subviews immediately.
> Should fix App crash on exception: "UITableView dataSource is not set".

- Vector/AppDelegate.m
if the contact book access is authorized.
Keep the app settings in case of logout (We don't want to reset the current `syncLocalContacts` flag on logout).
> Load the local contacts on first account creation,

- Vector/Assets/en.lproj/Vector.strings
- Vector/ViewController/ContactsTableViewController.m
#904
- Keep visible the Local contacts header even if no local contacts is displayed in order to keep visible the check box "Matrix user only".
> Improve the people invite screens

- Vector/Views/Authentication/AuthInputsView.m
> Bug Fix - Registration: support the dummy authentication flow.

- Vector/Assets/en.lproj/Vector.strings
- Vector/ViewController/RoomViewController.m
- Vector/ViewController/UsersDevicesViewController.m
As 2 buttons works better than 3 in MXKAlert, "Send Anyway" replaces the previous "Cancel" button. 
The end user can still "Cancel" the action but on the UsersDevicesViewController screen when he presses "Verify...".
> Warn unknown devices: Add a send anyway button.

- Riot/Categories/MXRoom+Vector.h
- Riot/Categories/MXRoom+Vector.m
- Riot/Model/Room/RoomPreviewData.m
- Riot/Model/RoomList/RecentCellData.m
- Riot/Model/RoomList/RecentsDataSource.m
- Riot/Model/Search/FilesSearchCellData.m
- Riot/ViewController/CallViewController.m
- Riot/Views/RoomList/RoomTableViewCell.m
- Riot/Views/RoomTitle/ExpandedRoomTitleView.m
- Riot/Views/RoomTitle/PreviewRoomTitleView.m
- Riot/Views/RoomTitle/RoomTitleView.m
- Riot/Views/RoomTitle/SimpleRoomTitleView.m
- Riot/Views/Search/MessagesSearchResultAttachmentBubbleCell.m
- Riot/Views/Search/MessagesSearchResultTextMsgBubbleCell.m
#1044
Improvements:
- If the room has only two members, use the avatar of the second member even if this member is invited.
- The plain solid circle (without initial) is used only for an "empty room" without display name (We name "empty room" a room in which the current user is the only active member).
> Bug Fix - default room avatar for an empty room should not be your own face

- Riot/Assets/en.lproj/Vector.strings
- Riot/Base.lproj/Main.storyboard
- Riot/ViewController/CallViewController.m
- Riot/ViewController/RoomViewController.m
- Riot/ViewController/UsersDevicesViewController.h
- Riot/ViewController/UsersDevicesViewController.m
#1058 
Placing and answering a call when there are unknown devices in the room have now the same UX as sending a message in the same condition.
The same alert and the same view are displayed.
In the alert, rather than "Send anyway", we use the strings "Call anyway" and "Answer anyway".
> BF: Unknown devices modal from calling page is different that room page one

- Riot/Model/Room/RoomDataSource.m
(#1129 - 2)
By simplifying the way how the last message cell is computed
> Room summary: fix "No timestamp on last bubble"

- Riot/ViewController/RecentsViewController.m
- Bug fix the last section header was missing in the sticky headers of the top.
- Handle tap gesture on the sticky headers
- Bug Fix: the first sticky header of the bottom container is sometimes cropped.
- Bug Fix: the sticky headers display failed on screen rotation.
> Prepare UX rework

- Riot/Assets/en.lproj/Vector.strings
- Riot/Model/RoomList/PublicRoomsDirectoryDataSource.h
- Riot/Model/RoomList/PublicRoomsDirectoryDataSource.m
- Riot/Model/RoomList/RecentsDataSource.m
- Riot/Model/RoomList/UnifiedSearchRecentsDataSource.m
- Riot/Riot-Defaults.plist
- Riot/ViewController/DirectoryServerPickerViewController.h
- Riot/ViewController/DirectoryServerPickerViewController.m
- Riot/ViewController/RoomsViewController.m
- Riot/Views/Directory/DirectoryServerTableViewCell.m
and add a roomDirectoryServers option to Riot-Defaults.plist to add custom homeservers.
Currently only matrix.org is added. That means if a user is from a random HS, he will always be able to list public rooms from the matrix.org HS.
Other changes:
- Fix a bug that paginated public rooms every time we switch to the rooms tab.
- After new directory selection, focus on the directory section.
> List user hs directories

- Riot/AppDelegate.m
`CallViewController` is dangling in the memory even if it was dismissed. The reason of this are `updateStatusTimer`, `roomDidFlushDataNotificationObserver`, `audioSessionRouteChangeNotificationObserver` and `roomListener` which prevent it from being dismissed if they weren't reset as part of dismissing process.  To handle this situation we just need to call `destroy` method in appropriate place in the `AppDelegate`.
> Fix dangling in the memory CallViewController

- Riot/ViewController/MediaPickerViewController.m
https://github.com/vector-im/riot-ios/issues/1252
Release objects on the same thread they have been created. This avoids race conditions on retry.
> Fix Crash in MediaPickerViewController

- Riot/Assets/en.lproj/Vector.strings
- Riot/Model/Contact/ContactsDataSource.m
- Riot/ViewController/ContactsTableViewController.m
- Riot/ViewController/PeopleViewController.m
- Make the permission popup display again (it appears when the user goes into the people tab)
- Display "You didn't allow Riot to access your local contacts" instead of "No local contacts" when the user has denied the phonebook access permission
> Contact permission

- Riot/ViewController/RoomViewController.m
Set it to the current read receipt position by default
> Initialise the read marker if it does not exist yet.

- Riot/ViewController/RoomViewController.m
This avoids that the indicator view hides the text input.
> RoomVC: Make the activity indicator follow the keyboard

- Riot/Base.lproj/Main.storyboard
https://github.com/matrix-org/riot-ios-rageshakes/issues/39
It happened when selecting "Start Chat" from the RoomsVC. Fixed by a missing segue.
> Fix Crash after hitting create button

- Riot/Model/Contact/ContactsDataSource.m
https://github.com/matrix-org/riot-ios-rageshakes/issues/36
Do not call this method from another thread than main to avoid race conditions within MXKContactManager queues.
This does not affect performance on the UI. CPU eating processing seems to be in the for-loops in the block.
> Fix crash in [MXKContactManager localContactsSplitByContactMethod]

- Riot/Model/Room/RoomBubbleCellData.m
- Riot/Model/Room/RoomDataSource.m
https://github.com/vector-im/riot-ios/issues/657
Do not call [AvatarGenerator imageFromText:withBackgroundColor:] outside main thread.
> Fix App crashes on [AvatarGenerator imageFromText:withBackgroundColor:]

- Riot.xcodeproj/project.pbxproj
- Riot/Model/Room/RoomBubbleCellData.h
- Riot/Model/Room/RoomBubbleCellData.m
- Riot/Model/Room/RoomDataSource.m
- Riot/ViewController/RoomViewController.m
- Riot/Views/RoomBubbleList/RoomEmptyBubbleCell.h
- Riot/Views/RoomBubbleList/RoomEmptyBubbleCell.m
- Riot/Views/RoomBubbleList/RoomEmptyBubbleCell.xib
The read marker may be defined on an event which is not displayed in the room history.
The MatrixKit has been updated to handle this kind of event in the MXKRoomBubbleCellData object.
Previously these events were ignored during the bubbles rendering. Now a bubble component is created even if the event has no actual display.
This component is useful to display the read marker in the room history, and to allow the user to jump on this read marker.
> Read marker

- Riot/Model/RoomList/RecentsDataSource.m
by displaying first the rooms with some missed notifs, the rooms with unread, then the others.
> UX Rework - Home Tab: Sort the rooms collections

- Riot/ViewController/RoomViewController.m
Do not display the banner "jump to last unread message" when the timeline is not in live.
> RoomViewController: Improve the read marker handling

- Riot/AppDelegate.m
This scenario very often causes to crash: receive an incoming call and press decline on alert view.
> Fix crash on decline button

- Riot/ViewController/CallViewController.m
See [PR 308](https://github.com/matrix-org/matrix-ios-kit/pull/308)
> Remove unnecessary construction methods from CallViewController

- Riot/ViewController/RoomsViewController.m
#1329 
I do not know what causes the regression but this fix avoids to show the footer spinner if the data source is not yet ready (=nil), which is a good sanity check anyway.
As the spinner view is used as a flag to indicate that a pagination is in progress, the pagination code fell in dead lock and did no more paginations.
This case happens because ```[RoomViewController triggerDirectoryPagination]``` is called with a nil datasource when the screen appears.
> Fix: Room directory: stuck after the 20 first items

- Riot/ViewController/DirectoryViewController.m
#1355
Make pagination UI update of DirectoryViewController simpler.
The issue is that the same PublicRoomsDirectoryDataSource instance is shared between DirectoryViewController and RoomsViewController. We can have parallel paginations which makes hard to count the exact number of added cells.
> Fix: Crash when scrolling in the public rooms from Unified Search

- Riot/ViewController/MediaPickerViewController.m
- Riot/ViewController/MediaPickerViewController.xib
The camera preview was set up with a wrong frame value. We wait for the first `viewDidLayoutSubviews` call before setting up the preview.
#686
+ fix the wrong preview layout on iPad described in PR #1372 MediaPicker xib layout fix.
> Bug Fix: Camera preview is broken after a second try

- Riot/ViewController/BugReportViewController.m
This will help triaging. Example at https://github.com/matrix-org/riot-ios-rageshakes/issues/176
> Bug Report: Make the crash dump appear in GH issues created for crashes.

- Riot/ViewController/SettingsViewController.m
I found that my [change](https://github.com/vector-im/riot-ios/pull/1470) of control events for UISwitch on settings screen has a bad influence. Some of handlers programmatically set value to switch and that leads to generating an event again.
> Rollback #1470

- Riot/AppDelegate.h
- Riot/AppDelegate.m
- Riot/ViewController/SettingsViewController.m
There is a problem:
Imagine that you disabled notifications for Riot on a system level, then when you'll try enable them on the settings screen and you'll see an alert which advices you to go to the system settings and enable them there. After you did that you return to the Riot and will try to enable them again but you will see the same alert.
Also if user has disabled notification between launches we don't delete stored push token, so server will send pushes, but we can't process them, since we don't have access to notifications.
It will be better to merge this with PushKit in the future.
> Improvements in notification registration flow

- Riot/AppDelegate.m
See #1480 
It can also fix:
> sometimes you would accept a call and the green phone icon next to the input textbox will change to a red "hang up" icon, but no "call screen" or "green call header bar at the top" would come up. You'd be looking at the chat and be able to talk (and hang up from that red "hang up" icon), but you won't be able to bring up that "call screen".
> Fix issue #1480

- Riot.xcodeproj/project.pbxproj
- Riot/AppDelegate.m
- Riot/Assets/en.lproj/Vector.strings
- Riot/Categories/MXSession+Riot.h
- Riot/Categories/MXSession+Riot.m
- Riot/ViewController/MasterTabBarController.m
- Riot/ViewController/SettingsViewController.m
To test PushKit notifications on your local machine change bundle id of the project to **im.vector.pushtest**. Perform changes in `initMatrixSession` to allow calling` [accountManager prepareSessionForActiveAccounts]` even in background mode. Also you will need a pem certificate which can be provided to you by me or Dave. To send pushes i use [Houston](https://github.com/nomad/houston).
Initially PushKit must be used only for VoIP notifications, but then it was decided to use it for all types of notifications in Riot. So the purpose of this is PR to provide this level of support.
The flow of registering for notifications didn't change a lot. There're new methods which replaced the old one. All of them belongs to `PKPushRegistryDelegate` protocol: …
> PushKit support

- Riot/ViewController/AuthenticationViewController.m
https://github.com/vector-im/riot-meta/issues/94
> Improvement - Create DM with Riot-bot on new account creation.

- Riot/AppDelegate.h
- Riot/AppDelegate.m
- Riot/Riot-Defaults.plist
- Riot/ViewController/SettingsViewController.m
Use new MXKAccount API to handle push token and settings.
- add format: 'event_id_only' to the data dict when you add the pusher
- use the following app ID: im.vector.app.ios.voip.prod
> Pushkit: Remove APNS use.

- Riot/AppDelegate.m
- Riot/Assets/de.lproj/Vector.strings
- Riot/Assets/en.lproj/Vector.strings
- Riot/Assets/fr.lproj/Vector.strings
- Riot/Assets/nl.lproj/Vector.strings
- Riot/Assets/ru.lproj/Vector.strings
- Riot/Utils/RiotDesignValues.m
- Riot/Utils/Widgets/Widget.m
- Riot/ViewController/SettingsViewController.h
- Riot/ViewController/SettingsViewController.m
https://github.com/vector-im/riot-ios/issues/1524
- the app does its own dark theme and prevents the OS from automatically revert the colors in the app
- there are 3 choices on iOS11 for the Riot theme: "auto", "light", "dark". "auto" uses the system settings
> BF: [iOS11] "Smart [colors] Invert" renders badly in the app

- Riot.xcodeproj/project.pbxproj
- Riot/Views/RoomInputToolbar/KeyboardGrowingTextView.m
- Riot/Views/RoomInputToolbar/RoomInputToolbarView.xib
Signed-off-by: Vivian Lim <vivvnlim@gmail.com>
Create a class KeyboardGrowingTextView which inherits from HPGrowingTextView, but defines keyCommands. keyCommands defined at any other view or controller layer weren’t being picked up by the OS, but they did work when added to HPGrowingTextView.
I was able to validate this on my machine based on release-v0.5.1 but I can't figure out how to build the project after the App Extension was added. If you have any tips please let me know.
Also let me know if you have any ideas on better ways to call from KeyboardGrowingTextView to RoomInputToolbarView, or why defining keyCommands at any other layer didn't work (I had trouble pinning down exactly which class is the First Responder, and where the OS was looking for keyCommands)
> Return key on hardware keyboards now sends messages

- Riot/ViewController/RoomMemberDetailsViewController.m
- Riot/Views/RoomMember/RoomMemberTitleView.m
Define directly the navigation titleView with the custom title view instance. Do not use anymore a container.
We had to add some constraints  to keep the custom title at the right position.
> Fix - Room member details: the member's avatar is cropped in the header

- Riot/ViewController/MediaPickerViewController.m
- [MediaPickerViewController setupAVCapture] (in Riot) (MediaPickerViewController.m:1158) (https://github.com/matrix-org/riot-ios-rageshakes/issues/312)
- [MediaPickerViewController tearDownAVCapture] (in Riot) (MediaPickerViewController.m:1198) (https://github.com/matrix-org/riot-ios-rageshakes/issues/314)
> MediaPickerViewController: Add sanity checks to avoid crashes

- Riot/AppDelegate.m
Add sanity check: Do not display local notifications during the initial sync.
> Bug Fix - Notification explosion on initial sync

- Riot/AppDelegate.m
+ Fix #1576: Notifs for named 1:1s don't show the room name, only the sender
+ Remove the room alias from the room name
+ Hide the room name when it is equal to the sender name
+ Consider the actual event date
> Bug Fix - Local notifications body

- RiotShareExtension/Model/ShareDataSource.m
Add a fake matrix session to each room summary to provide it a REST client (used to handle correctly the room avatar).
#1570
> Bug Fix - Share extension: Rooms have no avatars

- Riot/ViewController/ContactDetailsViewController.h
- Riot/ViewController/ContactDetailsViewController.m
- Riot/ViewController/ContactDetailsViewController.xib
- Riot/ViewController/RoomMemberDetailsViewController.m
- Riot/ViewController/RoomMemberDetailsViewController.xib
- Riot/ViewController/RoomViewController.m
- Riot/Views/RoomMember/RoomMemberTitleView.h
- Riot/Views/RoomMember/RoomMemberTitleView.m
- Riot/Views/RoomMember/RoomMemberTitleView.xib
- Riot/Views/RoomTitle/ExpandedRoomTitleView.h
- Riot/Views/RoomTitle/ExpandedRoomTitleView.m
- Riot/Views/RoomTitle/ExpandedRoomTitleView.xib
- Riot/Views/RoomTitle/PreviewRoomTitleView.h
- Riot/Views/RoomTitle/PreviewRoomTitleView.m
- Riot/Views/RoomTitle/PreviewRoomTitleView.xib
- Riot/Views/RoomTitle/RoomAvatarTitleView.h
- Riot/Views/RoomTitle/RoomAvatarTitleView.m
- Riot/Views/RoomTitle/RoomAvatarTitleView.xib
#1590 
The avatar are not displayed anymore in the navigation bar. They are displayed in a dedicated view in the view controller.
This change has been applied on RoomMemberDetailsViewController, ContactDetailsViewController and RoomViewController.
> Bug Fix - Member Info page avatars are systematically cropped (iOS 11)

- SiriIntents/Info.plist
- SiriIntents/IntentHandler.m
This PR for #1496. 
I didn't add possibility for sending messages for encrypted rooms because I need your advice. For encrypted rooms we need to use `MXCrypto`.
Firstly, we need to add ability for creation `MXCrypto` instance without `MXSession`. I suggest to add `checkCryptoWithCredentials:(MXCredentials *)credentials complete:(void (^)(MXCrypto *))complete` method that will have implementation of the existing one created for using with `MXSession`. Version with `MXSession` then will call this new method.
Secondly, we need new method for encryption that can work without `MXRoom` instance. It can look like `encryptEventContent:withType:forRoomState:success:failure:`. Since this method will work with `MXRoomState` a new async method for retrieving `MXRoomState` instances must be created. …
> Add message sending via Siri

- Riot/Model/Contact/ContactsDataSource.m
- Riot/ViewController/PeopleViewController.m
- Riot/ViewController/RoomParticipantsViewController.m
- Riot/ViewController/StartChatViewController.m
- Riot/ViewController/UsersDevicesViewController.m
return a fake cell to prevent app from crashing.
> Fix - tableView cellForRowAtIndexPath:

- RiotShareExtension/ViewController/RoomsListViewController.m
#1611
- display the search input by default
- on searching for something, the search filter seems to clear instantly on selecting a destination NOK.
> Bug Fix: Share extension improvements

- README.rst
This probably isn't the best way to word these instructions but something like this is needed for people to be able to build and run Riot for iOS on their own machines.
> Update developing instructions in README

- Riot/Assets/en.lproj/Vector.strings
- Riot/Utils/RiotDesignValues.h
- Riot/Utils/RiotDesignValues.m
- Riot/ViewController/RoomSettingsViewController.m
- Riot/ViewController/SettingsViewController.m
- Riot/Views/RoomInputToolbar/RoomInputToolbarView.m
Adds a basic OLED black theme. Only the main background color is changed in this PR but it opens up the ability to change other colors to work well on OLED screens.
This PR also changes the keyboard to be dark in the dark and black themes.
Works on #1444, fixes #1620
>  Add basic OLED black theme

- Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
- Riot/Utils/EventFormatter.m
- Riot/Utils/RiotDesignValues.h
- Riot/Utils/RiotDesignValues.m
- Riot/ViewController/RoomViewController.m
- Riot/Views/Directory/DirectoryServerDetailTableViewCell.xib
- Riot/Views/Directory/DirectoryServerTableViewCell.xib
- Riot/Views/RoomInputToolbar/RoomInputToolbarView.h
- Riot/Views/RoomInputToolbar/RoomInputToolbarView.m
- Riot/Views/RoomList/PublicRoomTableViewCell.xib
- Riot/Views/RoomList/RecentTableViewCell.m
- Riot/Views/RoomList/RecentTableViewCell.xib
- Riot/Views/RoomList/RoomIdOrAliasTableViewCell.xib
Related to issue #496.
This patch is not exhaustive - it doesn't make everything use Dynamic Type fonts.
Still, it makes most of the (frequently used) UI scalable, which should be a nice first step and an improvement for people with visibility problems.
Even in the generic case (no visibility problems and font size increase set in Accessibility settings), with this patch, the fonts appear a little larger and more legible than before (addresses issue #1487).
This patch defines some basic fonts, listens for a `UIContentSizeCategoryDidChangeNotification` and maintains these fonts updated accordingly.
To let the rest of the app know about such font size changes, we send the same `kRiotDesignValuesDidChangeThemeNotification` which gets dispatched when people change between the Dark/Light …
> Initial work on adding Dynamic Type support

- Riot/AppDelegate.m
- Riot/Assets/en.lproj/Vector.strings
- Riot/Assets/fr.lproj/Vector.strings
- Riot/ViewController/RoomKeyRequestViewController.h
- Riot/ViewController/RoomKeyRequestViewController.m
Make sure we download requester device keys before showing the share dialog.
Also, add "You added a new device '%@', which is requesting encryption keys." string
> Crypto: BF: The share key dialog can appear with a 'null' device (#1683)

- Riot/Utils/Widgets/Widget.m
instead of an expected string (https://github.com/matrix-org/riot-ios-rageshakes/issues/765)
> Widget: Fix crash when widget JSON data contains a number value

- Riot/AppDelegate.m
- Riot/Assets/en.lproj/Localizable.strings
Show a notification even if the app fails to sync with its hs to get all data.
#1696
I was not able to reproduce the use case but some rageshake logs show that it happens.
Commands to grep right lines:
`find ./2017-12-* -name '*.gz' -exec zgrep -- 'background sync fails' {} +`
or
`find ./2017-12-* -name '*.gz' -exec zgrep -- 'MXSession state changed while in background. mxSession.state: (' {} +`
A log file where the use case happened: https://riot.im/bugreports/listing/2017-12-27/163238/console.2.log.gz
> Missing Push Notifications again

- Riot/AppDelegate.m
Try another technique to save logs to files earlier.
The goal is to track unexpected app startup cycle like in https://riot.im/bugreports/listing/2017-12-29/081732/console.1.log.gz (https://github.com/matrix-org/riot-ios-rageshakes/issues/797) and https://riot.im/bugreports/listing/2017-12-31/133345/console.log.gz (https://github.com/matrix-org/riot-ios-rageshakes/issues/805).
> AppDelegate: Enable log to file earlier

- Riot.xcodeproj/project.pbxproj
- Riot/Assets/en.lproj/Vector.strings
- Riot/Assets/fr.lproj/Vector.strings
- Riot/ViewController/GroupDetailsViewController.m
- Riot/ViewController/GroupParticipantsViewController.m
- Riot/ViewController/GroupRoomsViewController.h
- Riot/ViewController/GroupRoomsViewController.m
- Riot/ViewController/GroupRoomsViewController.xib
- Riot/Views/RoomList/GroupRoomTableViewCell.h
- Riot/Views/RoomList/GroupRoomTableViewCell.m
- Riot/Views/RoomList/GroupRoomTableViewCell.xib
https://github.com/vector-im/riot-meta/issues/117
> Group details: Add Rooms page

- Riot/ViewController/BugReportViewController.m
Signed-off-by: Dawid Rączka <dawidraczka@gmail.com>
> Fixed keyboard color when entering bug report (#1720).

- RiotShareExtension/Model/ShareExtensionManager.m
Reported only by app store because we do not catch crashes from the share extension nor siri extension.
> Share Extension: Fix crash on a weak self

- Riot/AppDelegate.m
Force the matrix session to refresh the cached data related to the publicised groups of the users when the application enters in foreground
vector-im/riot-meta#118
> Groups: Display flair for users in room history.

- Riot.xcodeproj/project.pbxproj
- Riot/ViewController/RoomSettingsViewController.m
- Riot/ViewController/SettingsViewController.m
- Riot/Views/Group/GroupTableViewCell.h
- Riot/Views/Group/GroupTableViewCell.m
- Riot/Views/Group/GroupTableViewCellWithSwitch.h
- Riot/Views/Group/GroupTableViewCellWithSwitch.m
- Riot/Views/Group/GroupTableViewCellWithSwitch.xib
Display more details on the user's group (avatar, id)
vector-im/riot-meta#118
> Settings: Enhance flair handling

- Riot/AppDelegate.m
This adds interactive notifications, so that you can quickly reply to messages from the notification. Visually, the feature looks and works exactly like WhatsApp's notification action. If you have the "Show decrypted content" setting turned off, the quick reply functionality is disabled for encrypted notifications (since it doesn't make sense to reply to a message before actually seeing its content).
#625 
Signed-off-by: Joey Watts <joey.watts.96@gmail.com>
> Add support for interactive notifications (fixes #625)

- RiotShareExtension/Model/ShareExtensionManager.m
Reported in Xcode organiser so there is no detail how it happened.
The fix is a workaround to avoid the crash but it does not help the user for sending their image.
> Fix crash in ShareExtensionManager

- Riot/AppDelegate.m
#1798
Ugly fix to give time to load and show the launching animated screen before MXContactManager freezes the UI thread
> Fix screen flashing at startup

- Riot/ViewController/RoomViewController.m
- Riot/Views/RoomTitle/PreviewRoomTitleView.h
- Riot/Views/RoomTitle/PreviewRoomTitleView.m
- Riot/Views/RoomTitle/PreviewRoomTitleView.xib
#1645 
Main changes are:
- replace the topic UILabel to a scrollable UITextView.
- make the parent give the right height for his child room preview header so that the topic height scale to display enough text without eating all the screen.
There is an additional fix that removea right buttons in the nav bar (screenshots below do not have this fix).
5s:
X:
iPad:
>  BF: Cannot join from a room preview for room with a long topic

- Riot/Model/RoomList/HomeMessagesSearchDataSource.m
The messages were displayed only for the rooms opened recently by the users.
> Bug Fix - Global Messages search: some search results are missing

- Riot.xcodeproj/project.pbxproj
- Riot/AppDelegate.m
- Riot/Model/Search/FilesSearchCellData.m
- Riot/ViewController/RoomViewController.m
- Riot/Views/RoomBubbleList/RoomSelectedStickerBubbleCell.h
- Riot/Views/RoomBubbleList/RoomSelectedStickerBubbleCell.m
- Riot/Views/RoomBubbleList/RoomSelectedStickerBubbleCell.xib
> Render sticker events in the timeline

- Riot/Categories/MXRoom+Riot.m
- Riot/ViewController/RecentsViewController.m
- Riot/ViewController/RoomMemberDetailsViewController.m
- Riot/ViewController/SettingsViewController.m
Add the account identifier in userInfo dictionary to let the listener know which account is concerned by the error.
vector-im/riot-ios#1839
> Improve Error Notifications (based on kMXKErrorNotification)

- Riot.xcodeproj/project.pbxproj
- Riot/AppDelegate.m
- Riot/Assets/js/postMessageAPI.js
- Riot/Utils/EventFormatter.m
- Riot/Utils/Widgets/Widget.m
- Riot/Utils/Widgets/WidgetManager.h
- Riot/Utils/Widgets/WidgetManager.m
- Riot/ViewController/RoomViewController.m
- Riot/ViewController/Widgets/IntegrationManagerViewController.h
- Riot/ViewController/Widgets/IntegrationManagerViewController.m
- Riot/ViewController/Widgets/WidgetPickerViewController.m
- Riot/ViewController/Widgets/WidgetViewController.h
- Riot/ViewController/Widgets/WidgetViewController.m
#1860
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/492 & https://github.com/matrix-org/matrix-ios-kit/pull/425.
This code is able to retrieve user's widgets (like the sticker picker) as defined by [the spec proposal](https://docs.google.com/document/d/1uPF7XWY_dXTKVKV7jZQ2KmsI19wn9-kFRgQ1tFQP7wQ/edit?usp=sharing), to display the sticker picker widget and to send the selected picker.
Still missing:
- a better way to open the picker. You currently need to display the list of widgets to open it
- a screen name of the picker. This is currently m.stickerpicker, the widget type (because this widget has no name) 
- access to the sticker pack configuration screen
- a fix on the widget code for the display bug in a Safari webview (there is the same bug on MacOS/Safari). You currently …
>  Send Stickers: version 1

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Utils/EventFormatter.h
- Riot/Utils/EventFormatter.m
- Riot/ViewController/RoomViewController.m
#1879
The wording in the modal is subject to change.
> RoomVC: Add a re-request keys button on message unable to decrypt

- CHANGES.rst
- Riot/Model/Room/RoomBubbleCellData.h
- Riot/Model/Room/RoomBubbleCellData.m
- Riot/Model/Room/RoomDataSource.m
Closes #1899.
Requires https://github.com/matrix-org/matrix-ios-kit/pull/442.
Build, cache and update read receipts on the processing queue.
> RoomVC: BF: Read receipts processing dramatically slows down UI

- Riot/Model/Room/RoomBubbleCellData.m
Regression due to read receipt perf improvement.
Before:
With this PR:
> RoomVC: Fix regressions on vertical alignment of e2e padlock, read marker, etc

- CHANGES.rst
- Riot/Model/Room/RoomDataSource.m
Regression due to read receipt perf improvement.
Disable the optimisation with `foundSenders` because the assumption "As there is one (the last) read receipt displayed per user" was wrong  for internal processing data.
> RoomVC: Fix duplication of read receipts

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
#1911
Implement reply to an event with text message in a room. It is now possible to reply quickly to a message by highlighting it and then typing some text.
> Replies: Implement sending

- Riot/Modules/GlobalSearch/Messages/DataSources/HomeMessagesSearchDataSource.m
- Riot/Modules/Room/Search/DataSources/RoomSearchDataSource.m
Use profile info sent in the search response.
https://github.com/matrix-org/matrix-ios-kit/pull/455:
Before:
After:
> Lazy-loading: Fix search display

- Riot/Assets/en.lproj/Vector.strings
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.h
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
- Riot/Modules/GlobalSearch/DataSources/UnifiedSearchRecentsDataSource.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/554.
https://github.com/vector-im/riot-ios/issues/1937
> Recents: Recognise server notices room(s) and put them in the dedicated section

- Riot/Modules/Room/RoomViewController.m
A small update to #1989. We hide now the text composer too.
> RoomVC: Show a "Resource Limit Exceeded" banner

- Riot/Modules/Room/RoomViewController.m
Fix roomInputToolbar reset in RoomViewController when MXSession state change to MXSessionStateSyncError or MXSessionStateRunning. That was causing following issues:
- Cleared text
- Black avatar
- Wrong encryption state icon
This should fix following issues: #2006 and #2008
> Fix input toolbar reset in RoomViewController on MXSession state change

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Constants/RiotDesignValues.h
- Riot/Constants/RiotDesignValues.m
- Riot/Modules/Room/RoomViewController.h
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/Activities/RoomActivitiesView.h
- Riot/Modules/Room/Views/Activities/RoomActivitiesView.m
Closes #1937 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/572.
> Server Quota Notices: Implement the blue banner

- Riot/Modules/Authentication/AuthenticationViewController.xib
- Riot/Modules/Authentication/Views/AuthInputsView.xib
- Riot/Modules/Authentication/Views/ForgotPasswordInputsView.xib
- Riot/SupportingFiles/Riot.entitlements
Improves #2066
Not sure if there is anything better to be done with the current interface. With this patch iOS can now see the username field and password field. Unfortunately it tries to put the username in both the username field and the phone number field. I think that is a bug in the current heuristics for password autofill.
This patch is much improved over the old behavior though where it would only put the username in the home server field.
> Add UITextContentType values to AuthInputsView

- CHANGES.rst
- Riot/Categories/MXGroup+Riot.m
- Riot/Categories/MXRoomSummary+Riot.m
- Riot/Modules/Call/CallViewController.m
- Riot/Modules/Call/Views/IncomingCallView.h
- Riot/Modules/Call/Views/IncomingCallView.m
- Riot/Modules/Communities/Home/GroupHomeViewController.m
- Riot/Modules/Communities/Rooms/Views/GroupRoomTableViewCell.m
- Riot/Modules/Contacts/Details/ContactDetailsViewController.m
- Riot/Modules/GlobalSearch/Files/CellData/FilesSearchCellData.m
- Riot/Modules/GlobalSearch/Files/Views/FilesSearchTableViewCell.m
- Riot/Modules/PublicRoomList/Views/PublicRoomTableViewCell.m
- Riot/Modules/Room/DataSources/RoomDataSource.m
- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
- Riot/Modules/Room/ReadReceiptsDetail/ReadReceiptsViewController.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/BubbleCells/RoomMembershipCollapsedBubbleCell.m
- Riot/Modules/Room/Views/BubbleCells/RoomSelectedStickerBubbleCell.m
- Riot/Modules/Room/Views/Title/Preview/PreviewRoomTitleView.m
- Riot/Modules/Rooms/DirectoryPicker/Views/DirectoryServerTableViewCell.m
- Riot/Modules/Settings/SettingsViewController.m
- RiotShareExtension/Managers/ShareExtensionManager.m
Improvements:
* Replace the deprecated MXMediaManager and MXMediaLoader interfaces use (see matrix-org/matrix-ios-sdk/pull/593).
* Replace the deprecated MXKAttachment and MXKImageView interfaces use (see matrix-org/matrix-ios-kit/pull/487).
> MXMediaManager/MXMediaLoader: Do not allow non-mxc content URLs

- CHANGES.rst
- Riot/Modules/Authentication/Views/AuthInputsView.m
#2140
Note: There is no more conditions linked to kMXLoginFlowTypeRecaptcha in the code, which makes it look more flexible.
> BF: Registration: email or phone number is no more skippable

- Riot/AppDelegate.h
- Riot/AppDelegate.m
- Riot/Categories/MXRoom+Riot.h
- Riot/Categories/MXRoom+Riot.m
- Riot/Modules/Call/Views/IncomingCallView.h
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.h
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
- Riot/Modules/Integrations/Widgets/Jitsi/JitsiViewController.h
- Riot/Modules/Integrations/Widgets/Jitsi/JitsiViewController.m
- Riot/Modules/Room/Settings/RoomSettingsViewController.m
- Riot/Modules/RoomKeyRequest/RoomKeyRequestViewController.h
- Riot/Modules/RoomKeyRequest/RoomKeyRequestViewController.m
- Riot/Modules/Settings/SettingsViewController.m
- RiotShareExtension/Modules/Share/Listing/RoomsListViewController.h
- RiotShareExtension/Modules/Share/ShareViewController.m
See: https://stackoverflow.com/questions/44473146/this-function-declaration-is-not-a-prototype-warning-in-xcode-9
Signed-off-by: Fridtjof Mund <2780577+fridtjof@users.noreply.github.com>
> fix almost all the warnings caused by -Wstrict-prototypes

- CHANGES.rst
- Riot/Modules/Authentication/Views/TermsView.swift
Fixes #2164 and the tap gesture on the checkbox.
Do like on android (https://github.com/vector-im/riot-ios/issues/2164#issuecomment-455108199).
>  Registration: improve validation UX on the terms screen

- Riot/Managers/Theme/Theme.swift
- Riot/Managers/Theme/ThemeService.h
- Riot/Managers/Theme/ThemeService.m
- Riot/Managers/Theme/Themes/DarkTheme.swift
- Riot/Managers/Theme/Themes/DefaultTheme.swift
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Call/Views/IncomingCallView.m
- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Settings/RoomSettingsViewController.m
- Riot/Modules/Room/Views/Activities/RoomActivitiesView.m
- Riot/Modules/Room/Views/BubbleCells/RoomOutgoingAttachmentBubbleCell.m
- Riot/Modules/Settings/DeactivateAccount/DeactivateAccountViewController.m
- Riot/Modules/Settings/SettingsViewController.m
- Riot/Utils/EventFormatter.m
Merge them into Theme.warningColor
Part of #2174
We still need to fix tint in multi-color icons.
> reskin: kill riotColorRed & riotColorPinkRed

- CHANGES.rst
- Riot/AppDelegate.m
- Riot/Modules/TabBar/MasterTabBarController.m
regarding the AppDelegate change: There is no need to check for iOS 8+ notifications anymore, the minimum supported version is iOS 9.
Signed-off-by: 2780577+fridtjof@users.noreply.github.com
> Small iOS version checking clean ups

- Riot/AppDelegate.m
Jenkins now uses a timestamp as build number (ex:20190124155504) that is bigger than 32 bits
Before:
After:
> Fix display of build number in settings and bug reports

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/KeyBackup/Recover/Passphrase/KeyBackupRecoverFromPassphraseViewController.swift
- Riot/Modules/KeyBackup/Recover/Passphrase/KeyBackupRecoverFromPassphraseViewModel.swift
- Riot/Modules/KeyBackup/Recover/Passphrase/KeyBackupRecoverFromPassphraseViewState.swift
- Riot/Modules/KeyBackup/Recover/RecoveryKey/KeyBackupRecoverFromRecoveryKeyViewController.swift
- Riot/Modules/KeyBackup/Recover/RecoveryKey/KeyBackupRecoverFromRecoveryKeyViewModel.swift
- Riot/Modules/KeyBackup/Recover/RecoveryKey/KeyBackupRecoverFromRecoveryKeyViewState.swift
Fixes #2223.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/634.
I have removed the error on empty backup because even if the backup is empty, the app will now trust it.
I have added errors on invalid passphrase or recovery key:
> Key backup: Trust on Decrypt

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/KeyBackup/SettingsKeyBackupTableViewSection.swift
- Riot/Modules/Settings/KeyBackup/SettingsKeyBackupViewAction.swift
- Riot/Modules/Settings/KeyBackup/SettingsKeyBackupViewModel.swift
- Riot/Modules/Settings/KeyBackup/SettingsKeyBackupViewModelType.swift
- Riot/Modules/Settings/SettingsViewController.m
Verify button has been removed and replaced by "Use key backup", which makes a restore, because we trust on decrypt now.
* No backup
* Trusted backup
* Untrusted backup
> Backup settings: Update wording and rendering to match riot-web

- CHANGES.rst
- Riot/Modules/Room/Views/Title/Preview/PreviewRoomTitleView.m
- Riot/Modules/Room/Views/Title/RoomTitleView.m
* Fix navigation bar background after accepting an invite:
* Fix text color in room preview:
Before:
After:
> Reskin: Fix 2 color issues

- CHANGES.rst
- Riot/Modules/Common/SegmentedViewController/SegmentedViewController.m
> BF: 0.8.0: Tabs at the top of Room Details are hard to see in dark theme

- CHANGES.rst
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
A possible mitigation for #2265.
> Key backup: avoid to refresh the home room list on every backup state change

- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
This is a regression made in #2265 (Key backup: avoid to refresh the home room list on every backup state change).
On other tabs than `self.keyBackupBanner` must be reset to `KeyBackupBannerNone` so that there is no banner section.
> Key backup: Fix crash when switching tabs if there is a banner on the home tab

- Riot/AppDelegate.m
- Riot/Managers/Widgets/Widget.m
- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Communities/Home/GroupHomeViewController.m
- Riot/Modules/Integrations/IntegrationManagerViewController.m
- Riot/Modules/Room/RoomViewController.m
The new way to do this is by specifying an NSCharacterSet with all the allowed characters. I used the correct ones where it was obvious in what part of an URL strings would end up, but in Widget.m, placeholders can be anywhere in the URL, so I used the generic alphanumericCharacterSet there.
Signed-off-by: Fridtjof Mund <2780577+fridtjof@users.noreply.github.com>
> Take care of percent encoding related deprecations

- Riot/Modules/Main/RiotSplitViewController.m
> BF: Reskin: status bar text is no more readable on iPad

- CHANGES.rst
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
- Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
- Riot/Modules/Communities/Views/GroupTableViewCell.m
- Riot/Modules/Home/Views/RoomCollectionViewCell.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/TabBar/MasterTabBarController.m
> Reskin: Text in badges should be white in dark theme

- CHANGES.rst
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
> Reskin: HomeVC: Use notices colors for badges background in section headers

- CHANGES.rst
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
- Riot/Modules/Settings/SettingsViewController.m
- Riot/Modules/Settings/SignOut/SignOutAlertPresenter.swift
> BF: Do not display key backup UI if the user has no e2e rooms

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Authentication/Views/AuthInputsView.m
Fixes: #2117
Requires:
- https://github.com/matrix-org/matrix-ios-sdk/pull/644
- https://github.com/matrix-org/matrix-ios-kit/pull/528
> Authentication: .well-known support

- CHANGES.rst
- Riot/Modules/Room/Views/Activities/RoomActivitiesView.m
> RoomVC: Use accent color (green) for the ongoing conference call banner

- CHANGES.rst
- Riot/AppDelegate.h
- Riot/AppDelegate.m
WARNING: I couldn't test any of this, because I can't build this app for anything except the simulator (I don't have a paid dev membership - necessary for some capabilities the app has, and also I don't have (for obvious reasons) the entitlements that would allow me to easily receive push notifications from the "official" New Vector push server, which is needed to test any notification related behaviour).
Therefore, I'm kindly asking for someone from the team to test my changes on a device with iOS 10 or higher. Feedback is much appreciated :)
This is the first step in supporting newer notifications features. By using the UserNotifications framework, we will be able to implement new notification features, like titles, grouping and more (see …
> Add code to support the new notification system starting with iOS 10

- CHANGES.rst
- Riot/Assets/Riot-Defaults.plist
> Widgets: Use scalar prod urls in Riot mobile apps

- CHANGES.rst
- Riot/AppDelegate.m
- Riot/Assets/en.lproj/Localizable.strings
As with #2207, I can't test this myself.
This is based on riot_2337 instead of develop, because required code was only merged into that branch (see #2207)
This closes #2208 and #2337 
Signed-off-by: Fridtjof Mund 2780577+fridtjof@users.noreply.github.com
> Add notification titles and group them properly on iOS 10+

- CHANGES.rst
- Riot/Modules/Room/DataSources/RoomDataSource.m
Fix #2294, requires matrix-org/matrix-ios-kit/pull/539
> BF: +N read receipt text is invisible on dark theme

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/KeyBackup/SettingsKeyBackupTableViewSection.swift
This ports the wording changes from Riot Web
https://github.com/matrix-org/matrix-react-sdk/pull/2917.
"Use key backup" as button text feels like it's telling me I haven't set it up
at all. This changes to "Connect this device ..." which seems more reassuring
and applies for both the "add to backup" and "restore from backup" use cases.
This also updates the backup status text for the case where a backup exists, but
it's not being used by the current device so that it's much more clear that you
have a backup at least.
> Clarify key backup details when backup exists but is not trusted

- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- Riot/Modules/Room/DataSources/RoomDataSource.m
Requires https://github.com/matrix-org/matrix-ios-kit/pull/549
Need to replace TODOs once the final view is done.
There is a bug where RRs and all reactions disappears. This happens when there is a reaction and RR on the last message of the timeline.
This bug existed already on the aggregations branch (where there was RR only).
>  Reactions: Add placeholder for reactions list under message

- Riot.xcodeproj/project.pbxproj
- Riot/Modules/Room/ContextualMenu/RoomContextualMenuPresenter.swift
- Riot/Modules/Room/ContextualMenu/RoomContextualMenuViewController.storyboard
- Riot/Modules/Room/ContextualMenu/RoomContextualMenuViewController.swift
- Riot/Modules/Room/RoomViewController.m
Note: 
For the moment, we use the frame of the cell instead of the component. From a UI perpective, that means the menu will be around a paragraph instead of a message.
This is not bad as the paragraph is kept visible to provide more context to the user.
> RoomVC: ContextualMenu: Plug reactions menu

- Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuViewModel.swift
- Riot/Modules/Room/ContextualMenu/RoomContextualMenuPresenter.swift
This avoids to call the delegate twice.
Note: In a short future, we will no more have those 3 state buttons.
This PR contains the move of the send reaction hack to the SDK.
> Reactions menu: Do not notify delegate if reaction requires an unreaction

- Riot/Modules/Room/RoomViewController.m
2 changes in this PR
- Leave the menu once the user tapped a reaction
- Display the keyboard once the users tap on reply or edit
> Reaction Menu: UX polish

- README.rst
Hi, thanks for sharing this great project. 
I found a minor issue while building the project. 
Even though the project contains a Gemfile listing the dependencies, the current build instructions do not really make use of it.
I am just updating the instructions so that Cocoapods is ran on the expected version defined by Gemfile.
Signed-off-by: David Cordero <david@corderoramirez.com>
> Update build instructions to make use of Bundler

- Riot.xcodeproj/project.pbxproj
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Managers/Widgets/Widget.m
- Riot/Managers/Widgets/WidgetManager.h
- Riot/Managers/Widgets/WidgetManager.m
- Riot/Managers/Widgets/WidgetManagerConfig.swift
- Riot/Modules/Integrations/IntegrationManagerViewController.m
- Riot/Modules/Integrations/Widgets/WidgetViewController.m
Closes #2518 .
This PR displays errors instead of trying to hide things.
3 things in the PR:
- Make code support use of an integration manager other than modular/scalar. (It supports multi-account)
- Display a specific error in case of unset IM server
- Display a specific error in case of connection issue with the IM server
> Make sure there are no ugly edge cases running Riot without an integrations manager

- CHANGES.rst
- Riot.xcodeproj/project.pbxproj
- Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionMenuItemViewData.swift
- Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuButton.swift
- Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuView.swift
- Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuView.xib
- Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuViewModel.swift
- Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuViewModelType.swift
- Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuViewState.swift
- Riot/Modules/Room/ContextualMenu/RoomContextualMenuPresenter.swift
- Riot/Modules/Room/ContextualMenu/RoomContextualMenuViewController.storyboard
- Riot/Modules/Room/ContextualMenu/RoomContextualMenuViewController.swift
- Riot/Modules/Room/RoomViewController.m
> Reactions: Update quick reactions

- Riot/Modules/Room/Views/BubbleCells/Encryption/RoomEncryptedDataBubbleCell.m
Fixes vector-im/riot-ios#2449
Requires https://github.com/matrix-org/matrix-ios-kit/pull/571 & https://github.com/matrix-org/matrix-ios-sdk/pull/679
This is compatible with the current implementation in Riot-Web but this code may change with the update of MSC1849.
Note that synapse does not support aggregation in e2e rooms yet. That means the app may not display edited content when opening a permalink.
> Edits: Support edits in e2e rooms

- CHANGES.rst
- Riot/Modules/Room/RoomViewController.m
Closes #2486 by autojoining the upgraded room.
There is no more preview screen, no more room id leak.
> Room upgrade: Autojoin the upgraded room when the user taps on the tombstone banner

- Riot/Modules/Room/EditHistory/EditHistoryViewModel.swift
Closes #2559.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/691.
Note: This change has not been tested yet on a real homeserver.
> Edits history: Display original event

- CHANGES.rst
- RiotShareExtension/SupportingFiles/Info.plist
> Share extension: Enable any file upload (max 5).

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
according to https://github.com/matrix-org/matrix-doc/blob/master/data-definitions/sas-emoji.json#L41
Closes https://github.com/matrix-org/riot-ios-rageshakes/issues/2613.
> Device Verification: Name for ⏰ is "Clock

- Riot/AppDelegate.m
- Riot/Modules/Settings/SettingsViewController.m
#2348
Required by ttps://github.com/matrix-org/matrix-ios-kit/pull/582
> Push: Update code to follow API break

- CHANGES.rst
- Riot/Modules/Room/EditHistory/EditHistoryViewModel.swift
Close #2585
The original event is not an edit event. It must be processed a bit differently.
> BF: Edits history: Original event is missing

- CHANGES.rst
- Riot/AppDelegate.m
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Authentication/AuthenticationViewController.h
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Authentication/AuthenticationViewController.xib
- Riot/Modules/Authentication/Views/AuthInputsView.m
- Riot/Modules/TabBar/MasterTabBarController.h
- Riot/Modules/TabBar/MasterTabBarController.m
Requires https://github.com/matrix-org/matrix-ios-kit/pull/584
Part of #2540
It does:
> Support soft logout

- CHANGES.rst
- Riot/Modules/Settings/SettingsViewController.m
The exception was:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 10.  The number of rows contained in an existing section after the update (0) must be equal to the number of rows contained in that section before the update (3), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'
To raise this exception:
- Execute the removed code after a delay (2s)
- Enter and leave the settings page
-> Crash
> BF: Crash when leaving settings due to backup section refresh animation.

- CHANGES.rst
- Riot.xcodeproj/project.pbxproj
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Camera/CameraPresenter.swift
- Riot/Modules/MediaPicker/Library/MediaAlbumContentViewController.h
- Riot/Modules/MediaPicker/Library/MediaAlbumContentViewController.m
- Riot/Modules/MediaPicker/MediaPickerCoordinator.swift
- Riot/Modules/MediaPicker/MediaPickerCoordinatorBridgePresenter.swift
- Riot/Modules/MediaPicker/MediaPickerCoordinatorType.swift
- Riot/Modules/MediaPicker/MediaPickerViewController.h
- Riot/Modules/MediaPicker/MediaPickerViewController.m
- Riot/Modules/MediaPicker/MediaPickerViewController.xib
- Riot/Modules/MediaPicker/SingleImagePickerPresenter.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Settings/RoomSettingsViewController.h
- Riot/Modules/Room/Settings/RoomSettingsViewController.m
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
- Riot/Modules/Settings/SettingsViewController.h
- Riot/Modules/Settings/SettingsViewController.m
- Riot/SupportingFiles/Riot-Bridging-Header.h
> Replace camera implementation with something more standard and less limited 

- CHANGES.rst
- Tools/Release/buildRelease.sh
- fastlane/Fastfile
It was no more possible to build using tags. The reason was the fastlane git_branch method returned nil.
Internally, this method executes `git symbolic-ref HEAD --short` which returned `fatal: ref HEAD is not a symbolic ref` in our case.
We now checks out the tag as a local branch.
> BF: Build: Fix build based on git tag

- CHANGES.rst
- Riot.xcodeproj/project.pbxproj
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Storyboards.swift
- Riot/Generated/Strings.swift
- Riot/Managers/Widgets/WidgetManager.h
- Riot/Managers/Widgets/WidgetManager.m
- Riot/Managers/Widgets/WidgetManagerConfig.swift
- Riot/Modules/Integrations/IntegrationManagerViewController.m
- Riot/Modules/Integrations/Widgets/WidgetViewController.m
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenCoordinator.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenCoordinatorType.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewAction.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewController.storyboard
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewController.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewModel.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewModelType.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewState.swift
- Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinator.swift
- Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinatorBridgePresenter.swift
- Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinatorType.swift
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/704
Closes #2600
> Prompt to accept integration manager policies on use

- CHANGES.rst
- Riot/Assets/en.lproj/InfoPlist.strings
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Contacts/Details/ContactDetailsViewController.m
- Riot/Modules/Settings/SettingsViewController.m
- Riot/Modules/StartChat/StartChatViewController.h
- Riot/Modules/StartChat/StartChatViewController.m
#2643
Requires matrix-org/matrix-ios-sdk/pull/705 & matrix-org/matrix-ios-kit/pull/591
> Ability to disable all identity server functionality via the config file

- CHANGES.rst
- Riot/AppDelegate.m
- Riot/Generated/Strings.swift
- Riot/Modules/Authentication/Views/AuthInputsView.m
#2647
Requires matrix-org/matrix-ios-sdk/pull/706 & matrix-org/matrix-ios-kit/pull/592
> Use MXIdentityService to perform identity server requests

- CHANGES.rst
- Riot/Assets/Riot-Defaults.plist
As per MSC1961, add to the whitelisted integrations_widget_urls
the new paths. This allows us to switch Scalar over to use the
new path as default.
Note, the legacy "scalar-staging.riot.im" is these days just a redirect
to scalar-staging.vector.im, so there is no addition for that. It still
needs Riot side whitelisting though for existing widgets.
Refs: https://github.com/matrix-org/matrix-doc/pull/1961
> Add and prioritize the new "_matrix/integrations/v1" widget urls

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/SettingsViewController.m
> Make clear that device names are publicly readable

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Authentication/Views/AuthInputsView.m
Fixes #2675
We use new strings ids as the meaning changed.
> Privacy: Email help text on registration should be updated without binding

- CHANGES.rst
- Riot/AppDelegate.m
- Riot/Categories/UISearchBar.swift
- Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinatorBridgePresenter.swift
> Support identity server v2 API

- CHANGES.rst
- Riot/Modules/Authentication/AuthenticationViewController.m
Final touch. Closes #2661.
Require: https://github.com/matrix-org/matrix-ios-kit/pull/598
> Privacy: Remove the ability to set an IS at login/registration

- CHANGES.rst
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Authentication/Views/AuthInputsView.m
> Privacy: Allow email registration when no IS

- CHANGES.rst
- Riot/Assets/en.lproj/InfoPlist.strings
and mention that 3pids are now uploaded hashed.
Closes #2521.
> Privacy: Make NSContactsUsageDescription more generic

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Contacts/DataSources/ContactsDataSource.m
- Riot/Modules/Room/Members/RoomParticipantsViewController.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Settings/SettingsViewController.m
closes #2672 
This PR implements:
- an error message when the user tries to invite by email
- a message explaining why there is no matrix users in the local contact list
Note: In settings, there was already an error message if you try to add a email to your account on an HS that still requires an IS to operate.
> Make sure the app behaves clearly for the end user when there is no IS

- Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewController.swift
- Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewModel.swift
- Riot/Modules/Settings/SettingsViewController.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/726.
to:
- add 3pids to user's account (in SettingsVC)
- bind/unbind 3pids so that all the HS/IS flags logic stays in the SDK
> Use new MX3PidAddManager

- CHANGES.rst
- Riot/AppDelegate.m
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Integrations/IntegrationManagerViewController.m
- Riot/Modules/Integrations/Widgets/WidgetViewController.m
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenCoordinator.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenCoordinatorType.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewAction.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewController.storyboard
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewController.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewModel.swift
- Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewModelType.swift
- Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinator.swift
- Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinatorBridgePresenter.swift
- Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinatorType.swift
- Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewController.swift
Fixes #2760 .
The terms screen has now a variant when we have a "terms not signed" error from nowhere (like a background lookup).
> Privacy: Make IS terms wording clearer when we fallback to vector.im

- CHANGES.rst
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Settings/RoomSettingsViewController.m
Passing nil to `-[UIPasteboard setString:]` causes a crash whereas `string` property is nullable (See Radar issue https://openradar.appspot.com/36063433).
> Pasteboard: Fix a crash when passing a nil object to UIPasteboard

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/SettingsViewController.m
fixes vector-im/riot-ios#2744
requires https://github.com/matrix-org/matrix-ios-sdk/pull/737
In case of not supported authentication:
> Settings: Add User-Interactive Auth for adding email and msidsn to user's account

- CHANGES.rst
- Riot/Modules/TabBar/MasterTabBarController.m
> BF: Tab bar icons are not centered vertically on iOS 13

- CHANGES.rst
- Riot/Modules/DeviceVerification/Start/DeviceVerificationStartViewModel.swift
- Riot/Modules/DeviceVerification/Verify/DeviceVerificationVerifyViewModel.swift
Closes #2878
Don't stop listening to transaction updates if we receive unexpected events else you block the state machine.
> Device Verification: Stay in infinite waiting

- CHANGES.rst
- Riot/Modules/Room/DataSources/RoomDataSource.h
- Riot/Modules/Room/DataSources/RoomDataSource.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/BubbleCells/Encryption/RoomEncryptedDataBubbleCell.m
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
- Riot/Modules/Room/Views/Title/Expanded/ExpandedRoomTitleView.h
- Riot/Modules/Room/Views/Title/Expanded/ExpandedRoomTitleView.xib
Closes #2934, #2930, #2906.
Requires matrix-org/matrix-ios-sdk/pull/765
> RoomVC: Update encryption decoration with shields

- CHANGES.rst
- Riot/Modules/Settings/SettingsViewController.m
Closes #2941.
LABS looks like that now:
> Settings: Remove "End-to-End Encryption" from the LABS section

- Riot/AppDelegate.m
- Riot/Categories/MXSession+Riot.h
- Riot/Categories/MXSession+Riot.m
- Riot/Modules/Contacts/Details/ContactDetailsViewController.m
- Riot/Modules/StartChat/StartChatViewController.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/769
Closes #2943
This screenshot shows that e2e was enabled during the room creation (shields look wrong but this is another issue):
> Negotiate E2E by default for DMs

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Managers/Settings/RiotSettings.swift
- Riot/Modules/Settings/SettingsViewController.m
Use the same copy as riot-web:
> Settings: LABS: Keep only one flag for cross-signing

- Riot/AppDelegate.m
- Riot/Modules/DeviceVerification/DeviceVerificationCoordinator.swift
- Riot/Modules/DeviceVerification/Incoming/DeviceVerificationIncomingViewModel.swift
- Riot/Modules/DeviceVerification/Loading/DeviceVerificationDataLoadingCoordinator.swift
- Riot/Modules/DeviceVerification/Loading/DeviceVerificationDataLoadingCoordinatorType.swift
- Riot/Modules/DeviceVerification/Loading/DeviceVerificationDataLoadingViewModel.swift
- Riot/Modules/DeviceVerification/Loading/DeviceVerificationDataLoadingViewModelType.swift
- Riot/Modules/DeviceVerification/Start/DeviceVerificationStartViewModel.swift
- Riot/Modules/DeviceVerification/Verify/DeviceVerificationVerifyViewModel.swift
- Riot/Modules/Room/DataSources/RoomDataSource.m
- Riot/Modules/UserVerification/Start/UserVerificationStartViewModel.swift
Because it makes more sense now
Follows changes made by https://github.com/matrix-org/matrix-ios-sdk/pull/780
> MXCrypto: Rename MXDeviceVerificationManager to MXKeyVerificationManager

- Riot/AppDelegate.m
- Riot/Modules/DeviceVerification/DeviceVerificationCoordinator.swift
Requires: https://github.com/matrix-org/matrix-ios-sdk/pull/785.
Closes #2871.
We display the same modal as riot-web. It can look minimalist but this is not the main path for verifying a session. The main path being "Complete Security" just after signing in.
> Key Verification: Handle incoming self verification request

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/Security/SecurityViewController.m
Cross-signing information is based on the new `MXCrossSigning.state` (https://github.com/matrix-org/matrix-ios-sdk/pull/797).
This section has not been designed. It will probably be removed (or merged) soon as we are discussing to put all keys (backup and cross-signing) behind a main key. 
Its goal is help to debug and to better understand cross-signing states.
We need to work again on it before release cross-signing. 
Strings are not i18ned because it is a temporary thing.
Screen according to `MXCrossSigning.state`:
- MXCrossSigningStateNotBootstrapped
- MXCrossSigningStateCrossSigningExists
- MXCrossSigningStateTrustCrossSigning
- MXCrossSigningStateCanCrossSign / MXCrossSigningStateCanCrossSignAsynchronously
> Security screen: Add a dedicated cross-signing section

- Riot/Modules/Settings/Security/SecurityViewController.m
Part of #3024 .
Tested against RiotX that gossips USK and SSK.
> Security settings: Implement "Request (cross-signing private) keys"

- Riot/Assets/en.lproj/Vector.strings
- Riot/Categories/MXRoom+Riot.m
- Riot/Generated/Strings.swift
- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Fix #3046
Display also the shield on the user to have the same screen for e2e and non e2e rooms
> RoomMember scree: Display the verify button even in non e2e rooms

- CHANGES.rst
- Riot/Modules/Home/Fallback/AuthFallBackViewController.m
When doing a SAML based SSO via Gsuite, I must click a link specifying that I trust this app. That link will break me out of the SSO sign-in process, and open up safari.
To fix address this, I've removed the feature that opens links in safari.
Signed-off-by: Mark Schulte <schultetwin@gmail.com>
> AuthFallback: Stay in Riot App

- CHANGES.rst
- Riot/Categories/MXRoom+Riot.m
- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
- Riot/Modules/Room/Members/Detail/UserEncryptionTrustLevel.h
- Riot/Utils/EncryptionTrustLevelBadgeImageHelper.swift
Fix #3138.
We offer that by displaying the list of devices of the other user. Our user can verify them one by one:
> Cross-signing: Allow to verify each device of users with no cross-signing

- CHANGES.rst
- Riot/Modules/Authentication/AuthenticationViewController.m
> Remove login fallback to m.org when authentication failed

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.swift
Fix #3035
Copy took from riot-web. The screen looks empty but it should go a bottom sheet.
> Verification: Do not talk about QR code if only emoji is possible

- CHANGES.rst
- Riot/AppDelegate.h
- Riot/AppDelegate.m
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
- Riot/Modules/Settings/Security/SecurityViewController.m
It fixes bugs seen while testing
If the user skips verify on signin:
- this signin is not red in the sessions list (1st commit)
- on the complete security screen, the incoming verification popup is displayed (3rd commit)
2nd commit fixes #3033.
Commits are independent.
> Some polishing when the device is not trusted yet

- CHANGES.rst
- Riot/AppDelegate.m
This will mitigate unexpected state of cross-signing and backup.
> Secrets: On startup, request again private keys we are missing locally

- Riot/Modules/Authentication/AuthenticationViewController.xib
The crash was:
```
2020-05-11 17:53:44.125128+0200 Riot[60416:899392] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Configuration cannot be nil'
*** First throw call stack:
(
0   CoreFoundation                      0x000000010b0e98db __exceptionPreprocess + 331
1   libobjc.A.dylib                     0x0000000109d3dac5 objc_exception_throw + 48
2   CoreFoundation                      0x000000010b0e9735 +[NSException raise:format:] + 197
3   WebKit                              0x00000001080f112e -[WKWebView _initializeWithConfiguration:] + 88
4   WebKit                              0x00000001080f35ab -[WKWebView initWithCoder:] + 131
```
I checked this checkbox:
> AuthenticationVC: Fix crash due to update to WKWebView

- CHANGES.rst
- Riot/AppDelegate.m
The issue was the call view controller not being set to nil which caused future checks to be a false positive, when determining if there's already an ongoing call. This commit should fix that issue.
#2877
> Declined calls now properly reset call view controller

- CHANGES.rst
- Riot/Modules/Settings/SettingsViewController.m
> BF: SettingsVC: New phone number is invisible in dark theme

- CHANGES.rst
- Riot/Categories/UILabel.swift
- Riot/Modules/KeyVerification/User/SessionsStatus/UserVerificationSessionsStatusViewModel.swift
- Riot/Modules/Settings/PhoneCountry/CountryPickerViewController.m
Fix #3219
Requires matrix-org/matrix-ios-kit/pull/673
> CountryPickerVC: Search field is invisible in dark theme

- CHANGES.rst
- Riot/Modules/Authentication/AuthenticationViewController.m
and login if applicable.
#3292
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/860.
Cross-signing bootstrap is invisible to the user. 
It is under a compilation flag because riot-web is not happy with such a bootstrap flow for the moment. Also, I do not want us to deal with another branch.
I will close the issue once I am able to test SSO.
> Cross-signing: Bootstrap cross-sign on registration

- CHANGES.rst
- Riot/Modules/Home/Fallback/AuthFallBackViewController.m
This will help to debug our SSO support into a webview.
The HS with SSO I have gives me this logs:
```
2020-06-03 13:56:38.320748+0200 Riot[31562:1222934] -- JavaScript: Server accepts SSO 
```
> Authentication: Redirect webview (SSO) javascript logs to native logs

- CHANGES.rst
- RiotNSE/NotificationService.swift
For better troubleshooting with less rotation in case of too many pushes.
> Increase NSE Number of Log Files

- CHANGES.rst
- Riot/Modules/Room/Views/Title/Preview/PreviewRoomTitleView.m
Get inviter display name directly from the invite event, rather than looping in room members. Fixes #2520
> Fix Inviter Display Name

- CHANGES.rst
- Riot.xcodeproj/project.pbxproj
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/AuthenticatedSession/AuthenticatedSessionViewControllerFactory.swift
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Settings/Security/SecurityViewController.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/872
Part of #3299 
The password form for cross-signing setup is still a `UIAlertController` as we have elsewhere but we will be able to support SSO more easily and more transparently with the new `AuthenticatedSessionViewControllerFactory`.
> SecurityVC: Plug UX to set up cross-signing & secure backup

- Riot/Modules/Authentication/AuthenticationViewController.m
because we consider riot-web ready
Fixes #3292
> AuthVC: Remove NEW_CROSS_SIGNING_FLOW

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Secrets/Setup/RecoveryKey/SecretsSetupRecoveryKeyViewModel.swift
- Riot/Modules/SecureBackup/Setup/Intro/SecureBackupSetupIntroViewController.swift
- Riot/Modules/SecureBackup/Setup/SecureBackupSetupCoordinator.swift
- Riot/Modules/Settings/Security/SecurityViewController.m
Fix #3361 
We handle existing key backup but no private key with:
"Unlock it" opens the existing key backup recovery flow:
> Secure backup: Create and delete key backup with 4S

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/Security/SecurityViewController.m
Fixes #3296 
The key backup section is removed. This is now handle by the secure backup. The creation of the secure backup will re-use existing key backup.
The cross-signing section is gone. Cross-signing should be enabled by default now (on login or on registration). We will have a banner to migrate existing users (#3299). If the user taps on "set up secure backup", the cross-signing will be set up.
User migration:
> Settings: Secure backup

- Riot/AppDelegate.m
- Riot/Managers/AppVersion/AppVersion.swift
- Riot/Modules/MajorUpdate/MajorUpdateManager.swift
- Riot/Modules/SlidingModal/SlidingModalPresenter.swift
Eventually a fix for #3451 .
At least we have more logs for it.
> Poor fix for missing "Riot is now element" modal

- Riot.xcodeproj/xcshareddata/IDETemplateMacros.plist
Add Xcode file header template `IDETemplateMacros.plist` shared for all users.
> Add Xcode file header template

- CHANGES.rst
- Config/Common.xcconfig
- Riot/Modules/MajorUpdate/MajorUpdateManager.swift
Fixes #3497. No need to do anything on major update popup. It will only be visible for the users coming from < 1.0.0 versions.
> Remove Riot from App Name

- Gemfile.lock
- Podfile
- Podfile.lock
- fastlane/Fastfile
This PR adds Fastlane lanes necessary for CI
- `point_dependencies_to_pending_releases`
- `point_dependencies_to_same_feature`
- `build`
It is only a first iteration, so the CI pipeline runs.
> Note: a different PR will change the implementation in the future. Especially the `point_dependencies_to_*` switcheroos is done by going to the YAML world to facilitate the manipulation, but a refactoring will do those changes using RegExes in the `Podfile` later because using a `CocoaPods.podfile.yaml` file is not a well known feature and also doesn't support `post_install` scripts
> [Internal] fastlane: code for branch switcheroo used by CI

- fastlane/Fastfile
Fix switcheroo logic: we need to also edit the `:tag => s.version.to_s` from the `MatrixKit.podspec`
So that it downloads from the branch and not the tag when using that podspec in the Podfile
> [Internal] [CI] Fix switcheroo logic

- Riot/Categories/UIDevice.swift
- Riot/Modules/Common/NavigationController/RiotNavigationController.m
- Riot/Modules/SetPinCode/EnterPinCode/EnterPinCodeViewController.swift
- Riot/Modules/SetPinCode/EnterPinCode/EnterPinCodeViewModel.swift
- Riot/Modules/SetPinCode/EnterPinCode/EnterPinCodeViewModelType.swift
- Riot/Modules/SetPinCode/SetPinCoordinator.swift
- [ ] Numbers buttons color is not the same as Figma. Color in Figma is not in the palette also.
- [ ] Forgot button text color is not the same as Figma.
- [ ] Make UI more responsive to improve iPad portrait UI
Fixes #3514
> Polish Pin Screen

- CHANGES.rst
- Riot/Modules/KeyVerification/Common/KeyVerificationCoordinatorBridgePresenter.swift
> Gracefully cancel verification on iOS 13 drag gesture

- CHANGES.rst
- Tools/Release/buildRelease.sh
- fastlane/Fastfile
because fastlane `git_branch` method can fail.
It failed when using ./buildRelease.sh with a tag.
> buildRelease.sh: Pass a `git_tag` parameter to fastlane

- CHANGES.rst
- Config/AppConfiguration.swift
> Timeline: Hide encrypted history (pre-invite)

- CHANGES.rst
- Riot/Modules/TabBar/MasterTabBarController.m
The complete security flow can be unfortunately triggered from 2 places: AuthVC and MasterTabBarC.
On a fresh app installation, during authentication, it was unexpectedly displayed from MasterTabBarC. This prevented authentication flow from completing. The app stayed on the launching animation.
This commit fixes this race.
> Complete Security: Make sure the authentication flow display it if auth is not complete yet

- CHANGES.rst
- Riot/Modules/SetPinCode/EnterPinCode/EnterPinCodeViewController.storyboard
- Riot/Modules/SetPinCode/EnterPinCode/EnterPinCodeViewController.swift
Shrinked spaces a bit for small screens. For 5S, it'll be like:
> Fix Pin Code Screen Layout

- CHANGES.rst
- Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
- Riot/Modules/Settings/Security/SecurityViewController.m
Before that, a device you just verified stayed red.
> Security screens: Update automatically shields when the trust changes

- CHANGES.rst
- Riot/Modules/Application/LegacyAppDelegate.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/928
When it happens (on a reset), tt displays the verify this session prompt we already have:
> Cross-signing: Detect when cross-signing keys have been changed

- CHANGES.rst
- Config/BuildSettings.swift
- Riot/Modules/Room/RoomViewController.m
If needed, this will help to disable the size prompt before uploading the image.
> BuildSettings: Centralise RoomInputToolbar compression mode setting

- CHANGES.rst
- Riot/Managers/Analytics/Analytics.m
It is probably broken since May 2019 and Matomo 6. Only the first value (StorePreload) was sent.
This PR avoids to create X instances of Matomo but only one.
> Analytics: Fix analytics in order to track performance improvements

- CHANGES.rst
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
Fixes https://github.com/vector-im/element-ios/issues/3790.
> RoomInputToolBar: Prevent long placeholder to be displayed on small devices

- CHANGES.rst
- Riot/Managers/Analytics/Analytics.h
- Riot/Managers/Analytics/Analytics.m
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Room/RoomViewController.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/941
Durations were corrupted when the app went to background. In this case, the app process is stopped but not the clock. It explains huge values we had for the animation screen.
MXProfiler handles this case now and avoid those crazy values.
This PR provides a new analytic that will be useful to track improvement on #3579.
> Use new MXProfiler to get and report accurate durations

- CHANGES.rst
- Config/AppConfiguration.swift
- Config/BuildSettings.swift
- BuildSettings: Fix warnings about some force_cast
- AppConfiguration: Restore modular widget events in rooms histories (they were added previously). I consider we still want them because of this: https://github.com/vector-im/element-ios/blob/develop/Config/AppConfiguration.swift#L57, I may be wrong.
> Improve App Config:

- CHANGES.rst
- Riot/Modules/Room/RoomViewController.m
fix https://github.com/vector-im/element-ios/issues/3864
> BuildSettings.messageDetailsAllowShare now hide /show action button in document preview

- Riot/Modules/Application/LegacyAppDelegate.m
It is useless here as we start the profiling of this task in RoomVC.
> PushNotificationService: Remove double start for profiling AnalyticsNoficationsTimeToDisplayContent

- CHANGES.rst
- Riot/Modules/Room/Views/Title/Preview/PreviewRoomTitleView.m
fix https://github.com/vector-im/element-ios/issues/3839
> Show user id in the room invite preview screen

- CHANGES.rst
- Riot/Modules/BugReport/BugReportViewController.m
fix https://github.com/vector-im/element-ios/issues/3819
I cannot do much as the popup is stretched with my iPhone SE (iOS 14) so the usr can tap send button (see screenshot). Nevertheless, the user can now tap on the background view to dismiss the keyboard.
> Dismiss description textview on user tap on background.

- CHANGES.rst
- Riot/Managers/PushNotification/PushNotificationService.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1009
Fix #3986
> Fix PushKit Crashes due to Undecryptable Call Invites

- CHANGES.rst
- Riot/Modules/Room/RoomViewController.m
> VoIP: Expose Dial Pad only if PSTN Supported

- CHANGES.rst
- Podfile
- Podfile.lock
- fastlane/Fastfile
This PR fixes 2 things.
Commits and their descriptions can be reviewed one by one.
1/ We need the `New Build System` introduced Xcode 10 so that $(inherited) in xcconfig files work as expected (https://stackoverflow.com/a/50731052). This is really important now because we moved everything to xcconfigs.
2/ All targets must use the same set of pods in order to build with the `New Build System`. This is a CocoaPods or Apple issue. This workaround is described at https://github.com/CocoaPods/CocoaPods/issues/8206#issuecomment-432252559.
> Make our Fastfile compatible with all new xcconfig

- fastlane/Fastfile
increment_build_number_in_xcodeproj does not do the job. It does not overwrite what is in the xcconfig file.
Xcodeproj::Config reads xcconfig files well but it breaks the format when saving changes. Hence, the usage of a old good regex :/
> Fastlane: Fix update_build_number with the new xcconfig file

- Riot/Assets/en.lproj/Vector.strings
“and  be” > “and be”
Signed-off-by: Peter Lewis <820394+peterlewis@users.noreply.github.com >
> Remove extraneous space from string

- CHANGES.rst
- Riot/Modules/Room/EmojiPicker/Data/Store/EmojiStore.swift
- RiotTests/EmojiStoreTests.swift
This adds the "common" short name to the list of strings to match the search text against. Previously, only the "other" short names were included in the comparison. This causes an issue for certain emojis like, for instance, the "Hundred Points Symbol" where the term "100" is *only* included in the common short name. As a result, the emoji did not previously show up when searching for "100".
Note that as a side effect, searching for "2" will now also return things such as the "dog2" emoji. This matches the behavior in the Element Android app and also in the emoji-mart Node.js package.
**Before**
**After**
Closes: #4063
> EmojiStore: Include short name when searching for emojis

- CHANGES.rst
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
Fix #4217
The change is similar as for EA: https://github.com/vector-im/element-android/pull/3140. We had the same failures as android.
It just makes the flow work. UX and even wording need more work but we need to fix all platform.
Tests in both direction
- 👍  iOS vs web with small account. Known issue: the QR option is not proposed on iOS
- 👍  iOS vs android
- 👍 👎  iOS vs web with my real account: verification works but secrets cannot be shared - this is not a new issue.
> Self-verification: Fix compatibility with Element-Web

- CHANGES.rst
- RiotNSE/NotificationService.swift
Fix #4222
Require https://github.com/matrix-org/matrix-ios-sdk/pull/1073.
Review without whitespace changes. There is reindentation in this PR.
> Notifications: Fix sender display name that can miss

- CHANGES.rst
- Config/BuildSettings.swift
Add gitter.im to default list of room directories
Fix https://github.com/vector-im/element-ios/issues/4233
> Add gitter.im to default list of room directories

- CHANGES.rst
- Riot/Managers/UserSessions/UserSessionsService.swift
- Riot/Modules/Application/AppCoordinator.swift
- Riot/Modules/TabBar/MasterTabBarController.m
- Riot/Modules/TabBar/TabBarCoordinator.swift
Fix #4395 
FTR: A crash occurred in `TabBarCoordinator` with `self.masterTabBarController.mxSessions.contains(matrixSession)` due to a Xcode 12.5 runtime issue with Objective-C interoperability, more information here >  https://forums.swift.org/t/objective-c-interoperability-type-mismatch/12464
> UserSessionsService: Fix room lists lost after a reset cache

- .github/workflows/ci.yml
- .gitignore
- CHANGES.rst
We use a local version of the MatrixKit podspec, MatrixKit.edited.podspec. This creates an issue in the computation of Podfile.lock. MatrixKit is not associated to a commit. `pod install` will be happy with its marketing version. It will not try to update if this marketing version matches with the one in the cache.
So delete the MatrixKit pod cache.
Generated Podfile.lock:
```
...
EXTERNAL SOURCES:
MatrixKit:
:podspec: MatrixKit.edited.podspec
MatrixSDK:
:branch: manu/test_ci_2
:git: https://github.com/matrix-org/matrix-ios-sdk.git
CHECKOUT OPTIONS:
MatrixSDK:
:commit: 32614df19df3ef43e77f25a06ddb0b04e910f90b
:git: https://github.com/matrix-org/matrix-ios-sdk.git
...
```
> GH Actions: Make sure we use the latest version of MatrixKit

- CHANGES.rst
- Riot/Modules/Contacts/DataSources/ContactsDataSource.m
> iPad Crashes when you select a contact in search and then collapse a section or clear the query text

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/SettingsViewController.m
This updates the auto theme explanation to make it more obvious that it follows
the system theme when on iOS 13+.
Fixes https://github.com/vector-im/element-ios/issues/2860
> Tweak auto theme message

- INSTALL.md
Small spelling mistake I saw in the [`INSTALL.md`](https://github.com/vector-im/element-ios/blob/develop/INSTALL.md#install-ruby) file
> fix spelling in INSTALL.md

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Storyboards.swift
- Riot/Generated/Strings.swift
- Riot/Modules/Home/HomeViewController.m
- Riot/Modules/KeyBackup/Setup/KeyBackupSetupCoordinator.swift
- Riot/Modules/KeyBackup/Setup/Success/KeyBackupSetupSuccessFromSecureBackupViewController.storyboard
- Riot/Modules/KeyBackup/Setup/Success/KeyBackupSetupSuccessFromSecureBackupViewController.swift
- Riot/Modules/Secrets/Recover/RecoverWithKey/SecretsRecoveryWithKeyViewController.swift
- Riot/Modules/Secrets/Recover/RecoverWithPassphrase/SecretsRecoveryWithPassphraseViewController.swift
- Riot/Modules/Secrets/Recover/RecoverWithPassphrase/SecretsRecoveryWithPassphraseViewModel.swift
- Riot/Modules/Secrets/Recover/SecretsRecoveryCoordinatorBridgePresenter.swift
- Riot/Modules/Secrets/Recover/SecretsRecoveryGoal.swift
- Riot/Modules/Secrets/Setup/RecoveryKey/SecretsSetupRecoveryKeyCoordinator.swift
- Riot/Modules/Secrets/Setup/RecoveryKey/SecretsSetupRecoveryKeyViewModel.swift
- Riot/Modules/SecureBackup/Setup/SecureBackupSetupCoordinator.swift
- Riot/Modules/SecureBackup/Setup/SecureBackupSetupCoordinatorBridgePresenter.swift
- Riot/Modules/Settings/Security/SecureBackup/SettingsSecureBackupTableViewSection.swift
- Riot/Modules/Settings/Security/SecureBackup/SettingsSecureBackupViewAction.swift
- Riot/Modules/Settings/Security/SecureBackup/SettingsSecureBackupViewModel.swift
- Riot/Modules/Settings/Security/SecureBackup/SettingsSecureBackupViewModelType.swift
- Riot/Modules/Settings/Security/SecureBackup/SettingsSecureBackupViewState.swift
- Riot/Modules/Settings/Security/SecurityViewController.m
- Riot/Modules/Settings/SettingsViewController.m
by making it work like element-web.
Fix #4430.
Require https://github.com/matrix-org/matrix-ios-sdk/pull/1129.
This section now represents a mix of the secure backup (4S) state and the key backup state. The different combination are listed in `SettingsSecureBackupViewState`.
In the nominal state, when secure backup and key backup and up, the 3 buttons do:
- "Restore from Backup": restore the message keys (megolm) from the key backup. If the key backup key is in the local 4S, no passphrase will be asked.
- "Delete Backup": delete the key backup
- "Reset": Reset the secure backup and the key backup. A new security phrase will be asked. Then, it will delete existing backups and create new ones.
The "Set up" button can do 2 things:
- if there is a secure backup but no key backup, it will …
> Security settings: Improve the SECURE BACKUP section

- CHANGES.rst
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
- Riot/Modules/Common/Recents/DataSources/RecentsDataSourceState.swift
Partial fix for #3777.
List computation is surprisingly shorter. It varies from 50 to 150ms on my account. It used to 200ms every time.
This is still slow but it is done now in a separate thread.
Must be reviewed by ignoring white spaces.
> Room lists: Avoid app freezes by building them on a separated thread

- CHANGES.rst
- Riot/Assets/Base.lproj/Main.storyboard
to fix iPhone 12 Pro Max layout issues
fixes https://github.com/vector-im/element-ios/issues/4516
> enable extendedLayoutIncludesOpaqueBars on the other tabs (not just Home)

- CHANGES.rst
- Riot/Modules/Application/LegacyAppDelegate.m
The app was crashing on launch when running on macOS with an M1 Mac.
It turns out that `viewDidLoad` is getting called before `applicationDidFinishLaunching` on macOS and so `Analytics` was requesting the app's version before it had been set.
> Fix crash when running on macOS with Apple Silicon.

- CHANGES.rst
- Riot/Modules/GlobalSearch/Views/DirectoryRecentTableViewCell.m
- Riot/Modules/PublicRoomList/DataSources/PublicRoomsDirectoryDataSource.h
- Riot/Modules/PublicRoomList/DataSources/PublicRoomsDirectoryDataSource.m
Fixes #4537. Note: this is only happening in `ShowDirectoryViewController` (the one accessed via the #+ button).
Renamed the following for more obvious explanation (open to better suggestions):
`moreThanRoomsCount` → `searchResultsCountIsLimited`
`roomsCount` → `searchResultsCount`
Implemented a new `roomsCount` to be the number of rooms that have actually been fetched (again, open to better name suggestions).
> Fix duplicate results in the rooms directory.

- CHANGES.rst
- Riot/Modules/Room/DataSources/RoomDataSource.m
Fixes #4552.
Deliberated whether to fix this here or in `MXKRoomBubbleTableViewCell`'s `prepareForReuse`. Decided it's probably better here as otherwise it would alter the cells of other users of MatrixKit when they had their own custom masks.
> Fix image and video thumbnail masks on cell reuse.

- CHANGES.rst
- Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewController.storyboard
- Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewController.swift
Fixes #4593.
- Disables autocorrection and spell checking.
- Trims whitespace from the string before processing.
> Fix identity server entry

- CHANGES.rst
- Riot/Modules/Authentication/AuthenticationViewController.m
Fixes #4606.
Remove the observer in `destroy` rather than `viewDidDisappear` so it only occurs once.
> Fix crash from potentially calling removeObserver multiple times.

- CHANGES.rst
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Contacts/ContactsTableViewController.m
This is a simple first pass at #4616 by moving `LegacyAppDelegate.refreshLocalContacts` into `ContactsTableViewController`. This way, local contacts won't get loaded until they are about to be displayed. This technically fixes the contacts part of #4484 too, although there is additional work to complete for that issue around the appearance of behaviour of the request.
Depends on https://github.com/matrix-org/matrix-ios-sdk/pull/1172
> Delay access to local contacts until they're needed for display

- CHANGES.rst
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/VoiceMessages/VoiceMessageAudioPlayer.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessageMediaServiceProvider.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessagePlaybackController.swift
#4655 - Allowing voice message playback to be controlled from the lock screen or the control center.
- Doing this in the `VoiceMessageMediaServiceProvider` so that it keeps working properly if the currently playing voice message (cell) gets scrolled off screen and deallocated.
#4656 - Stop recording voice message and go into locked mode when the application becomes inactive.
> Voice message additions

- CHANGES.rst
- Riot/Modules/Common/Recents/Views/RecentTableViewCell.h
- Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
- Riot/Modules/Common/Recents/Views/RecentTableViewCell.xib
- Riot/Modules/Contacts/Details/Views/RoomTableViewCell.h
- Riot/Modules/Contacts/Details/Views/RoomTableViewCell.m
- Riot/Modules/Contacts/Details/Views/RoomTableViewCell.xib
- Riot/Modules/Home/Views/RoomCollectionViewCell.h
- Riot/Modules/Home/Views/RoomCollectionViewCell.m
- Riot/Modules/Home/Views/RoomCollectionViewCell.xib
Fixes #4520.
Before and after screenshots below:
> Remove the green border from DM avatars.

- CHANGES.rst
- INSTALL.md
Previously the build guide mentioned updating the bundle identifiers in `project.yml`, however these are now in `Config/AppIdentifiers.xcconfig`.
> Add reference to AppIdentifiers.xcconfig in INSTALL.md

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGES.md
- CONTRIBUTING.md
- Riot/Modules/Authentication/SSO/SSOAuthenticationService.swift
- Riot/Modules/Authentication/SSO/SSOURLConstants.swift
- changelog.d/.gitignore
- changelog.d/2368.change
- changelog.d/4362.change
- changelog.d/4393.build
- changelog.d/4393.doc
- changelog.d/4520.change
- changelog.d/4575.change
- changelog.d/4596.build
- changelog.d/4642.change
- changelog.d/4655.change
- changelog.d/4656.change
- changelog.d/4671.change
- changelog.d/4671.feature
- changelog.d/4674.doc
- changelog.d/_template.md.jinja
- project.yml
- towncrier.toml
part of #4393.
Output with current changes:
✨ Features
- Voice messages: Remove labs setting and enable them by default. ([#4671](https://github.com/vector-im/element-ios/issues/4671))
🙌 Improvements
- Settings: The notifications toggle no longer detects the system's "Deliver Quietly" configuration as disabled. ([#2368](https://github.com/vector-im/element-ios/issues/2368))
- Room: Remove the green border from direct message room avatars. ([#4520](https://github.com/vector-im/element-ios/issues/4520))
- Settings: Adds a link to open the Settings app to quickly configure app notifications. ([#4575](https://github.com/vector-im/element-ios/issues/4575))
- VoIP: Additional changes on call tiles. ([#4642](https://github.com/vector-im/element-ios/issues/4642))
- Voice messages: Allow voice …
> Enable Towncrier

- Riot/Modules/Room/VoiceMessages/VoiceMessageAttachmentCacheManager.swift
- changelog.d/4748.bugfix
Switched to using a serial OperationQueue that waits on a semaphore for all async operations to finish before continuing to the next enqueued task.
Fixed CompletionCallbackKeys not being genereated properly when encountering failures.
> Fixes #4748 - Fixed cached callbacks race condition

- Riot/Modules/Application/AppCoordinator.swift
- changelog.d/4816.bugfix
fixes #4816.
There was three problems here: 
- `themeId` from the service can be nil if there was nothing in `RiotSettings`, but a default theme still gets set. So we should get them theme id from the theme.
- We should also remove the guard and always listen for theme updates even if no theme id was found.
- Again when publishing theme updates we were getting the themeId from the service and not the current theme.
> Fix SwiftUI theme updates

- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- changelog.d/4823.bugfix
> Ensure the last bubble component has a link before loading the preview.

- Riot/Modules/Authentication/SSO/SSOAuthenticationService.swift
- Riot/Modules/Authentication/SSO/SSOURLConstants.swift
- changelog.d/4785.bugfix
Fixes #4785
Signed-off-by: Chelsea Finnie <chelseafinnie@catalyst.net.nz>
> Fix redirection issue when logging in with single sign on. Fixes #4785.

- Podfile.lock
- Riot/Modules/Room/DataSources/RoomDataSource.m
- Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgBubbleCell.m
- Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgWithPaginationTitleBubbleCell.m
- Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgWithoutSenderInfoBubbleCell.m
- Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgBubbleCell.m
- Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithoutSenderInfoBubbleCell.m
- Riot/Modules/Room/Views/URLPreviews/URLPreviewView.swift
- Riot/Modules/Room/Views/URLPreviews/URLPreviewView.xib
- changelog.d/4855.bugfix
Fixes #4855 by adding a `reducedWidth` constant and using this when the timeline's width is 320 points or less. This only affected 4" devices, 4.7" and 5.4" devices are both fine width wise.
Note: I had a go at calling the height calculation in `addVerticalWhitespaceToString:forEvent:`, however I haven't yet figured out a reliable trigger to update the height here when going from the loading state to loaded.
> Fix URL preview width on 4" devices

- Riot/Modules/Application/LegacyAppDelegate.m
- changelog.d/4932.bugfix
Fix https://github.com/vector-im/element-ios/issues/4932.
By avoiding to call `[MXCrossSigning refreshStateWithSuccess]`  because it leads to a crash in Realm.
The check on `[UIApplication sharedApplication].applicationState` was already made by other methods like `checkPendingRoomKeyRequestsInSession`.
> AppDelegate: Fix a crash when backgrounding the app

- .github/PULL_REQUEST_TEMPLATE.md
- changelog.d/4920.doc
Close https://github.com/vector-im/element-ios/issues/4920
> Update PR template with a checkbox for accessibility and self review.

- .github/workflows/release-alpha.yml
- changelog.d/4937.build
iOS 15 requires AdHoc and Enterprise builds to be signed with a newer code signature format which is applied automatically by signing with macOS 11. [Apple Docs](https://developer.apple.com/documentation/xcode/using-the-latest-code-signature-format).
Fixes #4937.
> Fix Element Alpha on iOS 15.

- CHANGES.rst
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
The block passed into `[MXSession listenToEventsOfTypes:onEvent:]` is stored with a strong reference in the `listenerBlock` property of `MXSessionEventListener`. The method also returns the listener and it is then stored into the `roomTagsListenerByUserId` dictionary on `self`. Since a strong reference to `self` is captured in the block that means the block retains `self` (via the capture) and `self` retains the block (via `roomTagsListenerByUserId`) so there is a memory leak.
The bug is most easily reproduced during testing #4168 which involves closing the current and creating a new session.
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>
> Fix memory leak in [RecentsDataSource dataSource:didStateChange:]

- CHANGES.md
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Managers/Widgets/WidgetManager.m
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Authentication/AuthenticationViewController.xib
- Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewController.storyboard
- Riot/Modules/Settings/SettingsViewController.m
This PR standardises the spelling and casing of the following terms, across the codebase, as per #2655:
- homeserver
- identity server
- integration manager
While the issue mentions only user-visible text, this PR changes all instances of the terms, regardless of whether they're user-visible or not. I think there's value in standardising these terms even in non-user-visible text, so I went ahead and applied the changes to all text.
For reference, here's the script I used to find candidates for replacement: https://gist.github.com/psrpinto/b3787bae212d5d99649b517e2efd4dce
The same work has been done on element-web, in vector-im/element-web#17980
> Standardise casing of identity server and integration manager

- Riot/Managers/Analytics/Analytics.h
- Riot/Managers/Analytics/Analytics.m
- Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinatorBridgePresenter.swift
- changelog.d/4955.change
Fixes #4955, this PR adds an analytics value of accept/decline of the identity server's terms. Depends on matrix-org/matrix-ios-kit#925.
In the context of this PR, a decline is being treated as dismissing without accepting, whether that's by tapping decline, cancel or swiping to dismiss.
> Add an analytics value of accept/decline of identity server terms.

- Riot/Categories/MXKImageView.swift
- Riot/Categories/MXRoomSummary+Riot.m
- Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
- Riot/Modules/Home/Views/RoomCollectionViewCell.m
- RiotShareExtension/SupportingFiles/RiotShareExtension-Bridging-Header.h
- RiotShareExtension/target.yml
- changelog.d/4978.bugfix
Fixes #4978 so that colours are consistent across iOS and Web.
Note: The cause is that rooms generate their colour from the room ID, whereas spaces are doing it from the display name.
> Fix generated avatar colours not matching Element Web.

- Riot/Modules/Application/AppCoordinator.swift
- Riot/Modules/SplitView/SplitViewCoordinator.swift
- Riot/Modules/SplitView/SplitViewCoordinatorType.swift
- changelog.d/5084.bugfix
> Do not make the placeholder appearing when leaving a room on iPhone

- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Common/Recents/Service/MatrixSDK/RecentsListService.swift
- Riot/Modules/GlobalSearch/Rooms/DirectoryViewController.m
- Riot/Modules/Room/RoomCoordinator.swift
- Riot/Modules/Room/RoomViewController.m
- changelog.d/5079.bugfix
- changelog.d/5081.bugfix
- changelog.d/5083.bugfix
Fixes #5083, #5079, #5081. Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1283
> Fix DisabledRoomInputToolbarView / Room Previews / Favourites

- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/5071.bugfix
Fixes #5071. Depends on https://github.com/matrix-org/matrix-ios-kit/pull/944.
Now that the `currentAlert` property is weak, alerts need a local strong reference before presentation.
> Fix more button not working.

- Riot/Modules/Room/RoomViewController.m
- changelog.d/5067.feature
This adds a `textInputContextIdentifier` to the RoomViewController to save the current language per room.
> Remeber keyboard language for room

- .github/workflows/ci-build.yml
- .github/workflows/ci-tests.yml
- .github/workflows/release-alpha.yml
- changelog.d/5039.build
This limits GitHub actions to only allow each workflow to have a single concurrent run per branch. The result is that pushing new changes to a PR will automatically cancel older runs, freeing up more CI instances for us to use.
**Caveat:** The same effect will happen on `develop` too, so if 2 PRs are merged within a short time of each other, only the newer one would have CI results. I'm not sure if this is desirable behaviour or not?
> Add concurrency to GitHub workflows to auto-cancel older runs.

- Riot/Modules/Common/Recents/Service/MatrixSDK/RecentsListService.swift
- Riot/Modules/Common/Recents/Service/Mock/MockRoomSummary.swift
- changelog.d/5105.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5105.
The filtering was perfectly fine, however it wasn't being updated when switching modes, so would be incorrect until a sync response that modified a room summary (I think there was more to it than just that) came in.
> Refresh RecentsListService when switching modes.

- .github/ISSUE_TEMPLATE/bug.yml
- changelog.d/4984.misc
This is a follow-up PR to https://github.com/vector-im/element-android/pull/4076. @kittykat Here you go.
> Remove redundancy in heading in bug report issue form

- Config/BuildSettings.swift
- RiotNSE/NotificationService.swift
- changelog.d/5155.bugfix
Fixes #5155 
We clear the `content.badge` for the voip notification(leaving the badge the same) from the virtual room and we also send the read receipt so that the server value for the badge is also correct for subsequent notifications.
> Ignore badge updates for virtual rooms.

- Riot/Managers/PushNotification/PushNotificationService.m
- RiotNSE/NotificationService.swift
- changelog.d/5199.bugfix
The issue arrives here when the notification share extension is first initialised.
For calls, you can get multiple notifications close together (room join, call invite).
I think a few changes will be required to fix this issue fully.
What this updates:
- `MXBackgroundSyncService` init deletes/creates realm stores, if you have two separate notifications initialising this service at the same time realm can crash.
- Restores the callKit push token when configuring callKit after signout/signin.
Fixes #5199
> Fix voip calls after singout/signin

- Riot/Modules/Communities/Home/GroupHomeViewController.m
- Riot/Utils/EventFormatter.m
- changelog.d/5165.change
Fixes https://github.com/vector-im/element-ios/issues/5165. Depends on https://github.com/matrix-org/matrix-ios-kit/pull/954.
Most of the changes occur in the MatrixKit PR, however this applies the same changes to `GroupHomeViewController` which does it's own rendering for the long description field. Unlike `MXKEventFormatter`, this update also includes the image handler block to make sure `img` tags have local file urls for DTCoreText to be able add them as attachments.
> Use DTCoreText callback for sanitizing HTML in GroupHomeViewController.

- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/BubbleCells/VoiceMessage/VoiceMessageBubbleCell.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessageAttachmentCacheManager.swift
- changelog.d/4753.feature
* Allow audio file attachments to be played back inline by reusing the existing voice message UI
* Prevent unnecessary conversions if final file already exists on disk
> Audio file playback using voice message UI

- .github/workflows/ci-build.yml
- .github/workflows/release-alpha.yml
- changelog.d/pr-5112.build
Following on from #5101, only run the build CI on `develop` as the Tests & Alpha should be enough for PRs. I've also reverted the concurrency group for the Alpha build as it only runs on develop so doesn't need the check for when it is run on develop.
> Only run build CI on develop.

- Riot/Modules/Common/Views/CopyableLabel.swift
- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.xib
- changelog.d/4568.change
Fix #4568 
Matrix ID and display name are now copyable.
|With display name|Without display name|
|-|-|
|![Simulator Screen Shot - iPhone 12 Pro - 2021-12-10 at 14 01 59](https://user-images.githubusercontent.com/2205780/145578396-4614a4c4-6b56-43be-9ab0-38482d700aba.png)|![Simulator Screen Shot - iPhone 12 Pro - 2021-12-10 at 14 00 52](https://user-images.githubusercontent.com/2205780/145578400-ae715862-723a-4a3e-aa65-3fc3a90b6895.png)|
> RoomMemberDetailsViewController: Show user Matrix id and make it copyable

- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Do not pay attention to wrong colors I built from Xcode 13.2
> RoomMemberDetailsViewController: Fix user id theming

- Riot/Modules/Analytics/DecryptionFailureTracker.m
- changelog.d/5345.change
A quick update to reduce the grace period for decryption from 60s to 4s (that would already be super annoying for a user)
> Reduce grace period to report decryption failure

- .github/workflows/triage-move-labelled.yml
- .github/workflows/triage-move-unlabelled.yml
- .github/workflows/triage-priority-bugs.yml
- .github/workflows/triage-review-requests.yml
- changelog.d/5294.misc
> Fix graphql warnings in issue automation

- Riot/Modules/Room/RoomViewController.m
- changelog.d/5399.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5399
iPads show popovers rather than alert views and you need to specify the source of the popover so that it knows how to position/orientate itself.
> Fix crash uploading video ipad

- Riot/Modules/Call/CallViewController.m
- changelog.d/5451.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5451
> Call transfer selection should put the other person on hold.

- RiotSwiftUI/Modules/Template/SimpleScreenExample/Coordinator/TemplateSimpleScreenCoordinator.swift
- RiotSwiftUI/Modules/Template/SimpleScreenExample/MockTemplateSimpleScreenScreenState.swift
- RiotSwiftUI/Modules/Template/SimpleScreenExample/TemplateSimpleScreenModels.swift
- RiotSwiftUI/Modules/Template/SimpleScreenExample/TemplateSimpleScreenViewModel.swift
- RiotSwiftUI/Modules/Template/SimpleScreenExample/TemplateSimpleScreenViewModelProtocol.swift
- RiotSwiftUI/Modules/Template/SimpleScreenExample/Test/UI/TemplateSimpleScreenUITests.swift
- RiotSwiftUI/Modules/Template/SimpleScreenExample/Test/Unit/TemplateSimpleScreenViewModelTests.swift
- RiotSwiftUI/Modules/Template/SimpleScreenExample/View/TemplateSimpleScreen.swift
- RiotSwiftUI/Modules/Template/SimpleUserProfileExample/View/TemplateUserProfile.swift
- Tools/Templates/createSwiftUISimpleScreen.sh
- changelog.d/5349.misc
The template is generated from the single screen template, with the service removed, but the reducer left in place for some basic state management. Fixes #5349.
> Add a simple screen SwiftUI template.

- Riot/Modules/MediaPicker/MediaPickerViewController.m
- changelog.d/5465.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5465
Multiple code paths that use `PHPhotoLibrary` hadn't yet requested authorization which happens asynchronously with a UI prompt.  Updating to reload code to make sure it includes the permissions check, no matter the route into the reload.
> Make sure all code paths that use PHPhotoLibrary request authorization.

- Riot/Modules/Room/RoomViewController.m
- changelog.d/4524.bugfix
Fixes #4524 
The `isBubblesTableScrollViewAtTheBottom` method was being used in `viewDidLayoutSubviews` to determine, whether to scroll to the bottom-most bubble. The issue is however that `viewDidLayoutSubviews` may change the size of the view, making `isBubblesTableScrollViewAtTheBottom` give the wrong result.
To solve this we need to capture the value of `isBubblesTableScrollViewAtTheBottom` during `viewWillLayout` and use that value in `viewDidLayoutSubviews`
> Scroll to the bottom of timeline automatically

- Riot/Modules/Spaces/SpaceList/SpaceListViewController.storyboard
- Riot/Modules/Spaces/SpaceList/SpaceListViewController.swift
fix #5323
@niquewoodhouse we are using a indicator presenter and each time the list is refreshed this presenter is shown then hidden animated. The refresh of the list itself takes long (some few ms) but it takes 300ms to show the indicator and 300ms to hide it. So the space list loses its responsiveness for at least 600ms.
To solve this issue I would rather use an activity indicator alongside the View title:
> Space list loses responsiveness upon refresh

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Managers/Theme/Theme.swift
- Riot/Managers/Theme/ThemeService.m
- Riot/Managers/Theme/Themes/DarkTheme.swift
- Riot/Managers/Theme/Themes/DefaultTheme.swift
- Riot/Modules/Common/Avatar/AvatarView.swift
- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Home/ContextMenuSnapshotPreviewViewController.swift
- Riot/Modules/Home/HomeViewController.m
- Riot/Modules/Home/RoomContextPreviewViewController.swift
- Riot/Modules/Room/Search/RoomSearchViewController.m
- Riot/SupportingFiles/Riot-Bridging-Header.h
- RiotSwiftUI/Modules/Room/LocationSharing/View/LocationSharingView.swift
- RiotSwiftUI/Modules/Room/NotificationSettings/View/RoomNotificationSettings.swift
- RiotSwiftUI/Modules/Room/PollEditForm/View/PollEditForm.swift
- RiotSwiftUI/RiotSwiftUI-Bridging-Header.h
- RiotSwiftUI/target.yml
- RiotSwiftUI/targetUITests.yml
- changelog.d/4883.bugfix
- changelog.d/4883.build
- fastlane/Fastfile
Fixes #4883.
- Navigation bars are assigned a bar appearance for both standard and scroll edges.
Fixes #4884
- Table view header padding is set to 0.
Fixes #4941
- Home space icon would update with incorrect content mode.
Fixes #5177
- Adopt the new tab bar style when scrolled to the bottom of a list.
- Fix room list jumping when long pressing a room on the Home tab by using the standard context menu on iOS 13+.
- Update Fastfile for CI
A couple of notes on the context menu:
- I've used SF Symbols as the outlined style is more familiar in UIKit's context menus, however some shapes are inconsistent with our other images 😕
- It is only added on the Home tab in this PR, but Favourites / People / Rooms could be updated if desired.
- The menu items are labeled are as follows:
| Enable | …
> Fix bugs when building with Xcode 13.

- RiotShareExtension/Sources/ShareExtensionShareItemProvider.swift
- changelog.d/3636.bugfix
Fixes #3636 
This adds a check on png/jpeg UTType with the same priority as kUTTypeImage (which already worked properly when sharing with UIImage). 
Reproducing issue should work with any app sharing an image file URL rather than an UIImage.
Screenshot of the receiving web app, first message is without this fix :
> Handle jpeg and png UTType properly

- CHANGES.rst
- Riot/Modules/Room/Views/BubbleCells/RoomMembershipCollapsedBubbleCell.m
This commit switches to displaying the target user's avatar for collapsed membership changes which addresses the avatar issue reported in #4102.
This now brings the avatar display on par with the Element web app. Collapsed membership changes use the target avatar, expanded changes use the sender avatar. Note that the web app currently still has more sophisticated logic around combining membership changes (e.g. "... invited and joined") which allows it to show less collapsed avatars in certain cases.
Depends on: matrix-org/matrix-ios-kit#793
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>
> Show target user avatars for collapsed membership changes

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- changelog.d/5426.bugfix
- Uses readable session states when logging for missed places.
- Adds some error logs around `event/(null)` requests.
- Updates in `MXKAccount` to gracefully pause the session on certain states.
Fixes #5426 and requires https://github.com/matrix-org/matrix-ios-sdk/pull/1359
> Handle session states better

- Riot/Managers/URLPreviews/Core Data/URLPreviewStore.swift
- Riot/Modules/Application/AppCoordinator.swift
- Riot/Modules/MatrixKit/Models/Contact/MXKContactManager.m
- Riot/Modules/MatrixKit/Models/MXKAppSettings.m
- changelog.d/5498.change
Fixes #5498 
Application-side changes corresponding to [SDK changes](https://github.com/matrix-org/matrix-ios-sdk/pull/1361). This means excluding some application-specific files (e.g. Core Data), as well as triggering a blanket exclusion of all top-level directories on app start. Note that if this is the first time a user has installed the app, some folders created after app start and not explicitly excluded will be backed up to iCloud. Once the app is relaunched, the newly created folders will not be excluded as well and removed from the backup.
> Exclude all items from iCloud backup

- Riot/Modules/Settings/SettingsViewController.m
Cherry picks [9b5b274](https://github.com/vector-im/element-ios/pull/5542/commits/9b5b27402222e6ea5b040ac0c7bcee1c9eb1dc48) and [8018b54](https://github.com/vector-im/element-ios/pull/5542/commits/8018b541cca4b2ce7954aca264a168afc1c7dc02) for the hotfix from #5542.
> Hotfix: Move bubbles to labs

- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/5463.bugfix
Fixes #5463. Fixes #5551
A few settings toggles were using `UIControlEventValueChanged` for their action, but `getLabelAndSwitchCell:forIndexPath:` clears the action on `UIControlEventTouchUpInside`, so it was possible that toggling a switch could change two settings after cell reuse.
> Use UIControlEventTouchUpInside for all toggles in SettingsViewController

- Riot/Modules/Room/MXKRoomViewController.h
- Riot/Modules/Room/MXKRoomViewController.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
- Riot/Modules/Threads/Thread/ThreadViewController.swift
- changelog.d/5564.bugfix
Following on from https://github.com/matrix-org/matrix-ios-sdk/pull/1358 it is possible in 1.8.0 TF for the [query](https://github.com/matrix-org/matrix-ios-sdk/blob/7be07981c3f2932b0205797f234982ca32da7dff/MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m#L819) to a room's encryption algorithm to occur before that algorithm has been stored in the realm when sending an image. When sending a text message the algorithm gets stored when `shareEncryptionKeys` is called before a typing notification is created.
This PR mimics the same behaviour by calling `shareEncryptionKeys` when the composer's action menu is displayed as none of those events send typing notifications. That said, I think some deeper thought needs to go into the timing of all of this if we are going to rely …
> Fix for images sometimes being sent unencrypted in an encrypted room.

- Riot/Modules/Room/Views/BubbleCells/RoomBubbleCellLayout.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/BubbleRoomCellLayoutConstants.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/BubbleRoomCellLayoutUpdater.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/BubbleRoomTimelineCellDecorator.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/FileWithoutThumbnail/Common/FileWithoutThumbnailCellContentView.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/FileWithoutThumbnail/Incoming/FileWithoutThumbnailIncomingBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/FileWithoutThumbnail/Outgoing/FileWithoutThumbnailOutoingWithoutSenderInfoBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/Location/Incoming/LocationIncomingBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/Location/Outgoing/LocationOutgoingWithoutSenderInfoBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/Poll/Incoming/PollIncomingBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/Poll/Outgoing/PollOutgoingWithoutSenderInfoBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/Poll/PollBaseBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/TextMessage/Common/TextMessageBaseBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/TextMessage/Common/TextMessageBubbleCellContentView.xib
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/TextMessage/Incoming/TextMessageIncomingBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/TextMessage/Outgoing/TextMessageOutgoingWithoutSenderInfoBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/VoiceMessage/Incoming/VoiceMessageIncomingBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/Cells/VoiceMessage/Outgoing/VoiceMessageOutgoingWithoutSenderInfoBubbleCell.swift
- Riot/Modules/Room/Views/BubbleCells/Styles/Bubble/RoomMessageBubbleBackgroundView.swift
- changelog.d/5409.misc
> Message bubbles: Use layout constants instead magic numbers

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Authentication/AuthenticationCoordinator.swift
- Riot/Modules/Authentication/AuthenticationCoordinatorProtocol.swift
- Riot/Modules/Authentication/AuthenticationViewController.h
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/LaunchLoading/LaunchLoadingViewController.swift
- Riot/Modules/LaunchLoading/LaunchLoadingViewController.xib
- Riot/Modules/Onboarding/OnboardingCoordinator.swift
- Riot/Modules/TabBar/MasterTabBarController.m
- changelog.d/5621.change
This will allow other screens to be presented during onboarding without having the spinner thrown on top of them. Additionally moves key verification out of a bridge presenter in AuthenticationVC and into the AuthenticationCoordinator.
I may end up moving both the spinner and the key verification the `OnboardingCoordinator` instead of the `AuthenticationCoordinator`, but this seems like a decent sized PR for now and fixes a couple of potential issues with the spinner presentation that would be great to get into the next release.
Fixes #5621.
> Use a different green spinner during onboarding

- Riot/Modules/Room/TimelineCells/BaseRoomCell/BaseRoomCell.swift
- Riot/Modules/Room/TimelineCells/Common/MXKRoomBubbleTableViewCell.h
- Riot/Modules/Room/TimelineCells/Common/MXKRoomBubbleTableViewCell.m
- Riot/Modules/Room/TimelineCells/Styles/Bubble/Cells/TextMessage/Common/TextMessageBaseBubbleCell.swift
- changelog.d/5553.bugfix
Fix https://github.com/vector-im/element-ios/issues/5553
Also fix sender name label not tappable.
> Message bubbles: Fix edited text message `edited` link not working

- Riot/Modules/Home/Views/AccessibleCollectionView.swift
- Riot/Modules/Home/Views/RoomCollectionViewCell.m
- Riot/Modules/Home/Views/TableViewCellWithCollectionView.m
- Riot/Modules/Home/Views/TableViewCellWithCollectionView.xib
- changelog.d/1433.bugfix
First step at improving voiceover support on the Home tab (#1433). The collection view cells are now set as accessibility elements with an appropriate label and the table view cells and collection views are all hidden.
It is by no means perfect whilst swiping through the cells, particularly when the data source paginates more rooms, but it at least feels somewhat usable now.
Next steps for future PRs
- Allow 2-finger swipes between sections.
- Add the + button as an element.
- Tidy up labels for section headers.
> Expose room cells to voiceover on Home tab.

- DesignKit/Source/FontsSwiftUI.swift
- DesignKit/Source/FontsUIkit.swift
- DesignKit/Variants/Fonts/ElementFonts.swift
- changelog.d/5027.bugfix
Fixes #5027 by defining SwiftUI fonts natively alongside the UIKit fonts.
I've marked everything as available for iOS 13, so when iOS 12 support is dropped most of the properties can be be reverted back to 1 liners.
> Add a `SharedFont` type to `ElementFonts`.

- Riot/Modules/GlobalSearch/DataSources/UnifiedSearchRecentsDataSource.m
- changelog.d/5672.bugfix
Reverts a change to `UnifiedSearchRecentsDataSource ` that removed the `init` due to a "Implementing unavailable method" warning. This PR adds it back and renames it to `initWithMatrixSession:recentsListService:`.
Whilst the `init` it was marked as unavailable, it seemingly was being used by the available init.
> Revert change to UnifiedSearchRecentsDataSource

- Riot/Modules/Application/LegacyAppDelegate.m
- changelog.d/5674.bugfix
Moved set language and fallback language to willFinishLaunchingWithOptions()
Fixes #5674
> Fix L10n not always defaulting to English

- Riot/Modules/Communities/GroupsViewController.m
- Riot/Modules/Favorites/FavouritesViewController.m
- Riot/Modules/Home/HomeViewController.m
- Riot/Modules/Home/VersionCheck/HomeViewControllerWithBannerWrapperViewController.swift
- Riot/Modules/People/PeopleViewController.m
- Riot/Modules/Rooms/RoomsViewController.m
- Riot/Modules/TabBar/MasterTabBarController.m
- Riot/Modules/TabBar/MasterTabBarItemDisplayProtocol.swift
Fixes https://github.com/vector-im/element-ios/issues/5489
It appearsd we do not sue the VC title as setting the title causes text to display on the tabs, which we don't want. Creating a protocol to be a bit more explicit rather thatn the current approach of using the accessibilityLabel.
> Fix tab bar title localisation

- Config/BuildSettings.swift
- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Analytics/PHGPostHogConfiguration.swift
- RiotSwiftUI/Modules/AnalyticsPrompt/Coordinator/AnalyticsPromptCoordinator.swift
- changelog.d/5687.misc
Adds an `AnalyticsConfiguration` to contain all settings in a single object.
I've nested this inside of `BuildSettings` to avoid needing to add it to every target that contains `BuildSettings` as that seemed more sensible to me, but happy to change this if not.
Fixes #5687
> Disable the default analytics configurations for forks.

- Riot/Modules/Room/DataSources/RoomDataSource.m
- changelog.d/5694.bugfix
Fix #5694 (won't be autoclosed)
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1381
> Room: Fix scrolling to bottom on back pagination

- Riot/Modules/People/Views/InviteRecentTableViewCell.h
- Riot/Modules/People/Views/InviteRecentTableViewCell.m
- Riot/Modules/People/Views/InviteRecentTableViewCell.xib
- changelog.d/5249.change
> Remove exclamation mark badge in invites cell

- Config/BuildSettings.swift
- Riot/Modules/Common/ActivityPresenters/ToastUserIndicatorPresenter.swift
- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Common/Toasts/RoundedToastView.swift
- changelog.d/5663.change
Resolves #5663 
| iPhone 8 portrait | iPhone 8 landscape |
|------------------|---------------------|
| ![Simulator Screen Shot - iPhone 8 - 2022-02-22 at 11 49 10](https://user-images.githubusercontent.com/3922159/155129171-d9e4d95c-d525-4fa1-bfb1-555fc03a2443.png) | ![Simulator Screen Shot - iPhone 8 - 2022-02-22 at 11 49 12](https://user-images.githubusercontent.com/3922159/155129175-001886fc-0c01-4ca4-b249-10effe65c997.png) |
| iPhone 13 dark 1 | iPhone 13 dark 2 |
|------------------|------------------|
| ![Simulator Screen Shot - iPhone 13 - 2022-02-22 at 11 51 03](https://user-images.githubusercontent.com/3922159/155129319-a36a6ebc-10c1-4207-92b0-3e13109687b7.png) | ![Simulator Screen Shot - iPhone 13 - 2022-02-22 at 11 51 …
> Enable home activity indicator

- Riot/Modules/Room/RoomViewController.xib
- changelog.d/5691.bugfix
Switched the `RoomViewController` `previewHeaderContainer` to the safe area layout guide for its top constraint.
> Fixes partially hidden room invitation header.

- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- Riot/Modules/Room/DataSources/RoomDataSource.m
- changelog.d/5581.bugfix
Fixes #5581 by correcting the tag type of room creation event cell
Additionally enable the conversation start header for every user, not only those that created the room
| Screenshot |
|-------------|
| ![IMG_6C75865CE226-1](https://user-images.githubusercontent.com/3922159/155732015-4bd1e24b-35d0-46f1-957f-6614bd99de69.jpeg) |
> Show DM/room start header for every user

- Podfile.lock
- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Analytics/AnalyticsScreen.swift
- Riot/Modules/Analytics/AnalyticsUIElement.swift
- Riot/Modules/Analytics/Helpers/UserProperties+Element.swift
- Riot/Modules/Analytics/PostHogAnalyticsClient.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Threads/ThreadList/ThreadListViewController.swift
- changelog.d/5365.change
Adapts to the latest changes in [matrix-org/matrix-analytics-events](https://github.com/matrix-org/matrix-analytics-events) repository. Adds a simplified initializer for `AnalyticsEvents.UserProperties` class, which is splitting all Web properties.
Fixes #5365 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1384 & https://github.com/matrix-org/matrix-analytics-events/pull/49.
> Threads: Analytics

- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- RiotTests/AnalyticsTests.swift
- changelog.d/5712.bugfix
Fixes #5712 by altering the font for only the `event.content.body` in the whole event string rendered.
> Fix Font Size for Emoji Only Replies

- Riot/Modules/Common/Recents/RecentsViewController.m
- changelog.d/5727.bugfix
This appears to have stopped working since the changes to the room list pagination (although there might be some intermediate changes between 1.6.12 and now):
https://github.com/vector-im/element-ios/commit/2ac2c981fc7976737432ed41f04daa3db0c73f84#diff-8f61a94c5dc8f433447c91a5e149cf49ac2db96dc1217ff17d0759ad6da9183eL1439-R1471
This is the most obvious fix, but happy to update if there is a better solution that wouldn't call this method any time the data source changes.
Fixes #5727
> Fix emptyView never being shown in RecentsViewController.

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Utils/EventFormatter.m
- changelog.d/5739.change
Resolves #5739 
After investigating reports of [missing messages](https://github.com/vector-im/element-ios/issues/5374) I noticed that messages that fail to be formatted (for whatever reason, the formatting code has hundreds of lines of code), the formatting error is never logged and the message is not rendered at all on the timeline, appearing as if it was never delivered.
Whilst we want to understand why formatting of messages fails and thus fix the root cause of this behaviour, we first need to acquire more logs when this happens.
Additionally we need to signal to the user an error has occured, because in this case it is more dangerous to fail silently and make it look like a message was never delivered. See screenshot for comparison.
With these changes in place we can use future …
> Track failed creation of attributed strings

- Riot/target.yml
- changelog.d/pr-5759.i18n
Adds all languages with a >80% translation coverage.
> Add missing languages.

- Config/BuildSettings.swift
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Managers/Settings/RiotSettings.swift
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellDataWithAppendingMode.m
- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- Riot/Modules/Room/Search/DataSources/RoomSearchDataSource.m
- Riot/Modules/Settings/SettingsViewController.m
- Riot/Utils/EventFormatter.m
- changelog.d/5726.change
Closes #5726 
Note: Enabling or disabling this setting will require a clear cache in order to be immediately effective (otherwise it will only apply for new events or after someone updates their profile in `enabled` case).
> Use only latest profiles in the room timeline (labs)

- RiotSwiftUI/Modules/Common/ErrorHandling/AlertInfo.swift
- RiotSwiftUI/Modules/Common/ErrorHandling/ErrorAlertBuilder.swift
- RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingModels.swift
- RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingViewModel.swift
- RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingViewModelProtocol.swift
- RiotSwiftUI/Modules/Room/LocationSharing/View/LocationSharingView.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollModels.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollViewModel.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollView.swift
- changelog.d/pr-5742.change
Adds a generic `ErrorAlertType` struct that can be used to describe an Alert to be presented. We can pass an `NSError` to the init to use it in a similar way to the existing `errorPresenter` in the UIKit templates. Additionally replaces `LocationSharingErrorAlertInfo` and `TimelinePollErrorAlertInfo` with this new type.
@stefanceriu WDYT about the style of having the `ErrorAlertType.alert` property where the type creates and returns the view? I'm perfectly happy with this when it's simple, but happy to revert it back to the previous commit where there is only a convenience property for the `messageText` if you prefer?
Note: I haven't tested the errors for polls/location sharing.
> Add generic SwiftUI Error type

- RiotSwiftUI/Modules/Common/ErrorHandling/AlertInfo.swift
Small bugfix for #5742 that resulted in a disabled button when the `action` was `nil`.
> Fix alert button action when not set.

- Riot/Modules/Room/RoomCoordinator.swift
- Riot/Modules/SplitView/SplitViewCoordinator.swift
- Riot/Modules/SplitView/SplitViewPresentable.swift
- Riot/Modules/TabBar/TabBarCoordinator.swift
- changelog.d/5752.bugfix
Fixes #5752 
The issue of missing spinner is actually a layout issue caused by split view controller allowing multiple nested navigation controllers. Previously when a toast was presented on a navigation controller, it was added on top of the navigation bar and anchored to the title, which could happen before the navigation controller itself was added to the view controller hierarchy. Once the navigation controller was properly added to the hierarchy, the parent navigation took control over the navigation bar and placed it on top of the spinner as well as invalidating any previously set constraints.
To solve for this issue the app needs to get hold of the ever-present top navigation controller, owned by the split view controller. On iPhones, this is the navigation controller that holds …
> Use split controller's top navigation controller to present toasts

- Riot/Modules/Authentication/AuthenticationCoordinator.swift
- Riot/Modules/Authentication/AuthenticationCoordinatorProtocol.swift
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Onboarding/OnboardingCoordinator.swift
- changelog.d/5879.bugfix
The social buttons were never hidden during registration after having added them to the registration page. Additionally 
- Hides the navigation back button during registration to enforce use of the custom bar buttons.
- Make sure custom server entry is disabled if navigating back to the use case screen and choosing a different option.
Fixes #5789
> Fix social button visibility during registration

- Riot/Modules/Room/RoomViewController.m
- changelog.d/5800.bugfix
Fixes #5800 
This will effectively refresh on data source updates (i.e. RoomState updates), it seems fine performance-wise, we might be able to look into a finer mechanism if needed, but I'm not sure how easy it would be.
> Room: Refresh header when call actions become available

- Riot/Modules/Common/ActivityIndicator/UserIndicatorPresenterWrapper.swift
- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Room/RoomViewController.m
- changelog.d/5801.bugfix
Fixes #5801 
The architecture around user indicators is still not quite ideal, now that we have global user indicators it becomes problematic when view controllers attempt to display something whilst they are not actually visible. For example most view controllers subclass from `MXViewController` which monitors the `MXSession` at all times and starts / stops activity indicator accordingly.
For now I am simply adding some flags to avoid presenting when the view controller is not visible, but this is not a robust enough solution and something else will need to be put in place. In an idea case the loading is more centralized and each room communicates its state changes via some delegate, but this obviously requires a bigger change.
Another angle to this is removing all the state change …
> Do not show user indicators when the view controller is not visible

- Riot/Managers/Theme/Theme.swift
- Riot/Managers/Theme/Themes/DarkTheme.swift
- Riot/Managers/Theme/Themes/DefaultTheme.swift
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Common/SwiftUI/VectorHostingController.swift
- RiotSwiftUI/Modules/Onboarding/UseCase/Coordinator/OnboardingUseCaseSelectionCoordinator.swift
- RiotSwiftUI/Modules/Spaces/SpaceSettings/SpaceSettings/Coordinator/SpaceSettingsCoordinator.swift
- changelog.d/pr-5826.api
`scrollEdgesAppearance` → `scrollEdgeAppearance`
Not sure where I got the plural version from.
> Make scrollEdgesAppearance singular to match UIKit

- Riot/Managers/Settings/RiotSettings.swift
- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Analytics/AnalyticsSpaceTracker.swift
- Riot/Modules/Analytics/AnalyticsUIElement.swift
- Riot/Modules/Spaces/SpaceList/SpaceListViewModel.swift
- changelog.d/5401.change
fix https://github.com/vector-im/element-ios/issues/5401
> Instrument metrics for iOS for the IA project #5401

- Riot/Modules/Favorites/FavouritesViewController.m
- Riot/Modules/Home/HomeViewController.m
- Riot/Modules/People/PeopleViewController.m
- Riot/Modules/Rooms/RoomsViewController.m
- changelog.d/5547.bugfix
Fixes #5547 
Fix crash where we try to get the number of rows in a section before we ensure the tableview / collectionview has enough sections to begin with.
This would ideally be extracted even further out (3.5x code duplication) into the `RecentsViewController`, but the parent does not seem to know much about pagination so the API might be displaced there.
As to why the tableview / collectionview does not have adequate section even though the `willDisplayCell` is called, this is entirely because of the async throttler. An easy way to reproduce this bug is by forcing `[tableView reloadData]` inside of the throttle block.
> Fix crash when pressing tabs

- Riot/Categories/Bundle.swift
- Riot/Modules/Analytics/Analytics.swift
- RiotShareExtension/Shared/ShareDataSource.h
- RiotShareExtension/Shared/ShareDataSource.m
- RiotShareExtension/Shared/ShareManager.m
- RiotShareExtension/Sources/ShareExtensionRootViewController.m
- RiotShareExtension/Sources/ShareItemSender.m
- SiriIntents/IntentHandler.m
- changelog.d/5805.bugfix
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1414
Initial attempts in this PR were to fix the memory issues seen in the share extension. Unfortunately this has been abandoned for now due to the `MXSession` created when sending having a log of strong references to it from all over the place. The PR does include some changes to reduce memory usage as some parts of the share extension are used for message forwarding inside the app.
Additionally there are now strong references to the `MXRoom`s being used in the Share extension and Siri extension as the retain cycles on these have been fixed in the SDK PR above.
> Disable crash logging in the Share Extension, and reduce memory usage.

- Riot/Modules/Application/AppCoordinator.swift
- Riot/Modules/Application/LegacyAppDelegate.m
- changelog.d/5846.bugfix
The app was crashing whenever it was in a soft logout state due to a nil `MXSession` being used to try and remove `UserSession` (after a valid call to remove the session had already been made). There is more work to be done as there is also a crash when tapping the "Clear all data" button (#5881), but that looks more involved and I wanted to get this submitted before the next RC so that it at least allows users to log back in without having a crash loop.
Fixes #5846
> Fix crash trying to remove a UserSession for a nil MXSession.

- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- changelog.d/5873.bugfix
Resolves #5873 and depends on https://github.com/matrix-org/matrix-ios-sdk/pull/1416
If there are no locally stored filters (see https://github.com/matrix-org/matrix-ios-sdk/pull/1416), do not report an incompatibility when `checkSyncFilterCompatibility` is called. Otherwise all cache would be cleared and a full sync triggered.
> Do not clear cache if there are no stored filters

- Riot/Modules/Room/RoomViewController.m
Small change that will prevent the "left room" message from showing multiple times, which is caused by the room view controller reporting `roomViewControllerDidLeaveRoom` to its delegate more than once (because it tells delegate directly as well as monitors mxsession updates passively)
> Prevent "left room" message from showing twice

- Riot/Modules/Application/LegacyAppDelegate.m
- changelog.d/5472.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5472
The green spinner should not hide for `MXSessionStateProcessingBackgroundSyncCache`.
> Green spinner hidden too early

- Riot/Modules/Application/LegacyAppDelegate.h
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Communities/Home/GroupHomeViewController.m
- Riot/Modules/DeepLink/UniversalLinkParameters.swift
- changelog.d/5883.bugfix
Fixes #5883 
Apparently a deeplink can be opened with only a fragment and no url, as seen for example [here](https://github.com/vector-im/element-ios/blob/96c3ed8df300be5fd743eb0cf6a832644b0ee976/Riot/Modules/Application/LegacyAppDelegate.m#L1268). This means that the `UniversalLinkParameters` must be able to accept nil urls by design. Otherwise the obj-c code may inject nil value (compiler does not prevent obj-c passing nil value to non-nil swift code) and the app crashes.
> Prevent crash when searching for rooms

- Riot/Modules/Authentication/AuthenticationViewController.h
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Authentication/AuthenticationViewController.xib
- changelog.d/5875.bugfix
Fixes #5875
Ensure that login / register button is always visible by separating the button and "forgot password" onto two separate lines.
|--------|------|
| ![159138005-7b7d6925-6042-4f69-a411-a0413e81f522](https://user-images.githubusercontent.com/3922159/159474755-0d39609f-e07a-4608-917a-0d79176301ad.jpeg) | ![Simulator Screen Shot - iPhone 13 - 2022-03-22 at 11 29 30](https://user-images.githubusercontent.com/3922159/159474879-38534c44-2a44-402d-b11d-5e74622ae4bc.png) |
The constraints in the xib file are quite messy so I just embedded the main 3 components (submit, skip, forgotten button) into stack views and replicating the existing distances. Below are a number of different views to make sure there are no collisions
| Login | Register | With Skip | Double length …
> Ensure the login button is always visible

- Config/BuildSettings.swift
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Managers/Widgets/WidgetManager.h
- Riot/Managers/Widgets/WidgetManager.m
- Riot/Model/HomeserverConfiguration/HomeserverConfigurationBuilder.swift
- Riot/Model/HomeserverConfiguration/HomeserverJitsiConfiguration.swift
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Integrations/Widgets/Jitsi/JitsiService.swift
- Riot/Modules/Room/RoomViewController.m
- RiotTests/HomeserverConfigurationTests.swift
- changelog.d/5837.change
Fixes #5837 
This allows to remove default Jitsi URL from BuildSettings.
> Allow empty Jitsi default url in BuildSettings

- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Home/HomeViewController.m
- Riot/Modules/MatrixKit/Controllers/MXKRecentListViewController.h
- Riot/Modules/MatrixKit/Controllers/MXKRecentListViewController.m
- Riot/Modules/Spaces/SpaceRoomList/SpaceChildRoomDetail/SpaceChildRoomDetailBridgePresenter.swift
- changelog.d/5771.change
> Update suggested room preview to behave the same way in all cases

- RiotSwiftUI/Modules/Common/Util/RoundedBorderTextEditor.swift
- RiotSwiftUI/Modules/Common/Util/RoundedBorderTextField.swift
- RiotSwiftUI/Modules/Spaces/SpaceCreation/SpaceCreationEmailInvites/View/SpaceCreationEmailInvites.swift
- RiotSwiftUI/Modules/Spaces/SpaceCreation/SpaceCreationSettings/View/SpaceCreationSettings.swift
- RiotSwiftUI/Modules/Spaces/SpaceSettings/SpaceSettings/View/SpaceSettings.swift
- changelog.d/pr-5910.api
These Bindings were only ever read and never mutated so regular properties are cleaner here.
Additionally I removed the explicit `init` as the synthesised init does everything we need (but happy to revert that if preferred).
> Remove unused Bindings in RoundedBorderTextField/Editor.

- Riot/Modules/Room/MXKRoomViewController.m
- Riot/Modules/Room/RoomViewController.m
- changelog.d/5906.bugfix
Relates to #5906
There are a few things going on here, and all related to an insane amount of spaghetti layout code in RoomViewController. Often time a simple sounding method will internally call other less innocent code, escalating the performance cost This is what I observed:
1. On each `viewDidLayoutSubview` we will try to scroll back to the bottom, even if the size of the view has not really changed. The scrolling itself would be fine, but it is one of those methods that trigger a number of other heavy updates (e.g. `updateViewControllerAppearanceOnRoomDataSourceState`). Note that `viewDidLayoutSubview` is called every time you type a character, which means that when typing fast we are essentially doing all of this expensive work many times per second.
2. I think that a [recent …
> Fix typing performance by avoiding expensive UI operations

- Riot/Managers/Call/CallPresenter.swift
- changelog.d/1575.bugfix
> Fix app not leaving call when Jitsi widget is removed

- Riot/Modules/MatrixKit/Utils/MXKTools.m
- changelog.d/pr-5926.bugfix
How it looks like now:
vs. web:
vs after the fix:
> Fixed the regular expression used for link detection in attributed strings

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Communities/Home/GroupHomeViewController.m
- Riot/Modules/DeepLink/MXRoomAliasResolution+Deeplink.swift
- RiotTests/Modules/DeepLink/MXRoomAliasResolutionDeeplinkTests.swift
- changelog.d/4858.bugfix
Resolves #4858 
A room can be joined by providing either an alias or an identifier. When joining via an alias, the server is able to resolve this alias to an identifier as well as whichever homeserver is aware of this room, meaning that it is possible to join a room from one home server by a user on another home server.
This is not the case for joining via an identifier: synapse will currently return a "No known servers" error if the client attempts to join a room without specifying `server_name` (see https://github.com/matrix-org/matrix-spec-proposals/blob/old_master/proposals/1704-matrix.to-permalinks.md for details).
To solve this issue we need to [hold onto a list of servers](https://github.com/matrix-org/matrix-ios-sdk/pull/1426) provided by the API when resolving an alias, and then …
> Enable joining a room via identifier from another home server

- Riot/Modules/Authentication/AuthenticationViewController.xib
- changelog.d/5898.change
- Make layout margins on content view follow readable width
- Set zero edge insets on content view
- Constrain all subviews of content view to leading & trailing layout margins of superview
Fixes: #5898
> Restrict UI components on authentication screen to readable width

- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- changelog.d/5058.bugfix
This is the first part of a fix for a triple-leak involving `MXKRoomDataSource`, `MXRoomEventTimeline` and `MXEventListener`. The second part can be found in matrix-org/matrix-ios-sdk#1424.
The concrete issue here is that `MXKRoomDataSource` stores an event listener in a strong property but captures `self` in the listener's `onEvent` block.
I haven't found concrete steps to reproduce the leak (and the memory graph debugger is also not 100% reliable) but the cycle frequently shows after having entered, left and posted in rooms a few times.
Relates to: #5058
> Fix retain cycle in MXKRoomDataSource

- RiotSwiftUI/Modules/Room/RoomAccess/RoomAccessTypeChooser/Service/MatrixSDK/RoomAccessTypeChooserService.swift
- changelog.d/5943.bugfix
> m.room.join_rules not properly set for private access

- Riot/Modules/Application/LegacyAppDelegate.m
Fixes #5883
Whilst the issue was fixed previously by removing API that allows passing of `nil` to a method, which then created Swift object that assumes non-nul values (and thus crashes), it is still theoretically possible that at some point some code is passing in some implicitely nil values. To make sure we catch this, check for nil values each time before creating the parameters.
> Exit early if universal link parameters cannot be created

- Riot/Categories/MXEvent.swift
- Riot/Modules/Room/TimelineDecorations/Threads/Summary/ThreadSummaryView.swift
- Riot/Modules/Threads/ThreadList/ThreadListViewModel.swift
- changelog.d/5488.change
Part of #5488 
Will be based on develop when other thread PRs merged.
> Strip `in reply to` from thread summaries and latest messages

- Riot/Categories/NSAttributedString.swift
- Riot/Modules/GlobalSearch/Files/HomeFilesSearchViewController.m
- Riot/Modules/GlobalSearch/Messages/HomeMessagesSearchViewController.m
- Riot/Modules/MatrixKit/Categories/NSAttributedString+MatrixKit.swift
- Riot/Modules/Room/Search/RoomSearchViewController.m
- Riot/Modules/Room/Views/Title/Thread/ThreadRoomTitleView.xib
- Riot/Modules/Threads/ThreadList/ThreadListViewModel.swift
- Riot/Modules/Threads/ThreadList/Views/Cell/ThreadTableViewCell.xib
- Riot/Modules/Threads/ThreadList/Views/Empty/ThreadListEmptyView.xib
- changelog.d/5878.bugfix
> Threads design tweaks

- Riot/Categories/Bundle.swift
- Riot/Generated/Strings.swift
- Riot/Modules/MatrixKit/Categories/NSBundle+MXKLanguage.m
- RiotNSE/NotificationService.swift
- Tools/SwiftGen/Templates/Strings/flat-swift4-vector.stencil
- changelog.d/5996.bugfix
This was a long running bug which become more visible following on from #5936. Instead of using `NSString.localizedUserNotificationString` which provides no fallback, this PR adds a `localizedString(forKey:_:)` method that uses similar logic to `VectorL10n`, but specifically requests the strings from the main app bundle.
In order for this to work, MXKLanguageBundle now always references `Bundle.app` instead of `Bundle.main` so that `setupMXKLanguageBundle` was called on the same bundle that the strings request goes to. I've updated `VectorL10n` to do the same thing - this has the happy coincidence of allowing the share extension to show in the system language as well which I don't believe it was doing before 😄
Fixes #5996
> Make sure strings fall back to English if missing in the Notification extension

- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.h
- Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
- Riot/Modules/Common/Recents/DataSources/RecentsDataSourceSectionType.swift
- Riot/Modules/Common/Recents/DataSources/RecentsDataSourceSections.swift
- Riot/Modules/Favorites/FavouritesViewController.m
- Riot/Modules/GlobalSearch/DataSources/UnifiedSearchRecentsDataSource.m
- Riot/Modules/Home/HomeViewController.m
- Riot/Modules/People/PeopleViewController.m
- Riot/Modules/Rooms/RoomsViewController.m
- RiotTests/Modules/Common/Recents/DataSources/RecentsDataSourceSectionsTests.swift
`RecentsDataSource` and its subclasses have a very brittle way of managing state, which consists in declaring a set of externally mutable integer properties which are set, reset and mutated at random point, and which indicate number of sections in the table view.
In this PR I am replacing all of this state by inetrnalizing inside of `RecentsDataSourceSections` object which ensures strong types via an enum for each section, and no mutability after creation. To alter sections, one must create a whole new object. This also makes it possible to compare and diff two sections objects to see whether a table view needs to be reloaded or not (will come in future PR).
This PR is very large and touches a lot of lines, so there is some room for error. The new code is tested, but the old code is quite …
> Refactor sections as enum types

- Config/CommonConfiguration.swift
- Riot/Assets/ar.lproj/Localizable.strings
- Riot/Assets/ca.lproj/Localizable.strings
- Riot/Assets/cs.lproj/Localizable.strings
- Riot/Assets/de.lproj/Localizable.strings
- Riot/Assets/en.lproj/Localizable.strings
- Riot/Assets/es.lproj/Localizable.strings
- Riot/Assets/et.lproj/Localizable.strings
- Riot/Assets/fr.lproj/Localizable.strings
- Riot/Assets/hu.lproj/Localizable.strings
- Riot/Assets/id.lproj/Localizable.strings
- Riot/Assets/is.lproj/Localizable.strings
- Riot/Assets/it.lproj/Localizable.strings
- Riot/Assets/ja.lproj/Localizable.strings
- Riot/Assets/ko.lproj/Localizable.strings
- Riot/Assets/nl.lproj/Localizable.strings
- Riot/Assets/pl.lproj/Localizable.strings
- Riot/Assets/pt_BR.lproj/Localizable.strings
- Riot/Assets/ru.lproj/Localizable.strings
- Riot/Assets/sk.lproj/Localizable.strings
- Riot/Assets/sq.lproj/Localizable.strings
- Riot/Assets/sv.lproj/Localizable.strings
- Riot/Assets/uk.lproj/Localizable.strings
- Riot/Assets/vi.lproj/Localizable.strings
- Riot/Assets/zh_Hans.lproj/Localizable.strings
- Riot/Categories/Bundle.swift
- Riot/target.yml
- changelog.d/pr-6011.i18n
This PR adds a few small changes following on from #5936 and #5996.
- The `NOTIFICATION` key has been renamed to `Notification` as this is what will be shown for languages without a translation of this key.
- `Bundle.app` is now a stored property as its value isn't going to change and we're using it every time we load a string.
- The Pirate language has been excluded from the project as it generates a warning when submitting to ASC 🏴‍☠️
Note: I've synced with Weblate and locked it for now to avoid any conflicts with the change in the translations.
> Small changes to localisation

- RiotSwiftUI/Modules/Template/SimpleScreenExample/Coordinator/TemplateSimpleScreenCoordinator.swift
- RiotSwiftUI/Modules/Template/SimpleUserProfileExample/Coordinator/TemplateUserProfileCoordinator.swift
- changelog.d/pr-6014.change
This PR adds a basic implementation of the new user indicators to the SwiftUI templates.
> Add loading indicators to the SwiftUI templates.

- project.yml
Small technical update to have a convenient access to create/browse changelog.d directly from Xcode workspace.
> Display changelog folder into workspace

- Gemfile.lock
Fixes https://github.com/vector-im/element-ios/security/dependabot/1
> Bump cocoapods-downloader from 1.5.1 to 1.6.3

- Riot/Modules/Application/ScreenNavigation/RoomNavigationParameters.swift
- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Room/RoomCoordinator.swift
- Riot/Modules/Room/RoomCoordinatorParameters.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/TabBar/TabBarCoordinator.swift
- changelog.d/4986.change
> When accepting an invite, expecting to see the room

- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Analytics/DecryptionFailure.swift
- Riot/Modules/Analytics/DecryptionFailureTracker.m
- changelog.d/6046_uisi_context
Resolves #6046
Use the existing `context` property of `AnalyticsEvent` type to log additional details about UISI and decryption errors, which are currently being discared (and making it harder to monitor and fix errors). The `context` is just a string field and does not have any standardized format, in this particular PR I am logging the data as "code: X, description: more details of the error".
This PR is meant as a transitionary solution to find out faster what the majority of "unknown" errors in our analytics are. As the next step we would like to define a dedicated `DecryptionError` type in the analytics schema and define a broader range of errors suitable for our analytics.
> Log decryption error details as context in AnalyticsEvent

- .github/workflows/triage-move-labelled.yml
Don't label A-Threads with Z-Labs any more because threads have been released
> Update issue labelling automation

- Riot/Modules/Common/Recents/RecentsViewController.m
Fix crash of querying number of rows in a section when that section does not exist. This type of behaviour should not exist if we had a consistent data model, but there is an issue somewhere in the DataSource that creates inconsistent data model.
To fix the crash, we simply check number of existing sections and log and error otherwise.
There are a number of rageshakes possibily related to this crash:
https://github.com/matrix-org/element-ios-rageshakes/issues/18165
https://github.com/matrix-org/element-ios-rageshakes/issues/18160
https://github.com/matrix-org/element-ios-rageshakes/issues/18156
https://github.com/matrix-org/element-ios-rageshakes/issues/18150
> Fix crash with sections

- Config/BuildSettings.swift
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/Location/LocationPlainCell.swift
- changelog.d/6110.bugfix
close: #6110 
To test this, you need to start sharing your location from develop.element.io. Start live location sharing is not available yep on iOS.
> [Location sharing] Fix timeline cell stop button

- Riot/Assets/en.lproj/Untranslated.strings
- Riot/Generated/UntranslatedStrings.swift
- Riot/Modules/Authentication/Views/AuthInputsView.m
- Riot/Modules/MatrixKit/Views/Authentication/MXKAuthenticationRecaptchaWebView.m
- RiotNSE/target.yml
- RiotShareExtension/target.yml
- RiotSwiftUI/Modules/Authentication/ReCaptcha/AuthenticationReCaptchaModels.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/AuthenticationReCaptchaViewModel.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/AuthenticationReCaptchaViewModelProtocol.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/Coordinator/AuthenticationReCaptchaCoordinator.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/MockAuthenticationReCaptchaScreenState.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/Test/UI/AuthenticationReCaptchaUITests.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/Test/Unit/AuthenticationReCaptchaViewModelTests.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/View/AuthenticationReCaptchaScreen.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/View/AuthenticationReCaptchaWebView.swift
- RiotSwiftUI/Modules/Authentication/Terms/View/AuthenticationTermsScreen.swift
- RiotSwiftUI/Modules/Authentication/VerifyEmail/Coordinator/AuthenticationVerifyEmailCoordinator.swift
- RiotSwiftUI/Modules/Common/Mock/MockAppScreens.swift
- SiriIntents/target.yml
- changelog.d/5650.wip
This PR adds the views, but it isn't yet part of the flow and the coordinator only has an initial implementation so far. Additionally this PR adds support for dark mode to the `MXKAuthenticationReCaptchaWebView`.
Note: Voiceover only partially works on the ReCaptcha form and Dynamic Type doesn't seem to work at all. There is also potentially more work required to get the sizing of the form to be optimal on a larger range of devices.
Part of issue https://github.com/vector-im/element-ios/issues/5650
Fixes #6054
| Light Begin | Light Challenge | Dark Begin | Dark Challenge |
| - | - | - | - |
| ![Screenshot 2022-05-09 at 4 43 42 pm](https://user-images.githubusercontent.com/6060466/167447591-3b9edc9b-adc8-4412-9da8-1d076b60e6d2.png) | ![Screenshot 2022-05-09 at 4 43 54 …
> Add ReCaptcha screen 

- Riot/Modules/MediaPicker/MediaPickerViewController.m
- changelog.d/6096.bugfix
Fixes #6096 by handling the Hidden album in the same way as the Recently Delete album:
> Hide the hidden album's thumbnail.

- Riot/Modules/Room/Views/Title/Thread/ThreadRoomTitleView.swift
- Riot/Modules/Room/Views/Title/Thread/ThreadRoomTitleView.xib
- changelog.d/5878.change
> Thread title view fixes

- Riot/Modules/Onboarding/AuthenticationCoordinator.swift
- Riot/Modules/Onboarding/OnboardingCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Registration/AuthenticationRegistrationViewModel.swift
- RiotSwiftUI/Modules/Authentication/Registration/AuthenticationRegistrationViewModelProtocol.swift
- RiotSwiftUI/Modules/Authentication/Registration/Coordinator/AuthenticationRegistrationCoordinator.swift
- RiotSwiftUI/Modules/Authentication/ServerSelection/AuthenticationServerSelectionViewModel.swift
- RiotSwiftUI/Modules/Authentication/ServerSelection/AuthenticationServerSelectionViewModelProtocol.swift
- RiotSwiftUI/Modules/Authentication/ServerSelection/Coordinator/AuthenticationServerSelectionCoordinator.swift
- RiotSwiftUI/Modules/Onboarding/Avatar/Coordinator/OnboardingAvatarCoordinator.swift
- RiotSwiftUI/Modules/Onboarding/Avatar/OnboardingAvatarViewModel.swift
- RiotSwiftUI/Modules/Onboarding/Avatar/OnboardingAvatarViewModelProtocol.swift
- changelog.d/pr-6141.wip
A small tidy up following on from #6056 and #6048.
- Completion handlers that are called more than once in the onboarding flow are renamed to `callback`.
- Actor usage is simplified in `start` and `process(viewAction:)` to align with Email/Terms/ReCaptcha screens.
> Rename completion to callback and simplify actor usage.

- Riot/Modules/Room/RoomViewController.swift
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
- RiotTests/PillsFormatterTests.swift
Fixes issue where composer won't use default text primary color after using a pill.
Also moves all the font/color attributes updates to the toolbar attributedText setter.
#3526
> Fix composer text coloration

- Riot/Modules/Room/RoomViewController.m
Closure capturing the Cell reference. And the cell reference changes when block executes , due to iOS internal changes in the way of handling cells.
[#5737]
> copy not working in > iOS 15.4 

- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
- changelog.d/pr-6188.bugfix
This is just an educated guess, don't know much more than that
Crashlogs available here: xcode://organizer/crashes/downloadPoint?adamId=1083446067&platformId=iOS&installPlatformId=iOS&analyticsPointId=DAnw6bxyqudU75gNw0fsNY&bundleId=im.vector.app
> Attempt at fixing [CALayer animationForKey] crashes.

- Riot/Categories/MXRestClient+Async.swift
- Riot/Utils/DictionaryEncodable.swift
- RiotSwiftUI/Modules/Authentication/Common/AuthenticationModels.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationRestClient.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationService.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginModels.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginParameters.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginWizard.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/RegistrationParameters.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/RegistrationWizard.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/SessionCreator.swift
- RiotSwiftUI/Modules/Authentication/Registration/Coordinator/AuthenticationRegistrationCoordinator.swift
- RiotTests/Modules/Authentication/LoginTests.swift
- changelog.d/5896.wip
This is the second part of #5896 that implements the `LoginWizard` similarly to the Android implementation. Additionally
- Adds an `AuthenticationRestClient` protocol so that the client can be mocked for testing the service layer.
- Adds a `DictionaryEncodable` protocol with a default implementation as I needed to get a dictionary from multiple `Encodable` types.
There are some remaining commented out parts of the from the Android service, but in essence this closes #5896 and those can be added/removed with the remaining tasks.
> Implement LoginWizard and add AuthenticationRestClient protocol

- Riot/SupportingFiles/Info.plist
- changelog.d/6159.bugfix
> Fix ITMS Warning on CFBundleDocumentTypes

- Riot/Modules/LocationSharing/UserLocationService.swift
- changelog.d/6199.wip
Part of #6199 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1474
> Location sharing: Support restarting location sending after app kill (PSF-1036)

- Riot/Modules/Onboarding/AuthenticationCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Common/AuthenticationHomeserverViewData.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationService.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationState.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginModels.swift
- RiotSwiftUI/Modules/Authentication/Login/AuthenticationLoginModels.swift
- RiotSwiftUI/Modules/Authentication/Login/AuthenticationLoginViewModel.swift
- RiotSwiftUI/Modules/Authentication/Login/Coordinator/AuthenticationLoginCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Login/MockAuthenticationLoginScreenState.swift
- RiotSwiftUI/Modules/Authentication/Login/Test/UI/AuthenticationLoginUITests.swift
- RiotSwiftUI/Modules/Authentication/Login/Test/Unit/AuthenticationLoginViewModelTests.swift
- RiotSwiftUI/Modules/Authentication/Login/View/AuthenticationLoginScreen.swift
- RiotSwiftUI/Modules/Authentication/Registration/AuthenticationRegistrationModels.swift
- RiotSwiftUI/Modules/Authentication/Registration/AuthenticationRegistrationViewModel.swift
- RiotSwiftUI/Modules/Authentication/Registration/Coordinator/AuthenticationRegistrationCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Registration/MockAuthenticationRegistrationScreenState.swift
- RiotSwiftUI/Modules/Authentication/Registration/Test/UI/AuthenticationRegistrationUITests.swift
- RiotSwiftUI/Modules/Authentication/Registration/Test/Unit/AuthenticationRegistrationViewModelTests.swift
- RiotSwiftUI/Modules/Authentication/Registration/View/AuthenticationRegistrationScreen.swift
- RiotSwiftUI/Modules/Onboarding/UseCase/Coordinator/OnboardingUseCaseSelectionCoordinator.swift
- changelog.d/6176.change
> Show fallback when unsupported stages are mandatory

- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationRestClient.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationService.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginWizard.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/RegistrationParameters.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/RegistrationWizard.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/SessionCreator.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/ThreePIDModels.swift
- RiotTests/Modules/Authentication/AuthenticationServiceTests.swift
- RiotTests/Modules/Authentication/Fixtures/basic-loginsession.json
- RiotTests/Modules/Authentication/Fixtures/basic-registersession.json
- RiotTests/Modules/Authentication/Fixtures/basic-wellknown.json
- RiotTests/Modules/Authentication/Fixtures/loginOnly-loginsession.json
- RiotTests/Modules/Authentication/Fixtures/matrix-loginsession.json
- RiotTests/Modules/Authentication/Fixtures/matrix-registersession.json
- RiotTests/Modules/Authentication/Fixtures/matrix-wellknown.json
- RiotTests/Modules/Authentication/Fixtures/ssoOnly-loginsession.json
- RiotTests/Modules/Authentication/Fixtures/ssoOnly-wellknown.json
- RiotTests/Modules/Authentication/Mocks/MockAuthenticationRestClient.swift
- RiotTests/Modules/Authentication/Mocks/MockAuthenticationRestClientConfig.swift
- RiotTests/Modules/Authentication/Mocks/MockSessionCreator.swift
- changelog.d/6179.wip
Most of the authentication service was untested (and some of the tests were temporarily using live servers). This PR adds a `MockAuthenticationRestClient` and tests for login/registration. There is room for more tests (and adding an email/MSISDN identifier still needs implementation), but these tests cover the majority of the flow/state and can be added to over time.
Part of #6179 depends on https://github.com/matrix-org/matrix-ios-sdk/pull/1484
> Add initial tests on the authentication service.

- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- changelog.d/4586.bugfix
Fixes #4586 
This fix reduces the range for the regex inspecting a reply to the mx-reply body only.
It also allows the usage of both single quote and double quotes for href inside an mx-reply ```a``` tag.
It will also opt-out of the reply treatment if no mx-reply block is found (screenshot).
It should cover most frequent cases of pesky ```in reply to``` blocks, apart for some very badly built mx-replies.
| - | - |
| ![image](https://user-images.githubusercontent.com/80891108/171877341-185a6c2c-77f8-4a4e-8faa-7ffab9e1fa7b.png) | ![image](https://user-images.githubusercontent.com/80891108/171876628-dad955c4-715e-4c2a-85a8-06163f81e263.png) |
> Fix in reply to links appearing outside of mx-quote

- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.h
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- Riot/Modules/Room/DataSources/RoomDataSource.swift
- Riot/Utils/EventFormatter.m
- changelog.d/pr-6155.change
This is a partial implementation of [rich replies](https://matrix.org/docs/spec/client_server/r0.4.0.html#rich-replies)
It constructs the reply body directly from the related event, but only if it is available in the local DB.
Replies to unavailable events will fallback to the current behaviour.
It is therefore a partial fix for https://github.com/vector-im/element-ios/issues/3828 https://github.com/vector-im/element-ios/issues/3517 https://github.com/vector-im/element-ios/issues/4586 https://github.com/vector-im/element-ios/issues/5479 https://github.com/vector-im/element-ios/issues/5823 
https://user-images.githubusercontent.com/80891108/171646377-14111c89-1f34-41fb-afd2-55183fddfce5.mp4
> Construct formatted body from replied event

- Riot/Modules/Application/LegacyAppDelegate.h
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Authentication/AuthenticationCoordinatorProtocol.swift
- Riot/Modules/Authentication/LegacyAuthenticationCoordinator.swift
- Riot/Modules/DeepLink/UniversalLinkParameters.swift
- Riot/Modules/Onboarding/AuthenticationCoordinator.swift
- Riot/Modules/Onboarding/OnboardingCoordinator.swift
- Riot/Modules/Onboarding/OnboardingCoordinatorBridgePresenter.swift
- Riot/Modules/Onboarding/OnboardingCoordinatorProtocol.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/TabBar/MasterTabBarController.h
- Riot/Modules/TabBar/MasterTabBarController.m
- Riot/SupportingFiles/Riot-Bridging-Header.h
- Riot/Utils/UniversalLink.h
- Riot/Utils/UniversalLink.m
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationService.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationState.swift
- RiotTests/UniversalLinkTests.swift
- changelog.d/6180.change
> FTUE: Support server provisioning links

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/SetPinCode/SetPinCoordinatorBridgePresenter.swift
- changelog.d/pr-6249.bugfix
This PR moves the Pin entry screen to its own window so it doesn't get overlapped by other views, especially the session verification alert and screens.
> Prevent the Pin entry screen from being overlapped.

- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.h
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- Riot/Modules/Room/DataSources/RoomDataSource.swift
- changelog.d/pr-6251.bugfix
This removes the flag for edit mode and uses an empty room state instead for editable text HTML render.
Also, it fixes a crash when room state is empty while trying to render a reply.
> Remove render edit flag and fix a nil room state crash

- Riot/Modules/Home/Views/RoomCollectionViewCell.m
- changelog.d/6095.bugfix
This is basically just a guess but I think sometimes the avatar image views don't have a good frame setup when awaken from nib and the layer corner radius calculation fails. After this PR they should get updated after every frame change.
> Fixes vector-im/element-ios/issues/6095 - Random square home screen room avatars

- Riot/Modules/Authentication/LegacyAuthenticationCoordinator.swift
- Riot/Modules/Onboarding/AuthenticationCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationService.swift
- changelog.d/6174.wip
Adds the same unrecognised certificate alert to the new authentication flow as the current flow [shows](https://github.com/vector-im/element-ios/blob/fbbbbc0b79c3f70b5c18f198b81f756b2fa71cc7/Riot/Modules/MatrixKit/Controllers/MXKAuthenticationViewController.m#L1638-L1698).
Fixes #6174.
https://user-images.githubusercontent.com/6060466/172644925-d59a01a9-9520-4d03-bb26-88e5b958141e.mp4
> Add an unrecognised certificate alert to the new authentication flow.

- Riot/Categories/MXFileStore.swift
- Riot/Modules/Authentication/AuthenticationCoordinatorProtocol.swift
- Riot/Modules/Authentication/LegacyAuthenticationCoordinator.swift
- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- Riot/Modules/Onboarding/AuthenticationCoordinator.swift
- Riot/Modules/Onboarding/OnboardingCoordinator.swift
- Riot/Modules/Onboarding/OnboardingCoordinatorBridgePresenter.swift
- Riot/Modules/TabBar/MasterTabBarController.m
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationService.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginWizard.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/RegistrationWizard.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/SessionCreator.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/AuthenticationSoftLogoutModels.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/AuthenticationSoftLogoutViewModel.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/AuthenticationSoftLogoutViewModelProtocol.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/Coordinator/AuthenticationSoftLogoutCoordinator.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/MockAuthenticationSoftLogoutScreenState.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/Test/UI/AuthenticationSoftLogoutUITests.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/Test/Unit/AuthenticationSoftLogoutViewModelTests.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/View/AuthenticationSoftLogoutScreen.swift
- RiotSwiftUI/Modules/Common/Mock/MockAppScreens.swift
- RiotTests/Modules/Authentication/Mocks/MockSessionCreator.swift
- RiotTests/SessionCreatorTests.swift
- changelog.d/6181.feature
> FTUE: Soft logout

- RiotSwiftUI/Modules/Authentication/ForgotPassword/View/AuthenticationForgotPasswordScreen.swift
- RiotSwiftUI/Modules/Onboarding/Celebration/View/OnboardingCelebrationScreen.swift
- RiotSwiftUI/Modules/Onboarding/Congratulations/Test/UI/OnboardingCongratulationsUITests.swift
- RiotSwiftUI/Modules/Onboarding/Congratulations/View/OnboardingCongratulationsScreen.swift
- changelog.d/5151.wip
- A button title has been changed in the forgot password flow
- The confetti is now always shown on the congratulations screen and never on the celebration screen.
- The celebration screen now uses the gradient background.
https://user-images.githubusercontent.com/6060466/172883445-1e5eaaf5-c729-48b1-a8c8-3f4e162ed879.mp4
> Update labels and confetti presentation in new flow.

- Riot/Assets/en.lproj/Untranslated.strings
- Riot/Assets/en.lproj/Vector.strings
- Riot/Categories/MXRestClient+Async.swift
- Riot/Generated/Strings.swift
- Riot/Generated/UntranslatedStrings.swift
- Riot/Modules/MatrixKit/Models/Account/MXKAccount.h
- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- Riot/Modules/Settings/SettingsViewController.m
- Riot/Utils/PasswordValidator.swift
- RiotSwiftUI/Modules/Common/Mock/MockAppScreens.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/ChangePasswordModels.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/ChangePasswordViewModel.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/ChangePasswordViewModelProtocol.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/Coordinator/ChangePasswordBridgePresenter.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/Coordinator/ChangePasswordCoordinator.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/MockChangePasswordScreenState.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/Test/UI/ChangePasswordUITests.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/Test/Unit/ChangePasswordViewModelTests.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/View/ChangePasswordScreen.swift
- RiotTests/PasswordValidatorTests.swift
- changelog.d/6175.change
Fixes #6175 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1495
Replaces the change password alert controller in Settings with a brand new screen.
> Sign out from all devices option when changing password

- Riot/Assets/Riot-Defaults.plist
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/2180.change
Might be a fix for #2180 (which is labelled as requiring design input). This simply reuses the same design that's currently seen when the root message of a thread is redacted.
> Display redacted messages in the timeline

- Riot/Modules/LocationSharing/UserLocationService.swift
- Riot/SupportingFiles/Info.plist
The app was rejected in review, asking for details on how it uses location access in the background. It turns out that the corresponding labs flag is still disabled in release builds so we should avoid using the background location mode until that is changed.
Accordingly, this pull request reverts https://github.com/vector-im/element-ios/commit/ab3acab8d90f18e01efc11296c4a352a672b4e55 and https://github.com/vector-im/element-ios/commit/56c6ef321da48e0e4c289e2397908d080b26e7d3.
CC @SBiOSoftWhare & @MaximeEvrard42
> Back out background location access

- Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewController.swift
- changelog.d/5113.bugfix
Fixes #5113
Used `tableFooterView` instead of `contentInset` because `KeyboardAvoider` overrides that value.
> Fix directory bottom layout

- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
- Riot/Modules/Room/TimelineCells/RoomMembership/RoomMembershipCollapsedBubbleCell.m
- changelog.d/4102.bugfix
resolves https://github.com/vector-im/element-ios/issues/4102
Now use sender avatar instead of the target avatar for collapsed membership cell
> Invites are collapsed incorrectly

- Riot/Modules/Application/LegacyAppDelegate.m
- changelog.d/6288.bugfix
> Avoid launch animation for `backgroundSyncInProgress` state

- RiotSwiftUI/Modules/Authentication/ChoosePassword/AuthenticationChoosePasswordModels.swift
- RiotSwiftUI/Modules/Authentication/Login/AuthenticationLoginModels.swift
- RiotSwiftUI/Modules/Authentication/Login/Coordinator/AuthenticationLoginCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Registration/AuthenticationRegistrationModels.swift
- RiotSwiftUI/Modules/Authentication/Registration/Coordinator/AuthenticationRegistrationCoordinator.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/AuthenticationSoftLogoutModels.swift
- RiotSwiftUI/Modules/Authentication/SoftLogout/Coordinator/AuthenticationSoftLogoutCoordinator.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/ChangePasswordModels.swift
- RiotTests/Modules/Authentication/AuthenticationServiceTests.swift
- changelog.d/5151.wip
This PR makes sure that none of the view model/coordinator results in the new authentication flow (not yet enabled) include the password when being converted to a string. It uses `CustomStringConvertible` although perhaps should also conform to `CustomDebugStringConvertible` to save any possibility of the same happening via reflection?
> Add custom string representations of view model/coordinator results.

- Riot/Categories/NSAttributedString.swift
- Riot/Categories/RoomBubbleCellData.swift
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellDataWithAppendingMode.m
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleComponent.h
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleComponent.m
- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.h
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- Riot/Modules/Pills/PillTextAttachment.swift
- Riot/Modules/Pills/PillsFormatter.swift
- Riot/Modules/Room/CreationModal/RoomCreationEventsModal/RoomCreationEventsModalViewModel.swift
- Riot/Modules/Room/DataSources/RoomDataSource.swift
- Riot/Modules/Room/EditHistory/EditHistoryViewModel.swift
- Riot/Modules/Room/MXKRoomViewController.m
- Riot/Modules/Room/TimelineDecorations/Threads/Summary/ThreadSummaryView.swift
- Riot/Modules/Threads/ThreadList/ThreadListViewModel.swift
- Riot/Utils/EventFormatter.m
- RiotTests/MatrixKitTests/MXKEventFormatterTests.m
- RiotTests/MatrixKitTests/MXKRoomDataSourceTests.swift
- RiotTests/PillsFormatterTests.swift
- changelog.d/6302.bugfix
> Use latest user data for mention pills

- Riot/target.yml
- changelog.d/6296.build
[#6296](https://github.com/vector-im/element-ios/issues/6296)
> Fix locheck-script that fails the build when there is space character on PROJECT_DIR path

- .github/workflows/triage-priority-bugs.yml
- changelog.d/pr-6321.misc
It looks like 1 too many brackets were removed in #6230. This PR adds the missing one back and should make [CI](https://github.com/vector-im/element-ios/actions/workflows/triage-priority-bugs.yml) happy once more.
> Add missing ) in workflow.

- Riot/Modules/MatrixKit/Categories/NSBundle+MatrixKit.m
- Riot/Modules/MatrixKit/Controllers/MXKAuthenticationViewController.m
- RiotNSE/target.yml
- RiotShareExtension/target.yml
- RiotSwiftUI/Modules/Authentication/Common/AuthenticationModels.swift
- RiotTests/Modules/Authentication/AuthenticationServiceTests.swift
- SiriIntents/target.yml
- changelog.d/995.bugfix
This PR expands the checks made with `HomeserverAddress.sanitized(_:)` and adds it to `MXKAuthenticationViewController` as it was only being used on the new flow.
Additionally I've excluded all MatrixKit Views and ViewControllers from the NSE and SiriIntents targets as they'll never be needed for those.
Fixes #995 for new sign-ins.
> Strip the trailing slash from homeserver addresses.

- Riot/Modules/Authentication/AuthenticationViewController.h
- Riot/Modules/Authentication/AuthenticationViewController.m
- Riot/Modules/Authentication/LegacyAuthenticationCoordinator.swift
- Riot/Modules/Onboarding/OnboardingCoordinator.swift
- Riot/Modules/TabBar/MasterTabBarController.m
- changelog.d/5881.bugfix
Closes #5881 (the crash was already fixed as part of #6257) by making sure that splash screen/use case screen is presented after choosing to delete all data when using the old auth flow. This is done by
- Delegating logic to the `OnboardingCoordinator` like the new flow does.
- Reseting the credentials on every presentation of authVC.
- Making sure not to set the credentials again after deleting the data (the new soft logout screen was being shown twice).
> Fix unresponsive soft-logout in the legacy flow.

- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
- changelog.d/pr-6328.bugfix
This fixes the quoting action from the "more" section of the message context menu. The action previously didn't appear to do anything because the setter of `textMessage` only handled `nil` arguments.
I also made a small fix to prevent prepending an empty line when quoting with an empty composer.
| Context menu | Quoted text |
| - | - |
| ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-21 at 15 46 43](https://user-images.githubusercontent.com/1137962/174815148-92722c9f-5ca6-43d6-9b6d-7e4981ea688a.png) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-21 at 15 46 46](https://user-images.githubusercontent.com/1137962/174815175-adbfd814-1615-4e56-8374-17906479db25.png) |
> Make quoting context menu action work again

- Riot/Modules/Room/TimelineCells/BaseRoomCell/RoomCellContentView.xib
- changelog.d/5572.bugfix
Previously the avatar wasn't tappable in the bubble layout because its container view was collapsed to a height of 1 point. Increasing the container height is tricky though because it breaks the surrounding vertical stack view. As a workaround this change moves the avatar container out of the stack view so that it can safely be assigned a non-vanishing height that allows for receiving touches.
The vertical layout is fixed with a priority-999 alignment to the stack view and a priority-1000 alignment to the pagination label container (the only view above the avatar container). When the pagination container is hidden, the priority-1000 constraint takes no effect. When it is shown, the priority-1000 constraint trumps the priority-999 constraint.
Otherwise, moving the avatar container out of …
> Make avatar view tappable in bubble layout

- Riot/Assets/en.lproj/Untranslated.strings
- Riot/Categories/UIViewController.swift
- Riot/Generated/UntranslatedStrings.swift
- Riot/Modules/Communities/Home/GroupHomeViewController.m
- Riot/Modules/Communities/Members/GroupParticipantsViewController.m
- Riot/Modules/Communities/Rooms/GroupRoomsViewController.m
- Riot/Modules/GlobalSearch/UnifiedSearchViewController.m
- Riot/Modules/Integrations/WidgetPicker/WidgetPickerViewController.m
- Riot/Modules/Integrations/Widgets/StickerPicker/StickerPickerViewController.m
- Riot/Modules/MediaPicker/MediaPickerViewController.m
- Riot/Modules/Room/Members/RoomParticipantsViewController.m
- Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewController.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
- Riot/Modules/Settings/Security/SecurityViewController.m
- Riot/Modules/Settings/SettingsViewController.m
- Riot/Modules/TabBar/MasterTabBarController.m
- changelog.d/5971.change
Resolves #5971 
This takes advantage of the iOS 14 introduced `backButtonDisplayMode` to allow displaying VC titles (or back button titles, if defined) inside back button longpress menu.
As it is hard to exhaustively test every screen within the app, some displayed titles could be odd (but obviously still better than an empty cell).
https://user-images.githubusercontent.com/80891108/174811856-32b3c3be-2121-42d2-ac8c-f4bb5cf4240d.mp4
> Handle long press on back buttons

- Riot/Modules/Room/TimelineCells/Common/MXKRoomBubbleTableViewCell.m
- changelog.d/6031.bugfix
With bubbles disabled, file attachment names are parsed with data detectors meaning that tapping on a file named `foo@bar.baz` was opening the email app instead of the file.
This PR first checks if the associated event for the URL is a media attachment, and if so will stop the URL handling and instead indicate that the attachment was tapped.
Fixes #6031
> Ignore data detector URLs on file attachment names

- Riot/Modules/Room/TimelineCells/BaseRoomCell/RoomCellContentView.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Incoming/Clear/RoomIncomingAttachmentBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Incoming/Clear/RoomIncomingAttachmentWithPaginationTitleBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Incoming/Encrypted/RoomIncomingEncryptedAttachmentBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Incoming/Encrypted/RoomIncomingEncryptedAttachmentWithPaginationTitleBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Outgoing/Clear/RoomOutgoingAttachmentBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Outgoing/Clear/RoomOutgoingAttachmentWithPaginationTitleBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Outgoing/Encrypted/RoomOutgoingEncryptedAttachmentBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Outgoing/Encrypted/RoomOutgoingEncryptedAttachmentWithPaginationTitleBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/Sticker/RoomSelectedStickerBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/TextMessage/Incoming/Clear/RoomIncomingTextMsgBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/TextMessage/Incoming/Clear/RoomIncomingTextMsgWithPaginationTitleBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/TextMessage/Incoming/Encrypted/RoomIncomingEncryptedTextMsgBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/TextMessage/Incoming/Encrypted/RoomIncomingEncryptedTextMsgWithPaginationTitleBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/TextMessage/Outgoing/Clear/RoomOutgoingTextMsgBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/TextMessage/Outgoing/Clear/RoomOutgoingTextMsgWithPaginationTitleBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/TextMessage/Outgoing/Encrypted/RoomOutgoingEncryptedTextMsgBubbleCell.xib
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/TextMessage/Outgoing/Encrypted/RoomOutgoingEncryptedTextMsgWithPaginationTitleBubbleCell.xib
- changelog.d/4324.bugfix
The XIBs had the tap target extending 6pt below the name. This resulted in a frequent occurrence where you would go to tap the top message but end up tapping the name instead. This PR sets the bottom constant to 0pth to align with the name label. In my testing it was no harder to tap the name, and significantly easier to tap the top message.
**Before**
**After**
(Width differences seen above are due to different size devices)
The height on bubbles has been reduced to 3pt so it exactly matches to the top of the bubble.
**Bubbles**
Fixes #4324
> Remove overlap of sender name and first message tap targets.

- Riot/Modules/Application/LegacyAppDelegate.m
- changelog.d/pr-6331.bugfix
This fixes an issue where failed syncs after user migration could trigger an unwanted display of the mandatory secure backup setup.
> Display mandatory backup only if session is running

- Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m
- changelog.d/5324.bugfix
Inspecting the items on the pasteboard to determine whether pasting is possible causes the banner to appear. This PR updates the check to inspect the types on the pasteboard instead. I didn't seem to see this when copying an image from Safari (presumably as there is also text on the pasteboard in the form of a URL so it doesn't go up the responder chain to check), but could reproduce it when copying an image from the photos app.
Fixes #5324
> Fix pasteboard banner when editing text.

- RiotSwiftUI/Modules/Authentication/Login/AuthenticationLoginModels.swift
- RiotSwiftUI/Modules/Authentication/Login/View/AuthenticationLoginScreen.swift
- changelog.d/pr-6338.bugfix
Tiny bugfix I noticed whilst porting the screen over to ElementX where you could hit return whilst the service was loading a homeserver and it would attempt to login.
> Prevent login using keyboard when homeserver is loading.

- RiotShareExtension/Shared/View/ShareViewController.m
- changelog.d/3029.bugfix
Fixes #3029
| - | - |
| ![IMG_B9BBBE9E0DAE-1](https://user-images.githubusercontent.com/6060466/151335083-5de0dbfe-2cf3-4ec0-b334-9991f485ba3e.jpeg) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-06-23 at 16 19 43](https://user-images.githubusercontent.com/6060466/175336185-2b52bfc3-d775-429b-b215-cffbca2307b7.png) |
> Fix share extension background in dark mode.

- Riot/Utils/EventFormatter+DTCoreTextFix.m
- changelog.d/pr-6340.bugfix
A tiny fix that updates the swizzle to match [ElementX](https://github.com/vector-im/element-x-ios/blob/b6b8b4be26b0d14a172f24b4a2818e17c490fd5e/ElementX/Sources/Other/HTMLParsing/UIFont%2BAttributedStringBuilder.m#L33) as it doesn't work when using the Designed for iPad version of Element on M1.
| - | - |
| <img alt="Screenshot 2022-06-24 at 11 08 21 am" src="https://user-images.githubusercontent.com/6060466/175514056-5b55effa-477b-49ef-a4f8-4929f32b1310.png"> | <img alt="Screenshot 2022-06-24 at 11 09 17 am" src="https://user-images.githubusercontent.com/6060466/175514063-5079c358-33b5-4614-a076-49405f6fdf3d.png"> |
> Fix the font when using an Apple Silicon Mac.

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/ContextMenu/ActionProviders/RoomActionProvider.swift
- Riot/Modules/ContextMenu/Services/RoomContextActionService.swift
- changelog.d/6278.feature
> Add "Mark as read"

- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- Riot/Modules/Room/RoomViewController.m
- changelog.d/pr-6326.change
This sets the display text of `beacon_info` events which enables the context menu on live location shares which in turn allows users to report the events. Other events in the menus will be implemented separately.
| Timeline | Location cell selected | More menu |
|-|-|-|
| ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-21 at 15 05 37](https://user-images.githubusercontent.com/1137962/174808860-b43f8210-b434-45c2-b3e3-8e7a61e22fad.png) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-21 at 15 05 40](https://user-images.githubusercontent.com/1137962/174808875-d527d922-d486-4952-a6a0-9d9f6a79ce9c.png) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-21 at 15 05 43](https://user-images.githubusercontent.com/1137962/174808882-806cca77-b267-4d26-ace1-6d0cb322cd35.png) |
> Enable reporting of live location shares (PSF-1066)

- Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.swift
- Riot/Modules/QRCode/QRCodeGenerator.swift
- changelog.d/6358.bugfix
Resolves https://github.com/vector-im/element-ios/issues/6358
I do not have a ton of historical context here ...
At the moment cross-signing works between most clients but when scanning QR code generated on iOS by an Android device, the cross-signing fails (the opposite direction works). Both clients use ZXing library to scan QR code image, but only Android uses it to also generate one. On iOS we (used to) use native `CIFilter`.
After some rabbit hole investigation as to why Android cannot parse the iOS image I found that parsing works correctly if all data is a so-called [byte mode](https://github.com/zxingify/zxingify-objc/blob/e75eeff2089d66fc94514b43db3678a8812a9bbe/ZXingObjC/qrcode/decoder/ZXQRCodeMode.h#L49). This is similar to an issue discovered in …
> Use ZXing library to generate QR codes

- Podfile
- Podfile.lock
- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Analytics/SentryMonitoringClient.swift
- changelog.d/pr-6308.feature
Adds [Sentry](https://sentry.io) as a monitoring tool to track app health metrics such as crashes and non-fatal issues logged via `MXLog.failure`. Using Sentry is subject to the same user consent as other crash and analytics data and is configurable from user settings.
Sentry in this PR is integrated directly into an existing `Analytics` class, which has some pros:
- the rest of the application does not need to understand the difference between PostHog and Sentry, Analytics merely serves as façade
- existing code related to starting / stoping / optingIn / optingOut of analytics would have to be duplicated in all places, if Sentry was another top-level service
The downside of this approach is giving `Analytics` more responsibilities than it was originally indented to have. I tried to …
> Track non-fatal issues via analytics / Sentry if consent provided

- RiotTests/MatrixKitTests/MXKEventFormatter+Tests.h
- RiotTests/MatrixKitTests/MXKEventFormatterTests.m
- RiotTests/MatrixKitTests/MXKEventFormatterTests.swift
- RiotTests/MatrixKitTests/MatrixKitTests-Bridging-Header.h
- changelog.d/pr-6380.change
Add unit tests discussed here: https://github.com/vector-im/element-ios/pull/6372#pullrequestreview-1027600953
> Add formatter build reply HTML unit tests

- Riot/Modules/Common/SwiftUI/VectorHostingController.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollCoordinator.swift
- changelog.d/pr-6381.bugfix
We've introduced an infinite loop on `VectorHostingController` when we tried to solve the safe area insets issue with method swizzling, by https://github.com/vector-im/element-ios/pull/6374. This PR removes the method swizzling and fixes the infinite loop.
> Fix VectorHostingController infinite loop

- RiotSwiftUI/Modules/Authentication/ServerSelection/MockAuthenticationServerSelectionScreenState.swift
- RiotSwiftUI/Modules/Authentication/ServerSelection/Test/UI/AuthenticationServerSelectionUITests.swift
- RiotSwiftUI/Modules/Settings/ChangePassword/Test/UI/ChangePasswordUITests.swift
- changelog.d/6386.bugfix
It seems they've been silently failing for a while now.
> Fix a few failing UI tests.

- Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
- Riot/Modules/Settings/Security/SecurityViewController.m
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/6392.misc
I forgot to come back to investigate why the theme fonts weren't working from Objective-C.
> Revert some fonts that were changed in #6275

- Riot/Assets/en.lproj/Untranslated.strings
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Generated/UntranslatedStrings.swift
This simply moves the "Room Info" back button title (visible on long press gestures) for translations, as discussed with Product. 
It's probably not worth a changelog unless someone thinks otherwise ?
> Move room info back button title for translation

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Utils/UniversalLink.m
- changelog.d/6395.bugfix
> Fix inoperant room links with alias/identifiers

- Riot/Modules/KeyBackup/ManualExport/EncryptionKeysExportPresenter.swift
- Riot/Modules/Settings/Security/SecurityViewController.m
- changelog.d/6391.bugfix
> Rename riot-keys.txt to element-keys.txt.

- Riot/Modules/MatrixKit/Controllers/MXKAuthenticationViewController.m
- changelog.d/pr-6417.bugfix
When selecting "Create account" from the splash screen, the soft logout credentials were set to `nil` which was causing the login screen to be shown instead of the registration screen. This adds the a check for `nil` credentials to `MXKAuthenticationViewController` like the one in `AuthenticationViewController`.
> Fix a bug setting nil soft logout credentials.

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/6436.change
Rewords the account deactivation button to clarify that this is a permanent action before even tapping the button.
Fixes #6436.
> Reword account deactivation button in Settings.

- Riot/Modules/Authentication/Legacy/LegacyAuthenticationCoordinator.swift
- changelog.d/6425.bugfix
The `LegacyAuthenticationCoordinator` would listen for deep links after presentation, but didn't look to the authentication service in case a deep link had already been opened. This PR fixes that. As `AuthenticationCoordinator` uses the authentication service directly, this issue doesn't affect the new flow.
Closes #6425
> Fix deep links not working until AuthenticationViewController has been presented.

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/Location/LocationPlainCell.swift
- changelog.d/6423.change
> Location sharing: Handle live location sharing start event reply in the timeline (PSG-4)

- Riot/Modules/Room/Location/RoomTimelineLocationView.swift
- changelog.d/6448.change
> Location sharing: Show map credits on live location timeline tile only when map is shown (PSG-626)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Onboarding/OnboardingCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationService.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginWizard.swift
- RiotSwiftUI/Modules/Authentication/Login/Coordinator/AuthenticationLoginCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Login/Test/Unit/AuthenticationLoginViewModelTests.swift
- RiotSwiftUI/Modules/Authentication/ReCaptcha/View/AuthenticationReCaptchaWebView.swift
- RiotSwiftUI/Modules/Authentication/Registration/AuthenticationRegistrationModels.swift
- RiotSwiftUI/Modules/Authentication/Registration/AuthenticationRegistrationViewModel.swift
- RiotSwiftUI/Modules/Authentication/Registration/AuthenticationRegistrationViewModelProtocol.swift
- RiotSwiftUI/Modules/Authentication/Registration/Coordinator/AuthenticationRegistrationCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Registration/Test/Unit/AuthenticationRegistrationViewModelTests.swift
- RiotSwiftUI/Modules/Authentication/Registration/View/AuthenticationRegistrationScreen.swift
- RiotTests/Modules/Authentication/AuthenticationServiceTests.swift
- changelog.d/6428.wip
- changelog.d/6429.wip
- changelog.d/6430.wip
There is one more string to update, otherwise this is it (pending user testing).
- Allow login using a phone number.
- Update the server when entering a full MXID during registration.
- Reset the authentication service back to matrix.org after onboarding completes.
- Disable zoom on ReCaptcha to fix responsiveness issue.
- Tidy up unused methods.
Closes #6428. Closes #6429. Closes #6430.
**Input of full MXID during Registration**
> FTUE tweaks

- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/RegistrationWizard.swift
- changelog.d/6459.wip
Dummy stages were only being performed when mandatory and not when optional. This PR no longer makes the distinction and performs the request when it can.
Fixes #6459.
> Always perform the registration dummy stage immediately after the first one.

- RiotSwiftUI/Modules/Authentication/VerifyEmail/Coordinator/AuthenticationVerifyEmailCoordinator.swift
- changelog.d/2594.bugfix
Small PR to trim whitespace when verifying an email address during registration. In testing it seems that synapse handles this automatically but could be useful for other homeservers.
Closes #2594.
> Trim whitespace from email address on register.

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- RiotSwiftUI/Modules/Room/LocationSharing/Coordinator/LocationSharingCoordinator.swift
- RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingModels.swift
- RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingViewModel.swift
- RiotSwiftUI/Modules/Room/LocationSharing/Test/Unit/LocationSharingViewModelTests.swift
- changelog.d/6477.change
> Location sharing: Display clearer error message when the user doesn't have permission to share location in the room (PSG-619)

- RiotSwiftUI/Modules/Room/LiveLocationSharingViewer/LiveLocationSharingViewerModels.swift
- RiotSwiftUI/Modules/Room/LiveLocationSharingViewer/LiveLocationSharingViewerViewModel.swift
- RiotSwiftUI/Modules/Room/LiveLocationSharingViewer/View/LiveLocationSharingViewer.swift
- RiotSwiftUI/Modules/Room/LocationSharing/LocationAnnotation.swift
- changelog.d/6488.change
#6488
| Light | Dark |
|-|-|
| ![IMG_0050](https://user-images.githubusercontent.com/2205780/181448362-0b104e6b-d2aa-41c9-9df7-2edc99962826.PNG) | ![IMG_0049](https://user-images.githubusercontent.com/2205780/181448424-448a7b12-15a7-4821-bb41-5a0f02c5d12c.PNG) |
> Location sharing: Improve live location sharing expanded map state when no more live location shares (PSG-628)

- Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewController.swift
- Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewModel.swift
- Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewState.swift
- changelog.d/4700.bugfix
> Show switch button if there are no public rooms on homeserver (to fix #4700)

- Riot/Modules/PublicRoomList/DataSources/PublicRoomsDirectoryDataSource.m
- Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewController.swift
- Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewModel.swift
- Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewState.swift
- changelog.d/4700.bugfix
Adds a small addition to #6498 in commit 54e4351. The rest of the PR has been reviewed.
Previously the data source was capturing an operation that was unassigned, and so would never error as it was always `nil`. This change checks the `NSError` instead.
This missing errors could be seen when using a local (unfederated) synapse and switching networks, as the loading spinner would never get dismissed.
> Fix missing errors after #6498.

- Riot/Managers/PushNotification/PushNotificationService.m
- changelog.d/6503.change
This PR fixes #6503 by included in-app notifications in Notification Centre. They're handled just like regular notifications and get dismissed in the same way.
> Add Notification Centre to in-app notification delivery options.

- Riot/Modules/Home/VersionCheck/HomeViewControllerWithBannerWrapperViewController.swift
- changelog.d/6487.bugfix
This PR fixes reproducible issues of #6487 where the home tab shows with an incorrect status bar colour.
Since adding the wrapper view, the system hasn't been calling preferredStatusBarStyle directly on `HomeViewController` so has left it as the default style.
| - | - |
| ![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-08-01 at 17 39 39](https://user-images.githubusercontent.com/6060466/182201632-c5d06290-1008-4a69-a141-13fddc8f35df.png) | ![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-08-01 at 17 38 36](https://user-images.githubusercontent.com/6060466/182201643-c8b1d8ff-bc00-40ef-9f09-6bc3b574e3ab.png) |
> Fix status bar style when using a custom theme.

- Riot/Modules/Room/Attachements/AttachmentsViewController.m
- Riot/Modules/Room/Attachements/MXKAttachmentsViewController.h
- Riot/Modules/Room/Attachements/MXKAttachmentsViewController.m
- Riot/Modules/Room/Attachements/MXKAttachmentsViewController.xib
- changelog.d/6486.bugfix
The navigation bar wasn't using the safe area correctly, so it is now inside of a container that ignores the safe area and the top of the bar is aligned to the top of the safe area.
Realistically this view should use a Navigation Controller but this interferes animations so I've themed the container to match the nav bar. One down side of this is that it won't gain the system material when we enable the new app layout 😕
Fixes #6486.
| Light Mode | Dark Mode | iPhone SE |
| - | - | - |
| ![Simulator Screen Shot - iPhone 13 mini - 2022-08-03 at 14 27 22](https://user-images.githubusercontent.com/6060466/182624173-6bd38342-e601-474d-b6f6-0ed17e9da36c.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-08-03 at 14 27 29](https://user-images.githubusercontent.com/6060466/182624199-e18c07f8-e1 …
> Move the attachment navigation bar into a container.

- Riot/Modules/Application/LegacyAppDelegate.h
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Communities/Home/GroupHomeViewController.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Utils/UniversalLink.h
- Riot/Utils/UniversalLink.m
- changelog.d/6492.bugfix
When tapping on an unjoined room alias, the app delegate would look up the room ID for it, but as the link wasn't updated when it attempted to handle the new fragment the look up was made again.
Fixes #6492.
> Fix an infinite loop when tapping an unjoined room alias.

- Riot/Modules/Onboarding/OnboardingCoordinator.swift
- changelog.d/6530.change
Small change in logic that ignores the personalisation steps when registration occurred via a generic SSO provider (i.e. it wasn't a social login provider).
Fixes #6530
> Don't show personalisation after registering with a generic SSO provider.

- RiotShareExtension/Sources/ShareExtensionShareItemProvider.swift
- changelog.d/5922.bugfix
There was a race condition when sending multiple images in the share extension, where the `sendPendingImages` block could be called multiple times. This was because the items were marked as `loaded` on a different thread to the completion handler.
Fixes #5922.
> Fix a race condition when sending multiple images.

- Riot/Modules/MatrixKit/Animators/MXKAttachmentAnimator.h
- Riot/Modules/MatrixKit/Animators/MXKAttachmentInteractionController.m
- Riot/Modules/Room/Attachements/MXKAttachmentsViewController.m
- changelog.d/6475.bugfix
Fixes #6475 - Added logic to the interaction controller, when the interaction starts and cancels, so we can hide / show the WKWebView when the attachment is a GIF image type.
https://user-images.githubusercontent.com/26399/180901176-15861e53-bc22-46b8-b65d-07addee026cc.mp4
https://user-images.githubusercontent.com/26399/180900809-d9e99720-b125-4c5c-ad2c-5452e27c1790.mov
> Fixes a glitch when dismissing a GIF in the media attachment viewer (#6475)

- Riot/Modules/Authentication/AuthenticationCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/AuthenticationService.swift
- RiotTests/Modules/Authentication/AuthenticationServiceTests.swift
- changelog.d/6489.bugfix
This PR makes 2 changes to the authentication.
- Always load the default homeserver (or provisioned one) when starting a new auth flow
- If an error occurs when starting a new auth flow, show the server selection screen instead of an error (so the user can potentially choose a different server to fix the error).
Fixes #6489.
> Reset registration.

- Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift
- changelog.d/6529.change
This reverts commit f92bda4e8822bb9cceeda293120c01f5ba0f569e, reversing
changes made to b7713043b15b26606b2d11fb183379881d7ad498.
This undoes the changes from #6529. Testing with longer voice messages and on real devices has revealed that the absence of a loading state both for sending and receiving voice messages can make the feature very hard to use on longer voice messages. The issue still persists on 2m voice messages, too, but is at least less apparent.
Relates to #5415
> Revert maximum voice message recording length back to 2m (PSG-662)

- Riot/Modules/Room/Attachements/MXKAttachmentsViewController.m
- changelog.d/6548.bugfix
Adds a small sanity check following a few crashes reported in the RC.
Fixes #6548.
> Fix potential crash when dismissing an image.

- Riot/Assets/en.lproj/InfoPlist.strings
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/SupportingFiles/Info.plist
- changelog.d/6559.misc
Updates some usage strings and a screen title in FTUE
Fixes #6559 🤞
| Contacts | Photos | Camera |
| - | - | - |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-08-11 at 16 48 51](https://user-images.githubusercontent.com/6060466/184175666-8234408a-baee-434b-b3ba-997e6a0156f1.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-08-11 at 16 49 09](https://user-images.githubusercontent.com/6060466/184175687-bddfb436-a7f3-4e9c-abd5-e6e6bfdef246.png) | ![IMG_360742F9BE29-1](https://user-images.githubusercontent.com/6060466/184176794-a2a543b4-aae4-478a-bb5e-7c7e3afe444e.jpeg) |
| FTUE Header |
| - |
| ![Screenshot 2022-08-11 at 4 42 55 pm](https://user-images.githubusercontent.com/6060466/184174000-adda72f9-aef0-4f26-80f5-6a3ec449b621.png) |
> Update camera, contacts and photos usage strings for App Store review.

- Riot/Modules/KeyBackup/Recover/KeyBackupRecoverCoordinator.swift
- Riot/Modules/KeyBackup/Setup/KeyBackupSetupCoordinator.swift
- Riot/Modules/KeyBackup/Setup/Passphrase/KeyBackupSetupPassphraseViewModel.swift
- Riot/Modules/MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.m
- changelog.d/pr-6555.change
Adapt to changes in https://github.com/matrix-org/matrix-ios-sdk/pull/1542.
Adds an entry into the encryption info view for `MXEvent.isUntrusted`. It's for debugging purposes, will be updated later.
> Symmetric backup

- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginModels.swift
- changelog.d/6569.bugfix
The identity providers list is optional in the spec and can be missing on homeservers that **do** support SSO.
The solution is to provide a nameless fallback identity provider that would make a generic button be shown on the login screen and use the base path as the sso redirect path here https://github.com/vector-im/element-ios/blob/develop/Riot/Modules/Authentication/SSO/SSOAuthenticationService.swift#L53
> Fixes #6569 - Provide SSO backup for homeservers that don't return an identity providers list

- Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h
- Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m
- Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithSimpleTextView.m
- Riot/Modules/Room/MXKRoomViewController.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/RoomViewController.xib
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
- changelog.d/5932.bugfix
I couldn't reproduce the issue by playing with network connection. I could see a blank screen but also a syncing spinner was there.
The issue seen on iPad was due to an unnecessary `inputAccessoryView` on message text view. Somehow the table view was insetted wrongly (so that all the content to be out of screen).
This PR also addresses some suspicious `UITableView` errors i saw in logs.
There may be other cases for the issue we're not aware of yet.
1. `Element[4045:46257] [Assert] Attempted to access the table view's visibleCells while they were in the process of being updated, which is not allowed. Make a symbolic breakpoint at UITableViewAlertForVisibleCellsAccessDuringUpdate to catch this in the debugger and see what caused this to occur. Perhaps you are trying to ask the table view …
> Fix blank room screen

- .github/workflows/release-alpha.yml
- Brewfile
- Gemfile.lock
- changelog.d/pr-6413.misc
- fastlane/Fastfile
- fastlane/Pluginfile
Automatically upload dsym files to [sentry](https://docs.sentry.io/platforms/apple/guides/ios/dsym/#dsym-without-bitcode) when Alpha build is produced and binary uploaded to Diawi
> Upload Dsyms to Sentry when building Alpha

- Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
- Riot/Modules/KeyVerification/User/Start/UserVerificationStartViewModel.swift
Small changes on the client side related to Crypto SDK verification flow changes https://github.com/matrix-org/matrix-ios-sdk/pull/1532
> Outgoing SAS User Verification Flow

- Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
- changelog.d/6578.bugfix
> App Layout: reintroduced existing left markers on room cells

- Config/BuildSettings.swift
- changelog.d/6616.change
> App Layout: Activate feature

- Riot/Modules/SetPinCode/SetPinCoordinatorBridgePresenter.swift
- changelog.d/pr-6629.bugfix
This PR fixes the PIN entry screen layout if the app is used in landscape mode. It will still force it to be rendered in portrait as per original code.
> Render the PIN entry screen correctly on landscape

- Riot/Modules/Analytics/SentryMonitoringClient.swift
- fastlane/Fastfile
- Reduce sampling of Sentry errors to 10% (previously I only reduced tracesSampleRate, used for transaction sampling)
- Upload Dsyms only as part of App Store builds (made from local machines), not Alpha builds uploaded to Diawi
> Upload Sentry Dsyms for App Store builds

- Riot/Modules/Application/LegacyAppDelegate.m
- changelog.d/6589.feature
Resolves #6589 
[SDK changes](https://github.com/matrix-org/matrix-ios-sdk/pull/1565)
App delegate is relying on concrete implementations of verification requests. We need to change this to protocols instead for it to work with v2 requests sa well
> Self-verification flow in Crypto V2

- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Analytics/SentryMonitoringClient.swift
- changelog.d/pr-6647.change
Implement `startDurationTracking` of `MAnalyticsDelegate` and send performance events to Sentry
> Measure performance in Sentry

- Riot/Modules/MatrixKit/Models/Room/MXKSlashCommands.h
- Riot/Modules/MatrixKit/Models/Room/MXKSlashCommands.m
- Riot/Modules/Room/MXKRoomViewController.m
- changelog.d/pr-6668.change
This is equivalent to the `/discardsession` command used in the web client
> Slash command to manually discard outbound session

- Riot/Modules/Common/Recents/Views/RecentTableViewCell.xib
- changelog.d/6512.bugfix
> Last message time ellipsis

- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.h
- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- Riot/Modules/Room/MXKRoomViewController.m
- Riot/Modules/Room/RoomViewController.m
- changelog.d/6670.bugfix
Fixes #6670 
Remove partialTextMessage on Matrix SDK: https://github.com/matrix-org/matrix-ios-sdk/pull/1571
> Fix mention pills display when coming back to a room with an unsent message

- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
- changelog.d/6441.bugfix
This fixes empty gaps on the timeline caused by incorrect text height calculations. It does so by switching to NSAttributedString's own boundingRectWithSize and reading textContainer defaults from a dummy text view. 
Ideally the actual UITextView that will render the text should be used here but that's not possible without major refactoring.
> Fixes vector-im/element-ios/issues/6441 - Incorrect timeline item text height calculation

- Riot/Assets/de.lproj/Vector.strings
- Riot/Assets/en.lproj/Vector.strings
- Riot/Assets/fr.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Application/LegacyAppDelegate.h
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Application/ScreenNavigation/RoomNavigationParameters.swift
- Riot/Modules/Contacts/Details/ContactDetailsViewController.m
- Riot/Modules/Home/AllChats/AllChatsCoordinator.swift
- Riot/Modules/MatrixKit/Views/RoomTitle/MXKRoomTitleView.h
- Riot/Modules/MatrixKit/Views/RoomTitle/MXKRoomTitleView.m
- Riot/Modules/Room/Members/RoomParticipantsViewController.m
- Riot/Modules/Room/RoomCoordinator.swift
- Riot/Modules/Room/RoomCoordinatorParameters.swift
- Riot/Modules/Room/RoomCoordinatorProtocol.swift
- Riot/Modules/Room/RoomViewController.h
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Settings/RoomSettingsViewController.m
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
- Riot/Modules/TabBar/TabBarCoordinator.swift
- Riot/Modules/Threads/ThreadsCoordinator.swift
> Start DM on first message

- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
- changelog.d/pr-6702.bugfix
> Fix timeline items text height calculation

- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- changelog.d/6709.bugfix
When clearing the cache with the new app layout, the launch screen spinner was never hidden. `addMatrixSession`/`removeMatrixSession` had some extra logic in the master tab bar controller that was no longer being called. This PR adds it back.
It's not possible to set the `dataSource` to `nil` when no sessions are present as [done in the tab bar](https://github.com/vector-im/element-ios/blob/a12ef0118d5968e60e15214a69ac98bb17e7f03a/Riot/Modules/TabBar/MasterTabBarController.m#L437-L438), but this doesn't seem to cause an issue here.
<del>I wonder if this could be related to #6705 as well.</del> Nope I just read that one properly 🤦‍♂️
Fixes #6709
> Dismiss the launching screen when clearing cache.

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- changelog.d/6584.bugfix
Fixes https://github.com/vector-im/element-ios/issues/6584
> Fix Crash when some opus files are added to a room

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Common/Recents/Service/MatrixSDK/RecentsListService.swift
- changelog.d/6705.bugfix
- changelog.d/6724.bugfix
Fixes #6705 #6724 
* Updates the tooManyErrors popup display that wasn't showing up over the pin code screen and was blocking the app from returning to the Onboarding/Login screen. It is now displayed right after the logout over the Onboarding/Login screen.
* Closes the session immediately when a logout is triggered.
* Updates the RecentsListService to avoid trying to setup fetchers when session is closed or currently closing (fix for the race condition is not optimal, perhaps a MXSessionStateClosing transition state would be better, but it probably would imply some impactful changes across MatrixSDK & the app).
> Fix crash on logout when syncing is currently in progress

- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/LoginWizard.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/RegistrationWizard.swift
- RiotSwiftUI/Modules/Authentication/Common/Service/MatrixSDK/SessionCreator.swift
- RiotTests/Modules/Authentication/Mocks/MockSessionCreator.swift
- RiotTests/SessionCreatorTests.swift
- changelog.d/6722.bugfix
Fixes #6722
To be honest, I'm not sure if this is a Swift bug or not but the additional `@MainActor` appears to force the `await`ed call onto the main thread which prevents the assertion.
> Fix login crash on Xcode 14 builds

- Riot/Modules/Home/AllChats/AllChatsCoordinator.swift
- changelog.d/6654.bugfix
Fixes #6654 as the popovers were missing their source views.
> Add missing source views for iPad.

- Riot/Generated/Strings.swift
- Riot/Modules/Room/RoomViewController.m
- changelog.d/6708.bugfix
Fixes #6708 as the composer was being disabled and then immediately re-enabled. Didn't figure out why this was only visible on some devices, but the fix was to not disable the composer in an existing room.
| - | - |
| ![Before](https://user-images.githubusercontent.com/6060466/190711837-e4825143-f3c9-4afa-92ed-be9367344308.gif) | ![After](https://user-images.githubusercontent.com/6060466/190711839-202f8cf7-2b4e-4eaa-b530-5c1952b97763.gif) |
> Only disable the composer if the room is yet to be created.

- Riot/Modules/Room/RoomViewController.h
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/RoomViewController.xib
- RiotSwiftUI/Modules/Room/UserSuggestion/Coordinator/UserSuggestionCoordinator.swift
- RiotSwiftUI/Modules/Room/UserSuggestion/Coordinator/UserSuggestionCoordinatorBridge.swift
- changelog.d/6734.bugfix
> Timeline composer layout loop fix

- Riot/Modules/DeepLink/MXRoomAliasResolution+Deeplink.swift
- RiotTests/Modules/DeepLink/MXRoomAliasResolutionDeeplinkTests.swift
- changelog.d/6653.bugfix
resolves #6653 
I don't get why `stringByAddingPercentEncodingWithAllowedCharacters` is applied to the result as per the comment of this member https://github.com/matrix-org/matrix-spec-proposals/blob/old_master/proposals/1704-matrix.to-permalinks.md is not intended.
Also this breaks the only caller `LegacyAppDelegate.handleUniversalLinkWithParameters()`.
> Fixed failed to join room (was not legal room)

- changelog.d/pr-6757.build
- codecov.yml
Matching https://github.com/vector-im/element-x-ios/pull/202 and https://github.com/matrix-org/matrix-rust-sdk/pull/700 to remove the failures we've been seeing on PRs recently.
> Disable codecov/patch.

- Riot/Modules/MatrixKit/Utils/EventFormatter/MarkdownToHTMLRenderer.swift
- RiotTests/MarkdownToHTMLRendererTests.swift
- changelog.d/6748.bugfix
> Fix render of links with both characters requiring percent encoding and markdown-like syntax

- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/6723.bugfix
Fixes #6723
Unfortunately, this still leaves the user on what looks like a rate limiting error. Element Web has the same issue so this appears to be a separate problem.
> Pass country code into MSISDN requests

- Config/CommonConfiguration.swift
- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Riot/Assets/third_party_licenses.html
- Riot/target.yml
- RiotNSE/target.yml
- RiotShareExtension/target.yml
- RiotTests/target.yml
- SiriIntents/target.yml
- changelog.d/6742.change
- project.yml
> Include concrete device model in user agent (PSG-754)

- Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
A small fix for cross-signing that checks the type of key verification transaction. Crypto V1 has some legacy issue where this check is needed, whereas Crypto V2 does not, so changing the code to only apply to the legacy types
> Fix verification check

- Riot/Utils/EventFormatter.m
- changelog.d/6778.bugfix
> Fix code block background colour

- Riot/Modules/KeyVerification/User/UserVerificationCoordinator.swift
- Riot/Modules/KeyVerification/User/UserVerificationCoordinatorBridgePresenter.swift
- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
- Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
- changelog.d/6781.change
Relates to https://github.com/vector-im/element-ios/issues/6781
Small changes to refresh a view controller when manual device verification is complete. The relevant delegate methods existed previously but delegates were never set and called.
> Manual device verification with Crypto V2

- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- Riot/Modules/Home/AllChats/AllChatsViewController.xib
- changelog.d/6755.bugfix
resolves #6755 
Using the `UIToolbar` of the `UINavigationController` was not a great idea as the toolbar could overlap the UI when navigating (even if the toolbar was explicitly hidden). The `AllChatsViewController` has now its own toolbar to avoid this issue.
> Unable to send message after filtering for room

- Riot/target.yml
- RiotSwiftUI/Modules/UserSessions/Common/UserSessionLastActivityFormatter.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardView.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardViewData.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Coordinator/UserSessionsOverviewCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/MockUserSessionsOverviewScreenState.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsDataProvider.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsDataProviderProtocol.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsOverviewService.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/Mock/MockUserSessionsOverviewService.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Test/UI/UserSessionsOverviewUITests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Test/Unit/UserSessionsOverviewViewModelTests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/UserSessionsOverviewModels.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionListItemViewData.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionsOverview.swift
- RiotSwiftUI/target.yml
- RiotSwiftUI/targetUITests.yml
- RiotSwiftUI/targetUnitTests.yml
- RiotTests/UserSessionsOverviewServiceTests.swift
- RiotTests/target.yml
- Add UserSessionsOverviewService unit tests, introduce a DataProvider and abstract away from MXSession and friends
- Add sessions overview UI tests
- Add UserSessionsOverviewViewModel unit tests
- Expose static methods from the UserSession name and lastActivity formatters
- cleaned up the UserSessionsOverview a bit 
- enable coverage gathering on all schemes
> Add UserSessionOverview tests

- Config/BuildSettings.swift
- Config/CommonConfiguration.swift
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Managers/Settings/RiotSettings.swift
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/pr-6780.change
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1588
Adds two labs flag to the settings screen.
> New session manager labs flag (PSG-792)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Home/AllChats/AllChatsCoordinator.swift
- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- changelog.d/6580.bugfix
The User Menu and Spaces buttons were just described as "Button".
Part of #6580, but doesn't close it as the spaces sheet needs more work to properly define accessibility elements and test across iOS 14-16.
> Add missing accessibility labels on All Chats buttons.

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Managers/Call/CallPresenter.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardView.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardViewData.swift
- RiotSwiftUI/Modules/UserSessions/Coordinator/UserSessionsFlowCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Coordinator/UserSessionOverviewCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/MockUserSessionOverviewScreenState.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Service/MatrixSDK/UserSessionOverviewService.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Service/Mock/MockUserSessionOverviewService.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Service/UserSessionOverviewServiceProtocol.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Test/UI/UserSessionOverviewUITests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Test/Unit/UserSessionOverviewViewModelTests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/UserSessionOverviewModels.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/UserSessionOverviewViewModel.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverview.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverviewDisclosureCell.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverviewToggleCell.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Coordinator/UserSessionsOverviewCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsDataProvider.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/UserSessionsOverviewModels.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/UserSessionsOverviewViewModel.swift
- RiotTests/UserSessionsOverviewServiceTests.swift
- changelog.d/6787.change
> Added support for MSC3881

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- RiotSwiftUI/Modules/UserSessions/Common/UserAgentParser.swift
- RiotSwiftUI/Modules/UserSessions/Common/UserSessionInfo.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardView.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionDetails/MockUserSessionDetailsScreenState.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionDetails/Test/Unit/UserSessionDetailsViewModelTests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionDetails/UserSessionDetailsViewModel.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/MockUserSessionOverviewScreenState.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Test/Unit/UserSessionOverviewViewModelTests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsDataProvider.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsDataProviderProtocol.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsOverviewService.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/Mock/MockUserSessionsOverviewService.swift
- RiotTests/UserAgentParserTests.swift
- changelog.d/pr-6788.change
Parses browser version and also polishes formatting for macOS:
> Include browser version in parsed user agent (PSG-761)

- CHANGES.md
- Riot/Modules/Common/Recents/RecentsViewController.h
- Riot/Modules/Common/Recents/RecentsViewController.m
- Riot/Modules/Home/AllChats/AllChatsViewController.swift
The empty artwork view was obscuring it. Changelog added directly to CHANGES.md for the release branch. 
| - | - |
| ![Simulator Screen Shot - iPhone 12 - 2022-10-04 at 14 31 42](https://user-images.githubusercontent.com/6060466/193838879-cd9e3ffa-d751-4667-be53-d429ac858d7b.png) | ![Simulator Screen Shot - iPhone 12 - 2022-10-04 at 14 47 14](https://user-images.githubusercontent.com/6060466/193838899-faebf7e4-6da0-4d7d-9397-1febd20baa75.png) |
> Fix missing toolbar in AllChatsViewController.

- CHANGES.md
- Riot/Modules/Common/SwiftUI/VectorHostingController.swift
- RiotSwiftUI/Modules/AnalyticsPrompt/Coordinator/AnalyticsPromptCoordinator.swift
- RiotSwiftUI/Modules/Onboarding/Celebration/Coordinator/OnboardingCelebrationCoordinator.swift
- RiotSwiftUI/Modules/Onboarding/Congratulations/Coordinator/OnboardingCongratulationsCoordinator.swift
- RiotSwiftUI/Modules/Onboarding/SplashScreen/Coordinator/OnboardingSplashScreenCoordinator.swift
When building with Xcode 13, Element iOS running on iOS 16 has had some issues with the navigation bars not behaving as expected from SwiftUI. This appears to be twofold:
1. The `.navigationBarHidden(true)` modifier doesn't appear to work inside of `VectorHostingController` on presentation (it does however work when popping back to a screen with the modifier.
2. Using `viewWillAppear` to update the navigation controller with the custom  `isNavigationBarHidden` appears to now occur before the hosting controller has been added to the navigation controller.
This PR sets the `isNavigationBarHidden` on screens that weren't using it and uses this property in `viewWillLayoutSubviews`.
The changelog is included in CHANGES.md ready for the release branch. Fixes #6738
| Splash Screen Before | …
> Fix navigation bars inside of VectorHostingController.

- Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewController.swift
- Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewController.swift
- Riot/Modules/Settings/Language/LanguagePickerViewController.m
- Riot/Modules/Settings/PhoneCountry/CountryPickerViewController.m
- Riot/Modules/Settings/Security/SecurityViewController.m
- Riot/Modules/Settings/SettingsViewController.m
- RiotSwiftUI/Modules/Settings/Notifications/Coordinator/NotificationSettingsCoordinator.swift
- changelog.d/6804.bugfix
Fixes #6804 
Some screenshots below:
| Terms | Identity | Discovery | Notifications |
| - | - | - | - |
| ![Simulator Screen Shot - iPhone 13 mini - 2022-10-05 at 15 15 56](https://user-images.githubusercontent.com/6060466/194083295-006edbb7-140f-44af-9a25-72e0676dcbd6.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-10-05 at 15 16 01](https://user-images.githubusercontent.com/6060466/194083323-975812f7-e452-44aa-8f73-cce327e5bac8.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-10-05 at 15 16 11](https://user-images.githubusercontent.com/6060466/194083462-fb3a27c7-3d53-4ef0-9af7-f0d2063a8b7e.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-10-05 at 15 16 17](https://user-images.githubusercontent.com/6060466/194083484-c0cf92ec-b296-4c9c-89cb-b0dc8c455e53.png) |
> Use regular titles for sub-screens of Settings.

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/UserInteractiveAuthentication/AuthenticatedEndpointRequest.swift
- RiotSwiftUI/Modules/UserSessions/Coordinator/UserSessionsFlowCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/Coordinator/UserSessionsFlowCoordinatorBridgePresenter.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Coordinator/UserSessionOverviewCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/UserSessionOverviewModels.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/UserSessionOverviewViewModel.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverview.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverviewItem.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Coordinator/UserSessionsOverviewCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/UserSessionsOverviewModels.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/UserSessionsOverviewViewModel.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionsOverview.swift
- changelog.d/6802.wip
Adds the logout actions to both the current session section in the all sessions overview and to the single session overview screen as a button.
The UI for the rename action has been added but isn't hooked up to any logic yet.
Fixes #6802
| Light Mode | Dark Mode |
| - | - |
| ![Simulator Screen Recording - iPhone 13 mini - 2022-10-05 at 14 14 06](https://user-images.githubusercontent.com/6060466/194073234-515e79e3-436e-4e91-97db-451ecdda0de6.gif) | ![Simulator Screen Recording - iPhone 13 mini - 2022-10-05 at 14 14 59](https://user-images.githubusercontent.com/6060466/194073289-0ce9d128-7cb3-48af-8880-a5bdc9d5e555.gif) |
> Session Manager: Single session logout

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
- Riot/Modules/KeyVerification/Common/KeyVerificationCoordinatorBridgePresenter.swift
- Riot/Modules/KeyVerification/Common/KeyVerificationFlow.swift
- Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
- Riot/Modules/KeyVerification/Device/Incoming/DeviceVerificationIncomingCoordinator.swift
- Riot/Modules/KeyVerification/Device/Incoming/DeviceVerificationIncomingViewModel.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinator.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinatorType.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModelType.swift
- Riot/Modules/KeyVerification/Device/Start/DeviceVerificationStartViewModel.swift
- Riot/Modules/Room/DataSources/RoomDataSource.m
- changelog.d/6809.change
Turn `MXKeyVerificationManager` into a protocol and rename all existing objective-c implementations to `MXLegacy...` variants. Additionally replace all references to concrete implementations of `...Request` and `...Transaction` to relevant protocols. This is to make Crypto V2 verification api safer.
Corresponding [API change](https://github.com/matrix-org/matrix-ios-sdk/pull/1599)
> Refactor verification manager, request, transactions

- Riot/Assets/en.lproj/Vector.strings
- Riot/Categories/UIDevice.swift
- Riot/Generated/Strings.swift
- changelog.d/6828.change
The current default session display name is "Mobile" or "Tablet" which isn't very descriptive as it doesn't disclose what actual client this session belongs to. This PR changes the default session name to "%@ iOS" where current application name (e.g. "Element") is inserted into the placeholder. This harmonizes the default name with Element Android which uses the same pattern.
There is an argument to be made about including the device type (phone vs. tablet) in the name. However, since we have the concrete device model available via the new device manager, I think this is better solved via the UI.
> Include app name in default session display name

- Riot/Modules/Common/SwiftUI/VectorHostingController.swift
- changelog.d/6833.bugfix
Fixes #6833. The glitch was caused by my fix for #6738 not taking into account the embedded SwiftUI `UserSuggestions` module in `RoomViewController`, so it was modifying the navigation bar when it shouldn't have.
I've tested this change on iOS 15/16 with the auth flow and the navigation bar shows/hides as intended.
> Only update the nav bar from the top SwiftUI hosting controller.

- RiotSwiftUI/Modules/LocationSharing/StartLocationSharing/Coordinator/LocationSharingCoordinator.swift
- changelog.d/5571.bugfix
This PR removes the loader when sharing a location or a live location.
Ticket -> https://element-io.atlassian.net/browse/PSG-818?atlOrigin=eyJpIjoiMjg2ODk3NjJkZmY1NDZmYmIxYjI1NDNiMzgxMTAwYTIiLCJwIjoiaiJ9
Fixes https://github.com/vector-im/element-ios/issues/5571
> Remove location loader (PSG-818)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastService.swift
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastSettings.swift
- RiotSwiftUI/Modules/UserSessions/Common/UserSessionInfo.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardViewData.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionName/MockUserSessionNameScreenState.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionName/Test/Unit/UserSessionNameViewModelTests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsOverviewService.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Test/Unit/UserSessionListItemViewDataFactoryTests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionListItemViewDataFactory.swift
- RiotTests/target.yml
This PR updates the strings for #6832.
It also makes sure that unverified sessions card is hidden when the current session is unverified.
No changelog as it already exists from the previous PR.
| Sessions | Unknown Session |
| - | - |
| ![Simulator Screen Shot - iPhone 13 mini - 2022-10-12 at 12 10 23](https://user-images.githubusercontent.com/6060466/195328035-a0bf8188-418c-4c46-8204-9f16dbbb734c.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-10-12 at 12 10 32](https://user-images.githubusercontent.com/6060466/195328053-be2f545a-19bd-422a-8254-0a774a9789a4.png) |
> Update strings for unknown sessions.

- Config/BuildSettings.swift
- Riot/Modules/Authentication/AuthenticationCoordinator.swift
- RiotSwiftUI/Modules/Authentication/Login/Coordinator/AuthenticationLoginCoordinator.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Models/QRLoginCode.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/Mock/MockQRLoginService.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/QRLoginServiceProtocol.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Loading/MockAuthenticationQRLoginLoadingScreenState.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Scan/Coordinator/AuthenticationQRLoginScanCoordinator.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Start/Coordinator/AuthenticationQRLoginStartCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Test/Unit/UserSessionListItemViewDataFactoryTests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionsOverview.swift
- RiotTests/Modules/Authentication/Mocks/MockAuthenticationRestClient.swift
This PR adds E2EE setup support for sessions created through QR Code login rendezvous channels. It locally verifies the existing devices and then proceeds to recoving the secrets and finishing the session setup. It also slightly changes the authentication flows to cater to this
> E2EE support for Login with QR Code

- RiotSwiftUI/Modules/UserSessions/Coordinator/UserSessionsFlowCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserOtherSessions/Coordinator/UserOtherSessionsCoordinator.swift
- RiotSwiftUI/Modules/UserSessions/UserOtherSessions/UserOtherSessionsModels.swift
- changelog.d/6877.bugfix
closes #6877
Selecting a session from other sessions screen should go to session overview.
> Device Manager: Navigating to session overview goes to session details

- Podfile
- Podfile.lock
- RiotSwiftUI/target.yml
- changelog.d/6886.build
This PR makes 2 changes:
- Un-pin versions to update tools on each release.
- SwiftLint isn't updated regularly, this will help us keep updated but in a more stable way than on EX as running `pod install` will still give reproducible results.
- Switch to SwiftFormat as a pod
- Ensures that it is run for everyone and not skipped if it hasn't been installed.
> Update build tools.

- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- changelog.d/6869.bugfix
> All chats shows no rooms in the list

- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardView.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardViewData.swift
- changelog.d/6881.wip
closes #6881 
Session tiles for inactive sessions show ‘inactive for 90+ days’ UI
> Device manager: Identify inactive sessions.

- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/6888.bugfix
> "Notifications on this device" not refreshed in user settings screen

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
- project.yml
> Fix tap area being too small on composer

- RiotSwiftUI/Modules/UserSessions/UserSessionDetails/UserSessionDetailsViewModel.swift
- changelog.d/pr-6898.bugfix
Ticket -> https://element-io.atlassian.net/browse/PSG-898
**Description**
This PR hides the "Application" section in the session details when no information are available.
> Filter out application section in session details (PSG-898)

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
- RiotSwiftUI/Modules/Room/Composer/View/FormattingToolbar.swift
- changelog.d/6903.change
- changelog.d/pr-6901.change
- project.yml
Improvements to match as closely as possible the Figma designs
https://user-images.githubusercontent.com/34335419/196231198-91eb2fd1-8439-4802-b378-df13fd815473.MP4
> WYSIWYG design improvements

- Riot/Modules/Rendezvous/RendezvousService.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Models/QRLoginCode.swift
- changelog.d/pr-6899.misc
> Use unstable prefixes for QR code login

- .github/workflows/ci-tests.yml
- .github/workflows/ci-ui-tests.yml
- .github/workflows/release-alpha.yml
- codecov.yml
This PR:
* introduces codecov flags for unit and ui tests and carries them forward automatically
* makes it so alpha builds only happen when the PR is labeled with `Trigger-PR-Build`
> Codecov flags + PR build labels

- Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.xib
- changelog.d/pr-6919.bugfix
Fixes #6900 
This file was missing from https://github.com/vector-im/element-ios/pull/6902 by mistake.
> Rich Text Composer :Missing change from fix for interactive dismissal

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/VoiceBroadcast/MXSession+VoiceBroadcast.swift
- RiotSwiftUI/Modules/Room/Composer/CreateActionList/Model/ComposerCreateActionListModels.swift
- Update the existing implementation used to start/stop a voice broadcast in order to handle the different cases where voice broadcast is denied
- Add the optional Voice broadcast action to the new wysiwyg composer
- no change-log has been added because the feature is still hidden behind a Labs flag
> Display info dialogs when we prevent the user from starting a new voice broadcast

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
- Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.swift
- Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
- RiotSwiftUI/Modules/Room/Composer/Model/ComposerViewState.swift
- RiotSwiftUI/Modules/Room/Composer/Test/Unit/ComposerViewModelTests.swift
- RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
- RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModel.swift
- RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModelProtocol.swift
- changelog.d/6935.change
- project.yml
Implemented a responsive placeholder text in the RichTextComposer using the same logic of the normal composer
https://user-images.githubusercontent.com/34335419/196721183-99507d49-5b97-4f9b-8c2a-c6ffbefa5aa5.MP4
> Rich Text Composer Placeholder Text

- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/TimelineCells/Common/MXKRoomBubbleTableViewCell.m
- changelog.d/pr-6936.change
**Ticket** -> https://element-io.atlassian.net/browse/PSG-819
This PR improves the interaction with external links by:
- Adding a visual feedback for taps
- Adding the possibility to see a preview of the web page in the room
https://user-images.githubusercontent.com/19324622/196694579-ffbef7ec-939b-40b6-ac36-263cbc0b8431.mp4
> Improve external links interaction UX (PSG-819)

- Riot/Modules/Common/Avatar/AvatarView.swift
- Riot/Modules/Common/Avatar/AvatarViewData.swift
- Riot/Modules/Common/Avatar/AvatarViewDataProtocol.swift
- Riot/Modules/Home/AllChats/AllChatsCoordinator.swift
- Riot/Modules/Room/NotificationSettings/UIKit/RoomNotificationSettingsAvatarView.swift
- Riot/Modules/Room/Views/Avatar/RoomAvatarViewData.swift
- Riot/Modules/Rooms/ShowDirectory/Cells/Room/DirectoryRoomTableViewCellVM.swift
- Riot/Modules/User/Avatar/UserAvatarViewData.swift
- changelog.d/6847.bugfix
**Ticket**: https://element-io.atlassian.net/browse/PSB-198
**Description**
This PR makes the avatar image loading more robust:
* Adding multiple fallback images
* Setting the fallback before the avatar url is fetched to avoid leaving a blank image view
Fixes: https://github.com/vector-im/element-ios/issues/6847
> Update avatar image loading logics (PSB-198)

- Riot/Modules/Common/Avatar/AvatarView.swift
This PR fixes a potential crash introduced by this PR: https://github.com/vector-im/element-ios/pull/6927 
It looks like sometimes the avatar view doesn't have the inner image view ready.
> Fix AvatarView crash

- Riot/Modules/Room/MXKRoomViewController.h
- Riot/Modules/Room/RoomViewController.m
- changelog.d/6949.bugfix
Removed legacy lines of code which actually did nothing aside from cause the flickering of the placeholder.
> Bugfix for placeholder flickering in the normal and new composer when there is a height change.

- Riot/Modules/Application/LegacyAppDelegate.h
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
- Riot/Modules/KeyVerification/Device/Start/DeviceVerificationStartCoordinator.swift
- Riot/Modules/KeyVerification/Device/Start/DeviceVerificationStartCoordinatorType.swift
- Riot/Modules/KeyVerification/Device/Start/DeviceVerificationStartViewModel.swift
- Riot/Modules/KeyVerification/Device/Start/DeviceVerificationStartViewModelType.swift
- Riot/Modules/KeyVerification/User/UserVerificationCoordinator.swift
- Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
- changelog.d/pr-6937.change
Corresponding [SDK change](https://github.com/matrix-org/matrix-ios-sdk/pull/1613)
Deprecate legacy device-to-device verification that begins with `m.key.verification.start` events rather than `m.key.verification.request`. This means that device verification will be observing verification request rather than a transaction
> Deprecate legacy device-to-device verification

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- Riot/Modules/Settings/Security/SecurityViewController.m
- RiotTests/UserSessionsDataProviderTests.swift
- changelog.d/pr-6943.change
See related [SDK change](https://github.com/matrix-org/matrix-ios-sdk/pull/1614)
> Define MXCrypto and MXCrossSigning as protocols

- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleComponent.m
- Riot/Modules/Room/TimelineCells/Common/MXKRoomBubbleTableViewCell.m
- RiotSwiftUI/Modules/Common/Mock/ScreenList.swift
- RiotSwiftUI/Modules/Common/Test/UI/XCUIApplication+Riot.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Test/UI/TimelinePollUITests.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollAnswerOptionButton.swift
- RiotSwiftUI/Modules/Room/UserSuggestion/Test/UI/UserSuggestionUITests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionDetails/Test/UI/UserSessionDetailsUITests.swift
- fastlane/Fastfile
This PR switches the CI to Xcode 14 and the iPhone 14 simulator. 
Following this change some of the UI tests were broken:
* default identifiers for some buttons have changed format internally. Fixed the majority of them by adding extra accessibility identifiers
* some SwiftUI views are no longer tableView based
* the root screen filtering stopped working consistenly and I had to work around it
> Switch the CI to code 14 and the iOS 14 simulator

- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift
- prevents incorrect camera access requests
- prevents crashes after actor hopping when tearing down rendezvous
> QR login fixes

- .github/workflows/triage-move-labelled.yml
- changelog.d/pr-6996.build
Add Z-Labs tag for rich text editor and update to the new label naming
> Add Z-Labs tag for rich text editor and update to the new label naming

- Riot/Modules/Settings/Security/SecurityViewController.m
- changelog.d/pr-6999.change
This PR hides the old session list when the new device manager is enabled.
> Hide old sessions list when the new dm is enabled (PSG-716)

- RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/MatrixSDK/VoiceBroadcastRecorderService.swift
Send the last chunk with the right sequence number
We reset now and teardown the service only after the last chunk is sent
Fix #6997
> Voice Broadcast - BugFix - send the last chunk

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Authentication/SessionVerificationListener.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- Riot/Modules/Settings/SettingsViewController.m
- RiotShareExtension/Shared/ShareManager.m
- SiriIntents/IntentHandlers/SendMessage/SendMessageIntentHandler.m
A few changes to [CryptoV2 implementation](https://github.com/vector-im/element-ios/pull/6985) after extensive testing with polyjuce:
- always ensure correct type before typecasting to legacy crypto
- create new or accept existing self-verification request
> CryptoV2 changes

- Config/CommonConfiguration.swift
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Authentication/AuthenticationCoordinator.swift
- Riot/Modules/Authentication/Legacy/LegacyAuthenticationCoordinator.swift
- Riot/Modules/Authentication/SessionVerificationListener.swift
- Riot/Modules/Call/CallViewController.m
- Riot/Modules/CrossSigning/CrossSigningService.swift
- Riot/Modules/CrossSigning/Setup/CrossSigningSetupCoordinator.swift
- Riot/Modules/KeyBackup/Recover/KeyBackupRecoverCoordinator.swift
- Riot/Modules/KeyBackup/Recover/KeyBackupRecoverCoordinatorBridgePresenter.swift
- Riot/Modules/KeyBackup/Setup/KeyBackupSetupCoordinator.swift
- Riot/Modules/KeyBackup/Setup/Passphrase/KeyBackupSetupPassphraseCoordinator.swift
- Riot/Modules/KeyVerification/Common/Loading/KeyVerificationDataLoadingViewModel.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
- Riot/Modules/KeyVerification/User/SessionsStatus/UserVerificationSessionsStatusViewModel.swift
- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/RoomKeyRequest/RoomKeyRequestViewController.h
- Riot/Modules/RoomKeyRequest/RoomKeyRequestViewController.m
- Riot/Modules/Secrets/Reset/SecretsResetViewModel.swift
- Riot/Modules/SecureBackup/Setup/SecureBackupSetupCoordinator.swift
- Riot/Modules/Settings/SettingsViewController.m
- Riot/Modules/UserDevices/UsersDevicesViewController.m
- RiotShareExtension/Shared/ShareManager.m
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsDataProvider.swift
- RiotTests/UserSessionsDataProviderTests.swift
- SiriIntents/IntentHandlers/SendMessage/SendMessageIntentHandler.m
Conform to the latest [SDK changes](https://github.com/matrix-org/matrix-ios-sdk/pull/1620) mostly consisting in changes of nullability in `MXCrypto` protocol and `MXLegacyCrypto` typecasing for functionality not supported by Crypto V2 (or handled internally by `MXCryptoMachine`)
> Complete MXCryptoV2 implementation

- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/Test/UI/UserSessionOverviewUITests.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverview.swift
- changelog.d/pr-7001.change
This PR adds the sign out option in the menu in the session overview.
> Improve kebab menu in session overview (PSG-832)

- Riot/Modules/Common/UserIndicators/ViewPresenters/ToastViewPresenter.swift
- changelog.d/pr-7046.bugfix
Prevent `Unable to activate constraint with anchors .. because they have no common ancestor.` crashes. Only link toasts to the top safe area instead of the navigation controller
> Prevent autolayout crashes when showing toast notifications

- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
Even after all the attempted fixes the timeline still doesn't look right at times.
This PR reverts the underlying message string heights calculations to what was there pre iOS16 and add an extra call to `layoutManager` to force correct calculations.
> Fix incorrect timeline item heights

- Config/BuildSettings.swift
- Riot/Assets/en.lproj/Vector.strings
- Riot/Categories/Date+Calculation.swift
- Riot/Generated/Strings.swift
- Riot/Managers/Settings/RiotSettings.swift
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- Riot/Modules/Home/AllChats/ReviewSessionAlertSnoozeController.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Settings/SettingsViewController.h
- Riot/Modules/TabBar/MasterTabBarController.m
- RiotTests/ReviewSessionAlertSnoozeControllerTests.swift
- changelog.d/7056.feature
Closses #7043 
Change current unverified sessions alert using following ACs:
- A dedicated build setting / equivalent exists that allows to toggle the alerts on / off
- The default value of the build setting is on
- The alert reuses the existing UX
- The alert title is “You have unverified sessions”
- The alert body is “Review to ensure your account is safe.”
- The alert contains two options: “Review” and “Later”
- “Review” takes the user to the currently active device manager (when the flag is OFF the current one, when it is ON the new one).
- “Later” snoozes the alert for one week. The delay is stored per device and not synced across all devices in the account.
- The existing "Do not ask again" from iOS is removed. It's only shown on that platform and can't be reverted intuitively (sign …
> Unverified sessions alert

- RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
- changelog.d/7054.bugfix
> Labs: Rich-text editor - Fix text formatting switch losing the current content of the composer

- Riot/Modules/MatrixKit/Models/Account/MXKAccount.h
- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- changelog.d/7066.bugfix
resolves https://github.com/vector-im/element-ios/issues/7066
> Threads: removed "unread_thread_notifications" from sync filters

- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- changelog.d/pr-7068.change
There is no reason to arbitrarily delay another sync, and waiting too long could lead to server clearing any cache it has.
> Remove 10s wait on failed initial sync

- Riot/Modules/Application/LegacyAppDelegate.m
- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollProvider.swift
- changelog.d/7070.bugfix
Closes #7070 
Fix for
> After I logged out and in again I had four bug cases:
> - I could not end the poll (pressing the button did nothing)
> - I could not see changed votes by others
> - I could not see the closed poll after someone else closed it
> - When I changed my vote, the others did not get an event from me.
> Poll not usable after logging out and back in

- Riot/Modules/Room/RoomCoordinator.swift
- Riot/Modules/Room/RoomViewController.m
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/Coordinator/VoiceBroadcastPlaybackCoordinator.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/Coordinator/VoiceBroadcastPlaybackProvider.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/MatrixSDK/VoiceBroadcastPlaybackViewModel.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackScreenState.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Coordinator/VoiceBroadcastRecorderProvider.swift
- Fix crash observed after a clear cache
- Fix multiple voice broadcast issues related to the buffering state:
- display the buffering mode when the user moves the current playback position
- display the buffering mode in case of data shortage (see `stopIfVoiceBroadcastOver` update)
- fix unexpected resume of paused playbacks
- Fix some typos
- Pause the potential playback when the user navigates outside the room
TODO: Pause the playback when the user clicks on the loading wheel (buffering state) to let the user cancel the action
> Fix Voice Broadcast buffering

- Riot/Modules/Room/RoomViewController.m
- changelog.d/7076.bugfix
resolves https://github.com/vector-im/element-ios/issues/7076
> Display number of unread messages above threads button

- Riot/Modules/Settings/Security/SecureBackup/SettingsSecureBackupTableViewSection.swift
- Riot/Modules/Settings/Security/SecureBackup/SettingsSecureBackupViewModel.swift
- Riot/Modules/Settings/Security/SecureBackup/SettingsSecureBackupViewState.swift
- Riot/Modules/Settings/Security/SecurityViewController.m
- changelog.d/pr-7078.change
[SDK change](https://github.com/matrix-org/matrix-ios-sdk/pull/1637)
If we are actively importing keys from backup, display the current import progress as a percentage in the settings, whilst disabling the "restore from backup" button. The import progress replaces the previously unused backup progress.
To keep the progress updating I had to add a simple 1s timer, though I don't think this works very well with the current view model architecture, as it forces the entire section to refresh, leading to visible refresh of the other button rows. In practice only the WIP Crypto V2 will trigger this behaviour, because legacy crypto always returns nil for import progress. This means we can improve the UI behaviour in a future PR
| In progress | Done |
|------------|-------|
|  ![Simulator Screen …
> Import progress for room keys

- Riot/Modules/Room/VoiceMessages/VoiceMessageAudioPlayer.swift
- changelog.d/7074.bugfix
When playing a voice message to the end, there is a crash with the `CALayer` as the waveform's progress gets set to `Double.nan`. This PR will set it to `.zero` in this instance.
Fixes #7074.
> Fix a crash when a voice message finishes.

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- changelog.d/6930.bugfix
- changelog.d/6983.bugfix
- changelog.d/7042.bugfix
- changelog.d/7086.bugfix
- project.yml
Fixes #6930
Fixes #6983 (gif does make it look odd but it has the same behaviour as a standard keyboard & text field)
Fixes #7042 
Fixes #7086 
Library implementation details: https://github.com/matrix-org/matrix-rich-text-editor/pull/316
> Update Rich text editor library version

- Riot/Modules/Room/RoomViewController.xib
- Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
- RiotSwiftUI/Modules/Room/Composer/MockComposerScreenState.swift
- RiotSwiftUI/Modules/Room/Composer/Model/ComposerModels.swift
- RiotSwiftUI/Modules/Room/Composer/Model/ComposerViewState.swift
- RiotSwiftUI/Modules/Room/Composer/Test/Unit/ComposerViewModelTests.swift
- RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
- RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModel.swift
- RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModelProtocol.swift
- changelog.d/7096.change
Also moved the position of underline and strikethrough to match the design and improved the landscape sizing, when the view is compressed.
Also I removed a constraint reference from the XIB, that was probably causing a freezing when minimising in some cases.
> Rich Text Composer: On iPhone in Landscape mode the fullscreen toggle should be hidden

- RiotSwiftUI/Modules/Common/InfoSheet/Coordinator/InfoSheetCoordinator.swift
- changelog.d/pr-7107.change
This PR make easier the code to present a bottom sheet in the device manager using detents.
> Refactor bottom sheet presentation

- Riot/Modules/Room/TimelineCells/SizableCell/SizableBaseRoomCell.swift
- changelog.d/pr-7105.bugfix
Fix scroll issues with VoiceBroadcastPlayback cells, by fixing SizableBaseRoomCell.
> Fix scroll issues with VoiceBroadcast and Poll cells

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Analytics/SentryMonitoringClient.swift
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Authentication/AuthenticationCoordinator.swift
- Riot/Modules/Authentication/Legacy/LegacyAuthenticationCoordinator.swift
- Riot/Modules/LaunchLoading/LaunchLoadingView.swift
- Riot/Modules/LaunchLoading/LaunchLoadingView.xib
- Riot/Modules/LaunchLoading/LaunchLoadingViewController.swift
- changelog.d/pr-7101.change
Related [SDK change](https://github.com/matrix-org/matrix-ios-sdk/pull/1643)
Use changes in the SDK to display sync status on the launch loading screen, if the feature flag is enabled. The design is a simple copy that can be further tweaked, as the flag is currently disabled, and only enabled on Element-R builds.
Unrelatedly, change the fingerprint of Sentry issues to match the message of the issue
| Syncing | Processing |
|---------|------------|
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-11-23 at 09 53 04](https://user-images.githubusercontent.com/3922159/203529087-8dbf1a65-ff2a-4f9a-a26a-47143f942d93.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-11-23 at 09 53 34](https://user-images.githubusercontent.com/3922159/203529109-622e077c-f2b8-4f1a-97f8-4a4eea36779f.png) |
> Display sync progress on the loading screen

- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/VoiceBroadcast/Playback/VoiceBroadcastPlaybackPlainCell.swift
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/VoiceBroadcast/Recorder/VoiceBroadcastRecorderPlainCell.swift
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastAggregator.swift
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastInfo.swift
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastInfoState.swift
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastService.swift
- Riot/Modules/VoiceBroadcast/VoiceBroadcastServiceProvider.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/Coordinator/VoiceBroadcastPlaybackCoordinator.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/Coordinator/VoiceBroadcastPlaybackProvider.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/MatrixSDK/VoiceBroadcastPlaybackViewModel.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/View/VoiceBroadcastPlaybackView.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackModels.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackScreenState.swift
- RiotSwiftUI/target.yml
- RiotSwiftUI/targetUITests.yml
- changelog.d/6721.wip
- changelog.d/7094.bugfix
If a voice broadcast is in live the player starts playing the last chunk.
The duration and the slider are update at each chunks received.
The listener can navigate in the voice broadcast and return live.
> Support voice broadcast live playback

- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollCoordinator.swift
- changelog.d/5329.bugfix
This PR mitigate [this problem](https://github.com/vector-im/element-ios/issues/5329) by making larger the debounce of votes.
Fixes https://github.com/vector-im/element-ios/issues/5329
> Mitigate flickering on polls votes (PSG-816)

- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- RiotNSE/target.yml
- RiotShareExtension/target.yml
- SiriIntents/target.yml
- changelog.d/pr-7133.bugfix
Remove the voice broadcast chunks from the attachments list
> Remove the voice broadcast chunks from the attachments list

- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastInfo.h
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastInfo.m
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastService.swift
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastSettings.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/MatrixSDK/VoiceBroadcastRecorderService.swift
- changelog.d/pr-7136.bugfix
Add the last sequence number in the paused/stopped state event for Voice Broadcast
> [VoiceBroadcast] Add the last sequence number in the paused/stopped state event

- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- changelog.d/pr-7115.change
If we encounter fatal error during initial sync (defined as a list of error domains), do not attempt another sync as this will not resolve the issue
> Do not retry initial sync on fatal errors

- Riot/Modules/Room/DataSources/RoomDataSource.m
During a bug investigation, we found that the FileStore may be corrupted with peeking feature (when previewing a room), but not joining the room after previewing it.
To avoid this on peeking rooms, I excluded to fetch all room members from RoomDataSource when isPeeking is set to YES.
A second part is on MatrixSDK, [here](https://github.com/matrix-org/matrix-ios-sdk/pull/1373).
> Update RoomDataSource init finalization to fix peeking case

- Riot/Managers/UISIAutoReporter/UISIAutoReporter.swift
- changelog.d/pr-7141.change
See related [SDK change](https://github.com/matrix-org/matrix-ios-sdk/pull/1652)
> Add message id for to-device events

- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift
- changelog.d/pr-7142.bugfix
This PR resolves the equivalent of https://github.com/vector-im/element-android/issues/7676 but for iOS.
There is a race in the current QR implementation around device keys.
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
> Download device keys for self prior to verification checks

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- changelog.d/7147.bugfix
> Use cross-platform consistent naming for threads in labs

- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- changelog.d/pr-7140.change
This PR puts a threshold on the count of unread messages visibile in the home screen.
Currently the threshold is **999 messages/invites**.
> Add threshold for unread messages in all the spaces

- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- Riot/Modules/Room/VoiceMessages/VoiceMessageAttachmentCacheManager.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift
Fix a few unrelated issues logged in Sentry, such as passing nil `eventId` or trying to remove file that does not exist
> Fix Sentry errors

- Riot/Modules/MatrixKit/Utils/EventFormatter/HTMLFormatter.swift
- changelog.d/7109.bugfix
> Fix for formatted links appearing in black

- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/View/VoiceBroadcastPlaybackView.swift
- changelog.d/pr-7163.change
> VoiceBroadcast: Link the live icon color to the recording state

- Riot/Assets/de.lproj/Vector.strings
- Riot/Assets/en.lproj/Vector.strings
- Riot/Assets/et.lproj/Vector.strings
- Riot/Assets/fr.lproj/Vector.strings
- Riot/Assets/hu.lproj/Vector.strings
- Riot/Assets/id.lproj/Vector.strings
- Riot/Assets/it.lproj/Vector.strings
- Riot/Assets/nl.lproj/Vector.strings
- Riot/Assets/pt_BR.lproj/Vector.strings
- Riot/Assets/sk.lproj/Vector.strings
- Riot/Assets/sq.lproj/Vector.strings
- Riot/Assets/uk.lproj/Vector.strings
- Riot/Generated/Strings.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/DeviceAvatarView.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/SeparatorLine.swift
- RiotSwiftUI/Modules/UserSessions/Common/View/UserSessionCardView.swift
- RiotSwiftUI/Modules/UserSessions/UserOtherSessions/View/UserOtherSessions.swift
- RiotSwiftUI/Modules/UserSessions/UserOtherSessions/View/UserOtherSessionsHeaderView.swift
- RiotSwiftUI/Modules/UserSessions/UserOtherSessions/View/UserOtherSessionsToolbar.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionDetails/View/UserSessionDetails.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverview.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverviewItem.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionOverview/View/UserSessionOverviewToggleCell.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/SecurityRecommendationCard.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionListItem.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionsListViewAllView.swift
- RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionsOverview.swift
- changelog.d/pr-7180.change
This PR makes small changes on the UI/UX to conform the device manager to the design.
> UI/UX fixes on device manager after design review (PSG-1100)

- Riot/Modules/Threads/ThreadList/ThreadListViewController.swift
- Riot/Modules/Threads/ThreadList/ThreadListViewModel.swift
- changelog.d/6059.feature
> Load the thread list using server-side sorting and pagination

- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- changelog.d/pr-7220.bugfix
This prevents `MXEventTypeBeaconInfo` events from being added into other bubble cell data objects.
Previously, when starting a live location share right after sending a text message, the beacon info event would get appended into the text message's bubble cell data which prevented it from rendering.
Similarly, when restarting the app in such a situation the events would be getting reprocessed _in backwards order_ which meant the final beacon info landed in its own bubble cell data (causing it to render) but a beacon info right before the text message would now get combined with the text message causing it to go hidden.
To reproduce:
* Send a text message
* Start a live location share
* Notice that the map tile doesn't render
> Fix hidden live location timeline tiles after text messages (PSG-1082)

- Riot/Modules/Room/VoiceMessages/VoiceMessageAttachmentCacheManager.swift
- changelog.d/pr-7244.bugfix
voice messages temporary audio files are not deleted when clearing the cache because we are testing the existence of the temporary directory url using absoluteString instead of path.
> Fix clearCache method on VoiceMessageAttachmentCacheManager

- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/VoiceBroadcast/Playback/VoiceBroadcastPlaybackPlainCell.swift
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/VoiceBroadcast/Recorder/VoiceBroadcastRecorderPlainCell.swift
- changelog.d/7179.feature
This PR contains:
- allow to perform actions on a voice broadcast event (MXKRoomDataSource)
- take into account the height of the reactions area in a VoiceBroadcastPlaybackPlainCell (RoomBubbleCellData)
> add support for reactions on VB (#7179)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift
- changelog.d/7235.bugfix
> Send voice message should not be allowed during a voice broadcast recording (#7235)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Categories/Sequence.swift
- Riot/Generated/Strings.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollCoordinator.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollProvider.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Test/Unit/TimelinePollViewModelTests.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollModels.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollScreenState.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollAnswerOptionButton.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollView.swift
- changelog.d/pr-7206.change
This PR adds the logic for showing decryption errors in polls.
https://github.com/matrix-org/matrix-ios-sdk/pull/1673
> Handle decryption errors in polls (PSG-1023)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Categories/MXEvent.swift
- Riot/Generated/Strings.swift
- Riot/Modules/MatrixKit/Models/MXKAppSettings.m
- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/Poll/PollPlainCell.swift
- RiotNSE/NotificationService.swift
- RiotNSE/target.yml
- RiotShareExtension/target.yml
- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollCoordinator.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollProvider.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Test/Unit/TimelinePollViewModelTests.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollModels.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollScreenState.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollAnswerOptionButton.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollView.swift
- SiriIntents/target.yml
- changelog.d/pr-7231.change
This PR renders a poll in the timeline whenever a poll ended event arrives.
Users should be able to reply to this kind of events as well.
https://github.com/matrix-org/matrix-ios-sdk/pull/1674
<image src="https://user-images.githubusercontent.com/19324622/210575244-b8abc16a-e2d7-445e-87b5-4f156933934d.png" width=50% height=50%>
> Render poll ended event in the timeline (PSG-196)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Room/RoomViewController.m
- RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Coordinator/VoiceBroadcastRecorderCoordinator.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Coordinator/VoiceBroadcastRecorderProvider.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/MatrixSDK/VoiceBroadcastRecorderService.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/VoiceBroadcastRecorderServiceProtocol.swift
- changelog.d/pr-7225.change
Handle VoIP buttons when VB is used
> Handle VoIP buttons when VB is used

- .github/workflows/release-alpha.yml
- changelog.d/pr-7256.build
`set-output` is deprecated and the generated warning fails the secret check.
This change [matches the workflow](https://github.com/vector-im/element-x-ios/blob/3d1266ca255585436bc368fc9318f0c2eff8db35/.github/workflows/release-alpha.yml#L12) used on ElementX which compares the PR's repo to make sure it matches the workflow's repo.
> Fix Element Alpha workflow

- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastAggregator.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/MatrixSDK/VoiceBroadcastPlaybackViewModel.swift
- changelog.d/pr-7273.change
For a voice broadcast, the paused/stopped state event contains a last_chunk_sequence indicating what the last chunk sequence number is.
During playback, we should use this last_chunk_sequence to detect whether we should stop playback or enter buffering state.
> Improved detection of voice broadcast completion during playback 

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastService.swift
- changelog.d/7234.change
> Handle a connection issue when we try to start a new voice broadcast

- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/MatrixSDK/VoiceBroadcastPlaybackViewModel.swift
- changelog.d/7252.bugfix
Fixes #7252 
This PR resolves the following issues on the Voice Broadcast audio player:
- the progress bar did not behave as expected after a seek.
- the progress bar did not always reach the end after the playback was finished.
- the displayLink was not paused when stopping or pausing the audio player.
> Fix voicebroadcast playback slider on seek

- RiotSwiftUI/Modules/Room/PollHistory/MockPollHistoryScreenState.swift
- RiotSwiftUI/Modules/Room/PollHistory/PollHistoryModels.swift
- RiotSwiftUI/Modules/Room/PollHistory/PollHistoryViewModel.swift
- RiotSwiftUI/Modules/Room/PollHistory/Service/Mock/MockPollHistoryService.swift
- RiotSwiftUI/Modules/Room/PollHistory/Test/UI/PollHistoryUITests.swift
- RiotSwiftUI/Modules/Room/PollHistory/View/PollHistory.swift
- RiotSwiftUI/Modules/Room/PollHistory/View/PollListItem.swift
- changelog.d/pr-7278.change
This pr adds the UI for rendering ended polls in the "past polls" tab.
**Notes**
- The UI is currently populated with mocked data
- Because of the above model objects are likely going to change
> Past poll history UI (PSG-1027)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/MatrixKit/Models/Room/MXKSendReplyEventStringLocalizer.swift
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- RiotTests/MatrixKitTests/MXKEventFormatterSwiftTests.swift
- changelog.d/pr-7284.change
This PR replaces the "Ended poll" placeholder inside replies to `m.poll.end` events.
The placeholder will be replaced with one of the following in order:
- The `question` of the related `m.poll.start` event
- The localized version of "Ended poll"
https://github.com/matrix-org/matrix-ios-sdk/pull/1685
> Render replies to ended polls (PSG-1131)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Authentication/AuthenticationCoordinator.swift
- Riot/Modules/Authentication/Legacy/LegacyAuthenticationCoordinator.swift
- Riot/Modules/LaunchLoading/LaunchLoadingView.swift
- Riot/Modules/LaunchLoading/LaunchLoadingViewController.swift
- changelog.d/pr-7286.change
Related [SDK change](https://github.com/matrix-org/matrix-ios-sdk/pull/1687)
Display progress for the newly added `migratingData` stage during session startup that is shown on the loading page
|Loading|
|--------|
|  ![Simulator Screen Shot - iPhone 14 Pro - 2023-01-18 at 16 41 06](https://user-images.githubusercontent.com/3922159/213242249-8c82191a-2046-4ee6-a61a-94405b4a19bc.png) |
> Display migration progress during startup

- Riot/Modules/Application/AppCoordinator.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Coordinator/VoiceBroadcastRecorderProvider.swift
- changelog.d/7285.change
Fixes #7285 
While recording a voice broadcast, we now pause it if the session state changes to .homeserverNotReachable instead of just relying on network connectivity because a device might be considered online, but it's always possible that the home server is unreachable.
The easiest way to test this PR is to shutdown the local homeserver while recording a voice broadcast.
> Detect and handle the lost of connectivity with the homeserver while recording a voice broadcast

- Riot/Modules/Room/RoomViewController.m
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/Coordinator/VoiceBroadcastPlaybackCoordinator.swift
- changelog.d/7283.feature
Fixes #7283 
This PR is based on the [msc3912 implementation](https://github.com/matrix-org/matrix-ios-sdk/pull/1688) in matrix-ios-sdk
> Implement MSC3912 to delete server side all the data of the deleted voice broadcast

- Riot/Modules/Room/Settings/RoomSettingsViewController.m
- changelog.d/pr-7275.change
As described in [this issue](https://github.com/tchapgouv/tchap-ios/issues/593), after the redesign of the room settings screen, there is now 2 "Leave" buttons on these screens : 1 at the first level, and 1 on the "Settings" one.
So, the goal of this PR is to remove the old one on "Settings".
**1st level screen :**
**Settings screen before / After :**
> Remove "Leave" button on Room details screen

- Riot/Utils/EventFormatter.m
- changelog.d/pr-7300.bugfix
This PR is a hotfix fixing a deadlock happening when we try to update the summary of a room that has a voice broadcast.
To reproduce this issue in the current 1.9.16, simply clear the cache and a deadlock should occur if there is a voice broadcast in a room.
> Fix a deadlock when updating the summary of a room that has a voice broadcast

- Riot/Modules/Analytics/DecryptionFailure.swift
- Riot/Modules/Analytics/DecryptionFailureTracker.m
- Riot/Modules/Analytics/Helpers/MXCallHangupReason+Analytics.swift
- changelog.d/pr-7304.change
We have been using `UnknownError` analytics event to track some types of E2EE errors. This error type is however used for other unrelated events as well (notably VOIP), which makes it impossible to distinguish the area of concern.
To solve this we will never use the generic `UnknownError` to track E2EE errors and instead only rely on the existing `OlmUnspecifiedError` (even if the "Olm" in the name is misleading). Further details about the error are always present in the `context` property
> Ensure E2EE never tracks UnknownError

- RiotSwiftUI/Modules/Common/Avatar/View/AvatarImage.swift
- RiotSwiftUI/Modules/Common/Avatar/View/SpaceAvatarImage.swift
- RiotSwiftUI/Modules/Common/Avatar/ViewModel/AvatarViewModel.swift
- changelog.d/7305.bugfix
Fixes #7305. The view model is now injected at a top level and shared across multiple avatars so no longer works with the state being held within the model. As this is a lightweight component it seems reasonable to me to move it to an `@State` variable within the view itself.
Note: Also fixes the same bug in user suggestions and possibly elsewhere in SwiftUI.
| - | - |
| ![Simulator Screen Shot - iPhone 14 - 2023-01-26 at 12 02 13](https://user-images.githubusercontent.com/6060466/214830583-a40d1c04-e485-4781-9d56-9e0c94458ec3.png) | ![Simulator Screen Shot - iPhone 14 - 2023-01-26 at 11 56 40](https://user-images.githubusercontent.com/6060466/214830596-2edc9af2-b432-4256-95ab-4742ebb71b48.png) |
> Fix Space Switcher avatars

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- RiotSwiftUI/Modules/Room/PollHistory/Coordinator/PollHistoryCoordinator.swift
- RiotSwiftUI/Modules/Room/PollHistory/MockPollHistoryScreenState.swift
- RiotSwiftUI/Modules/Room/PollHistory/PollHistoryModels.swift
- RiotSwiftUI/Modules/Room/PollHistory/PollHistoryViewModel.swift
- RiotSwiftUI/Modules/Room/PollHistory/Service/MatrixSDK/PollHistoryService.swift
- RiotSwiftUI/Modules/Room/PollHistory/Service/Mock/MockPollHistoryService.swift
- RiotSwiftUI/Modules/Room/PollHistory/Service/PollHistoryServiceProtocol.swift
- RiotSwiftUI/Modules/Room/PollHistory/Test/UI/PollHistoryUITests.swift
- RiotSwiftUI/Modules/Room/PollHistory/Test/Unit/PollHistoryViewModelTests.swift
- RiotSwiftUI/Modules/Room/PollHistory/View/PollHistory.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollAnswerOptionButton.swift
- changelog.d/pr-7303.change
This PR improves the poll history by adding the following features:
- Add the possibility to manually fetch more polls backwards
- Handle live poll updates
- Show errors when the pagination fails
> Poll history: load more polls (PSG-1093)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Categories/MatrixSDKCrypto+LocalizedError.swift
- Riot/Generated/Strings.swift
- Riot/Managers/EncryptionKeyManager/EncryptionKeyManager.swift
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/pr-7310.change
Use the existing `EncryptionKeyManager` to generate new Crypto SDK store key used to encrypt the [sqlite store](https://github.com/matrix-org/matrix-ios-sdk/pull/1699).
Additionally change some of the copy for the Labs option to enable crypto v2
> Generate Crypto SDK store key

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastAggregator.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/MatrixSDK/VoiceBroadcastPlaybackViewModel.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/View/VoiceBroadcastPlaybackDecryptionErrorView.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/View/VoiceBroadcastPlaybackView.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackModels.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackScreenState.swift
- changelog.d/7189.change
Fixes #7189 
If a decryption error occurs during a voice broadcast:
- don't display an entry for the encrypted chunk in the room
- pause the voice broadcast playback and show an error in the cell until there is a decryption error
> Inform the user about decryption errors during a voice broadcast

- Config/AppConfiguration.swift
- Config/CommonConfiguration.swift
- Config/CryptoSDKConfiguration.swift
- Riot/Categories/MXRoom+Riot.m
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/MatrixKit/Controllers/MXKNotificationSettingsViewController.m
- Riot/Modules/MatrixKit/Views/PushRule/MXKPushRuleTableViewCell.m
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/pr-7323.change
We don't really have any mechanism to reset specific user defaults when the user logs out (e.g. all labs flags remain toggled after another user login). That may not be an issue for most settings, but logging out needs to reset crypto SDK setting. To make this a bit more consolidated add `CryptoSDKConfiguration` and disable from legacy app delegate.
> Reset Crypto SDK labs on logout

- Config/AppConfiguration.swift
- Config/CommonConfiguration.swift
- Config/CryptoSDKConfiguration.swift
Fix how crypto v2 config is setup, given that `AppConfiguration` does not belong to NSE target as is required by Crypto V2
> Fix crypto v2 config

- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/MatrixSDK/VoiceBroadcastPlaybackViewModel.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/View/VoiceBroadcastPlaybackView.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackModels.swift
- RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackScreenState.swift
- changelog.d/7311.change
This PR fixes #7311 by pausing the voice broadcast playback if an error occurs. Also, the error is only displayed when playback stops.
> Improve error handling during a voice broadcast playback

- RiotNSE/NotificationService.swift
- changelog.d/pr-7332.change
CryptoSDK labs flag can be enabled after the notification service has been setup so we need to make sure that background sync service (which internally creates crypto module) is refreshed accordingly
> Refresh notification service on crypto change

- Config/CommonConfiguration.swift
- Config/CryptoSDKConfiguration.swift
- Riot/Categories/MatrixSDKCrypto+LocalizedError.swift
- Riot/Managers/Settings/RiotSettings.swift
- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- Riot/Modules/Settings/SettingsViewController.m
- RiotNSE/NotificationService.swift
- changelog.d/pr-7333.change
Remove all `DEBUG` compiler flags to enable CryptoSDK for production. Additionally ensure that `enableStartupProgress` is enabled only when `cryptoSDK` is enabled (at least for now)
Corresponding [SDK change](https://github.com/matrix-org/matrix-ios-sdk/pull/1708)
> Enable Crypto SDK for production

- Config/CommonConfiguration.swift
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Settings/SettingsViewController.m
Add temporary and local-only analytics event that gets trigged when users select the Crypto SDK Labs option
> Track crypto SDK being enabled

- Config/AppConfiguration.swift
- Riot/Categories/Publisher+Riot.swift
- Riot/Managers/PushRulesUpdater/PushRulesUpdater.swift
- Riot/Modules/Application/AppCoordinator.swift
- RiotSwiftUI/Modules/Settings/Notifications/Model/MatrixSDK/MXNotificationPushRule.swift
- RiotSwiftUI/Modules/Settings/Notifications/Model/Mock/MockNotificationPushRule.swift
- RiotSwiftUI/Modules/Settings/Notifications/Model/NotificationPushRuleType.swift
- RiotSwiftUI/Modules/Settings/Notifications/Service/MatrixSDK/MXNotificationSettingsService.swift
- RiotSwiftUI/Modules/Settings/Notifications/Service/Mock/MockNotificationSettingsService.swift
- RiotSwiftUI/Modules/Settings/Notifications/ViewModel/NotificationSettingsViewModel.swift
- RiotTests/PushRulesUpdaterTests.swift
- changelog.d/pr-7335.change
This PR adds logic to update poll push rules when don't match the ones of normal messages (see the table below).
The check is triggered the first time the matrix session is ready and when the app enters the foreground.
> Automatic poll rules sync (PSG-1135)

- RiotSwiftUI/Modules/Room/PollHistory/View/SegmentedPicker.swift
- changelog.d/pr-7341.change
This PR slightly changes the UI of the `SegmentedPicker` component currently being used just in the **poll history**.
|---|---|
|  ![bef](https://user-images.githubusercontent.com/19324622/216962004-6def516a-b966-4b17-a190-b58660a15536.png) |  ![aft](https://user-images.githubusercontent.com/19324622/216962044-b36c5258-2060-48ca-991b-22416627a986.png)|
> Improve SegmentedPicker UI

- Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift
- changelog.d/7326.bugfix
> Fix an issue where a voice message disappears after being sent

- Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
- Riot/Modules/MatrixKit/Models/RoomList/MXKRecentCellData.m
- Riot/Modules/MatrixKit/Models/RoomList/MXKRecentCellDataStoring.h
- changelog.d/7530.bugfix
fix green dot appearing also for silent rooms
> "Mark as unread" dot appears on rooms that are actually unread, not marked as such

- Riot/Categories/MXBugReportRestClient+Riot.swift
- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinator.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- RiotSwiftUI/Modules/Room/NotificationSettings/Service/MatrixSDK/MXRoomNotificationSettingsService.swift
Resolves https://github.com/matrix-org/element-ios-rageshakes/issues/23067
Fix a bunch of unrelated crashes as reported by Sentry and Xcode. Most of them are caused by accessing obj-c properties from Swift when exposed as implicitely unwrapped optional, which is one of the greatest evils of the objc-Swift interoperability, far more unstable than just using pure objective-c.
> Fix some crashes

- Riot/Modules/Room/VoiceMessages/VoiceMessageAudioPlayer.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessageAudioRecorder.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessageMediaServiceProvider.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessagePlaybackController.swift
- changelog.d/7217.bugfix
- changelog.d/7325.bugfix
Fix #7325: prevent setting the audio session to inactive during recording
Fix #7217: ensure that an audio player has its content loaded when it reaches the end to allow seek and replay.
> Fix some voice message issues (#7325, #7217)

- Riot/Modules/MatrixKit/Models/MXKAppSettings.m
- Riot/Modules/MatrixKit/Models/Room/MXKSendReplyEventStringLocalizer.swift
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- Riot/Modules/Room/TimelineCells/Styles/Bubble/Cells/Poll/PollBaseBubbleCell.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollProvider.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollMessageView.swift
- changelog.d/pr-7353.change
This PR:
- Adds a fallback text for m.poll.end events. These fallbacks are useful for receivers when the associated m.poll.start event is unavailable. (see screenshots below)
- Fixes a bug that prevented to see the last "poll ended" event in the room list
https://github.com/matrix-org/matrix-ios-sdk/pull/1713
| Plain | Bubble |
|---|---|
|![normal](https://user-images.githubusercontent.com/19324622/217592574-b5e183e3-7a45-437d-b3da-8c065f349009.png)| ![bubble](https://user-images.githubusercontent.com/19324622/217592817-8322a1b8-4274-442e-9785-8cf76505921b.png)
|
> Fallback for poll ended event (PSG-1156)

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
- RiotSwiftUI/Modules/Room/Composer/Model/ComposerModels.swift
- RiotSwiftUI/Modules/Room/Composer/Test/UI/ComposerUITests.swift
- RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
- changelog.d/pr-7365.change
- project.yml
Updates the composer version to 1.1.0
See dedicated [changelog](https://github.com/matrix-org/matrix-rich-text-editor/blob/main/CHANGELOG.md) for update details.
Also changes the indent/unindent buttons to be hidden outside of lists
> Update composer library version to 1.1.0

- Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
- changelog.d/pr-7369.change
Legacy crypto does some kind of patchwork and resets device keys on session reload. In practice this means that we reset all tracked users, and when migrating to CryptoSDK we do not have any of the tracked users information.
To solve this we simply avoid resetting device keys when the `cryptoSDK` feature flag has just been enabled (note that the next time we are resetting session, crypto will no longer be the `MXLegacyCrypto` type)
> Do not reset device keys if migrating to CryptoSDK

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- changelog.d/pr-7365.change
- changelog.d/pr-7370.change
- project.yml
Contains a hotfix for a selection/cursor issue within the composer library, see https://github.com/matrix-org/matrix-rich-text-editor/pull/582
Replaced changelog file from previous update: #7365
> Update composer library version to 1.1.1

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Rendezvous/RendezvousService.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/QRLoginServiceProtocol.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Failure/AuthenticationQRLoginFailureViewModel.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Failure/MockAuthenticationQRLoginFailureScreenState.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Failure/Test/UI/AuthenticationQRLoginFailureUITests.swift
- RiotTests/RendezvousServiceTests.swift
- changelog.d/pr-7372.change
- Support for `org.matrix.msc3903.rendezvous.v2.curve25519-aes-sha256` whilst maintaining compatibility with `org.matrix.msc3903.rendezvous.v1.curve25519-aes-sha256`
- Improves the feedback in case of valid code but of unsupported algorithm or transport.
- Added some test cases.
- Fixed scenario where invalid QR would have led to app crashing.
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
> Support for v2 of MSC3903

- Riot/Modules/LocationSharing/LocationManager.swift
- RiotSwiftUI/Modules/LocationSharing/LiveLocationSharingViewer/LiveLocationSharingViewerModels.swift
- RiotSwiftUI/Modules/LocationSharing/LiveLocationSharingViewer/LiveLocationSharingViewerViewModel.swift
- RiotSwiftUI/Modules/LocationSharing/LiveLocationSharingViewer/Service/LiveLocationSharingViewerServiceProtocol.swift
- RiotSwiftUI/Modules/LocationSharing/LiveLocationSharingViewer/Service/MatrixSDK/LiveLocationSharingViewerService.swift
- RiotSwiftUI/Modules/LocationSharing/LiveLocationSharingViewer/Service/Mock/MockLiveLocationSharingViewerService.swift
- RiotSwiftUI/Modules/LocationSharing/LiveLocationSharingViewer/Test/Unit/LiveLocationSharingViewerViewModelTests.swift
- RiotSwiftUI/Modules/LocationSharing/LiveLocationSharingViewer/View/LiveLocationSharingViewer.swift
- RiotSwiftUI/Modules/LocationSharing/MapError/MapViewErrorAlertInfoBuilder.swift
- RiotSwiftUI/Modules/LocationSharing/MapView/View/LocationSharingMapView.swift
- RiotSwiftUI/Modules/LocationSharing/MapView/View/UserLocationAnnotationView.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/Coordinator/StaticLocationViewingCoordinator.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/MockStaticLocationViewingScreenState.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/Service/MatrixSDK/StaticLocationSharingViewerService.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/Service/Mock/MockStaticLocationSharingViewerService.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/Service/StaticLocationSharingViewerServiceProtocol.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/StaticLocationViewingModels.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/StaticLocationViewingViewModel.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/Test/Unit/StaticLocationViewingViewModelTests.swift
- RiotSwiftUI/Modules/LocationSharing/StaticLocationSharingViewer/View/StaticLocationView.swift
- changelog.d/pr-7361.change
The expanded map view contains a control to display / center on the user’s own location.
The button is hidden when the user is currently sharing their own live location in the same room.
The button is always shown for static location shares, even if it was from the current user.
> Show own location in map views

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/KeyVerification/Common/ScanConfirmation/KeyVerificationScanConfirmationViewController.storyboard
- Riot/Modules/KeyVerification/Common/ScanConfirmation/KeyVerificationScanConfirmationViewController.swift
- Riot/Modules/KeyVerification/Common/Verified/KeyVerificationVerifiedViewController.storyboard
- Riot/Modules/KeyVerification/Common/Verified/KeyVerificationVerifiedViewController.swift
- Riot/Modules/KeyVerification/Common/Verify/SAS/KeyVerificationVerifyBySASViewController.storyboard
- Riot/Modules/KeyVerification/Common/Verify/SAS/KeyVerificationVerifyBySASViewController.swift
- Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.storyboard
- Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.swift
- Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.storyboard
- Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.swift
- Riot/Modules/QRCode/Reader/QRCodeReaderView.swift
- Riot/Modules/QRCode/Reader/QRCodeReaderViewController.swift
- changelog.d/3115.change
Fixes #3115 
When we try to verify a session, sometimes the device doesn't have a QR code to display. In this case, we want to allow the user to directly scan the QR code displayed on another device without breaking the verification flow.
Here is what we currently see in this case:
Here is the implemented design:
> Automatically starts scanning the QR code if we have not received a QR code

- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- changelog.d/pr-7402.bugfix
This PR improves the rendering of the `m.poll.end` message adding always the sender information.
|---|---|
| ![b](https://user-images.githubusercontent.com/19324622/222496949-df429128-b06c-4200-a6ae-816366f14ec6.png)| ![a](https://user-images.githubusercontent.com/19324622/222497017-d308dde7-8b14-4626-a440-bc3e68f307f0.png)|
> Fix poll ended event rendering (PSG-1177)

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Room/RoomInfo/RoomInfoCoordinator.swift
- Riot/Modules/Room/RoomInfo/RoomInfoCoordinatorParameters.swift
- Riot/Modules/Room/RoomViewController.h
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/RoomViewController.swift
- Riot/Modules/StartChat/StartChatViewController.m
- Riot/Modules/StartChat/StartChatViewController.xib
- RiotSwiftUI/Modules/Room/WaitingForMembers/View/RoomWaitingForMembers.swift
- changelog.d/6612.change
This PR fixes #6612 
Here is a summary of the changes:
- Don’t allow to invite more than one contact by email
- The DM will be created by enabling the encryption when the HS promotes the encryption
- The chat composer is disabled until a matrix account is created by using the invited email
This PR is related to [matrix-ios-sdk PR #1727](https://github.com/matrix-org/matrix-ios-sdk/pull/1727)
> Direct Message: manage encrypted DM in case of invite by email

- Riot/Modules/Home/AllChats/AllChatsCoordinator.swift
- changelog.d/pr-7427.bugfix
This PR improves the tappability area (in red) of the avatar icon in the room list.
It also improves bit the fallback case when the avatar may not be available.
Fixes https://github.com/vector-im/customer-retainer/issues/13
| **Before** | **After** |
|---|---|
| ![b2](https://user-images.githubusercontent.com/19324622/225049953-ad03e1f4-e4fe-4e10-a111-5e222a2b20b7.png)| ![b3](https://user-images.githubusercontent.com/19324622/225050053-503eb96a-1817-483f-b77b-5263b64b9518.png)|
> Improve avatar tappability

- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- changelog.d/7406.bugfix
Fixes https://github.com/vector-im/element-ios/issues/7406
By using value type checker methods.
With this fix, attachments with a wrong `size` format are still displayed in the timeline. Only the size is omitted like on the last item on this screenshot:
> Manage bad m.file attachment format

- Riot/Experiments/CryptoSDKFeature.swift
- Riot/Modules/Analytics/SentryMonitoringClient.swift
- changelog.d/pr-7434.change
Depends on https://github.com/matrix-org/matrix-ios-sdk/pull/1742
Also, add crypto module identification to Sentry issues
> Increase local rust crypto rollout to 20% of all users

- Riot/Modules/Pills/PillProvider.swift
This PR fixes a crash that can occur if we don't have a display name to put in the user pill.
> Fix: prevent a crash if we don’t have a display name for the user mentionned by the pill

- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleComponent.m
- Riot/Modules/MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.m
- Riot/Modules/Room/TimelineCells/Encryption/EventEncryptionDecoration.h
- Riot/Modules/Room/TimelineCells/Encryption/RoomEncryptedDataBubbleCell.m
- changelog.d/pr-7440.change
Related SDK change https://github.com/matrix-org/matrix-ios-sdk/pull/1743
Resolves https://github.com/vector-im/element-ios/issues/7441
Move some of the event encryption decoration logic down into the SDK and simplify the model to only mention colors (red, grey, none) rather than reasons (unsafe key, untrusted ...)
> Simplify event encryption decoration

- Riot/Assets/en.lproj/Vector.strings
- Riot/Experiments/CryptoSDKFeature.swift
- Riot/Generated/Strings.swift
- Riot/Managers/Settings/RiotSettings.swift
- Riot/Modules/Home/AllChats/AllChatsViewController.swift
- changelog.d/pr-7454.change
Related SDK change https://github.com/matrix-org/matrix-ios-sdk/pull/1751
Resolves https://github.com/vector-im/crypto-internal/issues/58
Display customized modal alert if upgrading from legacy to rust crypto and needing to verify the account.
> Display upgrade verification prompt

- Riot/Modules/Pills/PillAttachmentView.swift
- Riot/Modules/Pills/PillAttachmentViewProvider.swift
- Riot/Modules/Pills/PillTextAttachment.swift
- Riot/Modules/Pills/PillTextAttachmentData.swift
- changelog.d/7413.bugfix
> Fix: truncate pills if they are too long

- Riot/Modules/Rendezvous/RendezvousService.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Models/QRLoginCode.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift
- RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/Mock/MockQRLoginService.swift
This PR adds support for v2 of [MSC3906](https://github.com/matrix-org/matrix-spec-proposals/pull/3906) which is used for Sign in with QR.
Both v1 and v2 are supported so compatibility is maintained.
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
> Support for MSC3906 v2

- Riot/Modules/Room/MXKRoomViewController.m
- Riot/Modules/Room/RoomViewController.m
- changelog.d/7420.bugfix
This PR fixes #7420 
The current implementation only updates the read marker if we are able to display the read marker view and we have identified some cases where the read marker is not updated because its view cannot be displayed:
- when it is placed on a reaction (or potentially any event that relates to another one)
- when it is placed on a redaction
- when it is placed on an event displayed in a collapsed cell (e.g. a room member update)
Also, relatesTo events can be problematic as they can cause the user to jump backwards in the timeline, even if the current read marker timestamp is more recent than the related event.
To fix these issues:
- When checking the visibility of the "jump to unread" banner, we now ask for the read marker to be updated when we are supposed to render it.
- …
> Fix: Update the read marker position even if it is not displayed

- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleComponent.m
- Riot/Modules/MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.m
- changelog.d/pr-7471.bugfix
There is a bug in objective-c event trust decoration, where the absence of event's `decryptionDecoration`  (i.e. it is `nil`) gets evaluated to `0` in a switch statement, which happens to be a red shield. The `decryptionDecoration` gets set pretty quickly after local echo but it does display a brief moment where a red shield is shown, even though it shoudn't be.
To solve this add explicit `nill handling to objective-c, and also [swap the order](https://github.com/matrix-org/matrix-ios-sdk/pull/1756/files#diff-ceca7b4860bf6983c2b04390eba12a4044161831c0d68b82d1de35f6df275ac1R20-R23) of decoration colors, so that 0 is none rather than red
> No event decoration if no decryption result

- Riot/Modules/MatrixKit/Utils/MXKTools.m
- Riot/Modules/Pills/PillType.swift
- changelog.d/pr-7482.bugfix
Currently, if a custom permalinkBaseUrl is set, matrix.to permalinks are not rendered as pills.
This fix is intended to support both types of permalinks.
Current behaviour:
New behaviour:
> Fix: If a clientPermalinkBaseUrl is defined, we still have to support matrix.to links

- Riot/Experiments/CryptoSDKFeature.swift
- RiotTests/SessionCreatorTests.swift
- changelog.d/pr-7485.change
In this final stage of Rust Crypto rollout enable the feature to all users. The feature flags mechanism and other now-unnecessary code will be removed in future PRs
Note that this change will be released as "hotfix" to only contain the target percentage change and no other features
> Enable Rust Crypto for all users

- Riot/Modules/Room/VoiceMessages/VoiceMessageAttachmentCacheManager.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessageAudioConverter.swift
- changelog.d/7451.bugfix
Essentially any audio message that was not a voice message or an mp4, could not be played in the timeline.
Now we can support multiple formats (the most common ones like .mp4, .aac, .mp3, .wav)
> Fix for unsupported audio messages

- RiotSwiftUI/Modules/Room/UserSuggestion/View/UserSuggestionList.swift
- changelog.d/7492.bugfix
Fixes #7492 
| Device\OS | iOS 15.5  | iOS 16.2 |
| ------------- | ------------- | ------------- |
| iPhone 13/14 Pro | ![iPhone 13 Pro iOS 15 5](https://user-images.githubusercontent.com/80891108/232488068-d6dd2b8c-cae6-4639-97ef-a6f5919e6e38.png) | ![iPhone 14 Pro iOS 16 2](https://user-images.githubusercontent.com/80891108/232488495-74e71c63-1959-40db-9f62-271f91116538.png) |
| iPhone SE | ![iPhone SE iOS 15 5](https://user-images.githubusercontent.com/80891108/232488635-a8513bd3-6f67-422c-9bdc-493f11f67f9f.png) | ![iPhone SE iOS 16 2](https://user-images.githubusercontent.com/80891108/232488727-96162cb1-c561-4db4-95a5-2d63f6dcfba6.png) |
| iPad Pro 12.9 | ![iPad Pro iOS 15 5](https://user-images.githubusercontent.com/80891108/232488788-a1b59625-6572-4575-8617-01d2a86dacd1.png) | …
> Fix user suggestion list item height on iOS 16+

- Riot/Utils/EventFormatter.m
- changelog.d/pr-7501.bugfix
If the event formatter fails to create an attributed string for an event, a default attributed string is generated but it does not have a colour attribute, making it difficult to see in dark mode.
Current behaviour:
With this fix:
> Fix: add missing foreground color attribute

- Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.h
- Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
- Riot/Modules/Room/TimelineCells/Styles/Bubble/Cells/TextMessage/Outgoing/TextMessageOutgoingWithoutSenderInfoBubbleCell.swift
- changelog.d/pr-7512.bugfix
This PR fixes some issues with the calculation of the frame for a bubble component.
- the height of the text is not calculated with the correct width, resulting in an incorrect calculated Y position when using the bubble timeline style.
- the component's position may be calculated with an extra positioning space (to make room for the timestamp above the component), even for cells of kind `TextMessageOutgoingWithoutSenderInfoBubbleCell`
These issues result in the sent confirmation icon being misplaced and make it difficult to run to detect the sent confirmation icon in UITests.
**Current implementation:**
<kbd><img width="388" alt="1st message" src="https://user-images.githubusercontent.com/4334885/233298324-9d9599f4-bb3c-4a17-9bc9-0481d4a600bf.png"></kbd>
after a restart of the app, the …
> Fix: Calculation of the frame for a component of a bubble

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- changelog.d/7517.change
This PR fixes #7517 
Old behaviour:
New behaviour:
> Fix: Remove the matrix id from the notice display name changed event

- Riot/Modules/SetPinCode/EnterPinCode/EnterPinCodeViewController.storyboard
- Riot/Modules/SetPinCode/SetPinCoordinatorBridgePresenter.swift
- changelog.d/pr-7522.bugfix
This PR fixes a couple of accessibility issue on the "enter PIN" screen:
1. The VoiceOver doesn't read anymore the underlying content while the PIN screen is on top
2. The VoiceOver doesn't read anymore a layout non interactive button in the screen
**Affected screen**
> Fix accessibility behavior on "enter PIN" screen

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- RiotSwiftUI/Modules/Room/PollHistory/PollHistoryDetail/MockPollHistoryDetailScreenState.swift
- RiotSwiftUI/Modules/Room/PollHistory/Service/MatrixSDK/PollHistoryService.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Coordinator/TimelinePollCoordinator.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/Test/Unit/TimelinePollViewModelTests.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollModels.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollScreenState.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollViewModel.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/TimelinePollViewModelProtocol.swift
- RiotSwiftUI/Modules/Room/TimelinePoll/View/TimelinePollView.swift
- changelog.d/7497.bugfix
This PR fix #7497 
_This PR is related to this one (matrix-ios-sdk): [Fix: Refreshing the poll when receiving pollEnd can break the chronological order in the store. #1776](https://github.com/matrix-org/matrix-ios-sdk/pull/1776)_
It displays a temporary poll while fetching the `pollStartEvent`:
If we failed to get the start event (or to decrypt it), we'll fallback on the normal rendering:
Also, the `PollAggregator` delegate was not defined early enough in `TimelinePollCoordinator` (and so the delegate's methods were not called).
I had to make public the `PollAggregator.reloadPollData()` method because:
- once the PollAggregator is instantiated, it immediately loads the poll data.
- and once the poll is loaded, the delegate is called (but not yet defined).
- the delegate method `func …
> Fix: allow to render a TimelinePoll even if the poll is loading

- Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
- changelog.d/7523.bugfix
This PR fixes #7523 
When the `MXKRoomDataSource` was reloaded, the tableView was refreshed immediately after the reset, showing a blank screen.
With this fix, the tableView is refreshed at the end of the `reload` method, which prevents a blank screen from appearing.
The `MXKRoomDataSource resetNotifying` method no longer seems necessary with this fix, as the original reset method was only called from:
- `MXKRoomDataSource::reload`
- `MXKRoomDataSource::destroy`: in this case its delegate is already nil
> Fix a flickering issue when the timeline datasource is reloaded.

- Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
- Riot/Modules/Room/RoomViewController.m
- changelog.d/7526.bugfix
This PR fixes #7526 
Current behaviour:
New behaviour:
> Fix the position of the marker highlighting an event.

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h
- Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m
- Riot/Modules/Room/MXKRoomViewController.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
- RiotSwiftUI/Modules/Room/Composer/LinkAction/MockComposerLinkActionScreenState.swift
- RiotSwiftUI/Modules/Room/Composer/LinkAction/Test/Unit/ComposerLinkActionViewModelTests.swift
- RiotSwiftUI/Modules/Room/Composer/LinkAction/ViewModel/ComposerLinkActionViewModel.swift
- RiotSwiftUI/Modules/Room/Composer/Test/Unit/ComposerViewModelTests.swift
- changelog.d/7535.bugfix
- project.yml
Fixes #7535 
Also updates the RTE library version to 2.1.0 and apply API changes. See [CHANGELOG](https://github.com/matrix-org/matrix-rich-text-editor/blob/2.1.0/CHANGELOG.md) for details.
https://user-images.githubusercontent.com/80891108/235922934-bf71fd18-3b02-48c1-a921-13639514b952.mp4
> Fix partial text messages not being saved for each room with RTE enabled

- Riot/Modules/Secrets/Recover/SecretsRecoveryCoordinator.swift
- Riot/Modules/Secrets/Reset/SecretsResetCoordinator.swift
- Riot/Modules/Secrets/Reset/SecretsResetViewAction.swift
- Riot/Modules/Secrets/Reset/SecretsResetViewController.swift
- Riot/Modules/Secrets/Reset/SecretsResetViewModel.swift
- Riot/Modules/Secrets/Reset/SecretsResetViewState.swift
- Riot/Modules/SecureBackup/Setup/SecureBackupSetupCoordinator.swift
- changelog.d/pr-7404.bugfix
This PR fixes the following issues when resetting secrets:
- SecureBackupSetupIntroViewController is pushed twice into the navigation router (once as a view controller, once via its navigation controller)
- SecureBackupSetupCoordinator is never removed from child coordinators
> Secrets recovery: Fix an issue where the Secrets Reset screen would open twice.

- Riot/Modules/Application/LegacyAppDelegate.m
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/pr-7493.bugfix
When using a device set to use language A but running Element with language B, this PR makes sure to use the voice from language B for VoiceOver.
Fixes https://github.com/vector-im/customer-retainer/issues/39
Caveats:
- Notifications shown whilst in-app will always be in the system language as they are presented outside of the app.
- The share extension doesn't have a `UIApplication` to set the language on and from what I can tell, doesn't respect the `accessibilityLanguage` property set on the root view controller for setting the voice.
> Use the app's language for accessibility.

- Riot/Modules/Room/RoomViewController.m
Removes unnecessary trying to delete the trigger text of a mention with RTE enabled.
This might not be worth a changelog, as it doesn't change anything (as RTE doesn't allow editing the attributedText) but it will avoid a MXLog.failure(...) in debug mode.
> Disable removing mention/command text trigger with RTE enabled

- Riot/Modules/Threads/ThreadList/Views/Cell/ThreadTableViewCell.swift
- Riot/Modules/Threads/ThreadList/Views/Cell/ThreadTableViewCell.xib
- changelog.d/7322.bugfix
Fixes #7322 
Replace the UILabel by a MXKMessageTextView to get the same Pill capacities as the Timeline.
> Fix mention pills display in thread list

- Riot/Categories/NSAttributedString+Theme.swift
- Riot/Managers/Theme/ThemeService.swift
- Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
- Riot/Utils/EventFormatter.m
- Riot/Utils/ThemeColorResolver.swift
- changelog.d/pr-7545.bugfix
This PR fixes a problem where the font color of `lastEventDescription` is not updated when the theme changes.
In the `RecentTableViewCell`, the `lastEventDescription` label has a foreground color but most of the time it displays the `roomCellData.lastEventAttributedTextMessage` which is an attributed string containing its own set of text color attributes.
By default, this attributed string uses only the `secondaryTextColor`, but in some scenarios (such as a live broadcast), the text may have a different color.
This attributed string is calculated by the `EventFormatter` when updating the room summary. The solution chosen for this PR was add two custom attributes for this attributed string:
- `themeIdentifierAttributeName`: to store which theme was active when the attributed string was …
> Fix: text color of the last event description was incorrect.

- Riot/Modules/Room/TimelineCells/RoomCreationIntro/RoomCreationIntroCell.swift
- changelog.d/7554.bugfix
RoomCreationIntroCell now conforms to Themable protocol, making this cell type able to be updated when the system changes from light to dark theme and vice-versa. The update method was already implemented but just not called because the runtime did not match the Themable protocol on the TableViewCell object.
This fixes issue #7554 , as shown in video below:
Signed-off-by: Milton Moura <miltonmoura@gmail.com>
> RoomCreationIntroCell now conforms to Themable protocol

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/MatrixKit/Views/RoomTitle/MXKRoomTitleView.m
- Riot/Modules/Room/ParticipantsInviteModal/ContactsPicker/ContactsPickerCoordinator.swift
- Riot/Modules/Room/ParticipantsInviteModal/ContactsPicker/ContactsPickerViewModel.swift
- Riot/Modules/Room/ParticipantsInviteModal/ContactsPicker/ContactsPickerViewModelProtocol.swift
- Riot/Modules/Room/RoomCoordinator.swift
- Riot/Modules/Room/RoomViewController.m
- changelog.d/7558.change
This PR applies the change requested by #7558
> Prompt the user when the invited MatrixId is not recognized

- Riot/Categories/MXRoom+Riot.m
- RiotNSE/NotificationService.swift
- RiotSwiftUI/Modules/Room/NotificationSettings/Service/MatrixSDK/MXRoomNotificationSettingsService.swift
- RiotSwiftUI/Modules/Settings/Notifications/Model/MatrixSDK/MXNotificationPushRule.swift
- changelog.d/7576.change
This PR implements the change requested by #7576 by adding support for [MSC3987](https://github.com/matrix-org/matrix-spec-proposals/pull/3987) which deprecates the dont_notify action for a push_rule.
> Implement MSC3987: Push actions clean-up

- Riot/Modules/Home/AllChats/AllChatsCoordinator.swift
- changelog.d/pr-7587.bugfix
This PR fixes an issue where the user's avatar can disappear from the top left menu of `AllChatsViewController` because the width of the AvatarView has become 0.
> Fix: Prevents UserAvatarView from disappearing due to incorrect width.

- Config/BuildSettings.swift
The posthog ingress is no longer posthog.hss.element.io, and, although it is running in parallel it will be removed in the future.
> Update posthog URL to posthog.element.io

- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
- changelog.d/7633.bugfix
`creator` was removed in `v11` instead favouring `sender`. This field is currently defined in the spec as required, hence the crash.
https://github.com/matrix-org/matrix-spec-proposals/pull/2175
Probably best to hide whitespaces on that diff.
Fixes #7633
> Fix a crash when opening v11 rooms.

- Riot/Modules/Authentication/SSO/SSOAuthenticationService.swift
- changelog.d/pr-7639.bugfix
When signing into to element.io the generated URL was `login/sso/redirect/?redirectUrl=…` but should be `login/sso/redirect?redirectUrl=…` without the trailing slash.
> Fix SSO generating invalid URLs.

- Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
On Room v11 it is possible that the sender could put in a fake creator. Don't allow this to happen.
The changelog already exists for this as #7633
> Only use the sender when rendering the room creation event.

- Podfile.lock
- Riot/Modules/Pills/PillsFormatter.swift
- Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
- RiotSwiftUI/Modules/Common/Util/ListBackground.swift
- changelog.d/7651.bugfix
- changelog.d/pr-7649.bugfix
* update introspect to the latest version, remove now duplicate `introspectCollectionView`
* Fixes #7651
* prevent mention crashes when room members are missing display names (objc interop)
> Various bug fixes

- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/7648.bugfix
> Hide deactivate account if the auth property is present on the WK.

- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/Settings/SettingsViewController.m
- changelog.d/7653.feature
fixes #7653 
https://github.com/vector-im/element-ios/assets/34335419/90395a60-fc2f-4cb2-99cf-aa65f1553350
EDIT:
Changed the string "Manage" to" Manage Account"
> Manage account through MAS if available

- Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
- RiotSwiftUI/Modules/UserSessions/Coordinator/UserSessionsFlowCoordinator.swift
- changelog.d/7646.bugfix
fixes #7646 
Requires this to be merged to develop first:
https://github.com/matrix-org/matrix-ios-sdk/pull/1813
> Open MAS Web page when logging out from other sessions on OIDC authenticated homeservers

- Riot/Modules/Room/RoomViewController.m
- RiotShareExtension/Shared/ForwardingShareItemSender.swift
- RiotShareExtension/Shared/ShareManager.h
- RiotShareExtension/Shared/ShareManager.m
- changelog.d/7641.bugfix
This PR fixes #7641 
There were two issues:
- The `ShareManager` was using a specific session and store.
- The `MXRoom`, during its initialization, resets the timestamp of outgoing messages. 
The fix is in two parts:
- `ShareManager` can now be used with a specific session (in this case, message forwarding is done inside the application and not using a share extension, so using the current session seems fine).
- The corresponding room summary is reset once the message has been sent (to take account of the fact that it may have been created with an incorrect timestamp).
> Fix event forwarding

- BroadcastUploadExtension/target.yml
- Config/BuildSettings.swift
- Config/MDMSettings.swift
- RiotNSE/target.yml
- RiotShareExtension/target.yml
- RiotSwiftUI/target.yml
- RiotSwiftUI/targetUITests.yml
- RiotTests/target.yml
- SiriIntents/target.yml
This will allow MDM providers to configure the:
* default homeserver URL - `im.vector.app.serverConfigDefaultHomeserverUrlString`
* push gateway URL - `im.vector.app.serverConfigSygnalAPIUrlString`
* permalink base URL - `im.vector.app.clientPermalinkBaseUrl`
These methods will always try to fetch the MDM configuration first, if available, otherwise they will just use the existing defaults.
> Add initial support for configuration through MDM

- RiotSwiftUI/Modules/UserSessions/UserOtherSessions/View/UserOtherSessionsToolbar.swift
Small follow on to #7674 which missed the fact you can multi-select sessions and sign them out too.
Not including a changelog for this as its covered by the previous PR.
> Also hide session selection with OIDC in the device manager.

- Riot/Modules/Room/RoomViewController.m
Fix https://github.com/vector-im/element-ios/issues/7689
> Fix new dm crash with RTE is enabled

- Riot/Modules/Room/RoomViewController.m
- changelog.d/7704.bugfix
> Sliding to end a Jitsi call for everyone successfully ends the call for the user.

- Riot/Managers/Widgets/WidgetManager.m
- Riot/Modules/Room/RoomViewController.m
- changelog.d/7706.bugfix
> Jitsi call ends if the jitsi widget is removed from the room

- Riot/Modules/Integrations/Widgets/Jitsi/JitsiViewController.m
- changelog.d/7709.bugfix
> Jitsi conference terminated function ends the call correctly

- Riot/Modules/Room/EventMenu/EventMenuItemType.swift
- Riot/Modules/Room/RoomViewController.m
- changelog.d/7691.bugfix
This PR fixes #7691 by removing the `Quote` action from the menu of the selected message.
> Fix: Remove the “Quote” action from the menu of the selected message.

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- project.yml
Update RTE to 2.19.0 fixes:
- the position of the caret.
- double space shortcut. 
[RTE 2.19.0 - Changelog](https://github.com/matrix-org/matrix-rich-text-editor/blob/main/CHANGELOG.md)
> Update RTE to 2.19.0

- Riot/Assets/en.lproj/Vector.strings
- changelog.d/pr-7743.bugfix
The code was fine, but the provided original copies were swapped, so we needed to change them in the original english string file. Now this change needs to be propagated through weblate for all the other languages.
> Fix for swapped accessibility labels for the underline and the strikethrough on RTE

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Riot/Generated/Strings.swift
- RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
- changelog.d/7752.bugfix
- project.yml
Upgrades to the latest version of the RTE package, and adjusts the key commands to fix build errors.
https://github.com/element-hq/element-ios/assets/6060466/810ca870-3bbd-4e33-9444-cc27dd025389
> Fix dictation when using the Rich Text Editor.

- Podfile
- Podfile.lock
- Riot/Modules/QRCode/Reader/QRCodeReaderView.swift
- changelog.d/pr-7762.bugfix
There were reports about not being able to scan QR codes to verify a device, but it turns out that it does work, just not if you fill the entire frame with the code. Moving back a bit so the code is smaller does work.
My conclusion was that the `applyRectOfInterest` method isn't really necessary as we don't do that when [logging in](https://github.com/element-hq/element-ios/blob/b39923fbc1b047494a5d01e13e24501b661343bd/RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift#L30) with a QR code. The removal of that method has no effect on the UI, it simply constrained the area of the capture that ZXing was looking in.
> Fix a bug where QR codes aren't detected if the camera is too close.

- Riot/Modules/Analytics/DecryptionFailureTracker.m
Increase decryption failure grace period as per https://github.com/element-hq/element-meta/issues/2303
> Increase decryption failure grace period

- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Analytics/DecryptionFailure+Analytics.swift
- Riot/Modules/Analytics/DecryptionFailure.swift
- Riot/Modules/Analytics/DecryptionFailureTracker.swift
- RiotTests/DecryptionFailureTrackerTests.swift
Preliminary work for https://github.com/element-hq/element-ios/issues/7767
depends on https://github.com/element-hq/element-ios/pull/7769
Add support for permanent vs temporary UTD.
If an event is decrypted in less than 4s after decryption, it should be graced.
If it's decrypted in > 4s and less than 60s, we still report as an UTD but with the time to decrypt.
If after 60s it's not decrypted report as permanent UTD
> Analytics | permanent vs temporary utd

- Riot/Modules/Analytics/DecryptionFailure+Analytics.swift
- Riot/Modules/Analytics/DecryptionFailure.swift
- Riot/Modules/Analytics/DecryptionFailureTracker.swift
- Riot/Utils/EventFormatter.m
- RiotTests/DecryptionFailureTrackerTests.swift
- RiotTests/FakeUtils.swift
Part of https://github.com/element-hq/element-ios/issues/7767
Depends on SDK Change: https://github.com/matrix-org/matrix-ios-sdk/pull/1848
Adds `eventLocalAgeMillis` and `trustOwnIdentityAtTimeOfFailure` properties for posthog reporting. Also use a new error name when a decryption is expected to fail: `HistoricalMessage` (device historical and session not verified so can't access backup)
> Analytics | Report expected UTDs as HistoricalMessage error

- Riot/Modules/Analytics/DecryptionFailure+Analytics.swift
- Riot/Modules/Analytics/DecryptionFailure.swift
- Riot/Modules/Analytics/DecryptionFailureTracker.swift
- RiotTests/DecryptionFailureTrackerTests.swift
Based on https://github.com/element-hq/element-ios/pull/7775
Last step of https://github.com/element-hq/element-ios/issues/7767
Add the new properties `isMatrixOrg`, `isFederated` and `wasVisibleToUser`.
Note: `wasVisibleToUser` is always true for now, as the UTD are reported only from the `EventFormatter`.
Additional work is needed to report visible vs not visible. This would require to move down the `DecryptionFailureTracker` into the SDK
> Telemetry | Add additional properties to posthog UTD errors

- Riot/Modules/Room/Attachements/MXKAttachmentsViewController.m
- changelog.d/7791.bugfix
Fixes #7791
The crash had nothing to do with the network failures, tapping play once and killing the network fails gracefully. However if the user tapped play multiple times, then the app would crash handling the failure multiple times.
> Fix a crash when the user taps play multiple times and the download fails

- Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Riot/Modules/Analytics/Analytics.swift
- Riot/Modules/Analytics/AnalyticsClientProtocol.swift
- Riot/Modules/Analytics/PostHogAnalyticsClient.swift
- Riot/Modules/Analytics/PosthogProtocol.swift
- RiotTests/AnalyticsTests.swift
- RiotTests/FakeUtils.swift
- RiotTests/PostHogAnalyticsClientTests.swift
- changelog.d/7801.misc
- project.yml
Add support for posthog super properties (added to all events).
The analytics-event dependency has been updated to latest release.
In order to add unit test I had to introduce a protocol interface for PostHog and added some Mock classes.
Fixes https://github.com/element-hq/crypto-internal/issues/322
> Analytics | Add support for super properties and appPlatform

- Podfile.lock
Needed for https://github.com/element-hq/element-ios/pull/7808
> Update the SDK.

- RiotSwiftUI/Modules/LocationSharing/StartLocationSharing/Coordinator/LocationSharingCoordinator.swift
- changelog.d/pr-7808.change
#7808 cherry picked and squashed without the commits from #7778.
Original sign off is in the previous PR.
> Check power level before starting live sharing location

- Podfile.lock
- Riot/Modules/Pills/PillAttachmentView.swift
- Riot/Modules/Pills/PillProvider.swift
- Riot/Modules/Pills/PillTextAttachment.swift
- Riot/Modules/Pills/PillTextAttachmentData.swift
- Riot/Modules/Pills/PillType.swift
- Riot/Modules/Pills/PillsFormatter.swift
- Riot/Modules/Room/VoiceMessages/VoiceMessagePlaybackView.swift
- Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewModel.swift
also updated some pods and swifftlint
> Update iOS SDK to use Crypto Sdk for content scanner

- Podfile.lock
- Riot/Assets/en.lproj/Localizable.strings
- Riot/Assets/en.lproj/Vector.strings
- Riot/Generated/Strings.swift
- Riot/Modules/MatrixKit/Models/MXKAppSettings.m
- Riot/Modules/Room/CellData/RoomBubbleCellData.h
- Riot/Modules/Room/CellData/RoomBubbleCellData.m
- Riot/Modules/Room/RoomViewController.m
- Riot/Modules/Room/TimelineCells/Call/CallCellContentView.xib
- Riot/Modules/Room/TimelineCells/Call/MatrixRTC/RoomMatrixRTCCallCell.swift
- Riot/Modules/Room/TimelineCells/RoomTimelineCellIdentifier.h
- Riot/Modules/Room/TimelineCells/Styles/Plain/PlainRoomTimelineCellProvider.m
- RiotNSE/NotificationService.swift
This PR makes the following changes:
- Process `m.call.notify` events in the NSE (only when `m.mentions` includes you) showing an unsupported call notification.
- Show `m.call.notify` events in the timeline as unsupported calls.
- Update the SDK to include https://github.com/matrix-org/matrix-ios-sdk/pull/1887
Part of https://github.com/element-hq/element-ios/issues/7861
**EX on the left | EI on the right**
https://github.com/user-attachments/assets/66eadf1d-c9bd-4c62-bcde-4e587894cebe
> Show Matrix RTC calls as unsupported.

- RiotNSE/NotificationService.swift
The `m.call.notify` notification was getting marked as "to be removed", and then immediately followed up by an `m.call.member` event which, whilst it is ignored as a notification, still triggers [the removal](https://github.com/element-hq/element-ios/blob/34ddefaac01f49e01ee8e69d31db4378c1ae1e13/RiotNSE/NotificationService.swift#L104) before being handled.
> Fix a bug where Matrix RTC call notifications are removed immediately after display.

- Podfile.lock
- Riot/Modules/CrossSigning/Setup/CrossSigningSetupCoordinator.swift
The check didn't include the parameters that are used for the reset, and as mentioned in [the spec](https://spec.matrix.org/latest/client-server-api/#post_matrixclientv3keysdevice_signingupload), from v1.11 the use of UIA depends on the change being made.
The fix is to simply attempt to reset, and then handle the UIA failure manually after this if it occurs (retrying when the user has completed the authentication).
Unrelated: I updated the SDK so that we pull in https://github.com/matrix-org/matrix-ios-sdk/pull/1885 ready for the next release.
Fixes https://github.com/element-hq/element-ios/issues/7838
> Fix a bug where UIA for cross signing wasn't needed until after checking for it.

- Riot/Modules/MatrixKit/Categories/DTHTMLElement+MatrixKit.swift
- RiotTests/MatrixKitTests/MXKEventFormatterTests.m
- changelog.d/pr-7927.change
Ref: https://github.com/matrix-org/matrix-spec-proposals/pull/4286
|-|-|
|![Simulator Screenshot - iPhone 16 Pro - 2025-05-26 at 17 38 09](https://github.com/user-attachments/assets/e6d7fa24-aeb3-4d7b-8688-b9e35e5059b5)|![Simulator Screenshot - iPhone 16 Pro - 2025-05-26 at 17 35 46](https://github.com/user-attachments/assets/4e8667ba-9214-41eb-97ad-639a4159636f)|
In the above example the `formatted_body` of the event looks like this:
`Thanks for subscribing!<span data-msc4286-external-payment-details> You can manage your subscription and view your payment history <a href="https://account.example.com/account/plan">here</a> at any time</span>`
> Support for experimental MSC4286 to not render external payment details
