CHANGES.rst
Riot/AppDelegate.m

Registration: Support email verification link from homeserver

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/Modules/KeyVerification/Common/KeyVerificationKind.swift
Riot/Modules/KeyVerification/Common/Loading/KeyVerificationDataLoadingCoordinator.swift
Riot/Modules/KeyVerification/Common/Loading/KeyVerificationDataLoadingViewController.swift
Riot/Modules/KeyVerification/Common/Loading/KeyVerificationDataLoadingViewModel.swift
Riot/Modules/KeyVerification/Common/Loading/KeyVerificationDataLoadingViewModelType.swift
Riot/Modules/KeyVerification/Common/ScanConfirmation/KeyVerificationScanConfirmationViewController.swift
Riot/Modules/KeyVerification/Common/Verified/KeyVerificationVerifiedViewController.swift
Riot/Modules/KeyVerification/Common/Verify/SAS/KeyVerificationVerifyBySASViewController.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningCoordinator.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningCoordinatorType.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewState.swift
Riot/Modules/KeyVerification/Device/Incoming/DeviceVerificationIncomingViewController.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewController.storyboard
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewController.swift
Riot/Modules/KeyVerification/Device/Start/DeviceVerificationStartViewController.swift

Key verification: Update key verification screens title. Update SAS screen wordings.

---

Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Common/Buttons/Close/RoundedButton.swift
Riot/Modules/KeyVerification/Common/ScanConfirmation/KeyVerificationScanConfirmationViewController.storyboard
Riot/Modules/KeyVerification/Common/ScanConfirmation/KeyVerificationScanConfirmationViewController.swift
Riot/Modules/KeyVerification/Common/Verify/SAS/KeyVerificationVerifyBySASViewController.storyboard
Riot/Modules/KeyVerification/Common/Verify/SAS/KeyVerificationVerifyBySASViewController.swift
Riot/Modules/Room/Views/BubbleCells/KeyVerification/KeyVerificationCellInnerContentView.swift
Riot/Modules/Room/Views/BubbleCells/KeyVerification/KeyVerificationCellInnerContentView.xib

Update SAS verification screen UI

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/Modules/KeyVerification/Common/Verified/KeyVerificationVerifiedViewController.storyboard
Riot/Modules/KeyVerification/Common/Verified/KeyVerificationVerifiedViewController.swift

Key verification: Update verified screen UI

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/TabBar/MasterTabBarController.m

Display the "Verify this session" modal at every startup

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinatorBridgePresenter.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinator.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinatorType.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModelType.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewState.swift

Complete Security screen: Support verification start

---

Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

New sign in alert: Update wording

---

CHANGES.rst
Riot/Assets/Base.lproj/Main.storyboard
Riot/Assets/en.lproj/Vector.strings
Riot/Categories/UIViewController.swift
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Settings/SettingsViewController.h
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/TabBar/MasterTabBarController.m

Key verification: Display "Verify your other sessions" modal at every startup if needed

---

CHANGES.rst
Riot/Modules/KeyVerification/Common/Loading/KeyVerificationDataLoadingViewController.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewController.storyboard
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewController.swift

BF: KeyVerificationSelfVerifyStartViewController has no navigation

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.storyboard
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.swift

BF: Copy on self-verification QR code scanning screen refers to other-person scanning

---

Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Categories/UILabel.swift
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Riot/Modules/KeyVerification/Device/ManuallyVerify/KeyVerificationManuallyVerifyCoordinator.swift
Riot/Modules/KeyVerification/Device/ManuallyVerify/KeyVerificationManuallyVerifyCoordinatorType.swift
Riot/Modules/KeyVerification/Device/ManuallyVerify/KeyVerificationManuallyVerifyViewAction.swift
Riot/Modules/KeyVerification/Device/ManuallyVerify/KeyVerificationManuallyVerifyViewController.storyboard
Riot/Modules/KeyVerification/Device/ManuallyVerify/KeyVerificationManuallyVerifyViewController.swift
Riot/Modules/KeyVerification/Device/ManuallyVerify/KeyVerificationManuallyVerifyViewModel.swift
Riot/Modules/KeyVerification/Device/ManuallyVerify/KeyVerificationManuallyVerifyViewModelType.swift
Riot/Modules/KeyVerification/Device/ManuallyVerify/KeyVerificationManuallyVerifyViewState.swift
Riot/Modules/KeyVerification/User/SessionStatus/UserVerificationSessionStatusCoordinator.swift
Riot/Modules/KeyVerification/User/SessionStatus/UserVerificationSessionStatusCoordinatorType.swift
Riot/Modules/KeyVerification/User/SessionStatus/UserVerificationSessionStatusViewAction.swift
Riot/Modules/KeyVerification/User/SessionStatus/UserVerificationSessionStatusViewController.storyboard
Riot/Modules/KeyVerification/User/SessionStatus/UserVerificationSessionStatusViewController.swift
Riot/Modules/KeyVerification/User/SessionStatus/UserVerificationSessionStatusViewModel.swift
Riot/Modules/KeyVerification/User/SessionStatus/UserVerificationSessionStatusViewModelType.swift
Riot/Modules/KeyVerification/User/UserVerificationCoordinator.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinator.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinator.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinatorType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewAction.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewController.storyboard
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewController.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModel.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModelType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewState.swift

Self verify my old riots

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Utils/EventFormatter+DTCoreTextFix.h
Riot/Utils/EventFormatter+DTCoreTextFix.m
Riot/Utils/EventFormatter.m

BF: Timeline: Fix font used for `org.matrix.custom.html`messages

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/Assets/Riot-Defaults.plist
Riot/Generated/RiotDefaults.swift
Riot/Managers/PushNotification/PushNotificationService.h
Riot/Managers/PushNotification/PushNotificationService.m
Riot/Modules/Settings/SettingsViewController.m

PushNotificationService Implementation

---

CHANGES.rst
Riot/AppDelegate.m

CallVC: Add improvements to reset callVC after decline, new call and hangup

---

CHANGES.rst
Riot/Managers/Theme/ThemeService.m
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift

Theme: Customize UISearchBar with new iOS 13 properties

---

CHANGES.rst
RiotNSE/NSEMemoryStore.swift
RiotNSE/NotificationService.swift

Fix Decryption on Notifications When Megolm Key is not Present

---

CHANGES.rst
Riot/Managers/Theme/Themes/DefaultTheme.swift

Fix Selected Background Color on Cells for iOS 13+

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Modules/Settings/Security/SecurityViewController.m

#3239
Requires matrix-org/matrix-ios-kit/pull/675

Timeline: Hide encrypted history (pre-invite)

---

CHANGES.rst
Riot/Managers/Theme/Theme.swift
Riot/Managers/Theme/ThemeService.h
Riot/Managers/Theme/ThemeService.m
Riot/Managers/Theme/Themes/BlackTheme.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift

Respect System Dark Mode Setting

---

CHANGES.rst
RiotNSE/NotificationService.swift

Avoid Default Notification Sound

---

CHANGES.rst
Riot/Modules/Room/EmojiPicker/EmojiPickerViewController.swift

Emoji Selection Screen Navigation Bar Bg Color

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Managers/PushNotification/PushNotificationService.h
Riot/Managers/PushNotification/PushNotificationService.m

Highlight Message when Opening from Notification

---

CHANGES.rst
RiotNSE/NotificationService.swift

Make NotificationServiceExtension Reusable

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Categories/MXRecoveryService.swift
Riot/Modules/KeyBackup/Recover/KeyBackupRecoverCoordinator.swift
Riot/Modules/KeyBackup/Recover/KeyBackupRecoverCoordinatorBridgePresenter.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
Riot/Modules/SecretsRecovery/RecoverWithKey/SecretsRecoveryWithKeyViewController.swift
Riot/Modules/SecretsRecovery/RecoverWithKey/SecretsRecoveryWithKeyViewModel.swift
Riot/Modules/SecretsRecovery/RecoverWithPassphrase/SecretsRecoveryWithPassphraseViewController.swift
Riot/Modules/SecretsRecovery/RecoverWithPassphrase/SecretsRecoveryWithPassphraseViewModel.swift
Riot/Modules/SecretsRecovery/SecretsRecoveryCoordinatorBridgePresenter.swift
Riot/Modules/SecretsRecovery/SecretsRecoveryGoal.swift
Riot/Modules/SecretsRecovery/SecretsRecoveryMode.swift
Riot/Modules/Settings/Security/SecurityViewController.m

Connect/restore backup created with SSSS

---

CHANGES.rst
RiotNSE/NSEMemoryStore.swift
RiotNSE/NotificationService.swift

This is a potential fix for the check in `MXPushRuleDisplayNameCondtionChecker`.

Fix Session User `displayname`

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Utils/DataProtectionHelper.swift
RiotNSE/NotificationService.swift

Fixes the problem of not processing the push payload even after unlocking the device.

Fix rebooted and not unlocked case for NSE

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Categories/MXSession+Riot.h
Riot/Categories/MXSession+Riot.m
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Contacts/Details/ContactDetailsViewController.m
Riot/Modules/StartChat/StartChatViewController.m
Tools/Rageshakes/getlogs.sh

Require https://github.com/matrix-org/matrix-ios-sdk/pull/870
Fix #3305.

E2E by default: Disable it if the HS admin disabled it

---

CHANGES.rst
Riot/Assets/en.lproj/Localizable.strings
RiotNSE/NotificationService.swift

New Fallback Content for Push Notifications

---

CHANGES.rst
Riot/SupportingFiles/Info.plist

Disable `voip` background mode to avoid VoIP Pushes

---

CHANGES.rst
RiotNSE/NotificationService.swift

Disable Key Backup on Push Extension

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/Security/SecurityViewController.m

SecurityVC: Update MY SESSIONS copy

---

CHANGES.rst
Riot/Modules/Room/Views/BubbleCells/RoomMembershipBubbleCell.xib

Fix Ban Reason Truncation

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Utils/EventFormatter.m

Use `you` instead of display name on notice events

---

CHANGES.rst
Riot/Assets/third_party_licenses.html

Add third party license for FlowCommoniOS

---

CHANGES.rst
Riot/SupportingFiles/Riot.entitlements

Fix Universal Links for Web Apps

---

Riot/Assets/Images.xcassets/Common/disclosure_icon.imageset/Contents.json
Riot/Assets/Images.xcassets/Common/shrink_icon.imageset/Contents.json
Riot/Categories/UITableViewCell.swift
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Authentication/Views/TermsView.swift
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
Riot/Modules/Contacts/DataSources/ContactsDataSource.m
Riot/Modules/GlobalSearch/UnifiedSearchViewController.m
Riot/Modules/MajorUpdate/MajorUpdateViewController.swift
Riot/Modules/People/PeopleViewController.m
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewController.swift
Riot/Modules/Settings/Discovery/SettingsDiscoveryTableViewSection.swift
Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
Riot/Modules/Settings/Security/SecurityViewController.m
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/Settings/Views/TableViewCellWithPhoneNumberTextField.m

Fix UITableView disclosure indicator color

---

CHANGES.rst
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Home/HomeViewController.m

Fix Crash on dequeue `CrossSigningSetupBannerCell`

---

CHANGES.rst
Riot/Modules/Authentication/AuthenticationViewController.m

 Registration: Do not display the skip button if email is mandatory

---

CHANGES.rst
RiotNSE/NotificationService.swift

Do not cache showDecryptedContentInNotifications

---

CHANGES.rst
Config/Common.xcconfig
Riot.xcodeproj/project.pbxproj
Riot/SupportingFiles/App-Debug.xcconfig
Riot/SupportingFiles/App-Release.xcconfig
Riot/SupportingFiles/Info.plist
RiotNSE/NSE-Debug.xcconfig
RiotNSE/NSE-Release.xcconfig
RiotShareExtension/SupportingFiles/Info.plist
RiotShareExtension/SupportingFiles/ShareExtension-Debug.xcconfig
RiotShareExtension/SupportingFiles/ShareExtension-Release.xcconfig
SiriIntents/SiriIntents-Debug.xcconfig
SiriIntents/SiriIntents-Release.xcconfig

Implemented both for the app and the share extension.

Read App Display Name from xcconfig Files

---

CHANGES.rst
Config/BuildSettings.swift
Config/Common.xcconfig
Config/CommonConfiguration.swift
Riot.xcodeproj/project.pbxproj
Riot/Categories/Bundle.swift
Riot/Generated/InfoPlist.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/SupportingFiles/Info.plist
Riot/SupportingFiles/Riot.entitlements
RiotNSE/RiotNSE.entitlements
RiotShareExtension/SupportingFiles/RiotShareExtension.entitlements
SiriIntents/SiriIntents.entitlements
Tools/SwiftGen/swiftgen-config.yml

I started to use it for "group.im.vector" that is now defined is a single place: in xcconfig.

BuildSettings: A new class that entralises build settings and exposes xcconfig variables

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Modules/Authentication/AuthenticationViewController.m

AuthenticationVC: Make custom server options and register button configurable

---

Config/BuildSettings.swift
Config/CommonConfiguration.swift
Riot/AppDelegate.m
Riot/Assets/Riot-Defaults.plist
Riot/Managers/Analytics/Analytics.m
Riot/Managers/Settings/RiotSettings.swift
Riot/Managers/Widgets/WidgetManager.m
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/BugReport/BugReportViewController.m
Riot/Modules/Rooms/RoomsViewController.m
Riot/Modules/Settings/SettingsViewController.m
Riot/Utils/Tools.h
Riot/Utils/Tools.m

They are now defined in BuildSettings.swift. I removed unused ones.
Commits can be reviewed one by one.

Remove keys that should not be in Riot-Defaults.plist

---

Config/BuildSettings.swift
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m

We can now hide public rooms and disable the selection on another public server

BuildSettings: Add options for Room directory

---

fastlane/Fastfile

[Internal] [CI] Remove unused require in scripts #trivial

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Categories/UIScrollView.swift
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/AuthenticationViewController.xib
Riot/Modules/Common/KeyboardAvoiding/KeyboardAvoider.swift

Fix Custom Homeserver Textfield on AuthenticationViewController

---

CHANGES.rst
Riot/Categories/UIImage.swift
Riot/Modules/Common/Recents/RecentsViewController.m

Fix Rooms List Swipe Actions Tint Color

---

CHANGES.rst
Riot/Modules/SetPinCode/PinCodePreferences.swift

Fix Biometry Name

---

CHANGES.rst
Riot/Modules/Authentication/Views/AuthInputsView.m

Avoid Email Validation to Redirect to Element Web

---

Riot.xcodeproj/project.pbxproj
Riot/AppDelegate.m
Riot/Managers/PushNotification/PushNotificationService.h
Riot/Managers/PushNotification/PushNotificationService.m
Riot/Managers/PushNotification/PushNotificationStore.swift
RiotNSE/NotificationService.swift

For later remarks of https://github.com/vector-im/element-ios/pull/3531

Fix Later Remarks on PushKit & CallKit

---

.gitignore
CHANGES.rst

Ignore fastlane `Preview.html`

---

CHANGES.rst
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m

Update room input toolbar on theme change

---

CHANGES.rst
Riot/Managers/PushNotification/PushNotificationService.m

Remove PushKit Pushers

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Managers/PushNotification/PushNotificationService.h
Riot/Managers/PushNotification/PushNotificationService.m

PushKit pusher: Add more logs when removing it

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Modules/SetPinCode/PinCodePreferences.swift

Show PIN Screen on Every Foreground

---

CHANGES.rst
Riot/Categories/UIApplication.swift
Riot/Modules/SetPinCode/EnterPinCode/EnterPinCodeViewController.swift

Close Keyboard on Pin Code Screen

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

PIN Code: Update explanation string

---

CHANGES.rst
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/Settings/Views/TableViewCellWithPhoneNumberTextField.m
Riot/Modules/Settings/Views/TableViewCellWithPhoneNumberTextField.xib

Settings: New phone number is invisible in dark theme

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj

i18n: Add Estonian language

---

CHANGES.rst
Riot/Managers/PushNotification/PushNotificationService.m

Handle Call Actions on Other Devices on VoIP Pushes

---

CHANGES.rst
Riot/Categories/MXSession+Riot.m
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m

Put specific additional check out of this method.

MXSession: Make sure vc_canSetupSecureBackup is reusable

---

CHANGES.rst
Riot/Modules/SetPinCode/SetupBiometrics/SetupBiometricsViewModel.swift

Handle retry biometrics case, on where the app was stuck.

Handle Retry on Biometrics

---

CHANGES.rst
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/CreationModal/RoomCreationEventsModal/RoomCreationEventsModalViewController.storyboard
Riot/Modules/Room/CreationModal/RoomCreationEventsModal/RoomCreationEventsModalViewController.swift

Remove Membership Events from Room Creation Modal

---

CHANGES.rst
Podfile
Riot/Assets/en.lproj/Vector.strings
Riot/Assets/third_party_licenses.html
Riot/Categories/UITableView.swift
Riot/Generated/Strings.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewController.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewData.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewModel.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/Views/RoomInfoBasicView.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/Views/RoomInfoBasicView.xib
Riot/Modules/Room/RoomInfo/RoomInfoList/Views/RoomInfoBasicViewData.swift

Room: Make topic links tappable & Show more/less on long topics

---

CHANGES.rst
Riot/Managers/BugReport/RageShakeManager.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Settings/RoomSettingsViewController.m

Use `MXKPasteboardManager.pasteboard` instead of generalPasteboard

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.storyboard
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.swift

Self-verification: Update complete security screen wording

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Secrets/Setup/RecoveryKey/SecretsSetupRecoveryKeyCoordinator.swift
Riot/Modules/Secrets/Setup/RecoveryKey/SecretsSetupRecoveryKeyViewController.storyboard
Riot/Modules/Secrets/Setup/RecoveryKey/SecretsSetupRecoveryKeyViewController.swift
Riot/Modules/Secrets/Setup/RecoveryKey/SecretsSetupRecoveryKeyViewModel.swift
Riot/Modules/Secrets/Setup/RecoveryKey/SecretsSetupRecoveryKeyViewState.swift
Riot/Modules/SecureBackup/Setup/SecureBackupSetupCoordinator.swift

Secure backup: Add possibility to not expose recovery key when creating a secure backup

---

Riot/Assets/Base.lproj/Main.storyboard
Riot/Modules/Contacts/Details/ContactDetailsViewController.m
Riot/Modules/GlobalSearch/Files/HomeFilesSearchViewController.m
Riot/Modules/GlobalSearch/Messages/HomeMessagesSearchViewController.m
Riot/Modules/Room/RoomViewController.m

Crash fixes

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings

Two items not ticked because assumed they are not necessary for minor typo fixes.
Signed-off-by: Stéphane Guillou <stephane.guillou@member.fsf.org>

fix typos in English UI messages

---

CHANGES.rst
Riot/Managers/Analytics/Analytics.h
Riot/Managers/Analytics/Analytics.m
Riot/Managers/Analytics/DecryptionFailureTracker.h
Riot/Managers/Analytics/DecryptionFailureTracker.m
Riot/Modules/Application/LegacyAppDelegate.m

Depends on https://github.com/matrix-org/matrix-ios-sdk/pull/938.
Commits can be reviewed one by one.
Here is what we can see on Matomo:

MXAnalyticsDelegate: Make it fully agnostic on tracked data

---

CHANGES.rst
RiotNSE/NotificationService.swift

Refresh Account Details on NSE Runs

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

AuthenticationVC: Update SSO wording

---

CHANGES.rst
Riot/Modules/Common/NavigationController/RiotNavigationController.m

Prevent navigation controller from pushing same view controller

---

CHANGES.rst
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/Views/TermsView.swift
Riot/Modules/Authentication/Views/TermsView.xib

AuthVC: Fix recaptcha view cropping

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.storyboard

Think I did everything on the list that's relevant/necessary, but let me know if there's anything else!
Signed-off-by: mtoohey31 <mtoohey31@users.noreply.github.com>

Fix cients spelling mistake in multiple files

---

CHANGES.rst
Riot/Modules/SplitView/SplitViewCoordinator.swift

Fix #3863
Remove weak because of https://github.com/vector-im/element-ios/issues/3863#issuecomment-762723419

Navigation: BF: Unable to open a room from a room list

---

RiotNSE/NotificationService.swift

Add some logs, notably one on `deinit` to track #3957.
I sent a rageshake. with new logs. GH should display in this PR timeline.

NotificationService: Update logs

---

CHANGES.rst
Riot/Managers/Widgets/Widget.h
Riot/Managers/Widgets/Widget.m

Widgets: Support $matrix_room_id and $matrix_widget_id parameters

---

CHANGES.rst
Riot/Modules/Application/LegacyAppDelegate.m

Fix #3990.
Fix #3991.
Fix #3993.
Commits can be reviewed one by one.

Several fixes around permalinks and matrix.to

---

CHANGES.rst
Riot/Modules/Application/LegacyAppDelegate.m
RiotNSE/NotificationService.swift

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1011
Fix #3903

3903 logs too big

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/AuthenticatedSession/AuthenticatedSessionViewControllerFactory.swift
Riot/Modules/AuthenticatedSession/AuthenticationParametersBuilder.swift
Riot/Modules/AuthenticatedSession/AuthenticationSessionParameters.swift
Riot/Modules/AuthenticatedSession/AuthenticationSessionService.swift
Riot/Modules/Authentication/SSO/SSOAuthenticationPresenter.swift
Riot/Modules/CrossSigning/CrossSigningService.swift
Riot/Modules/CrossSigning/Setup/CrossSigningSetupCoordinator.swift
Riot/Modules/CrossSigning/Setup/CrossSigningSetupCoordinatorBridgePresenter.swift
Riot/Modules/CrossSigning/Setup/CrossSigningSetupCoordinatorParameters.swift
Riot/Modules/CrossSigning/Setup/CrossSigningSetupCoordinatorType.swift
Riot/Modules/Home/HomeViewController.m
Riot/Modules/KeyVerification/Common/KeyVerificationService.swift
Riot/Modules/Reauthentication/ReauthFallBackViewController.swift
Riot/Modules/Reauthentication/ReauthenticationCoordinator.swift
Riot/Modules/Reauthentication/ReauthenticationCoordinatorBridgePresenter.swift
Riot/Modules/Reauthentication/ReauthenticationCoordinatorParameters.swift
Riot/Modules/Reauthentication/ReauthenticationCoordinatorType.swift
Riot/Modules/Secrets/Reset/SecretsResetCoordinator.swift
Riot/Modules/Secrets/Reset/SecretsResetViewController.swift
Riot/Modules/Secrets/Reset/SecretsResetViewModel.swift
Riot/Modules/Secrets/Reset/SecretsResetViewModelType.swift
Riot/Modules/Secrets/Reset/SecretsResetViewState.swift
Riot/Modules/Settings/Security/SecurityViewController.m
Riot/Modules/Settings/SettingsViewController.m
Riot/SupportingFiles/Riot-Bridging-Header.h
RiotTests/AuthenticationSessionServiceTests.swift

Handle User-Interactive Authentication fallback

---

CHANGES.rst
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/CrossSigning/CrossSigningService.swift

Cross-signing: Setup cross-signing without authentication parameters when a grace period is enabled after login

---

Config/BuildSettings.swift
Riot/Modules/Integrations/Widgets/Jitsi/JitsiService.swift
Riot/Modules/Integrations/Widgets/Jitsi/JitsiViewController.m

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1016

Pods: Update Jitsi to 3.1.0

---

CHANGES.rst
RiotNSE/NotificationService.swift

NSE: Wait for VoIP Push Requests

---

CHANGES.rst
Riot/Modules/Common/Recents/RecentsViewController.h
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Rooms/RoomsViewController.m

Home: Show room directory on join room action

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
Riot/Modules/GlobalSearch/UnifiedSearchViewController.m
Riot/Modules/PublicRoomList/DataSources/PublicRoomsDirectoryDataSource.h
Riot/Modules/PublicRoomList/DataSources/PublicRoomsDirectoryDataSource.m
Riot/Modules/Rooms/RoomsViewController.m
Riot/Modules/Settings/SettingsViewController.m

Settings: Add option to show NSFW public rooms

---

Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
Riot/Managers/Theme/Theme.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomBubbleCellLayout.swift
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithPaginationTitleBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithPaginationTitleWithoutSenderNameBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithoutSenderInfoBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithoutSenderNameBubbleCell.xib

SR sizing is inconsistent with RR & Message states cosmetic changes

---

CHANGES.rst
Config/CommonConfiguration.swift
Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
Riot/Modules/Contacts/Details/Views/RoomTableViewCell.m
Riot/Modules/Home/Views/RoomCollectionViewCell.m
Riot/Modules/Room/DataSources/RoomDataSource.m
RiotShareExtension/Modules/Share/Listing/Views/RecentRoomTableViewCell.m

Require https://github.com/matrix-org/matrix-ios-sdk/pull/1050
Fix #4115

Room lists: Remove shields on room avatars

---

CHANGES.rst
Gemfile
Gemfile.lock
Riot/Modules/Rooms/ShowDirectory/Cells/Room/DirectoryRoomTableViewCell.swift

Room directory: Fix crash

---

CHANGES.rst
RiotTests/Debug.xcconfig
RiotTests/Release.xcconfig
RiotTests/target.yml

Unit tests are broken

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Settings/Security/SecurityViewController.m
Riot/Modules/Settings/SettingsViewController.m

Make the application settings more configurable

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/CreateRoom/EnterNewRoomDetails/EnterNewRoomDetailsViewController.swift
Riot/Modules/CreateRoom/EnterNewRoomDetails/EnterNewRoomDetailsViewModel.swift

Possibility to lock some room creation parameters from settings

---

CHANGES.rst
Riot/Modules/Room/RoomViewController.m

RoomVC: Crash in refreshTypingNotification

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/TabBar/MasterTabBarController.m

Show/Hide Home Screen tabs

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Room/RoomViewController.m

Enable / Disable VoIP feature in Rooms

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/GlobalSearch/DataSources/UnifiedSearchRecentsDataSource.m

Show/Hide public directory in Unified Search

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewController.swift
Riot/Modules/Room/RoomViewController.m

Show / Hide integrations and actions in rooms

---

CHANGES.rst
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/TabBar/MasterTabBarController.m

clear cache support for RiotSettings

---

CHANGES.rst
Riot/Modules/Room/RoomViewController.m

Crash in [RoomViewController setScrollToBottomHidden:]

---

.github/workflows/ci.yml
CHANGES.rst
fastlane/Fastfile

By following what has been [done]()https://github.com/matrix-org/matrix-ios-kit/pull/804 in MatrixKit with `mx_git_branch`.

GH Actions: Make jobs use the right version of MatrixKit and MatrixSDK

---

CHANGES.rst
Config/AppConfiguration.swift
Config/CommonConfiguration.swift

Fix #4274.
Only the app needs MXUIKitBackgroundModeHandler.

Notifications: Make them work in debug mode

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Room/RoomViewController.m

Show / Hide More and Report Content contextual menu from settings

---

CHANGES.rst
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m

[Spaces] Hide spaces from room list and home but keep space invites

---

CHANGES.rst
Riot/Managers/Call/Operations/CallBarPresentOperation.swift

Fix Call Bar Layout Issue

---

INSTALL.md

[Rendered INSTALL.md](https://github.com/vector-im/element-ios/blob/5f0139c333080b7344d78ffa5e3c7b3b436a8eb7/INSTALL.md)

Update Build System Requirement in INSTALL.md

---

CHANGES.rst
Riot/Modules/Room/EditHistory/EditHistoryViewModel.swift

#4306
Needs https://github.com/matrix-org/matrix-ios-sdk/pull/1091

Crypto: Do not decrypt synchronously. It asynchronously happens upstream now

---

CHANGES.rst
Riot/Assets/Base.lproj/Main.storyboard
Riot/Managers/UserSessions/UserSession.swift
Riot/Managers/UserSessions/UserSessionsService.swift
Riot/Modules/Application/AppCoordinator.swift
Riot/Modules/Application/LegacyAppDelegate.h
Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Communities/GroupsViewController.h
Riot/Modules/Communities/GroupsViewController.m
Riot/Modules/Favorites/FavouritesViewController.h
Riot/Modules/Favorites/FavouritesViewController.m
Riot/Modules/GlobalSearch/UnifiedSearchViewController.h
Riot/Modules/GlobalSearch/UnifiedSearchViewController.m
Riot/Modules/Home/HomeViewController.h
Riot/Modules/Home/HomeViewController.m
Riot/Modules/People/PeopleViewController.h
Riot/Modules/People/PeopleViewController.m
Riot/Modules/Rooms/RoomsViewController.h
Riot/Modules/Rooms/RoomsViewController.m
Riot/Modules/SplitView/SplitViewCoordinator.swift
Riot/Modules/TabBar/MasterTabBarController.h
Riot/Modules/TabBar/MasterTabBarController.m
Riot/Modules/TabBar/TabBarCoordinator.swift
Riot/SupportingFiles/Riot-Bridging-Header.h

UI Navigation: Start decoupling view controllers managed by MasterTabBarController

---

CHANGES.rst
Riot/Modules/Integrations/Widgets/Jitsi/JitsiJWTPayload.swift
Riot/Modules/Integrations/Widgets/Jitsi/JitsiJWTTokenBuilder.swift
Riot/Modules/Integrations/Widgets/Jitsi/JitsiService.swift

Adds optional `server_name` field.

Jitsi JWT Payload Server Name

---

CHANGES.rst
Riot/Modules/Settings/SettingsViewController.m

Fix Crash When Changing App Language

---

CHANGES.rst
Riot/Managers/EncryptionKeyManager/EncryptionKeyManager.swift

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1116

Create Room Last Message Encryption Keys

---

CHANGES.rst
Podfile
Riot/Modules/Application/AppCoordinator.swift
Riot/Modules/Application/AppDelegate.swift

Set up [FLEX](https://github.com/FLEXTool/FLEX) for debug builds under a 2 finger double tap anywhere on the screen.

Integrate FLEX

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Categories/MXSession+Riot.h
Riot/Categories/MXSession+Riot.m
Riot/Generated/Strings.swift
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Rooms/RoomsDirectoryCoordinator.swift
Riot/Modules/Rooms/RoomsDirectoryCoordinatorBridgePresenter.swift
Riot/Modules/Rooms/RoomsDirectoryCoordinatorType.swift
Riot/Modules/Rooms/ShowDirectory/Cells/Network/DirectoryNetworkTableHeaderFooterView.xib
Riot/Modules/Rooms/ShowDirectory/Cells/Room/DirectoryRoomTableViewCell.swift
Riot/Modules/Rooms/ShowDirectory/Cells/Room/DirectoryRoomTableViewCell.xib
Riot/Modules/Rooms/ShowDirectory/Cells/Room/DirectoryRoomTableViewCellVM.swift
Riot/Modules/Rooms/ShowDirectory/PublicRoomsDirectoryViewModel.swift
Riot/Modules/Rooms/ShowDirectory/ShowDirectoryCoordinator.swift
Riot/Modules/Rooms/ShowDirectory/ShowDirectoryCoordinatorType.swift
Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewController.swift
Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewModel.swift
Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewModelType.swift
Riot/Modules/Rooms/ShowDirectory/ShowDirectoryViewState.swift

Rooms directory: Join room by alias or id

---

Riot/Categories/UIButton.swift
Riot/Modules/SideMenu/SideMenuActionView.swift
Riot/Modules/SideMenu/SideMenuActionView.xib
Riot/Modules/SideMenu/SideMenuVersionView.xib
Riot/Modules/SideMenu/SideMenuViewController.storyboard
Riot/Modules/SideMenu/SideMenuViewController.swift

Side menu: Support Dynamic Type

---

CHANGES.rst
RiotNSE/NotificationService.swift

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1133
Fix #3695

NSE: Fix Usage of Old Credentials

---

CHANGES.rst
Riot/Assets/Base.lproj/Main.storyboard

fixes https://github.com/vector-im/element-ios/issues/4449

enable extendedLayoutIncludesOpaqueBars on Home view in main storyboard

---

CHANGES.rst
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/SSO/SSOAuthenticationService.swift
Riot/SupportingFiles/Riot-Bridging-Header.h

SSO: Handle login callback URL with HTML entities

---

CHANGES.rst
RiotShareExtension/Modules/Fallback/FallbackViewController.m
RiotShareExtension/Modules/Share/Listing/RoomsListViewController.m
RiotShareExtension/Modules/Share/Listing/Views/RecentRoomTableViewCell.m
RiotShareExtension/Modules/Share/ShareViewController.m
RiotShareExtension/Modules/Share/ShareViewController.xib

Fixes #4486.
Is the colour of the view overlaid on the presenting app ok with the dark theme?

Fix theming in Share extension.

---

CHANGES.rst
Riot/Managers/Call/CallPresenter.swift

Fixes an issue where an ended call presented when doing an attended call transfer.

VoIP: Fix Call Transfer

---

CHANGES.rst
Riot/Modules/MediaPicker/MediaPickerViewController.m

Generate video thumbnails with the correct orientation.

---

Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinator.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorBridgePresenter.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinator.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinatorType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewAction.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewController.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModel.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModelType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewState.swift
Tools/Templates/buildable/SimpleScreenTemplate/SimpleScreenTemplateViewController.swift

Update template copyright date 

---

CHANGES.rst
Riot.xcodeproj/xcshareddata/xcschemes/Riot.xcscheme
Riot/Modules/TabBar/TabBarCoordinator.swift

it's easy for the back button to trigger a leftpanel reveal (#4438)

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Secrets/Recover/RecoverWithKey/SecretsRecoveryWithKeyViewController.swift
Riot/Modules/Secrets/Recover/RecoverWithPassphrase/SecretsRecoveryWithPassphraseViewController.swift

Show / hide reset button in secrets recovery screen (#4546).

---

CHANGES.rst
Riot/Modules/Room/RoomInfo/RoomInfoCoordinator.swift
Riot/Modules/Room/RoomInfo/RoomInfoCoordinatorBridgePresenter.swift
Riot/Modules/Room/RoomInfo/RoomInfoCoordinatorType.swift
Riot/Modules/Room/RoomViewController.m

Fixes #4583 -  broken user mentioning (settings -> members -> select a member -> mention)

Fixes #4583 - Mention user does not work

---

CHANGES.rst
Riot/Modules/Room/NotificationSettings/RoomNotificationsSettingsService.swift

Fix Crash when opening the new Room Notification Settings Screen

---

CHANGES.rst
Riot/Modules/Room/RoomViewController.m

Only set the voice message toolbar view on RoomInputToolbarView.

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/VoiceMessages/VoiceMessageToolbarView.swift

fix https://github.com/vector-im/element-ios/issues/4604, fix https://github.com/vector-im/element-ios/issues/4603, fix https://github.com/vector-im/element-ios/issues/4602, fix https://github.com/vector-im/element-ios/issues/4601

Release blockers for voice messages

---

Riot/Modules/Room/VoiceMessages/VoiceMessageMediaServiceProvider.swift

Inner PR for https://github.com/vector-im/element-ios/pull/4661

Fix Room Avatar

---

CHANGES.rst
Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
Riot/Modules/Room/VoiceMessages/VoiceMessageAudioConverter.swift
Riot/Modules/Room/VoiceMessages/VoiceMessageAudioRecorder.swift
Riot/Modules/Settings/SettingsViewController.m

* improved audio recording and conversion settings and voice message quality
* removed the setting from Labs and enabled them by default

Voice message audio quality

---

changelog.d/_template.md.jinja
changelog.d/pr-4689.build

Final part of vector-im/element-ios#4393
See the SDK [PR](https://github.com/matrix-org/matrix-ios-sdk/pull/1196) for more info.

Make Towncrier compatible with the release script

---

Riot/Assets/en.lproj/Vector.strings
changelog.d/4480.bugfix

fixed typo "adress" - fixes issue #4480

---

Riot/Modules/People/Views/InviteRecentTableViewCell.xib
RiotShareExtension/Modules/Share/Listing/Views/RecentRoomTableViewCell.m
RiotShareExtension/Modules/Share/Listing/Views/RecentRoomTableViewCell.xib
changelog.d/4698.bugfix

Fix crash when showing an invite in the People tab.

---

changelog.d/4726.bugfix
fastlane/Fastfile

Use AppVersion.xcconfig in Fastfile.

---

Riot/Modules/GlobalSearch/Rooms/DirectoryViewController.m
changelog.d/4778.bugfix

Fix joining public rooms

---

Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinator.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorBridgePresenter.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorParameters.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorProtocol.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinator.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinatorParameters.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinatorProtocol.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewController.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModel.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModelProtocol.swift
changelog.d/4792.misc

Templates: Add input parameters classes to coordinators

---

Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Common/Recents/RecentsViewController.h
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Home/HomeViewController.h
Riot/Modules/Home/HomeViewController.m
changelog.d/4797.change

Show animation instead of empty screen on app launch

---

Riot/Modules/Application/LegacyAppDelegate.h
Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Common/Recents/RecentsViewController.m
changelog.d/4801.bugfix

Wait for sync response when clearing cache

---

Riot/Managers/URLPreviews/Core Data/URLPreviewStore.swift
Riot/Utils/CoreDataHelper.swift

I missed a few comments on #4790 as I didn't realise GitHub hides unresolved comments in the "x more comments" section 🤦‍♂️
This addresses the 2 small ones, and I'll tackle the others in later PRs after release.

Resolves a couple of missed comments on URL previews

---

RiotSwiftUI/Modules/Common/Theme/ThemePublisher.swift
changelog.d/4835.bugfix

fixes https://github.com/vector-im/element-ios/issues/4835.

SwiftUI theme not set correctly after re-launch of the app.

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Settings/SettingsViewController.m
changelog.d/4828.change

Fixes #4828 🎉
The setting has it's own section, however after discussion with @niquewoodhouse today, we will look to reorganise the Settings in the future:

Enable URL Previews by default and remove from Labs.

---

Riot/Modules/Room/RoomViewController.m
changelog.d/4830.change

Using newly exposed room joining result types.

Fixes #4830 - Automatically dismissing invites for empty rooms after failing to join.

---

Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/VoiceMessages/VoiceMessageMediaServiceProvider.swift
changelog.d/47773.change

Add Pause/Resume support between rooms.

---

Riot/Categories/UITableView.swift
Riot/Modules/Common/Recents/RecentsViewController.m
changelog.d/4874.bugfix

RecentsViewController: Fix scroll crash

---

Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift

Voice message draft persistence

---

Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
changelog.d/4903.bugfix

Suggested Spaces appear as suggested rooms

---

Riot/Modules/SideMenu/SideMenuCoordinator.swift
Riot/Modules/Spaces/SpaceList/SpaceListCoordinator.swift
Riot/Modules/Spaces/SpaceList/SpaceListCoordinatorParameters.swift
Riot/Modules/Spaces/SpaceList/SpaceListViewModel.swift
changelog.d/4916.bugfix

fix https://github.com/vector-im/element-ios/issues/4916

Spaces still visible after logging in with another account #4916

---

Riot/Managers/PushNotification/PushNotificationService.m
changelog.d/4919.bugfix

fix https://github.com/vector-im/element-ios/issues/4919

App may not start in 1.6.0

---

Riot/Modules/Common/Avatar/AvatarViewData.swift
Riot/Modules/Common/Avatar/AvatarViewDataProtocol.swift
Riot/Modules/Room/Views/Avatar/RoomAvatarViewData.swift
Riot/Modules/User/Avatar/UserAvatarViewData.swift
changelog.d/4930.change

AvatarViewData: Make mediaManager optional

---

Riot/Modules/Spaces/SpaceList/SpaceListViewModel.swift

fix #4916
- fixed after AvatarViewData rework

Spaces still visible after logging in with another account

---

Podfile
Podfile.lock
changelog.d/4939.change

All minor bug fix updates, nothing exciting to report. Checked the follow and all fine:
- Sending and receiving voice messages
- FLEX
- Loading animation
- Views loaded through Reusable
Element part of #4939.

Update ffmpeg-kit-ios-audio, FLEX, FlowCommoniOS, Reusable and SwiftLint

---

RiotSwiftUI/Modules/Common/ViewFrameReader/FramePreferenceKey.swift
RiotSwiftUI/Modules/Common/ViewFrameReader/ViewFrameReader.swift
changelog.d/4974.change

Fixes #4974. Tested with the Chips view to ensure nothing has changed.

Add FramePreferenceKey for use in ViewFrameReader.

---

Riot/Managers/Settings/RiotSettings.swift

Set Show All Rooms to true by default

---

Riot/Modules/Spaces/SpaceList/SpaceListViewModel.swift
changelog.d/5082.bugfix

Fix a crash when selected space is not home and a clear cache or logout is performed

---

Riot/Modules/Settings/SettingsViewController.m
changelog.d/5090.change

Settings: Update about section footer text

---

Config/BuildSettings.swift
Config/CommonConfiguration.swift
Riot/Utils/Tools.m
changelog.d/4981.feature

depends on https://github.com/matrix-org/matrix-ios-sdk/pull/1279
resolves https://github.com/vector-im/element-ios/issues/4981

Add clientPermalinkBaseUrl and set in matrix-sdk options.

---

Config/BuildSettings.swift
changelog.d/5098.bugfix

Set correct default for clientPermalinkBaseUrl

---

.github/workflows/triage-move-unlabelled.yml
.github/workflows/triage-priority-bugs.yml
changelog.d/5153.misc

Move P1 issues to app and crypto team boards. Move unlabelled issues
without X-Needs-Info out of column on Triage board.

Update issue triage automation for P1 and need info

---

.github/workflows/triage-move-labelled.yml

Move X-Needs-Info on the triage board to needs info column
Design issues to Design team
Spaces to Delight
Voice messages to Voice message board
Threads to threads board
Fixes #5143
Covered by changelog entry 5153.misc

Add automation to move labelled issues

---

.github/workflows/triage-move-labelled.yml

Changelog covered by 5153.misc

Fix link to board in issue automation

---

Riot/Modules/Common/Recents/Service/MatrixSDK/RecentsListService.swift
changelog.d/5185.bugfix

Fix hidden rooms from showing.

---

Riot/Model/Room/RoomPreviewData.m
Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Authentication/Views/AuthInputsView.h
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Common/Recents/Model/RecentCellData.m
Riot/Modules/GlobalSearch/Files/CellData/FilesSearchCellData.m
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Settings/Security/SecurityViewController.m
Riot/Modules/TabBar/MasterTabBarController.m
changelog.d/5194.bugfix

Improve generated Swift header imports

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Utils/EventFormatter.m

Fix #5119
Will be based on `develop` after other thread PRs merged.

Removed Thread Root Event

---

.github/workflows/triage-move-labelled.yml

Covered by changelog entry 5235.misc

Issue workflows: quotes break validation

---

INSTALL.md
Podfile
README.md

Part of https://github.com/vector-im/element-ios/issues/5020

Remove MatrixKit references from Readme and install guide

---

fastlane/Fastfile

https://github.com/vector-im/element-ios/runs/4443336190?check_suite_focus=true#step:8:962

Run SwiftUI target unit tests on the CI.

---

Tools/SwiftGen/swiftgen-config.yml
changelog.d/5280.build

Fixes #5280 by using a single strings step with 2 actions.

Fix SwiftGen strings generation

---

.github/workflows/triage-move-labelled.yml
changelog.d/5285.misc

Remove issue automation for old Delight board

---

.github/workflows/triage-move-labelled.yml
changelog.d/5289.misc

Add automation to move Message Bubble issues to the project board

---

Podfile
Riot/Modules/Room/VoiceMessages/VoiceMessageAudioConverter.swift

Fixed ffmpeg-kit breaking changes after minor release, fixed version to 4.5.1

Fixed ffmpeg-kit breaking changes

---

Riot/Modules/Room/Views/BubbleCells/BaseBubbleCell/BubbleCellContentView.xib

Temporarily enable location sharing for design review purposes.
Based on https://github.com/vector-im/element-ios/pull/5320

Location sharing

---

Riot/Modules/Call/CallViewController.m
changelog.d/5375.bugfix

Fixes https://github.com/vector-im/element-ios/issues/5375
With https://github.com/matrix-org/matrix-ios-sdk/pull/1335

App: Fix DTMF

---

Riot/Modules/Analytics/Analytics.swift

Added to the doc comments for the `Analytics` class.

Add instructions for creating analytics events.

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

Just the strings for now so we can get ahead with Weblate (the rest to follow inc a changelog).

Add onboarding splash screen strings

---

Config/BuildSettings.swift
Riot/Modules/SideMenu/SideMenuViewModel.swift
changelog.d/5402.bugfix

Fixes https://github.com/vector-im/element-ios/issues/5402

Fix BuildSetting to hide "Invite Friends"

---

Config/BuildSettings.swift
Riot/Modules/Authentication/AuthenticationViewController.m
changelog.d/5404.bugfix

Add build setting to hide social login

---

.github/workflows/ci-build.yml
.github/workflows/ci-tests.yml
.github/workflows/release-alpha.yml
Config/BuildSettings.swift
Gemfile
Gemfile.lock
Podfile
Podfile.lock
Riot/Assets/Images.xcassets/Room/Location/location_marker_icon.imageset/Contents.json
Riot/Modules/Room/Location/LocationMarkerView.swift
Riot/Modules/Room/Location/LocationMarkerView.xib
Riot/Modules/Room/Location/RoomTimelineLocationView.swift
Riot/Modules/Room/Location/RoomTimelineLocationView.xib
Riot/Modules/Room/Views/BubbleCells/Location/LocationBubbleCell.swift
RiotSwiftUI/Modules/Room/LocationSharing/Coordinator/LocationSharingCoordinator.swift
RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingScreenState.swift
RiotSwiftUI/Modules/Room/LocationSharing/View/LocationSharingUserMarkerView.swift
changelog.d/5298.feature

- support rendering non-user locations
- offseting location markers so they actually point to the location
- removed cocoapods-keys and MapTiler key obfuscation

Static location sharing - part 2

---

Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Home/VersionCheck/HomeViewControllerWithBannerWrapperViewController.swift
changelog.d/5407.bugfix

Fix indefinite grey spinner on home view banner wrapper.

---

Riot/Modules/Common/Recents/RecentsViewController.m
changelog.d/5421.bugfix

Fix Tab Bar Badges

---

.github/ISSUE_TEMPLATE/bug.yml

See https://github.com/vector-im/element-android/pull/4963

Add case for local or non public homeserver.

---

Riot/Modules/Analytics/Analytics.swift

Small clarification around waiting to merge.

Update Analytics docs

---

Riot/target.yml
changelog.d/5048.i18n

Add Indonesian and Slovak languages.

---

Riot/Modules/Spaces/SpaceList/SpaceListViewCell.xib
changelog.d/5454.bugfix

Avatar view prevents to select space in space list

---

Riot/Modules/Spaces/SpaceDetail/SpaceDetailViewController.swift
changelog.d/5175.bugfix

Accepting a Space Invite has shouty button labels

---

Riot/Assets/Images.xcassets/Room/Actions/action_location.imageset/Contents.json
Riot/Assets/Images.xcassets/Room/Actions/action_poll.imageset/Contents.json
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Settings/SettingsViewController.m
changelog.d/5298.feature

Remove location sharing settings entry and enable it by default.

De-labs location sharing

---

Riot/Modules/Spaces/SpaceDetail/SpaceDetailViewModel.swift
changelog.d/5171.bugfix

fix https://github.com/vector-im/element-ios/issues/5171

joining a space seemed to noop

---

.github/workflows/release-alpha.yml
changelog.d/5491.build

Don't buld alpa release for non vector-im/element-ios repos

---

Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
Riot/Modules/Common/Recents/Model/RecentsSectionUpdate.swift
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Common/Recents/Service/MatrixSDK/RecentsListService.swift
Riot/Modules/Common/Recents/Service/Mock/MockRecentsListService.swift
Riot/Modules/Common/Recents/Service/RecentsListServiceDelegate.swift
changelog.d/5448.bugfix

Fixes #5448 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1356

HomeViewController: Fix empty sections

---

.github/workflows/release-alpha.yml
changelog.d/pr-5496.build

Fixes https://github.com/vector-im/element-ios/issues/5491

Only run job if secrets are available.

---

Riot/Managers/Theme/Theme.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift
Riot/Modules/GlobalSearch/Messages/DataSources/HomeMessagesSearchDataSource.m
Riot/Modules/Room/Search/DataSources/RoomSearchDataSource.m
changelog.d/5252.change

Display search matching pattern with a highlight color

---

Config/BuildSettings.swift
Riot/Model/HomeserverConfiguration/HomeserverConfiguration.swift
Riot/Model/HomeserverConfiguration/HomeserverConfigurationBuilder.swift
Riot/Model/HomeserverConfiguration/HomeserverTileServiceConfiguration.swift
Riot/Modules/Room/Location/RoomTimelineLocationView.swift
Riot/Modules/Room/RoomCoordinator.swift
Riot/Modules/Room/RoomViewController.h
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/BubbleCells/Location/LocationBubbleCell.swift
RiotSwiftUI/Modules/Room/LocationSharing/Coordinator/LocationSharingCoordinator.swift
RiotSwiftUI/Modules/Room/LocationSharing/Coordinator/ShareToMapsAppActivity.swift
RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingModels.swift
RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingScreenState.swift
RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingViewModel.swift
RiotSwiftUI/Modules/Room/LocationSharing/Test/Unit/LocationSharingViewModelTests.swift
RiotSwiftUI/Modules/Room/LocationSharing/View/LocationSharingView.swift
RiotTests/HomeserverConfigurationTests.swift
changelog.d/5298.feature

* converged on single external location sharing logic
* added .well-known configuration support for tile server and map styles.

Location sharing improvements

---

.github/workflows/triage-move-labelled.yml
changelog.d/5493.misc
changelog.d/5504.misc

Update automation for WTF and FTUE project boards

---

Riot/Modules/Room/DataSources/RoomDataSource.m
changelog.d/5263.bugfix

Avoid Thread Screen Blink

---

Riot/Modules/Room/Views/BubbleCells/RoomMembership/RoomMembershipCollapsedBubbleCell.m
changelog.d/pr-4148.change

Merged and rebased from https://github.com/vector-im/element-ios/pull/4148

Show target user avatars for collapsed membership changes

---

Riot/Assets/en.lproj/Vector.strings

Signed-off-by: Elsie Hupp <github@elsiehupp.com>
Fixes https://github.com/vector-im/element-ios/issues/5457.

Clarify "password" as "Matrix account password"

---

Riot/Modules/MatrixKit/Models/MXK3PID.m
changelog.d/3562.bugfix

Fixes duplication of issue #3562 in Authentication.
See https://github.com/matrix-org/matrix-ios-sdk/pull/1362

Fix phone number validation through custom URL

---

Riot/Modules/Common/Recents/DataSources/RecentsDataSource.h
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Common/SectionHeaders/SectionHeaderView.h
Riot/Modules/Common/SectionHeaders/SectionHeaderView.m
Riot/Modules/Contacts/ContactsTableViewController.m
Riot/Modules/Contacts/DataSources/ContactsDataSource.h
Riot/Modules/Contacts/DataSources/ContactsDataSource.m
Riot/Modules/GlobalSearch/DataSources/UnifiedSearchRecentsDataSource.m
Riot/Modules/MatrixKit/Controllers/MXKRecentListViewController.m
Riot/Modules/MatrixKit/Models/RoomList/MXKInterleavedRecentsDataSource.m
Riot/Modules/MatrixKit/Models/RoomList/MXKRecentsDataSource.h
Riot/Modules/MatrixKit/Models/RoomList/MXKRecentsDataSource.m
changelog.d/5537.bugfix

Home Screen: Fix Section & TabBar Badges

---

Riot/Modules/Application/LegacyAppDelegate.m
changelog.d/5559.bugfix

Fix for the green spinner not being dismissed with a local synapse.

---

Riot/Modules/Application/LegacyAppDelegate.m

Fix for clearing cache introduced in #5560.

Fix spinner when clearing cache.

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/MatrixKitStrings.swift
Riot/Generated/Strings.swift
Riot/Modules/MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
changelog.d/5346.bugfix

Fix #5346 
Replace "kick" and all derivative by "remove"

Replace "kick" by "remove" in all strings

---

Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
changelog.d/5582.change

Improve Opening Threads

---

Riot/Modules/Room/TimelineCells/Styles/Bubble/BubbleRoomCellLayoutUpdater.swift
Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/FileAttachment/Incoming/Common/MXKRoomIncomingAttachmentBubbleCell.m
Riot/Modules/Room/TimelineCells/Styles/RoomCellLayoutUpdating.swift

|||
|-|-|
| ![Simulator Screen Shot - iPhone 13 - 2022-02-18 at 15 59 57](https://user-images.githubusercontent.com/2205780/154708312-94e04c9a-cfd3-454c-be55-c8ac5b095e97.png) | ![Simulator Screen Shot - iPhone 13 - 2022-02-18 at 16 00 06](https://user-images.githubusercontent.com/2205780/154708290-2eb8442c-75ca-47bf-9127-9b6dc6e98191.png) |

Message bubbles: Fix incoming attachment leading margin

---

Riot/Modules/Room/MXKRoomViewController.m
changelog.d/5639.bugfix

Fix scrolling to the bottom of timeline when opening notification

---

Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
changelog.d/5552.bugfix

Fix color for thread fallback replies

---

Riot/Modules/TabBar/TabBarCoordinator.swift
changelog.d/5750.change

Resolves #5750
| Screens |
|---------|
| ![Simulator Screen Shot - iPhone 13 - 2022-03-04 at 16 48 13](https://user-images.githubusercontent.com/3922159/156805562-92cfeb5d-c727-40ab-8716-73812ce76edd.png) |
| ![Simulator Screen Shot - iPhone 13 - 2022-03-04 at 16 48 15](https://user-images.githubusercontent.com/3922159/156805567-b0264732-2058-4c2f-b43f-d0008c4439d0.png) |
| ![Simulator Screen Shot - iPhone 13 - 2022-03-04 at 16 48 16](https://user-images.githubusercontent.com/3922159/156805573-b872005e-feb9-485f-b513-1596adb2488f.png) |
| ![Simulator Screen Shot - iPhone 13 - 2022-03-04 at 16 48 18](https://user-images.githubusercontent.com/3922159/156805576-700ab30a-558b-4f8f-a2fe-b61bd14e8bcb.png) |

Use new activity indicators on all tabs

---

Riot/Utils/EventFormatter.m

Exclude redacted messages when considering which messages should be rendered.

Do not render redacted messages

---

Riot/Modules/Authentication/AuthenticationCoordinator.swift
Riot/Modules/Authentication/AuthenticationCoordinatorProtocol.swift
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Onboarding/OnboardingCoordinator.swift
changelog.d/5879.bugfix

Duplicate of #5793 as the hotfix branch ended up being based on `develop` after using GitHub's "rebase and merge" button.

Fix social button visibility during registration

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/RoomViewController.m
changelog.d/5807.change

Resolves #5807 and depends on https://github.com/matrix-org/matrix-ios-sdk/pull/1401
| Screenshot |
|-------------|
| ![Simulator Screen Shot - iPhone 13 - 2022-03-11 at 16 20 02](https://user-images.githubusercontent.com/3922159/157907401-1850f6aa-d364-40bd-8a07-4e584d83c5f9.png) |

Ignore the sender of a room invite without needing to join the room first

---

Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
changelog.d/5829.change

Fixes #5829 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1407

Fix replies to thread root events

---

Riot/Modules/Spaces/SpaceList/SpaceListViewModel.swift
changelog.d/5825.bugfix

Crash after leaving empty space and all rooms

---

Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Threads/ThreadsCoordinator.swift
changelog.d/5441.change

Thread Timeline Fixes

---

Riot/Modules/Contacts/Details/ContactDetailsViewController.m
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Riot/Modules/SplitView/SplitViewCoordinator.swift
changelog.d/5866.change

Allow ignoring invited users that have not joined a room yet

---

RiotSwiftUI/Modules/Room/UserSuggestion/UserSuggestionViewModel.swift
changelog.d/5058.bugfix

Steps to reproduce:
- Launch app
- Enter and leave a bunch of rooms
- Fire up the memory graph debugger
- Filter for `UserSuggestionViewModel`
Relates to: #5058
Signed-off-by: Johannes Marbach <johannesm@element.io>

Fix retain cycle in UserSuggestionViewModel

---

Riot/Modules/Spaces/SpaceList/SpaceListViewModel.swift
changelog.d/5134.bugfix

fix https://github.com/vector-im/element-ios/issues/5134

Sync space order with web #5134

---

Riot/Assets/en.lproj/Untranslated.strings
Riot/Generated/UntranslatedStrings.swift
Riot/Modules/SideMenu/SideMenuCoordinator.swift
changelog.d/5797.bugfix

Subspace error doesn't make sense

---

Riot/Managers/PushNotification/PushNotificationService.h
Riot/Managers/PushNotification/PushNotificationService.m
Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Application/ScreenNavigation/RoomNavigationParameters.swift
Riot/Modules/Application/ScreenNavigation/SpacePreviewNavigationParameters.swift
Riot/Modules/Spaces/SpaceDetail/SpaceDetailPresenter.swift
Riot/Modules/Spaces/SpaceDetail/SpaceDetailViewModel.swift
changelog.d/5915.bugfix

Can't view space invitations from system notifications

---

Riot/Modules/Spaces/SpaceRoomList/SpaceChildRoomDetail/SpaceChildRoomDetailViewModel.swift
changelog.d/5170.bugfix

Resolves https://github.com/vector-im/element-ios/issues/5170

Not possible to join an empty room on some suggested rooms

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Threads/Beta/ThreadsBetaCoordinator.swift
Riot/Modules/Threads/Beta/ThreadsBetaCoordinatorBridgePresenter.swift
Riot/Modules/Threads/Beta/ThreadsBetaCoordinatorProtocol.swift
Riot/Modules/Threads/Beta/ThreadsBetaViewController.storyboard
Riot/Modules/Threads/Beta/ThreadsBetaViewController.swift
changelog.d/5772.change

Threads opt-in screen

---

Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.h
Riot/Modules/Room/DataSources/RoomDataSource.m
changelog.d/5838.bugfix

Reload thread data source without notifying the screen

---

Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Home/HomeViewController.m
Riot/Modules/MatrixKit/Controllers/MXKRecentListViewController.h
Riot/Modules/MatrixKit/Controllers/MXKRecentListViewController.m
changelog.d/5992.bugfix

Room context preview dismissed unexpectedly

---

Config/BuildSettings.swift
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Common/PresenceIndicator/PresenceIndicatorView.swift
Riot/Modules/MatrixKit/Models/Account/MXKAccount.m
Riot/Modules/MatrixKit/Models/Account/MXKAccountData.h
Riot/Modules/MatrixKit/Models/Account/MXKAccountData.m
Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewModel.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/Views/RoomInfoBasicView.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/Views/RoomInfoBasicView.xib
Riot/Modules/Room/Views/Title/RoomTitleView.xib
Riot/Modules/Settings/SettingsViewController.m
RiotSwiftUI/Modules/Template/SimpleUserProfileExample/Service/MatrixSDK/TemplateUserProfileService.swift
changelog.d/5995.change

Closes #5995 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1436
https://user-images.githubusercontent.com/80891108/161988542-6cc9e44f-e3ec-467c-a050-ddcd963475f6.mov

Presence offline mode setting

---

RiotSwiftUI/Modules/Spaces/AddRoomSelector/View/AddRoomSelector.swift
RiotSwiftUI/Modules/Spaces/MatrixItemChooser/View/MatrixItemChooser.swift
changelog.d/5901.bugfix

Add button in create room dialog can be pressed multiple times

---

Config/BuildSettings.swift
changelog.d/pr-6020.misc

The PostHog staging server has been updated. This PR updates `BuildSettings` to point to the new one.

Update PostHog debug configuration.

---

Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Spaces/SpaceList/SpaceListItemViewData.swift
changelog.d/6023.bugfix

Fix some crashes

---

Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/ContextMenu/ContextMenuProviders/PublicRoomContextMenuProvider.swift
Riot/Modules/ContextMenu/ContextMenuProviders/RecentCellContextMenuProvider.swift
Riot/Modules/Room/DataSources/RoomPreviewDataSource.swift
Riot/Modules/Room/MXKRoomViewController.h
Riot/Modules/Room/MXKRoomViewController.m
Riot/Modules/Room/RoomViewController.h
Riot/Modules/Room/RoomViewController.m
changelog.d/6008.change

resolves https://github.com/vector-im/element-ios/issues/6008

Room preview on a long press should not update the read receipt

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/Threads/Beta/ThreadsBetaCoordinator.swift
Riot/Modules/Threads/Beta/ThreadsBetaCoordinatorBridgePresenter.swift
Riot/Modules/Threads/Beta/ThreadsBetaViewController.swift
changelog.d/6038.change

Threads discourage view

---

Riot/Modules/MatrixKit/Models/MXKAppSettings.m
Riot/Modules/Room/CellData/RoomBubbleCellData.h
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/RoomViewController.m
changelog.d/6057.wip

#6057 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1445

Location sharing: Support live location event in the timeline

---

Riot/Modules/Common/Recents/RecentsViewController.m
changelog.d/6076.bugfix

Fix room list search bar disappearing

---

Riot/Modules/Rooms/RoomsViewController.m
changelog.d/6086.bugfix

Fix crash when tabbar tapped for rooms

---

Config/BuildSettings.swift
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/Location/LocationMarkerView.xib
Riot/Modules/Room/Location/RoomTimelineLocationView.swift
Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/Location/LocationPlainCell.swift
changelog.d/6077.change

closes #6077 
Connect SDK to the timeline cell to handle live location cell with real data

[Location sharing] Connect SDK on timeline cell

---

Riot.xcodeproj/xcshareddata/xcschemes/Riot.xcscheme
Riot/Modules/Spaces/SpaceList/SpaceListViewModel.swift
Riot/Modules/Spaces/SpaceMembers/MemberList/SpaceMemberListViewController.swift
Riot/Modules/Spaces/SpaceRoomList/ExploreRoom/SpaceExploreRoomViewController.swift
Riot/Modules/TabBar/BreadcrumbView.swift
Riot/Modules/TabBar/MainTitleView.swift
Riot/Modules/TabBar/MasterTabBarController.m
changelog.d/5965.bugfix

resolves https://github.com/vector-im/element-ios/issues/5965
Note: UIStackView cannot be used in our case as it adds some constraints and the behaviour was not as expected for some corner cases.

Fail to open a sub space #5965

---

Riot/Modules/Common/Recents/RecentsViewController.m
changelog.d/6115.bugfix

Prevent crash when searching

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/CellData/RoomBubbleCellData.m
RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingModels.swift
RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingViewModel.swift
RiotSwiftUI/Modules/Room/LocationSharing/View/LocationSharingView.swift
RiotSwiftUI/Modules/Room/StaticLocationSharingViewer/Test/UI/StaticLocationViewingUITests.swift
changelog.d/6071.change

close #6071 
Add a action sheet to select timer for live location sharing

[Location sharing] Add timer selector 

---

.github/workflows/ci-ui-tests.yml
RiotSwiftUI/Modules/Authentication/ServerSelection/Test/UI/AuthenticationServerSelectionUITests.swift
RiotSwiftUI/Modules/Room/StaticLocationSharingViewer/Test/UI/StaticLocationViewingUITests.swift
fastlane/Fastfile

Fixes a small issue with #6048 along with minor tweaks to the GH action.

Fix UI tests action and Auth test.

---

Riot/Modules/Room/Location/RoomTimelineLocationView.swift
Riot/Modules/Room/TimelineCells/Styles/Plain/Cells/Location/LocationPlainCell.swift
changelog.d/6099.bugfix

6099: Fix bad interaction between static and live location cell

---

Riot/Modules/Room/CellData/RoomBubbleCellData.h
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/DataSources/RoomDataSource.m
changelog.d/6103.bugfix

close #6103 
Add listner to beaconInfoSummary update to handle timeline refresh after receive beacon from live location sharing

6103: Handle refreshing timeline with listner on beaconInfoSummary

---

Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewController.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewData.swift
Riot/Modules/Room/RoomInfo/RoomInfoList/RoomInfoListViewModel.swift
changelog.d/5725.change

Hide or disable search in the encrypted rooms

---

Riot/Categories/String.swift
Riot/Modules/MatrixKit/Categories/NSString+MatrixKit.swift
Riot/Modules/Room/RoomViewController.m
Riot/Utils/URLValidator.swift
RiotTests/String+Element.swift
RiotTests/URLValidatorTests.swift
changelog.d/6208.bugfix

Ask the user to confirm urls which contain unicode direction overrides

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/LocationSharing/UserLocationServiceProvider.swift
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Settings/SettingsViewController.m
RiotSwiftUI/Modules/Room/LocationSharing/Coordinator/LocationSharingCoordinator.swift
changelog.d/6195.change

[Location Sharing]: Add labbs flag for live location sharing - PSF-800

---

Riot/Categories/MXPreSharingStrategy.swift
Riot/Model/HomeserverConfiguration/HomeserverConfigurationBuilder.swift
Riot/Model/HomeserverConfiguration/HomeserverEncryptionConfiguration.swift
Riot/Model/WellKnown/VectorWellKnown.swift
Riot/Modules/Application/LegacyAppDelegate.m
RiotTests/HomeserverConfigurationTests.swift
changelog.d/6214.change

WellKnown: support outbound keys presharing strategy

---

.github/workflows/triage-move-labelled.yml
.github/workflows/triage-priority-bugs.yml

Removing the spaces issues to Delight board automation. The team's focus has shifted to new users journey and improving D1 retention

Remove spaces issues to delight board automation

---

Riot/Modules/Room/MXKRoomViewController.m
changelog.d/5746.change

Show user indicators when paginating a room

---

Riot/Modules/Room/CreationModal/RoomCreationEventsModal/RoomCreationEventsModalCoordinator.swift
Riot/Modules/Room/CreationModal/RoomCreationEventsModal/RoomCreationEventsModalViewModel.swift
Riot/Modules/Room/CreationModal/RoomCreationModalCoordinatorBridgePresenter.swift
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/TimelineCells/RoomCreationIntro/RoomCreationIntroCell.swift
Riot/Modules/Room/TimelineCells/RoomCreationIntro/RoomCreationIntroCellContentView.swift
changelog.d/5939.bugfix

resolves #5939 
- Displays room creation modal only if the user taps the room name
- Also fix empty room creation modal view

Room preview unexpectedly triggering within the room

---

Riot/Categories/UIScrollView.swift
Riot/Modules/CreateRoom/EnterNewRoomDetails/EnterNewRoomDetailsViewController.swift
changelog.d/6231.bugfix

Fix scroll to section crash

---

Riot/Modules/Room/RoomViewController.m
changelog.d/5989.bugfix

Add cancel action on context menu in every case

---

Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/TimelineCells/Styles/Bubble/BubbleRoomTimelineStyle.swift
Riot/Modules/Room/TimelineCells/Styles/Plain/PlainRoomTimelineStyle.swift
Riot/Modules/Room/TimelineCells/Styles/RoomTimelineStyle.swift
changelog.d/6242.bugfix

Avoid merging bubbles on bubbled timeline

---

Riot/Utils/EventFormatter.m
changelog.d/6293.bugfix

Do not show redacted reactions in the timeline

---

Riot/Utils/UniversalLink.m
changelog.d/6207.bugfix

Fix universal link for room invites

---

Riot/Modules/Room/RoomViewController.m
changelog.d/5584.bugfix

Update input actions on input toolbar refresh

---

Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Room/MXKRoomViewController.m
changelog.d/6271.bugfix

Fixes #6271 
Looks like this:
https://user-images.githubusercontent.com/3072286/173818156-ce0f73c7-90da-4644-9ff6-e8f593f1787a.mov

Present back pagination spinner faster and change wording

---

Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellData.m
Riot/Modules/MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h
Riot/Modules/Room/TimelineCells/RoomCreationIntro/RoomCreationIntroCell.swift
Riot/Modules/Room/TimelineCells/RoomCreationIntro/RoomCreationIntroCellContentView.swift
Riot/Modules/Room/TimelineCells/RoomCreationIntro/RoomCreationIntroViewData.swift
changelog.d/5731.bugfix

Fix room header invite button logic

---

Riot/Assets/third_party_licenses.html
Riot/Modules/Room/VoiceMessages/VoiceMessageAudioConverter.swift
Riot/target.yml
changelog.d/6263.change
project.yml

Reopens https://github.com/vector-im/element-ios/issues/6263

Revert "Replace ffmpeg with switf-ogg"

---

Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/LocationSharing/LocationManager.swift
Riot/Modules/LocationSharing/UserLocationServiceProvider.swift
changelog.d/6361.bugfix

No more app relaunch needed.
Fix #6361

Location sharing: Fix live location sharing lab flag activation

---

Riot/Modules/Contacts/ContactsTableViewController.m
Riot/Modules/Contacts/ContactsTableViewController.xib
Riot/Modules/Room/ParticipantsInviteModal/ContactsPicker/ContactsPickerViewModel.swift
changelog.d/5341.bugfix

Invite user UI is always hidden by the keyboard

---

Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
changelog.d/6371.bugfix

Display fallback when replied event content is partially missing

---

Riot/Modules/Common/SwiftUI/VectorHostingBottomSheetPreferences.swift
Riot/Modules/Common/SwiftUI/VectorHostingController.swift
changelog.d/6376.change

Enhance the VectorHostingController to be presented as a bottom sheet

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/Location/RoomTimelineLocationView.swift
RiotSwiftUI/Modules/Room/LiveLocationSharingViewer/View/LiveLocationListItem.swift
RiotSwiftUI/Modules/Room/LiveLocationSharingViewer/View/LiveLocationSharingViewer.swift
RiotSwiftUI/Modules/Room/LocationSharing/LocationSharingViewModel.swift
RiotSwiftUI/Modules/Room/LocationSharing/View/LocationSharingView.swift
changelog.d/6382.change

Location sharing: Live location sharing UI polishing

---

Riot/Modules/Pills/PillsFormatter.swift
Riot/Modules/Room/DataSources/RoomDataSource.swift
Riot/Modules/Room/MXKRoomViewController.h
Riot/Modules/Room/MXKRoomViewController.m
Riot/Modules/Room/RoomViewController.m
RiotTests/PillsFormatterTests.swift
changelog.d/6398.bugfix

Fixes #6398 
Also adds a nice replacer to make it possible to use "/ban", "/op", etc with a Pill.

Fix slash commands from room composer

---

.github/workflows/triage-move-labelled.yml

The design team would like to see all of their issues on their board for triage now

Update issue automation for the design team

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
RiotSwiftUI/Modules/Authentication/Common/AuthenticationServerInfoSection.swift
RiotSwiftUI/Modules/Authentication/Login/View/AuthenticationLoginScreen.swift
RiotSwiftUI/Modules/Authentication/Registration/View/AuthenticationRegistrationScreen.swift

Update a couple of strings in the FTUE auth flow. Changelog already covered by 6427.wip.
| Verify Email | Login |
| - | - |
| ![Screenshot 2022-07-20 at 8 51 39 am](https://user-images.githubusercontent.com/6060466/179928448-bc4d07fe-cae8-4180-b9e4-46f5a3f13cc5.png) | ![Screenshot 2022-07-20 at 8 51 15 am](https://user-images.githubusercontent.com/6060466/179928423-c13a65e1-2d7c-4c3f-9534-a549dce03ef1.png) |

Tweak strings for FTUE.

---

Config/BuildSettings.swift
changelog.d/5151.feature

This PR enables the new FTUE flow ready for the TF tomorrow 🥳

Enable authentication and personalisation flows.

---

Config/BuildSettings.swift
Riot/Model/HomeserverConfiguration/HomeserverConfigurationBuilder.swift
Riot/Modules/Room/RoomCoordinator.swift
RiotSwiftUI/Modules/Room/LiveLocationSharingViewer/Coordinator/LiveLocationSharingViewerCoordinator.swift
RiotSwiftUI/Modules/Room/LiveLocationSharingViewer/Test/Unit/LiveLocationSharingViewerViewModelTests.swift
RiotSwiftUI/Modules/Room/LocationSharing/Coordinator/LocationSharingCoordinator.swift
RiotSwiftUI/Modules/Room/StaticLocationSharingViewer/Coordinator/StaticLocationViewingCoordinator.swift
changelog.d/6472.feature

Signed-off-by: Johannes Marbach <johannesm@element.io>

Read tile server URL from .well-known (PSG-592)

---

Riot/Modules/Room/DataSources/RoomDataSource.m
changelog.d/6470.change

Handles https://github.com/vector-im/element-ios/issues/6470
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1534

Location sharing: Handle live location sharing delete (PSG-487)

---

Riot/Generated/Storyboards.swift

Apply missing Bundle renaming to SwiftGen generated files

Apply renamed bundle to SwiftGen generated files

---

changelog.d/6473.doc
docs/Customisation.md

The beginning of a document that explains where to begin when customising the app.

Add docs/Customisation.md.

---

RiotSwiftUI/Modules/Room/LiveLocationSharingViewer/View/LiveLocationSharingViewer.swift

Expected alignment: https://www.figma.com/file/uthEK6xuo9hSQRdWvPAre5/Location-Sharing
| Portrait | Landscape |
|-|-|
| ![IMG_0063](https://user-images.githubusercontent.com/2205780/182418287-e5808554-71fc-4de9-90eb-3aca4c3d7c10.PNG) | ![IMG_0064](https://user-images.githubusercontent.com/2205780/182418401-a727dcb1-4239-4344-b19a-71b014c030cd.PNG) |

Location sharing: Left align location ended banner content in expanded map

---

Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift
changelog.d/6529.change

Relates to: vector-im/element-ios#5415
Signed-off-by: Johannes Marbach <johannesm@element.io>

Increase max length of voice messages to 15m (PSG-662)

---

Riot/Managers/Widgets/WidgetManager.m
changelog.d/6539.bugfix

Fix unarchiving of the widget manager config.

---

Riot/Assets/en.lproj/InfoPlist.strings
Riot/SupportingFiles/Info.plist
changelog.d/6549.misc

Update the contacts permission string.

---

RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/Coordinator/SpaceSelectorBottomCoordinator.swift
RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/SpaceSelector/Coordinator/SpaceSelectorCoordinator.swift
RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/SpaceSelector/MockSpaceSelectorScreenState.swift
RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/SpaceSelector/SpaceSelectorModels.swift
RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/SpaceSelector/SpaceSelectorViewModel.swift
RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/SpaceSelector/SpaceSelectorViewModelProtocol.swift
RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/SpaceSelector/Test/Unit/SpaceSelectorViewModelTests.swift
RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/SpaceSelector/View/SpaceSelector.swift
changelog.d/6572.bugfix

App Layout: Cancel and Back on Spaces Bottom Sheet

---

Riot/Modules/Common/Recents/RecentsViewController.m
changelog.d/6568.change

|Before|After|
|---------|---------|
|<img width="1000px" src="https://user-images.githubusercontent.com/5855073/184525449-827c6f11-397b-447f-9842-c3c47eb548fb.png" />|<img width="1020px" src="https://user-images.githubusercontent.com/5855073/184525450-f8af9b72-ba44-4e99-8799-341f74cff70c.png" />|
Signed-off-by: Aaron Raimist <aaron@raim.ist>

Change text when swiping on room from Delete to Leave

---

Riot/Modules/Home/AllChats/AllChatsViewController.swift
changelog.d/6581.bugfix

App Layout: Leaving a Space now sends user to All Chats

---

Riot/Modules/Common/SectionHeaders/AllChatsFilterOptionListView.swift
Riot/Modules/Common/SectionHeaders/TabListView.swift
changelog.d/6605.change

App Layout: UI tweaks for Tabs

---

RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/Coordinator/SpaceSelectorBottomCoordinator.swift

App Layout: added space invites in space bottom sheet

---

Config/BuildSettings.swift
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/SettingsViewController.m
RiotSwiftUI/Modules/UserSessions/UserSessionsFlow/Coordinator/UserSessionsFlowCoordinator.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsFlow/Coordinator/UserSessionsFlowCoordinatorBridgePresenter.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Coordinator/UserSessionsOverviewCoordinator.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/MockUserSessionsOverviewScreenState.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/MatrixSDK/UserSessionsOverviewService.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/Mock/MockUserSessionsOverviewService.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Service/UserSessionsOverviewServiceProtocol.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Test/UI/UserSessionsOverviewUITests.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/Test/Unit/UserSessionsOverviewViewModelTests.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/UserSessionsOverviewModels.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/UserSessionsOverviewViewModel.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/UserSessionsOverviewViewModelProtocol.swift
RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionsOverview.swift
changelog.d/6585.wip

https://github.com/vector-im/element-ios/issues/6585

Device manager: Add new session management empty screen (PSG-675)

---

Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
changelog.d/6625.bugfix

App Layout: number of invites is limited to 10 in the All Chats screen

---

Riot/Modules/Common/Recents/Service/MatrixSDK/RecentsListService.swift
Riot/Modules/Home/AllChats/AllChatsLayoutSettingsManager.swift
changelog.d/6577.bugfix

app layout remove low priority rooms from filters

---

Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/ContextMenu/ContextMenuProviders/PublicRoomContextMenuProvider.swift
Riot/Modules/ContextMenu/ContextMenuProviders/RecentCellContextMenuProvider.swift
Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.h
Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSourceManager.h
Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSourceManager.m
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/DataSources/ThreadDataSource.swift
Riot/Modules/Room/MXKRoomViewController.m
Riot/Modules/Room/RoomCoordinator.swift
Riot/Modules/Room/RoomInfo/RoomInfoCoordinator.swift
Riot/Modules/Room/RoomViewController.m
Riot/Modules/SplitView/SplitViewCoordinator.swift
RiotTests/MatrixKitTests/MXKRoomDataSourceTests.swift
changelog.d/6628.bugfix

Fixes for thread notifications

---

Config/BuildSettings.swift
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Managers/Theme/Themes/BlackTheme.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift
Riot/Modules/Application/AppCoordinator.swift
Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
Riot/Modules/GlobalSearch/UnifiedSearchViewController.m
Riot/Modules/Home/HomeViewController.m
Riot/Modules/Room/MXKRoomViewController.m
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/TabBar/MasterTabBarController.m
Riot/Modules/TabBar/TabBarCoordinator.swift
changelog.d/6649.change

Added Labs flag for the new App Layout

---

Riot/Categories/UITextView.swift
Riot/Modules/MatrixKit/Views/MXKMessageTextView.m
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
RiotShareExtension/target.yml
changelog.d/6442.bugfix

Fix mention pills display on iOS 16

---

.github/workflows/triage-move-labelled.yml

The threads board has been closed and is now replaced by the Delight board

Remove threads board automation

---

Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
Riot/Modules/Common/Recents/Views/RecentsInvitesTableViewCell.swift
Riot/Modules/Common/Toasts/RoundedToastView.swift
Riot/Modules/Home/AllChats/AllChatsViewController.swift
Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithSimpleTextView.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/RoomViewController.xib
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
changelog.d/6645.bugfix

UI glitches in dark mode

---

Riot/Modules/Home/AllChats/AllChatsViewController.swift
changelog.d/6680.bugfix

Fixed last scrolling glitches in All Chats screen

---

Riot/Modules/Application/LegacyAppDelegate.m
changelog.d/6676.change

Reset allChatsOnboardingHasBeenDisplayed on logout

---

Config/BuildSettings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift
Riot/Modules/Application/AppCoordinator.swift
Riot/Modules/Application/LegacyAppDelegate.m
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/GlobalSearch/UnifiedSearchViewController.m
Riot/Modules/Home/AllChats/AllChatsViewController.swift
Riot/Modules/Home/HomeViewController.m
Riot/Modules/Room/MXKRoomViewController.m
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/SplitView/SplitViewCoordinator.swift
Riot/Modules/TabBar/MasterTabBarController.m
Riot/Modules/TabBar/TabBarCoordinator.swift
changelog.d/6673.change

Removed labs flag and enabled New App Layout

---

Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m
changelog.d/5864.feature
changelog.d/6689.bugfix

Fix composer expansion on Start DM

---

Riot/Modules/Room/RoomViewController.m
changelog.d/6691.bugfix

Remove the automatic invite on new message in a DM left by the direct user

---

changelog.d/6689.bugfix

Just update the changelog related to #6689

Update changelog related to #6689

---

Riot/Assets/en.lproj/Vector.strings

Signed-off-by: Germain Souquet <germains@element.io>

Fix typo in empty state

---

Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
changelog.d/6729.bugfix

Fix replied event content parsing for nested replies

---

Riot/Modules/Room/Attachements/MXKAttachmentsViewController.m
changelog.d/6717.bugfix

Avoid redundant media reloads

---

RiotSwiftUI/Modules/UserSessions/UserSessionOverview/MockUserSessionOverviewScreenState.swift

Tests are failing due to some missing parameters.

Fix failure building tests.

---

.github/workflows/triage-priority-bugs.yml

Column name has been updated, update automation to match

Fix issue automation

---

Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
Riot/Modules/Room/DataSources/RoomDataSource.m
changelog.d/6809.change

Adapt to [SDK changes](https://github.com/matrix-org/matrix-ios-sdk/pull/1600)

Incoming verification requests with Crypto V2

---

Riot/Modules/Room/MXKRoomViewController.m
Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
RiotSwiftUI/Modules/Room/Composer/View/Composer.swift

* Fixes animation for the composer resizing
* Fixes timeline scroll to bottom when resizing

Fix composer resizing animations

---

Config/BuildSettings.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/Mock/MockQRLoginService.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/QRLoginServiceProtocol.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Scan/AuthenticationQRLoginScanModels.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Scan/AuthenticationQRLoginScanViewModel.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Scan/MockAuthenticationQRLoginScanScreenState.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Scan/Test/UI/AuthenticationQRLoginScanUITests.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Scan/Test/Unit/AuthenticationQRLoginScanViewModelTests.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Scan/View/AuthenticationQRLoginScanScreen.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Start/AuthenticationQRLoginStartModels.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Start/AuthenticationQRLoginStartViewModel.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Start/MockAuthenticationQRLoginStartScreenState.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Start/Test/UI/AuthenticationQRLoginStartUITests.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Start/Test/Unit/AuthenticationQRLoginStartViewModelTests.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Start/View/AuthenticationQRLoginStartScreen.swift

- Adds a new build flag to distinguish QR login function availability according to the origin.
- Adds a new build flag to alter displaying QR functionality within this feature.
- Shows/hides display QR buttons on screens accordingly.

QR Login additional flags

---

Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
RiotSwiftUI/Modules/Room/Composer/View/FormattingToolbar.swift

Dark Mode Support for the WYSIWYG integration.
https://element-io.atlassian.net/jira/software/c/projects/PSU/boards/29?modal=detail&selectedIssue=PSU-854

WYSIWYG Dark Mode Support

---

Riot/Categories/UIViewController+RiotSearch.m
changelog.d/6762.bugfix

This is #6837, tidied up and targeting the hotfix branch.

Bugfix on hotfix branch: Element freezes after searching in a room #6762

---

RiotTests/Modules/Authentication/Mocks/MockAuthenticationRestClient.swift

Fix authentication tests.

---

Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Application/AppCoordinator.swift
Riot/Modules/TabBar/MasterTabBarController.m
Riot/Modules/TabBar/TabBarCoordinator.swift
changelog.d/6853.change

Tidy up TabBarCoordinator now that AllChatsCoordinator exists.

---

.github/ISSUE_TEMPLATE/enhancement.yml

Link to discussions for cross-platform and feature requests

Update enhancement issue template

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
RiotSwiftUI/Modules/Room/Composer/Model/ComposerModels.swift
RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
RiotSwiftUI/Modules/Room/Composer/View/FormattingToolbar.swift

WYSIWYG: Accessibility labels

---

Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
RiotSwiftUI/Modules/Room/Composer/View/Composer.swift

JIRA TICKETS:
https://element-io.atlassian.net/jira/software/c/projects/PSU/boards/29?modal=detail&selectedIssue=PSU-891
https://element-io.atlassian.net/jira/software/c/projects/PSU/boards/29?modal=detail&selectedIssue=PSU-884

WYSIWYG: Custom Tint + FIX blinking text when typing very fast in dark mode

---

Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
RiotSwiftUI/Modules/Room/Composer/Test/UI/ComposerUITests.swift
RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
project.yml

https://element-io.atlassian.net/jira/software/c/projects/PSU/boards/29?modal=detail&selectedIssue=PSU-898
https://user-images.githubusercontent.com/34335419/195830285-3344d5a6-65eb-4bc6-a174-7518b6f3400d.MP4

Send/Edit Button on WYSIWYG is disabled when there is no text instead of being hidden

---

Riot/Modules/Common/SwiftUI/VectorHostingBottomSheetPreferences.swift
RiotSwiftUI/Modules/Room/Composer/CreateActionList/Coordinator/ComposerCreateActionListCoordinator.swift
RiotSwiftUI/Modules/Room/Composer/CreateActionList/View/ComposerCreateActionList.swift

- Improved spacing
- Added handler
- Dimming
- Corner radius
-  ~~Implemented iOS 16 custom size detent (on iOS 15, medium will be used instead)~~
EDIT:
iOS 16 is not available yet on the CI, so the custom size detent can't be implemented yet, will have it on separate branch for when the Xcode version of the CI will be updated

wysiwyg bottom action sheet design improvements

---

Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h
Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
changelog.d/6897.bugfix
changelog.d/6900.bugfix

Rich Text Editor add support for interactive dismissal

---

Riot/Modules/Settings/SettingsViewController.m
changelog.d/6904.bugfix

closes https://github.com/vector-im/element-ios/issues/6904

Device Manger: Device client information not updated

---

Riot/Categories/UITextView.swift
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarTextView.swift
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.xib
changelog.d/6849.bugfix

**Ticket:** https://element-io.atlassian.net/browse/PSB-200
Fixes https://github.com/vector-im/element-ios/issues/6849

Fix text view height issue (PSB-200)

---

.github/workflows/triage-move-labelled.yml

Add issue automation for PS features teams

---

.github/workflows/triage-move-labelled.yml

Put only high priority issues in front of the design team, all of which the design team will aim to action to keep the queue at zero

Update issue automation for design

---

RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/MatrixSDK/VoiceBroadcastRecorderService.swift

Bug: The first chunk index was 2 instead of 1

Voice Broadcast - Fix the chunk sequence number index

---

Riot/Categories/MXRoom+Riot.m
RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift

Conform to related [SDK change](https://github.com/matrix-org/matrix-ios-sdk/pull/1618)

Curate MXCrypto protocol methods

---

RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/Coordinator/VoiceBroadcastPlaybackCoordinator.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Coordinator/VoiceBroadcastRecorderCoordinator.swift

Bug Fix : Crash if the room has avatar and voice broadcast tiles

---

RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/MatrixSDK/VoiceBroadcastRecorderService.swift

Currently go to "sleep mode" pauses the voice broadcast recording

Voice broadcast - Disable the sleep mode during the recording until we are able to handle it

---

.github/workflows/triage-move-labelled.yml

Add issue automation for the VoIP team

---

.github/workflows/triage-move-labelled.yml

Fix typo in issue automation

---

Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
RiotSwiftUI/Modules/Room/Composer/Test/UI/ComposerUITests.swift
RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
changelog.d/7005.bugfix
changelog.d/7006.bugfix
project.yml

Rich Text Composer: Fixing missing keystrokes + fixing long press backspace not deleting all the text

---

Riot/Modules/Room/RoomViewController.h
Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
RiotSwiftUI/Modules/Room/Composer/MockComposerScreenState.swift
RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
changelog.d/7025.bugfix

Synchronise composer and toolbar resizing animation duration

---

Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
RiotSwiftUI/Modules/Room/Composer/MockComposerScreenState.swift
RiotSwiftUI/Modules/Room/Composer/Model/ComposerViewState.swift
RiotSwiftUI/Modules/Room/Composer/Test/Unit/ComposerViewModelTests.swift
RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModel.swift
RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModelProtocol.swift
changelog.d/6946.bugfix

https://user-images.githubusercontent.com/34335419/199536206-c69b63be-eff6-4491-a61a-3a767de9bd1c.MP4

Labs: Rich text-editor fix for "does not support inserting custom iOS emojis"

---

.github/workflows/triage-move-labelled.yml

Stop using deprecated ProjectNext API in favour of the new ProjectV2 one

Update issue automation

---

.github/workflows/triage-review-requests.yml

Stop using deprecated ProjectNext API in favour of the new ProjectV2 one

Update PR automation

---

RiotSwiftUI/Modules/UserSessions/UserSessionsOverview/View/UserSessionListItem.swift
changelog.d/7035.bugfix

Device Manager: Session list item is not tappable everywhere

---

Riot/Modules/Room/RoomViewController.swift
changelog.d/6962.bugfix

Fixed IRC-style message and commands support in Rich text editor

---

Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
RiotSwiftUI/Modules/Room/Composer/MockComposerScreenState.swift
RiotSwiftUI/Modules/Room/Composer/Model/ComposerViewState.swift
changelog.d/7052.bugfix

Rich-text editor: Fix text formatting enabled inconsistent state

---

RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/MatrixSDK/VoiceBroadcastRecorderService.swift

Fix a crash when trying to start a VB record after playing at least one VB.

Fix AVAudioSession for Voice Broadcast Recording

---

RiotSwiftUI/Modules/Room/Composer/Test/Unit/ComposerViewModelTests.swift

Fix broken unit test for composer view model

Fix composer view model tests

---

Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
changelog.d/7124.bugfix
project.yml

https://user-images.githubusercontent.com/34335419/204587616-b5e3f4de-a06b-4e74-a962-b93321db4c12.MP4

Rich Text Editor: Fix for composer not resizing after a change of orientation

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Coordinator/VoiceBroadcastRecorderCoordinator.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/View/VoiceBroadcastRecorderView.swift
changelog.d/pr-7132.change

Prompt the user before ending a voice broadcast

Prompt the user before ending a voice broadcast

---

.github/workflows/triage-move-labelled.yml
.github/workflows/triage-review-requests.yml

"PN-" prefixed IDs are no longer working, update to new IDs

Update project board IDs for automation

---

Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Application/LegacyAppDelegate.m
changelog.d/7156.change

Turn on Threads for all users

---

RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/View/VoiceBroadcastRecorderView.swift
changelog.d/pr-7175.change

Update Voice Broadcast recorder cell by adjusting some padding values

Voice Broadcast: Update recorder cell layout

---

RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/View/VoiceBroadcastPlaybackView.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/View/VoiceBroadcastRecorderView.swift
changelog.d/pr-7178.change

Update live badge layout for recorder and player Voice Broadcast cells

VoiceBroadcast: Update live badge layout for recorder and player cells

---

Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastAggregator.swift

[Voice Broadcast] Add chunk after decrypting the event.

---

changelog.d/7182.change
fastlane/Fastfile

closes https://github.com/vector-im/element-ios/issues/7182

Update xcversion to 14.2

---

RiotSwiftUI/Modules/Spaces/SpaceSelectorBottomSheet/SpaceSelector/View/SpaceSelectorListRow.swift
changelog.d/6579.bugfix

App Layout: Space names in the bottom sheet should wrap to 1 line only

---

Riot/Modules/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
Riot/Modules/Room/RoomCoordinator.swift
changelog.d/7003.bugfix

This PR fixes the navigation of links in replies.
Fixes https://github.com/vector-im/element-ios/issues/7003

Fix navigation from replies

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

fix https://github.com/vector-im/element-ios/issues/7226

Remove "under active development“ sub-label from voice broadcast labs setting

---

Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/RoomViewController.swift
changelog.d/7232.bugfix

Signed-off-by: Nicolas Mauri <nicolasm@element.io>
Fix #7232

fixed a crash when a new DM room is created (#7232)

---

Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift

Signed-off-by: Nicolas Mauri <nicolasm@element.io>
Fix #7240 
I'm not sure if a changelog entry is relevant for this issue.

Fix temporary file deletion for a voice message (#7240)

---

Riot/Modules/VoiceBroadcast/VoiceBroadcastSDK/VoiceBroadcastAggregator.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/Coordinator/VoiceBroadcastPlaybackCoordinator.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/Coordinator/VoiceBroadcastPlaybackProvider.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/MatrixSDK/VoiceBroadcastPlaybackViewModel.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackModels.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackScreenState.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/VoiceBroadcastPlaybackViewModelProtocol.swift

Delete an existing broadcast (with the existing redact endpoint)

Delete an existing broadcast

---

Riot/Assets/de.lproj/Localizable.strings
Riot/Assets/de.lproj/Vector.strings
Riot/Assets/eo.lproj/InfoPlist.strings
Riot/Assets/eo.lproj/Vector.strings
Riot/Assets/et.lproj/Vector.strings
Riot/Assets/hu.lproj/Vector.strings
Riot/Assets/id.lproj/Localizable.strings
Riot/Assets/id.lproj/Vector.strings
Riot/Assets/it.lproj/Vector.strings
Riot/Assets/nl.lproj/Vector.strings
Riot/Assets/pt_BR.lproj/Vector.strings
Riot/Assets/ru.lproj/Vector.strings
Riot/Assets/sk.lproj/Vector.strings
Riot/Assets/sq.lproj/Vector.strings
Riot/Assets/th.lproj/Localizable.strings
Riot/Assets/uk.lproj/Vector.strings
Riot/Assets/zh_Hans.lproj/Vector.strings
Riot/Assets/zh_Hant.lproj/InfoPlist.strings
Riot/Assets/zh_Hant.lproj/Localizable.strings
Riot/Assets/zh_Hant.lproj/Vector.strings

This PR contains #7248, #7249, #7250 with fixes for placeholder errors.

Weblate (with fixes)

---

Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.h
Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
Riot/Modules/Room/RoomViewController.m
changelog.d/7261.bugfix

Fix how is resent a voice broadcast chunk

---

RiotSwiftUI/Modules/Room/PollHistory/MockPollHistoryScreenState.swift

Fix build error after the merge of https://github.com/vector-im/element-ios/pull/7268

Fix build error

---

Riot/Utils/EventFormatter.m

Unexpected live voice broadcast

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Application/AppCoordinator.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastPlayback/View/VoiceBroadcastPlaybackErrorView.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Coordinator/VoiceBroadcastRecorderCoordinator.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Coordinator/VoiceBroadcastRecorderProvider.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/MatrixSDK/VoiceBroadcastRecorderService.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/Service/VoiceBroadcastRecorderServiceProtocol.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/View/VoiceBroadcastRecorderConnectionErrorView.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/View/VoiceBroadcastRecorderView.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/VoiceBroadcastRecorderModels.swift
RiotSwiftUI/Modules/Room/VoiceBroadcastRecorder/VoiceBroadcastRecorderViewModel.swift
changelog.d/7229.change

Voice broadcast connection error handling while recording

---

Riot/Utils/Tools.m
changelog.d/6597.change

Hide the presence info if the presence status is unknown

---

.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/config.yml

Update issue template config

---

.github/ISSUE_TEMPLATE/bug.yml

Remove broken link in issue template

---

.github/workflows/triage-incoming.yml

Set up automation for new triage board

---

Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
changelog.d/3946.bugfix

Fix: incoming SAS transaction was accepted twice

---

Riot/Categories/MXBugReportRestClient+Riot.swift
Riot/Experiments/CryptoSDKFeature.swift
changelog.d/7457.change

Resolves https://github.com/vector-im/element-ios/issues/7457
Related SDK change https://github.com/matrix-org/matrix-ios-sdk/pull/1752

Display correct version of Crypto SDK

---

Config/BuildSettings.swift
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/SettingsViewController.m
changelog.d/7456.change

We now have an acceptable use policy instead of terms and conditions. This PR updates the Settings screen as such.
Fixes #7456.

Replace Ts&Cs with Acceptable Use Policy.

---

Riot/Modules/Room/RoomViewController.m
changelog.d/7530.bugfix

Fix application crashing when opening a thread with RTE enabled

---

Riot/Modules/Pills/PillTextAttachment.swift
changelog.d/7579.bugfix

Fix crashes when mentioning users without display names

---

Riot/Modules/Settings/SettingsViewController.m
changelog.d/7645.bugfix

Hide Add Email UI according to the 3 pid changes capability

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
RiotSwiftUI/Modules/UserSessions/Coordinator/UserSessionsFlowCoordinator.swift

fixes #7646
https://github.com/vector-im/element-ios/assets/34335419/d4fc0314-5599-422a-a804-020bdbb60495
https://github.com/vector-im/element-ios/assets/34335419/0ba8cd60-20bb-450f-bf65-89a17a27959e

Sign out through MAS redirect confirmation alerts

---

INSTALL.md

Quick documentation on how to run a local crypto rust sdk

Documentation to run local rust SDK

---

Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
Riot/Modules/Authentication/SSO/SSOAccountService.swift
Riot/Modules/Authentication/SSO/SSOAuthenticationPresenter.swift
Riot/Modules/Authentication/SSO/SSOAuthenticationService.swift
Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
Riot/Modules/Settings/SettingsViewController.m
RiotSwiftUI/Modules/UserSessions/Coordinator/UserSessionsFlowCoordinator.swift
changelog.d/7671.bugfix

Use ASWebAuthenticationSession to display OIDC account management URL

---

Riot/Modules/Rendezvous/RendezvousService.swift
RiotSwiftUI/Modules/Authentication/QRLogin/Common/Service/MatrixSDK/QRLoginService.swift

Add note about MSC3886, MSC3903 and MSC3906 being closed

---

README.md

Fix dead download button image link

---

.github/workflows/ci-tests.yml
.github/workflows/ci-ui-tests.yml

App version equivalent of https://github.com/matrix-org/matrix-ios-sdk/pull/1877

Use the codecov token.

---

Podfile
Podfile.lock
RiotSwiftUI/Modules/LocationSharing/LiveLocationSharingViewer/View/LiveLocationSharingViewer.swift

Removed  DSBottomSheet library

---

Riot/Assets/lv.lproj/InfoPlist.strings

Translations update from [Element Translations](https://translate.element.io) for [Element iOS/Element iOS (Dialogs)](https://translate.element.io/projects/riot-ios/riot-ios-dialogs/).
Current translation status:

Translations update from Element Translations
