Vector.xcodeproj/project.pbxproj
Vector/AppDelegate.h
Vector/AppDelegate.m
Vector/Assets/en.lproj/Vector.strings
Vector/Base.lproj/Main.storyboard
Vector/Utils/EventFormatter.m
Vector/Utils/VectorDesignValues.h
Vector/ViewController/RoomParticipantsViewController.m
Vector/ViewController/RoomSettingsViewController.h
Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/RoomViewController.m
Vector/ViewController/SegmentedViewController.h
Vector/ViewController/SegmentedViewController.m
Vector/ViewController/SegmentedViewController.xib
Vector/Views/RoomActivitiesView/RoomActivitiesView.m
Vector/Views/RoomTitle/RoomTitleViewWithTopic.h
Vector/Views/RoomTitle/RoomTitleViewWithTopic.m
Vector/Views/RoomTitle/RoomTitleViewWithTopic.xib

-> Add the vector segemented viewcontroller
-> Use it to manage the room details viewcontroller.

Room settings viewcontroller v2

---

Vector/ViewController/RecentsViewController.m

Add the gradient and the room creation button.

Room creation overlay

---

Vector/ViewController/RecentsViewController.m

Add the recents swipe menu to perform some dedicated actions.

Recents swipe actions2

---

Vector/Assets/en.lproj/Vector.strings
Vector/Model/RoomList/RecentsDataSource.h
Vector/Model/RoomList/RecentsDataSource.m
Vector/ViewController/RecentsViewController.m

Add the recents sections management.

Fav recents display

---

Vector/Model/Room/RoomDataSource.m
Vector/Model/RoomList/RecentsDataSource.m
Vector/ViewController/RecentsViewController.m
Vector/ViewController/RoomViewController.m
Vector/Views/RoomList/RecentTableViewCell.m

Table view cell are now defined at view controller level.
see https://github.com/matrix-org/matrix-ios-kit/pull/39

MXKDataSource refactoring

---

Vector/Views/RoomBubbleList/RoomOutgoingAttachmentBubbleCell.m
Vector/Views/RoomBubbleList/RoomOutgoingAttachmentWithPaginationTitleBubbleCell.m
Vector/Views/RoomBubbleList/RoomOutgoingAttachmentWithoutSenderInfoBubbleCell.m
Vector/Views/RoomBubbleList/RoomOutgoingTextMsgBubbleCell.m
Vector/Views/RoomBubbleList/RoomOutgoingTextMsgWithPaginationTitleBubbleCell.m
Vector/Views/RoomBubbleList/RoomOutgoingTextMsgWithoutSenderInfoBubbleCell.m

In vector applciation, the outgoing and the imcoming messages are displayed in the same screen side.

The read receipts are displayed for incoming messages.

---

Vector/ViewController/HomeViewController.m
Vector/ViewController/SegmentedViewController.h
Vector/ViewController/SegmentedViewController.m

These improvements (one per commit) helped to fix some issues:
- keyboard management in all child VCs of a segmentedVC
- blank screen when quitting the search in the home screen

Segmented VC improvement

---

Vector/Categories/MXRoom+Vector.h
Vector/Categories/MXRoom+Vector.m

-> fix a crash in the rule update observer

room_rules_deletion_issue

---

Vector/ViewController/HomeViewController.m
Vector/ViewController/SegmentedViewController.m

This fixes the room selection in master when playing when doing screen rotation with the splitVC.

SegmentedVC: Notify its child on viewWillAppear/viewDidAppear.

---

Vector.xcodeproj/project.pbxproj
Vector/Categories/UIViewController+VectorSearch.h
Vector/Categories/UIViewController+VectorSearch.m
Vector/Model/RoomList/HomeSearchCellData.h
Vector/Model/RoomList/HomeSearchCellData.m
Vector/ViewController/HomeSearchViewController.h
Vector/ViewController/HomeSearchViewController.m
Vector/ViewController/HomeViewController.m
Vector/ViewController/RoomViewController.h
Vector/ViewController/RoomViewController.m
Vector/ViewController/SegmentedViewController.m
Vector/Views/RoomList/HomeSearchTableViewCell.h
Vector/Views/RoomList/HomeSearchTableViewCell.m
Vector/Views/RoomList/HomeSearchTableViewCell.xib

Added messages search in HomeViewController and from the RoomViewController.
The two VCs use MXKSearchViewController from MatrixKit.
- The VC responsible for the search in a room reuses cellViews and cellDatas from the RoomViewController to display the results cells in its table view.
- The VC that makes search in all rooms has its own tableViewCells as they are specific to this page in the Vector design

Search api support

---

Vector.xcodeproj/project.pbxproj
Vector/Base.lproj/Main.storyboard
Vector/Model/Room/RoomSearchDataSource.h
Vector/Model/Room/RoomSearchDataSource.m
Vector/ViewController/RoomSearchViewController.h
Vector/ViewController/RoomSearchViewController.m
Vector/ViewController/RoomViewController.m

Added the screen for searching messages in a room

Room messages search

---

Vector/Model/Room/RoomDataSource.m

We hide here unsent buttons which is not present in Vector design.
TODO implement the right handling of unsent events.

Chat screen: Hide the unsent button.

---

Vector.xcodeproj/project.pbxproj
Vector/Assets/en.lproj/Vector.strings
Vector/Utils/VectorDesignValues.h
Vector/Utils/VectorDesignValues.m
Vector/ViewController/RoomViewController.h
Vector/ViewController/RoomViewController.m
Vector/ViewController/RoomViewController.xib
Vector/Views/RoomTitle/ExpandedRoomTitleView.h
Vector/Views/RoomTitle/ExpandedRoomTitleView.m
Vector/Views/RoomTitle/ExpandedRoomTitleView.xib
Vector/Views/RoomTitle/RoomAvatarTitleView.h
Vector/Views/RoomTitle/RoomAvatarTitleView.m
Vector/Views/RoomTitle/RoomAvatarTitleView.xib
Vector/Views/RoomTitle/RoomTitleView.h
Vector/Views/RoomTitle/RoomTitleView.m
Vector/Views/RoomTitle/RoomTitleView.xib

Add and handle expanded header on chat screen.

Chat expanded header

---

Vector/Utils/VectorDesignValues.h
Vector/Utils/VectorDesignValues.m
Vector/ViewController/AccountDetailsViewController.m
Vector/ViewController/AuthenticationViewController.m
Vector/ViewController/DirectoryViewController.m
Vector/ViewController/GlobalNotificationSettingsViewController.m
Vector/ViewController/HomeSearchViewController.m
Vector/ViewController/HomeViewController.m
Vector/ViewController/MediaAlbumContentViewController.m
Vector/ViewController/MediaPickerViewController.m
Vector/ViewController/RecentsViewController.m
Vector/ViewController/RoomCreationStep1ViewController.m
Vector/ViewController/RoomCreationStep2ViewController.m
Vector/ViewController/RoomParticipantsViewController.m
Vector/ViewController/RoomSearchViewController.m
Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/RoomViewController.m
Vector/ViewController/SegmentedViewController.m
Vector/ViewController/SettingsViewController.m

Rageshake doesn't work on the image upload screen #80
- Define the navigation bar tint color.
- Disable navigation bar tint color change according to HS status.
- Set RageShake manager.

issue_80: Rageshake handling

---

Vector/AppDelegate.m
Vector/ViewController/RoomViewController.m

Please can we have default ios long-tap to select and clipboard behaviour again?

BugFix: vector-ios #87

---

Vector/ViewController/RoomParticipantsViewController.m
Vector/ViewController/RoomViewController.m

Changes due to https://github.com/matrix-org/matrix-ios-sdk/pull/78

Update to support MXEventTimeline

---

Vector/ViewController/MediaPickerViewController.m

issue #113
Retrieve user's album on a specific processing queue

Image Picker: Launch must be speed up

---

Vector/AppDelegate.m
Vector/Vector-Defaults.plist

The push gateway url is now configurable.

---

Vector/Views/Authentication/AuthInputsView.m
Vector/Views/Authentication/AuthInputsView.xib

- Check first the validity of the parameters.
- Check the availability of the user id.
- Handle then the registration stages

Registration support: Finalize implementation

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/SettingsViewController.h
Vector/ViewController/SettingsViewController.m

In the settingsVC, list linked emails and add a button to bind new email to the user account.

Email bind

---

Vector/Assets/en.lproj/Vector.strings
Vector/Views/RoomInputToolbar/RoomInputToolbarView.m

He will be able to select Voice or Video Call

VoIP: Show an action sheet when the user clicks on the call button

---

Vector.xcodeproj/project.pbxproj
Vector/Assets/en.lproj/Vector.strings
Vector/Utils/VectorDesignValues.h
Vector/Utils/VectorDesignValues.m
Vector/ViewController/RoomMemberDetailsViewController.m
Vector/ViewController/RoomParticipantsViewController.h
Vector/ViewController/RoomParticipantsViewController.m
Vector/ViewController/RoomParticipantsViewController.xib
Vector/Views/Contact/ContactTableViewCell.h
Vector/Views/Contact/ContactTableViewCell.m
Vector/Views/Contact/ContactTableViewCell.xib
Vector/Views/RoomInputToolbar/RoomInputToolbarView.m
Vector/Views/RoomList/RecentTableViewCell.m

Fix Room members: Add a specific section INVITED

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomParticipantsViewController.h
Vector/ViewController/RoomParticipantsViewController.m

https://github.com/vector-im/vector-ios/issues/154

Room members: Support search option

---

Vector/Model/Contact/Contact.h
Vector/Model/Contact/Contact.m
Vector/ViewController/RoomParticipantsViewController.h
Vector/ViewController/RoomParticipantsViewController.m

https://github.com/vector-im/vector-ios/issues/181

Fix Room details opening is delayed

---

Vector/ViewController/RoomViewController.m

https://github.com/vector-im/vector-ios/issues/227

Bug Fix Room Preview: the navigation bar bottom border is visible.

---

Vector/ViewController/HomeViewController.m
Vector/ViewController/RoomViewController.h
Vector/ViewController/RoomViewController.m

https://github.com/vector-im/vector-ios/issues/229

Chat Screen: Expand header on new created room.

---

Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/RoomViewController.h
Vector/ViewController/RoomViewController.m
Vector/ViewController/RoomViewController.xib
Vector/Views/RoomTitle/ExpandedRoomTitleView.m
Vector/Views/RoomTitle/PreviewRoomTitleView.h
Vector/Views/RoomTitle/PreviewRoomTitleView.m
Vector/Views/RoomTitle/PreviewRoomTitleView.xib

- add topic in preview header
- remove new line characters in topic string
- collapse expander header when user scrolls it down.

Chat Screen: Improve Room header

---

Vector/AppDelegate.m
Vector/ViewController/HomeViewController.m
Vector/ViewController/SegmentedViewController.h
Vector/ViewController/SegmentedViewController.m

Improved UX: Display a loading wheel while the app is gathering information from the hs about the universal link

Show a loading wheel on universal link

---

Vector/ViewController/AuthenticationViewController.m
Vector/Views/Authentication/AuthInputsView.m

Bug Fix: https://github.com/vector-im/vector-ios/issues/240

Authentication: Fix registration cancellation

---

Vector/AppDelegate.m
Vector/ViewController/AuthenticationViewController.h
Vector/ViewController/AuthenticationViewController.m
Vector/ViewController/HomeViewController.h
Vector/ViewController/HomeViewController.m

Do something when the user clicks on the link in the email validation email.
The something is WIP.

Universal link + next_link

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/HomeViewController.m

A popup is shown if the user presses the create room buttom while a creation is already in progress.

Fixed the UX issue in https://github.com/vector-im/vector-ios/issues/249

---

Vector/AppDelegate.m

TODO: Display user friendly message in case of error.

Universal link: Manage email validation link as universal link

---

Vector/ViewController/HomeViewController.m

https://github.com/vector-im/vector-ios/issues/249

Bug Fix - Messages: Room creation button does not respond.

---

Vector/ViewController/RoomViewController.m

https://github.com/vector-im/vector-ios/issues/243

Bug Fix: Room avatar is missing at room creation

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomViewController.m

https://github.com/vector-im/vector-ios/issues/225

#225: Ability to copy message permalinks

---

Vector/AppDelegate.m
Vector/Model/Room/RoomPreviewData.h
Vector/ViewController/RoomViewController.m

https://github.com/vector-im/vector-ios/issues/246

Fixed #246: universal link on an unjoined room + an event iD is not properly managed

---

Vector/ViewController/MediaPickerViewController.m

https://github.com/vector-im/vector-ios/issues/208

BugFix: Media Picker: user's albums are missing

---

Vector/ViewController/RoomViewController.m

https://github.com/vector-im/vector-ios/issues/268

BugFix: 6+/iPad: Better manage user with no room in landscape

---

Vector/AppDelegate.m

https://github.com/vector-im/vector-ios/issues/320

Crash when the ?, the punctuation mark, is considered as part of a link

---

Vector/ViewController/RoomViewController.m
Vector/Views/RoomBubbleList/RoomIncomingAttachmentBubbleCell.xib
Vector/Views/RoomBubbleList/RoomIncomingAttachmentWithPaginationTitleBubbleCell.xib
Vector/Views/RoomBubbleList/RoomIncomingTextMsgBubbleCell.xib
Vector/Views/RoomBubbleList/RoomIncomingTextMsgWithPaginationTitleBubbleCell.xib
Vector/Views/RoomBubbleList/RoomOutgoingAttachmentBubbleCell.xib
Vector/Views/RoomBubbleList/RoomOutgoingAttachmentWithPaginationTitleBubbleCell.xib
Vector/Views/RoomBubbleList/RoomOutgoingTextMsgBubbleCell.xib
Vector/Views/RoomBubbleList/RoomOutgoingTextMsgWithPaginationTitleBubbleCell.xib

https://github.com/vector-im/vector-ios/issues/309

BugFix: It's too hard to press names to auto-insert nicks.

---

Vector/Utils/EventFormatter.m
Vector/Utils/VectorDesignValues.h
Vector/Utils/VectorDesignValues.m
Vector/ViewController/RoomMemberDetailsViewController.m
Vector/Views/RoomActivitiesView/RoomActivitiesView.m
Vector/Views/RoomBubbleList/RoomOutgoingAttachmentBubbleCell.m
Vector/Views/RoomList/RecentTableViewCell.h
Vector/Views/RoomList/RecentTableViewCell.m
Vector/Views/RoomList/RecentTableViewCell.xib

https://github.com/vector-im/vector-ios/issues/290

BugFix - Messages: missed notifs and unread msgs in the room list

---

Vector/ViewController/SegmentedViewController.m

Remove use of deprecated API: addConstraint/removeConstraint

Code cleaning

---

Vector/AppDelegate.h
Vector/AppDelegate.m
Vector/ViewController/RecentsViewController.m
Vector/ViewController/RoomParticipantsViewController.m
Vector/ViewController/RoomSearchViewController.m
Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/RoomViewController.m
Vector/ViewController/SettingsViewController.m

https://github.com/vector-im/vector-ios/issues/289
https://github.com/vector-im/vector-ios/issues/125

BugFix: Tap on clock status bar should scroll you up

---

Vector/AppDelegate.m
Vector/Assets/en.lproj/Vector.strings

Handle missing VoIP better 

---

Vector/ViewController/RoomViewController.h
Vector/ViewController/RoomViewController.m
Vector/ViewController/RoomViewController.xib
Vector/Views/RoomTitle/PreviewRoomTitleView.h
Vector/Views/RoomTitle/PreviewRoomTitleView.m
Vector/Views/RoomTitle/PreviewRoomTitleView.xib
Vector/Views/RoomTitle/RoomTitleView.h
Vector/Views/RoomTitle/RoomTitleView.xib

Hide room avatar in landscape orientation

Preview header landscape

---

Vector/AppDelegate.m
Vector/Model/Room/RoomPreviewData.h
Vector/Model/Room/RoomPreviewData.m
Vector/ViewController/HomeViewController.m
Vector/ViewController/RoomSearchViewController.m
Vector/Views/RoomTitle/PreviewRoomTitleView.m

RoomPreviewData provides now roomDataSource.
It can be used to preview the room history. This will be done in another PR.

Room history preview

---

Vector/Assets/en.lproj/Vector.strings
Vector/Model/Room/RoomPreviewData.m
Vector/ViewController/HomeViewController.m
Vector/ViewController/RoomViewController.h
Vector/ViewController/RoomViewController.m
Vector/Views/RoomTitle/PreviewRoomTitleView.h
Vector/Views/RoomTitle/PreviewRoomTitleView.m
Vector/Views/RoomTitle/PreviewRoomTitleView.xib
Vector/Views/RoomTitle/RoomTitleView.h
Vector/Views/RoomTitle/RoomTitleView.m

- Update preview header handling.

Room peeking support

---

Vector/ViewController/RoomParticipantsViewController.h
Vector/ViewController/RoomParticipantsViewController.m
Vector/ViewController/RoomViewController.m

- list only the contacts who has the search pattern as prefix

Room Participants: improve invitable contacts list

---

Vector/ViewController/MediaPickerViewController.m
Vector/Views/RoomInputToolbar/RoomInputToolbarView.m

https://github.com/vector-im/vector-ios/issues/373

Bug Fix Media Picker: move the camera roll at the top of the folders

---

Vector.xcodeproj/project.pbxproj
Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomSettingsViewController.m
Vector/Views/TableViewCell/TableViewCellWithSwitches.h
Vector/Views/TableViewCell/TableViewCellWithSwitches.m
Vector/Views/TableViewCell/TableViewCellWithSwitches.xib

https://github.com/vector-im/vector-ios/issues/218

Bug Fix - Room Settings: Add favourite/low prio toggle in room settings

---

Vector/Views/RoomList/InviteRecentTableViewCell.h
Vector/Views/RoomList/InviteRecentTableViewCell.m
Vector/Views/RoomList/InviteRecentTableViewCell.xib

https://github.com/vector-im/vector-ios/issues/426

Messages: Add pink red badge on each invitation

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomSettingsViewController.m

https://github.com/vector-im/vector-ios/issues/417

Enhancement: Add 'leave' button to room settings

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/SettingsViewController.m

We should show a list of ignored users in user settings somewhere

---

Vector/AppDelegate.h
Vector/AppDelegate.m
Vector/ViewController/RoomViewController.m

Remove KVO handling on [AppDelegate isOffline] by introducing a new notification kAppDelegateNetworkStatusDidChangeNotification.
#489

Bug Fix - Crash in [AppDelegate applicationDidBecomeActive:]

---

Vector/Base.lproj/Main.storyboard
Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/SettingsViewController.m

Update the section header label style and layout.
Before: ![bef](https://matrix.org/_matrix/media/v1/download/matrix.org/PpqgwmzDOdPunVPaVXJmErZi)
After: ![after](https://matrix.org/_matrix/media/v1/download/matrix.org/gVJxPwuWRlCdRFioukmnAzvQ)

Settings: Adjust the section header display.

---

Vector/ViewController/RoomViewController.m
Vector/Views/RoomActivitiesView/RoomActivitiesView.m

Bug Fix - Chat screen: tapping resend now does nothing

---

Vector/AppDelegate.m

Bug Fix - Profile changes shouldn't reorder the room list

---

Vector/ViewController/RoomSettingsViewController.h
Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/RoomViewController.m

Bug Fix - Expanded header: Add shortcuts on avatar and room name

---

Vector/ViewController/RoomSettingsViewController.m

Bug Fix - Room Settings: tap on existing room address is ignored

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomSettingsViewController.m

Bug Fix - Room Settings: Ability to copy permalinks for rooms and msgs

---

Vector/Base.lproj/Main.storyboard
Vector/Model/Room/RoomDataSource.m
Vector/ViewController/RoomViewController.m

#442 
Note: we do nothing on event ids because we cannot know the room they belong to.

hyperlink mxids and room aliases

---

Vector/AppDelegate.h
Vector/AppDelegate.m
Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/SettingsViewController.m

Settings: Add 'mark all as read' option

---

Vector/AppDelegate.m
Vector/Utils/Tools.m
Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/RoomViewController.m

Intercept matrix.to URLs within the app

---

Vector/ViewController/RoomViewController.m

Bug Fix - We should put an unread room count next to the back button

---

Vector/Categories/UIViewController+VectorSearch.m

https://github.com/vector-im/vector-ios/issues/440

BF: on iPad, after you use room search, there's no way to leave the search view

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomViewController.m

This PR fixes 2 issues:
- Context menu should have option to quote a message #502
- Chat screen: Add "view source" option on the selected event #459

Improve event edit menu

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomViewController.m
Vector/Views/RoomActivitiesView/RoomActivitiesView.h
Vector/Views/RoomActivitiesView/RoomActivitiesView.m
Vector/Views/RoomActivitiesView/RoomActivitiesView.xib

Let users join confs as voice or video

---

Vector.xcodeproj/project.pbxproj
Vector/Assets/en.lproj/Vector.strings
Vector/Base.lproj/Main.storyboard
Vector/ViewController/HomeViewController.m
Vector/ViewController/StartChatViewController.h
Vector/ViewController/StartChatViewController.m
Vector/ViewController/StartChatViewController.xib

#529
Prompt user to let him choose betwwen:
- Start chat by selecting people
or
- Create a new empty room

Enhancement: Improve room creation process

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomParticipantsViewController.m
Vector/ViewController/SettingsViewController.m
Vector/ViewController/StartChatViewController.m

Warn explicitly that your addressbook's emails are uploaded for discovering matrix IDs if you enable that permission

---

Vector/Categories/MXRoom+Vector.m
Vector/Model/Contact/Contact.m
Vector/Model/Room/RoomBubbleCellData.m
Vector/Model/Room/RoomDataSource.m
Vector/Utils/AvatarGenerator.h
Vector/Utils/AvatarGenerator.m
Vector/ViewController/CallViewController.h
Vector/ViewController/CallViewController.m
Vector/ViewController/CallViewController.xib
Vector/ViewController/ContactDetailsViewController.m
Vector/ViewController/RoomMemberDetailsViewController.m
Vector/ViewController/RoomViewController.m
Vector/ViewController/SettingsViewController.m
Vector/Views/Contact/ContactTableViewCell.m
Vector/Views/RoomList/PublicRoomTableViewCell.m

Bug Fix: Screen when placing a voip call can be incredibly ugly

---

Vector.xcodeproj/project.pbxproj
Vector/Assets/InfoPlist.strings

iOS10: App crashes when it wants to access user's data (Photos, Contacts, Camera, Mic)

---

Vector/ViewController/ContactDetailsViewController.m
Vector/ViewController/ContactPickerViewController.m

The user is now able to file an email or a matrix id in contact picker

People tab: support email and matrix id selection.

---

Vector/Views/RoomInputToolbar/RoomInputToolbarView.m
Vector/Views/RoomInputToolbar/RoomInputToolbarView.xib

Bug Fix - Chat screen: Hang up icon overlap the send button

---

Vector/ViewController/ContactDetailsViewController.h
Vector/ViewController/ContactDetailsViewController.m
Vector/ViewController/ContactDetailsViewController.xib
Vector/ViewController/RoomMemberDetailsViewController.h
Vector/ViewController/RoomMemberDetailsViewController.m
Vector/ViewController/RoomMemberDetailsViewController.xib

#517 
Did it on contacts details screen too

Tap on avatar in Member Info page to zoom to view avatar full page

---

Vector/ViewController/RoomViewController.m

Quoting a msg overrides what I already typed

---

Vector/Model/Room/RoomBubbleCellData.m

Bug Fix - Crash due to a race condition in read receipts management

---

Vector/Model/Room/RoomBubbleCellData.m
Vector/Model/Room/RoomSearchDataSource.m

Room message search : the search pattern is not highlighted in results

---

Vector.xcodeproj/project.pbxproj
Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomFilesSearchViewController.m
Vector/ViewController/RoomFilesViewController.h
Vector/ViewController/RoomFilesViewController.m
Vector/ViewController/RoomViewController.m
Vector/Views/Search/FilesSearchTableViewCell.m
Vector/Views/Search/FilesSearchTableViewCell.xib

Display now the index of room files

Room Details: Add 'Files' tab

---

Vector/AppDelegate.h
Vector/AppDelegate.m
Vector/ViewController/ContactDetailsViewController.m
Vector/ViewController/StartChatViewController.m

#715
Ensure 1:1 rooms are created with equal ops on both sides (the trusted_private_chat preset)

Feature - Converting existing rooms to/from DMs

---

Vector/Views/RoomInputToolbar/RoomInputToolbarView.m

#723
- Disable attachments and call options in encrypted room

End-to-end encryption UI/UX

---

Vector/Views/RoomInputToolbar/RoomInputToolbarView.m

Attachments will be sent encrypted with the corresponding
matrixkit / matrix-ios-sdk branches (https://github.com/matrix-org/matrix-ios-kit/pull/189 / https://github.com/matrix-org/matrix-ios-sdk/pull/164)

Don't disable the upload button in encrypted rooms

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomViewController.m
Vector/Views/RoomInputToolbar/RoomInputToolbarView.m

voip in group chat room is not supported.

Crypto: Enable voip in encrypted 1:1 room

---

Vector/Info.plist
Vector/Views/RoomBubbleList/Encryption/RoomEncryptedDataBubbleCell.m

* Fix padlocks on text messages
* Remove ITSAppUsesNonExemptEncryption

Backport fixes from e2e_release branch

---

Vector/ViewController/RoomViewController.m

Crypto: Do not allow to redact the event that enabled encryption in a room

---

Vector.xcodeproj/project.pbxproj
Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/SettingsViewController.h
Vector/ViewController/SettingsViewController.m
Vector/Views/DeviceView/DeviceView.h
Vector/Views/DeviceView/DeviceView.m
Vector/Views/DeviceView/DeviceView.xib

- support the device deletion.
- support the device renaming.

User Settings: List user's devices

---

Vector/AppDelegate.h
Vector/AppDelegate.m
Vector/ViewController/RoomViewController.m

Bug Fix - Voip : decline call when room opened freeze riot

---

Vector/Model/Room/RoomPreviewData.m
Vector/Model/RoomList/RecentsDataSource.m
Vector/Views/RoomList/RoomTableViewCell.m

Bug Fix -Wrong room name of a direct chat in user's profile

---

Vector/Model/RoomList/RecentsDataSource.m

`[__NSArrayM objectAtIndex:]: index 18446744073709551615 beyond bounds for empty array`

Bug Fix - App crashes on recents refresh

---

Vector/ViewController/RoomMemberDetailsViewController.m
Vector/ViewController/SettingsViewController.m
Vector/Views/RoomBubbleList/Encryption/RoomEncryptedDataBubbleCell.m

Changes related to matrix-org/matrix-ios-sdk#204

Crypto threading: Follow changes in the sdk

---

Vector/ViewController/RoomViewController.m
Vector/Views/RoomBubbleList/RoomOutgoingAttachmentBubbleCell.m
Vector/Views/Search/FilesSearchTableViewCell.m

- Apply the MatrixKit changes in the `MXKAttachment` class

Outgoing Messages Refactoring:

---

Vector/ViewController/StartChatViewController.m

#887
- Improve the contact search in the 'Start Chat' screen.
- TODO: Report this changes in 'Room Settings' to add new members, and in 'People Search' screen.

Bug Fix - Performance on searching people when inviting is terrible.

---

Vector/ViewController/ContactsTableViewController.m
Vector/ViewController/HomeViewController.m

#904.
Remove a contact from the "Known Contacts" section if a local contact matches with his Matrix identifier.

Improve the people invite screens

---

Vector/ViewController/RoomFilesViewController.m

Bug Fix: Hit File tab from room details view make Riot crash

---

Vector/ViewController/RoomViewController.m

Bug Fix: Crash on Create a room button

---

Vector/AppDelegate.m
Vector/ViewController/HomeViewController.m

Depends on https://github.com/matrix-org/matrix-ios-sdk/pull/217

Google Analytics: enable MXSession GA stats and send stat on launch screen display time

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/SettingsViewController.m

Warn that logging out will lose E2E keys

---

Vector/ViewController/ContactsTableViewController.h
Vector/ViewController/ContactsTableViewController.m

Bug Fix - Show riot enabled local contacts in known contacts too.

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomParticipantsViewController.m

Bug Fix - Trying to delete 3pid invites fails with terrible error

---

Vector/AppDelegate.m
Vector/Assets/en.lproj/Vector.strings
Vector/Model/Room/RoomPreviewData.h
Vector/Model/Room/RoomPreviewData.m
Vector/Views/RoomTitle/ExpandedRoomTitleView.m
Vector/Views/RoomTitle/PreviewRoomTitleView.m

If no data is available for this room, we name it with the known room alias if any.

Enhancement - Room preview

---

Vector.xcodeproj/project.pbxproj
Vector/Assets/en.lproj/Vector.strings
Vector/Base.lproj/Main.storyboard
Vector/ViewController/RoomViewController.m
Vector/ViewController/UsersDevicesViewController.h
Vector/ViewController/UsersDevicesViewController.m
Vector/Views/Device/DeviceTableViewCell.m
Vector/Views/RoomActivitiesView/RoomActivitiesView.h
Vector/Views/RoomActivitiesView/RoomActivitiesView.m
Vector/Views/RoomBubbleList/Encryption/RoomEncryptedDataBubbleCell.m

Give a chance to the end-user to check unknown devices before sending a message into an encrypted room.

Warn unknown devices

---

Vector/Assets/en.lproj/Vector.strings
Vector/ViewController/RoomSettingsViewController.m
Vector/ViewController/SettingsViewController.m

General settings:
Room settings:

e2e: Add global and per-room settings to blacklist unverified devices

---

Vector/Categories/MXRoom+Vector.m

Use a solid color avatar image as default for empty rooms

---

Vector/ViewController/SettingsViewController.m

Bug Fix - Device information modal broken

---

Riot/ViewController/SettingsViewController.m

- paint the “plus icon” in green when the 3pid input is editing.

SettingsViewController: Improve 3pid adding UI

---

Riot/Views/Authentication/AuthInputsView.m
Riot/Views/Authentication/AuthInputsView.xib

The username is not required to log in with a phone number

Bug Fix - Login parameters validation is buggy

---

Riot/ViewController/ContactsTableViewController.m

Increase hit area of the "Matrix users only" checkbox

---

Riot/ViewController/RoomSettingsViewController.m

Fix logic of changing room's avatar

---

Riot/Assets/en.lproj/Vector.strings
Riot/Model/RoomList/PublicRoomsDirectoryDataSource.h
Riot/Model/RoomList/PublicRoomsDirectoryDataSource.m
Riot/Model/RoomList/RecentsDataSource.m
Riot/ViewController/DirectoryViewController.m
Riot/ViewController/HomeViewController.m
Riot/Views/RoomList/DirectoryRecentTableViewCell.m

#628 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/278.
That gives these screens (note the ">20" and the spinner):

Support new directory search pagination & search APIs

---

Riot/Views/Authentication/ForgotPasswordInputsView.m

Check email validity during reset password operation

---

Riot/ViewController/HomeViewController.m

BF: Cancelling a search in room list doesn't refresh the room list

---

Riot/Model/RoomList/RecentsDataSource.m
Riot/ViewController/RecentsViewController.m

Recents data source

---

Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Base.lproj/Main.storyboard
Riot/ViewController/DirectoryServerPickerViewController.h
Riot/ViewController/DirectoryServerPickerViewController.m
Riot/ViewController/SettingsViewController.m
Riot/Views/Directory/DirectoryServerTableViewCell.h
Riot/Views/Directory/DirectoryServerTableViewCell.m
Riot/Views/Directory/DirectoryServerTableViewCell.xib

Currently the picker is a lost and found screen in the storyboard.
It misses the ability to add an homeserver URL.
TBC

Add a server directory picker

---

Riot/Assets/en.lproj/Vector.strings
Riot/Model/RoomList/RecentsDataSource.h
Riot/Model/RoomList/RecentsDataSource.m
Riot/Model/RoomList/UnifiedSearchRecentsDataSource.m
Riot/ViewController/RoomsViewController.m

The user can:
- list public rooms
- paginate them (via inconspicuous scrolling)
- select a one
Missing:
- local search (the screen is not yet ready)
- option to change the directory server

Fill the directory section

---

Riot/Model/Contact/ContactsDataSource.h
Riot/Model/Contact/ContactsDataSource.m
Riot/Model/RoomList/RecentsDataSource.h
Riot/Model/RoomList/RecentsDataSource.m
Riot/ViewController/PeopleViewController.m
Riot/ViewController/RecentsViewController.h
Riot/ViewController/RecentsViewController.m
Riot/ViewController/RecentsViewController.xib

- Handle optional sticky headers at RecentsViewController level.
TODO fix some flickering effects observed on the sticky headers during scrolling.

Prepare UX rework:

---

Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Model/Room/RoomDataSource.m
Riot/Model/RoomList/RecentCellData.m
Riot/ViewController/MasterTabBarController.h
Riot/ViewController/MasterTabBarController.m
Riot/ViewController/RoomViewController.m

TODO: Fix the missed discussions count, it is broken FTM.

Add the badge value for Home tab bar item.

---

Riot/AppDelegate.m
Riot/Model/Room/RoomDataSource.m
Riot/ViewController/ContactsTableViewController.m
Riot/ViewController/RoomViewController.m

- Apply API changes in matrixKit

Missed notifications handling:

---

Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/DirectoryServerPickerViewController.m
Riot/ViewController/RecentsViewController.m

through the + button in the navigation bar:

Directory server list: Let user enter random homeserver

---

Riot/Model/Search/FilesSearchCellData.m

Bug Fix: Files search: display the attachment thumbnail

---

Riot.xcodeproj/project.pbxproj
Riot/API/RageShakeManager.h
Riot/API/RageShakeManager.m
Riot/Assets/en.lproj/Vector.strings
Riot/Riot-Defaults.plist
Riot/ViewController/BugReportViewController.h
Riot/ViewController/BugReportViewController.m
Riot/ViewController/BugReportViewController.xib
Riot/ViewController/SettingsViewController.m
Riot/third_party_licenses.html

It uses the bug report API: https://github.com/matrix-org/rageshake
As indicated in the code, sending a screenshot is not yet available with this API.
This PR fixes:
- https://github.com/vector-im/riot-ios/issues/1140
- https://github.com/vector-im/riot-ios/issues/920
It is also now possible to report a bug from the settings menu

Add a new popup dialog for reporting bugs and crashes

---

Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/HomeViewController.m
Riot/ViewController/RecentsViewController.h
Riot/ViewController/RecentsViewController.m

Join room by id or alias

---

Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/DirectoryServerPickerViewController.m
Riot/Views/Directory/DirectoryServerDetailTableViewCell.h
Riot/Views/Directory/DirectoryServerDetailTableViewCell.m
Riot/Views/Directory/DirectoryServerDetailTableViewCell.xib

Add explanations to Matrix cells in the directory picker

---

Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/HomeViewController.m
Riot/ViewController/RecentsViewController.m

Improve tab filter: Implement the default iOS semantic.

---

Riot/ViewController/FavouritesViewController.m
Riot/ViewController/HomeViewController.m
Riot/ViewController/PeopleViewController.m
Riot/ViewController/RoomsViewController.m

Bug Fix: App may crash when the user changes the selected tab,

---

Riot/ViewController/BugReportViewController.m

Add screenshot upload and GH labels for crash and app version

Bug report update

---

Riot/Assets/en.lproj/Vector.strings
Riot/Model/RoomList/RecentsDataSource.m
Riot/Views/RoomList/PublicRoomTableViewCell.xib

Add network label in room directory header

---

Riot/Assets/en.lproj/Vector.strings
Riot/Model/Contact/ContactsDataSource.m

- Hide the known contacts section when no filter is defined

Prepare UX Rework - People tab:

---

Riot/ViewController/BugReportViewController.m

We are ok to do that now because we have decided that the rageshake repo is private.

Bug report: Add user id & device id

---

Riot/Assets/en.lproj/Vector.strings
Riot/Model/RoomList/RecentsDataSource.h
Riot/Model/RoomList/RecentsDataSource.m
Riot/Model/RoomList/UnifiedSearchRecentsDataSource.m
Riot/ViewController/RecentsViewController.h
Riot/ViewController/RecentsViewController.m
Riot/ViewController/UnifiedSearchViewController.m

- Add people section
- Order favourites according to their activities
https://github.com/vector-im/riot-meta/issues/75

UX Rework: Add home page

---

Riot/Model/RoomList/RecentsDataSource.m
Riot/ViewController/FavouritesViewController.m
Riot/ViewController/HomeViewController.m
Riot/ViewController/PeopleViewController.m
Riot/ViewController/RoomsViewController.m

Bug Fix: App crashes while the user switches the selected tab

---

Riot/ViewController/RecentsViewController.h
Riot/ViewController/RecentsViewController.m
Riot/ViewController/RecentsViewController.xib

The search input view should appear like in the email client, stuck to the top of the table.
#1194

Improve tab filter

---

Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/RoomViewController.m
Riot/Views/RoomInputToolbar/RoomInputToolbarView.m

Bug Fix: iOS should have 'Send a message (encrypted)' in placeholder

---

Riot/ViewController/RoomViewController.m

- Do not launch the read marker animation if the marker is outside the visible area.

Chat room read marker:

---

Riot/ViewController/DirectoryViewController.m

https://github.com/matrix-org/riot-ios-rageshakes/issues/32
I was able to reproduce the bug by using bad network conditioner.

Fix crash in global search

---

Riot/ViewController/RoomViewController.m

https://github.com/vector-im/riot-meta/issues/8

Read marker: Fix issues on marker handling

---

Riot/Model/RoomList/RecentsDataSource.m
Riot/Views/RoomList/RoomCollectionViewCell.m

- Add missed notifications badge in section header.
- Improve invites display.

UX-Rework - Home: Badge handling.

---

Riot/Model/RoomList/RecentsDataSource.m
Riot/ViewController/MasterTabBarController.m

Bug Fix: Home View sometimes is empty

---

Riot/ViewController/RoomViewController.m

Bug Fix: Read marker: preview mode interferes with typing indicator

---

Riot/Assets/en.lproj/Vector.strings
Riot/Model/RoomList/RecentsDataSource.m
Riot/Riot-Defaults.plist
Riot/ViewController/SettingsViewController.m

Add 2 settings: Pin rooms with missed notif and pin rooms with unread messages
this will pin the rooms at the beginning of the list on your home page

UX Rework - Home: Put the new ordering behind a setting.

---

Riot/ViewController/FavouritesViewController.h
Riot/ViewController/FavouritesViewController.m
Riot/ViewController/MasterTabBarController.m
Riot/ViewController/PeopleViewController.h
Riot/ViewController/PeopleViewController.m
Riot/ViewController/RecentsViewController.h
Riot/ViewController/RecentsViewController.m
Riot/ViewController/RoomsViewController.h
Riot/ViewController/RoomsViewController.m

Bug Fix - Repeatedly tapping on tab jumps through rooms in wrong order

---

Riot/Model/Contact/ContactsDataSource.m

To reproduce:
1- search with "tst" pattern
2- erase the 2 last characters of the pattern to set "test" -> empty result NOK

Bug Fix - Contact search: Unexpected empty search result.

---

Riot/AppDelegate.m

Add CallKit support

---

Riot/Model/RoomList/PublicRoomsDirectoryDataSource.m
Riot/ViewController/RoomsViewController.m

2 bug fixes:
- Room directory: "No public rooms available" is displayed while loading #1336
- a crash when tapping on "No public rooms available"

Room directory: "No public rooms available" bug fixes

---

Riot/Base.lproj/Main.storyboard

Bug Fix - Crash when hitting a room header after some special steps

---

Riot/ViewController/RoomViewController.m

Fix: Crash when hitting room from unified search/browse directory

---

Riot/ViewController/HomeViewController.m
Riot/Views/RoomList/RoomCollectionViewCell.m

Bug Fix - Home: tapping on an unread room on home page takes you to the wrong room

---

Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
Riot/Model/Room/RoomBubbleCellData.h
Riot/Model/Room/RoomBubbleCellData.m
Riot/Views/RoomBubbleList/Encryption/RoomEncryptedDataBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomIncomingEncryptedTextMsgBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomIncomingEncryptedTextMsgWithPaginationTitleBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomIncomingEncryptedTextMsgWithPaginationTitleWithoutSenderNameBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomIncomingEncryptedTextMsgWithoutSenderInfoBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomIncomingEncryptedTextMsgWithoutSenderNameBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomOutgoingEncryptedTextMsgBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomOutgoingEncryptedTextMsgWithPaginationTitleBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomOutgoingEncryptedTextMsgWithPaginationTitleWithoutSenderNameBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomOutgoingEncryptedTextMsgWithoutSenderInfoBubbleCell.m
Riot/Views/RoomBubbleList/Encryption/RoomOutgoingEncryptedTextMsgWithoutSenderNameBubbleCell.m

+Chat screen: several encryption icons are displayed on the same event.
#1361

Bug Fix - Chat screen: the message overlaps its timestamp

---

Riot/API/RageShakeManager.m
Riot/AppDelegate.m
Riot/ViewController/BugReportViewController.m

Several improvements in bug & crash report

---

Riot/Model/Room/RoomBubbleCellData.m
Riot/Model/Search/FilesSearchCellData.m
Riot/Views/Search/FilesSearchTableViewCell.m

We support here the display of the attached audio files, but we are still not able to attach audio file.
#1102

Bug Fix: Add the m.audio attachments support

---

Riot/ViewController/HomeViewController.m
Riot/ViewController/RecentsViewController.h
Riot/ViewController/RecentsViewController.m
Riot/Views/RoomList/RoomCollectionViewCell.h
Riot/Views/RoomList/RoomCollectionViewCell.m
Riot/Views/RoomList/RoomCollectionViewCell.xib
Riot/Views/TableViewCell/TableViewCellWithCollectionView.h
Riot/Views/TableViewCell/TableViewCellWithCollectionView.m
Riot/Views/TableViewCell/TableViewCellWithCollectionView.xib

https://github.com/vector-im/riot-meta/issues/75

UX Rework: Add edition mode in home page

---

Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/SettingsViewController.m
Riot/Views/Authentication/AuthInputsView.m
Riot/Views/Authentication/ForgotPasswordInputsView.m

https://github.com/vector-im/riot-meta/issues/85

Translate the potential error observed during 3pid handling

---

Riot/Views/TableViewCell/TableViewCellWithCheckBoxes.m

Bug Fix: Room settings, ticks are badly refreshed

---

Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/SettingsViewController.h
Riot/ViewController/SettingsViewController.m

- Add User Interface section in settings
https://github.com/vector-im/riot-meta/issues/22

Prepare Dark theme

---

Riot.xcodeproj/project.pbxproj
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/BugReportViewController.m
Riot/ViewController/LanguagePickerViewController.h
Riot/ViewController/LanguagePickerViewController.m
Riot/ViewController/SettingsViewController.m

The user can select the language of the app at runtime:

Language picker

---

Riot/AppDelegate.m

BF: the app doesn't do anything sensible with matrix.to user id hyperlinks #1410

Add support of matrix.to links to users

---

Riot/ViewController/MediaPickerViewController.m

#1445
Set up only one session at the time!

Bug Fix: App have crashed whilst uploading photos

---

RiotShareExtension/ViewController/ShareViewController.m

Only the first enabled account is considered FTM.

Bug Fix - App extension: handle correctly the account change.

---

RiotShareExtension/Model/ShareExtensionManager.h
RiotShareExtension/Model/ShareExtensionManager.m
RiotShareExtension/ViewController/ShareViewController.m
RiotShareExtension/ViewController/ShareViewController.xib

https://github.com/vector-im/riot-ios/issues/1432

App extension improvements

---

Riot/AppDelegate.m

Fix remote notifications registration even if user hasn't provide access

---

Riot/ViewController/SettingsViewController.m

Fix control event value which is used for adding target to UISwitch on settings screen

---

Riot/AppDelegate.m

This update adds Intents handling, so we can initiate outgoing call by tapping a call history item in the native app or by asking Siri.

Add Intents handling

---

RiotShareExtension/Model/ShareExtensionManager.m

Fix App crash on Exception "This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release."

App Extension - Bug Fix

---

Riot/AppDelegate.m

Add background mode handling

---

Riot/AppDelegate.m

Without this fix we can't start a call using Siri command.

Start background task when handling call intent in the background

---

SiriIntents/IntentHandler.m

Fix for #1491 
How Siri response looks like:

Handle situation with user that hasn't signed in yet

---

Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/SettingsViewController.m

Add option to settings for enable\disable showing decrypted content in notifications

---

Riot/Assets/de.lproj/Localizable.strings
Riot/Assets/en.lproj/Localizable.strings
Riot/Assets/fr.lproj/Localizable.strings
Riot/Assets/nl.lproj/Localizable.strings
Riot/Assets/ru.lproj/Localizable.strings

Connected with [#20](https://github.com/matrix-org/sygnal/pull/20)
It's safe to use it with PushKit only at that moment.

Update strings for push notifications

---

Riot/AppDelegate.m

Support the account settings: `showDecryptedContentInNotifications` value.

PushKit: local notifications handling

---

Riot/AppDelegate.m

Fix push registration process

---

Riot/Riot-Defaults.plist
Riot/ViewController/Widgets/IntegrationManagerViewController.m

Use scalar-staging.riot.im for the moment

Modular integrations Manager: Fix invite and listing of bots.

---

Riot/Utils/Widgets/Widget.m
Riot/ViewController/Widgets/IntegrationManagerViewController.m

A set of small bug fixes. Check each commit message for details

Widget manager: bug fixes

---

Riot/ViewController/BugReportViewController.m

This makes github happier and will help us on triaging.

BugReportVC: Force users to add a description in crash reports.

---

Riot/Assets/en.lproj/Vector.strings
Riot/Assets/fr.lproj/Vector.strings
Riot/ViewController/RoomSettingsViewController.m

https://github.com/vector-im/riot-ios/issues/1370

Improvement: Alter DMness from Room Settings.

---

Riot.xcodeproj/project.pbxproj
Riot/Utils/Widgets/WidgetManager.h
Riot/Utils/Widgets/WidgetManager.m
Riot/ViewController/RoomViewController.m
Riot/ViewController/Widgets/WidgetPickerViewController.h
Riot/ViewController/Widgets/WidgetPickerViewController.m

List them into an alertVC for the moment.
The apps icon becomes red when there are widgets in a room. The jitsi widget does not appear in the list because it is handled by the app.

Widgets: list active widgets in a room

---

Riot/AppDelegate.m

https://github.com/matrix-org/riot-ios-rageshakes/issues/388

Bug Fix - Some rooms have gone nameless after upgrade

---

Riot/API/RageShakeManager.m
Riot/Assets/en.lproj/Vector.strings
Riot/Assets/fr.lproj/Vector.strings
Riot/Riot-Defaults.plist
Riot/ViewController/SettingsViewController.m

https://github.com/vector-im/riot-ios/issues/1387
https://github.com/vector-im/riot-ios/issues/535
There is also a new "Do not ask again" button in the rageshake popup as a shortcut for this setting.

Rageshake: Add a setting to enable (disable) it.

---

Riot/AppDelegate.m

https://github.com/vector-im/riot-ios/issues/1522

A possible patch to avoid the app being killed in background on iOS11

---

Podfile
Riot.xcodeproj/project.pbxproj
use-dev-pods.sh

to make it easier to maintain even with several targets

Refactor the Podfile

---

Riot/Assets/zh_Hans.lproj/Vector.strings

https://github.com/matrix-org/riot-ios-rageshakes/issues/468

Search in directory: Fix crash in Simplified Chinese

---

Riot/AppDelegate.m

It created a strange screens mix between the system call screen and the incomingCallVC
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/388

Call: on incoming call, if CallKit is enabled, do not show the incomingCallVC

---

Riot/AppDelegate.m

Don't forget notifications lost while the device was offline

PushKit - Enhancement

---

Riot/AppDelegate.m
Riot/main.m
RiotShareExtension/Model/ShareExtensionManager.m
SiriIntents/IntentHandler.m

Requires  https://github.com/matrix-org/matrix-ios-sdk/pull/391

Logs app extensions to console.log

---

SiriIntents/IntentHandler.m

@manuroe thanks for your valuable comment in the previous PR.

Add support for sending messages via Siri in e2e rooms

---

Riot/Utils/Widgets/Widget.m
Riot/ViewController/Widgets/JitsiViewController.m

BF: Jitsi: Crash if the user display name has several components

---

Riot/AppDelegate.m
Riot/main.m

Set the App Group Id in `application:willFinishLaunchingWithOptions:` method instead of the `main` function of an iOS app

Should fix spontaneous logout.

---

Riot/ViewController/MediaPickerViewController.h
Riot/ViewController/MediaPickerViewController.m
Riot/ViewController/RoomSettingsViewController.m
Riot/ViewController/SettingsViewController.m
Riot/Views/RoomInputToolbar/RoomInputToolbarView.m

and must be downloaded from iCloud.
#1654

Bug Fix - Failed to send photos which are not stored on the local device

---

Riot/AppDelegate.m

Should fix spontaneous logout

---

Riot/Utils/Widgets/Widget.m

https://github.com/vector-im/riot-meta/issues/125

Widget: Integrate widget data into widget URL

---

Riot/AppDelegate.m

and add more logs to track lost notifications

Push Notifications: Prefix logs related push notifications with "[Push]"

---

Riot/AppDelegate.m

https://github.com/vector-im/riot-meta/issues/129

VoIP: increase call invite lifetime from 30 to 60s

---

Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/ViewController/AttachmentsViewController.m
Riot/ViewController/AuthenticationViewController.m
Riot/ViewController/ContactDetailsViewController.m
Riot/ViewController/ContactsTableViewController.m
Riot/ViewController/CountryPickerViewController.m
Riot/ViewController/DirectoryServerPickerViewController.m
Riot/ViewController/DirectoryViewController.m
Riot/ViewController/HomeFilesSearchViewController.m
Riot/ViewController/HomeMessagesSearchViewController.m
Riot/ViewController/LanguagePickerViewController.m
Riot/ViewController/MasterTabBarController.m
Riot/ViewController/MediaAlbumContentViewController.m
Riot/ViewController/MediaPickerViewController.m
Riot/ViewController/RecentsViewController.m
Riot/ViewController/RoomFilesSearchViewController.m
Riot/ViewController/RoomMemberDetailsViewController.m
Riot/ViewController/RoomMessagesSearchViewController.m
Riot/ViewController/RoomParticipantsViewController.m
Riot/ViewController/RoomSearchViewController.m
Riot/ViewController/RoomSettingsViewController.m
Riot/ViewController/RoomViewController.m
Riot/ViewController/SettingsViewController.m
Riot/ViewController/UnifiedSearchViewController.m
Riot/ViewController/UsersDevicesViewController.m

And move all Google Analytics code to AppDelegate.m

Analytics: Create a generic API in AppDelegate class

---

Riot.xcodeproj/project.pbxproj
Riot/AppDelegate.m
Riot/ViewController/SettingsViewController.m
RiotShareExtension/Model/ShareExtensionManager.m

Bug Fix: Share extension is not localized?

---

Riot/AppDelegate.m

at least for 10s to secure startup for the moment

App Startup: patchy patch: Reenable the loop on [application isProtecedDataAvailable] 

---

Riot/AppDelegate.m
Riot/Utils/Widgets/Widget.h
Riot/Utils/Widgets/Widget.m
Riot/Utils/Widgets/WidgetManager.h
Riot/Utils/Widgets/WidgetManager.m
Riot/ViewController/Widgets/JitsiViewController.h
Riot/ViewController/Widgets/JitsiViewController.m
Riot/ViewController/Widgets/WidgetPickerViewController.m
Riot/ViewController/Widgets/WidgetViewController.h
Riot/ViewController/Widgets/WidgetViewController.m

#1723
Make the build of the true widget URL asynchronous and build it only when necessary.

Widgets: Make sure we have a scalar token before opening one

---

Riot/AppDelegate.m
Riot/ViewController/RecentsViewController.m
Riot/ViewController/RoomParticipantsViewController.m
Riot/ViewController/RoomSettingsViewController.m
Riot/ViewController/RoomViewController.m
Riot/ViewController/SettingsViewController.m
Riot/Views/RoomInputToolbar/RoomInputToolbarView.m
RiotShareExtension/Model/ShareExtensionManager.m

This allows you to tap outside of the popup to cancel

Cancel Buttons use style Cancel

---

RiotShareExtension/Model/ShareExtensionManager.m
RiotShareExtension/ViewController/RoomsListViewController.m

Plus make sure the progress bar is always displayed.

Share: The extension crashes if you try to share a GIF image (#1759)

---

Podfile
Riot/third_party_licenses.html

to be able to use Google WebRTC lib (https://cocoapods.org/pods/GoogleWebRTC)

Podfile: Update the minimal iOS version to 9.0

---

Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/RoomViewController.m
Riot/Views/RoomInputToolbar/DisabledRoomInputToolbarView.h
Riot/Views/RoomInputToolbar/DisabledRoomInputToolbarView.m
Riot/Views/RoomInputToolbar/DisabledRoomInputToolbarView.xib

Room: Inform user when they cannot post to a room because of low power level

---

Riot/AppDelegate.m
Riot/ViewController/RoomMemberDetailsViewController.m

#1782 
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/456.

BF: e2e devices list not shown

---

Riot/Assets/bg.lproj/Vector.strings
Riot/Assets/ca.lproj/Vector.strings
Riot/Assets/de.lproj/Vector.strings
Riot/Assets/en.lproj/Vector.strings
Riot/Assets/eu.lproj/Vector.strings
Riot/Assets/fr.lproj/Vector.strings
Riot/Assets/nl.lproj/Vector.strings
Riot/Assets/ru.lproj/Vector.strings
Riot/Assets/vi.lproj/Vector.strings
Riot/Assets/zh_Hans.lproj/Vector.strings
Riot/Riot-Defaults.plist
Riot/ViewController/SettingsViewController.m

#1795
Move the setting as an app configuration settings in Riot-Defaults.plist

Matrix Apps: Enable them by default. Remove the setting from LABS section

---

Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/RoomMemberDetailsViewController.m

Signed-off-by: Arash Tabrizian <a.tabriziyan@gmail.com>

fixes issue #1816 support specifying kick and ban msgs

---

Podfile
Riot.xcodeproj/project.pbxproj

#1821
because of the WebRTC framework.

BF: Upgrade the minimal iOS version to 9.0 because the app crashes on iOS8

---

Riot/ViewController/HomeViewController.m
Riot/ViewController/RecentsViewController.m

Signed-off-by: Arash Tabrizian <a.tabriziyan@gmail.com>

fixes issue #1793 Confirmation popup when leaving room

---

Riot/Model/Room/RoomDataSource.m
Riot/Views/RoomBubbleList/RoomOutgoingAttachmentBubbleCell.m
Riot/Views/RoomBubbleList/RoomOutgoingAttachmentWithPaginationTitleBubbleCell.m
Riot/Views/RoomBubbleList/RoomOutgoingAttachmentWithoutSenderInfoBubbleCell.m
Riot/Views/RoomBubbleList/RoomOutgoingTextMsgBubbleCell.m
Riot/Views/RoomBubbleList/RoomOutgoingTextMsgWithoutSenderInfoBubbleCell.m
Riot/Views/RoomBubbleList/RoomSelectedStickerBubbleCell.m
Riot/Views/RoomBubbleList/RoomSelectedStickerBubbleCell.xib

- Animate the sticker in case of an animated gif
vector-im/riot-ios#1837

Render sticker events in the timeline

---

Riot/Utils/EventFormatter.m

This should fix #1274
Needs testing to confirm it definitely works properly (changing time zones in the simulator is clunky) and that it hasn't broken anything else. I'm a bit suspicious about fixing the calendar to GMT however 😕
Signed-off-by: Doug Earnshaw pixlwave@users.noreply.github.com

Fix timezone interval bug

---

Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings

#1871 
Add GDPR consent display when GDPR consent not given error is received.

Display the consent tool in case of M_CONSENT_NOT_GIVEN error

---

Riot/ViewController/Widgets/WidgetViewController.m

Requires https://github.com/matrix-org/matrix-ios-kit/pull/431
Before:
https://matrix.org/_matrix/media/v1/download/matrix.org/yJuVlAzCqgeGxgRZqCHLxYiX
After:
https://matrix.org/_matrix/media/v1/download/matrix.org/LfYXiGSnBOTigpQBHWQAVOIK

WidgetVC: Update UIWebView by WKWebview to improve Sticker Picker performance

---

Riot.xcodeproj/project.pbxproj
Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/ViewController/DeactivateAccount/DeactivateAccountViewController.h
Riot/ViewController/DeactivateAccount/DeactivateAccountViewController.m
Riot/ViewController/DeactivateAccount/DeactivateAccountViewController.storyboard
Riot/ViewController/SettingsViewController.m

#1870
Add deactivate account ability from settings with a checkbox for GDPR erasure.

Settings: Add deactivate account

---

Riot/AppDelegate.m

#1883
Put close action to left in navigation bar of GDPR consent screen.

GDPR consent screen could not be closed

---

Riot/AppDelegate.m

Fix GDPR consent alert not shown after account creation

Fix GDPR consent alert not shown after account creation

---

Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/ViewController/DeactivateAccount/DeactivateAccountViewController.m
Riot/ViewController/SettingsViewController.m

Update account deactivation success handling in SettingsViewController. Do not send logout request to home server.

Fix account deactivation completion

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Analytics/Analytics.h
Riot/Analytics/Analytics.m
Riot/Analytics/DecryptionFailure.h
Riot/Analytics/DecryptionFailure.m
Riot/Analytics/DecryptionFailureTracker.h
Riot/Analytics/DecryptionFailureTracker.m
Riot/AppDelegate.m
Riot/Utils/EventFormatter.m

Crypto: Add telemetry for events unable to decrypt (UTDs)

---

Riot/Model/Room/RoomDataSource.m

This fixes one case of duplication.

RoomVC: Fix regression where read receipts can be duplicated

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/API/RageShakeManager.m
Riot/Analytics/Analytics.m
Riot/AppDelegate.m
Riot/Model/RoomList/RecentsDataSource.m
Riot/Riot-Bridging-Header.h
Riot/Utils/RiotDesignValues.m
Riot/Utils/RiotSettings.swift
Riot/ViewController/MasterTabBarController.m
Riot/ViewController/RoomViewController.m
Riot/ViewController/SettingsViewController.m
RiotShareExtension/RiotShareExtension-Bridging-Header.h

#1914
Keep notification settings option "Show decrypted content" after logout.

e2e messages not decrypted in notifs after logging back in

---

Riot/Analytics/Analytics.m
Riot/Analytics/DecryptionFailure.h
Riot/Analytics/DecryptionFailure.m
Riot/Analytics/DecryptionFailureTracker.h
Riot/Analytics/DecryptionFailureTracker.m

Crypto: Telemetry: Categorise e2e failures

---

Riot/AppDelegate.m
Riot/Managers/Analytics/DecryptionFailureTracker.m
Riot/Modules/GlobalSearch/Files/CellData/FilesSearchCellData.m
Riot/Modules/Integrations/IntegrationManagerViewController.m
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/Members/RoomParticipantsViewController.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Settings/RoomSettingsViewController.m
Riot/Modules/Room/Views/Title/Expanded/ExpandedRoomTitleView.m
Riot/Utils/EventFormatter.m

Follows changes made in https://github.com/matrix-org/matrix-ios-sdk/pull/530.
#1931

Decouple room state and members

---

Riot/AppDelegate.m
Riot/Categories/MXRoom+Riot.m
Riot/Model/Room/RoomPreviewData.m
Riot/Modules/Call/CallViewController.m
Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Communities/GroupsViewController.m
Riot/Modules/Contacts/Details/ContactDetailsViewController.m
Riot/Modules/Contacts/Details/Views/RoomTableViewCell.m
Riot/Modules/Home/HomeViewController.m
Riot/Modules/Home/Views/RoomCollectionViewCell.m
Riot/Modules/Integrations/IntegrationManagerViewController.m
Riot/Modules/Room/Members/RoomParticipantsViewController.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Settings/RoomSettingsViewController.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomEncryptedDataBubbleCell.m
Riot/Modules/Room/Views/Title/Expanded/ExpandedRoomTitleView.m
Riot/Modules/Room/Views/Title/Preview/PreviewRoomTitleView.m
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/StartChat/StartChatViewController.m
Riot/Utils/EventFormatter.m
RiotShareExtension/Managers/ShareExtensionManager.m

Its access is going to be async.
vector-im/riot-ios#1931

Reduce dependency to room.state 

---

Riot/AppDelegate.m
Riot/Managers/Widgets/WidgetManager.h
Riot/Managers/Widgets/WidgetManager.m
Riot/Model/Room/RoomPreviewData.m
Riot/Modules/Communities/Home/GroupHomeViewController.m
Riot/Modules/Communities/Rooms/GroupRoomsViewController.m
Riot/Modules/GlobalSearch/Files/CellData/FilesSearchCellData.m
Riot/Modules/GlobalSearch/Messages/DataSources/HomeMessagesSearchDataSource.m
Riot/Modules/Integrations/IntegrationManagerViewController.m
Riot/Modules/Integrations/WidgetPicker/WidgetPickerViewController.m
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Riot/Modules/Room/Members/RoomParticipantsViewController.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Search/DataSources/RoomSearchDataSource.m
Riot/Modules/Room/Search/RoomSearchViewController.m
Riot/Modules/Room/Settings/RoomSettingsViewController.m
Riot/Modules/Room/Views/Title/Expanded/ExpandedRoomTitleView.m
Riot/Modules/Room/Views/Title/Preview/PreviewRoomTitleView.m
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/TabBar/MasterTabBarController.m
Riot/Utils/EventFormatter.m

Part of vector-im/riot-ios#1931 in order to decouple MXRoom.members from MXRoom.state

MXRoom: Make access to liveTimeline data async

---

RiotShareExtension/Modules/Share/Listing/RoomsListViewController.m
SiriIntents/IntentHandler.m

Required https://github.com/matrix-org/matrix-ios-sdk/pull/535

MXStore: Use the new async [MXStore stateOfRoom:] method

---

Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Model/Room/RoomPreviewData.m
Riot/Modules/Room/Members/RoomParticipantsViewController.m
Riot/Modules/Room/Views/Title/Expanded/ExpandedRoomTitleView.m
Riot/Modules/Room/Views/Title/Preview/PreviewRoomTitleView.m
Riot/Modules/Settings/SettingsViewController.m
RiotShareExtension/Modules/Share/Listing/RoomsListViewController.m
SiriIntents/IntentHandler.m

Part of https://github.com/vector-im/riot-ios/issues/1931
Fix some async bits and add "Settings > LABS > Lazy load rooms members"
Requires https://github.com/matrix-org/matrix-ios-kit/pull/454 & https://github.com/matrix-org/matrix-ios-sdk/pull/539

Lazy loading server side

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Modules/Room/CellData/RoomBubbleCellData.h
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/Activities/RoomActivitiesView.h
Riot/Modules/Room/Views/Activities/RoomActivitiesView.m
Riot/Modules/Room/Views/BubbleCells/RoomPredecessorBubbleCell.h
Riot/Modules/Room/Views/BubbleCells/RoomPredecessorBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomPredecessorBubbleCell.xib
Riot/Utils/EventFormatter.m

#1938
Old room (tombstone):
New room with predecessor:

Support room versioning

---

Riot/Modules/TabBar/MasterTabBarController.m

after changes in https://github.com/matrix-org/matrix-ios-kit/pull/459

Make it build

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Modules/Room/RoomViewController.m

Chat screen: Add "view decrypted source" option on the selected event

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Modules/Settings/SettingsViewController.m

That follows discussions at https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1533746228534738DJDAS:matrix.org.
\+ enable 2 new languages.

 Settings: Disable "Labs > Enable LL" for the coming release

---

Riot/Modules/TabBar/MasterTabBarController.h
Riot/Modules/TabBar/MasterTabBarController.m

Video at
https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1533808423412ynHll:matrix.org

Lazy-loading: Fix a regression when opening a room where we can see the Riot logo in bg

---

CHANGES.rst
Riot/Modules/Common/Recents/RecentsViewController.m

BF: Multiple rooms can be opened

---

Podfile
Riot.xcodeproj/project.pbxproj
Riot/Categories/MatrixSDK+Swift.h
Riot/Categories/MatrixSDK+Swift.m
Riot/Managers/OnBoarding/OnBoardingManager.swift
Riot/SupportingFiles/Riot-Bridging-Header.h

And make Swift code not using NS_REFINED_FOR_SWIFTed methods from MatrixSDK

Disable 'MatrixSDK/SwiftSupport' pod

---

Riot/Assets/en.lproj/Vector.strings
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/Activities/RoomActivitiesView.h
Riot/Modules/Room/Views/Activities/RoomActivitiesView.m

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/550.
Point 3 of of vector-im/riot-ios#1937

RoomVC: Show a "Resource Limit Exceeded" banner if it happens in a /sync response

---

CHANGES.rst
Riot/AppDelegate.m

AppDelegate: the userDefaults were registered after the application language handling

Bug Fix - User defaults: the preset application language (if any) is ignored

---

Riot/Modules/Settings/SettingsViewController.m

It uses /versions this time to check LL availability on the HS.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/551.
Still part of #1931.

Lazy-loading: Make "Settings > LABS > Enable LL" back

---

Riot/AppDelegate.m

Do not wait anymore for the completion of the creation of the room with riot-bot.
This is useful in case of the bad connection or bad hs.

GDPRConsentViewController: close it once the user has given their consent

---

CHANGES.rst
Riot/Modules/Common/Recents/RecentsViewController.m

It crashed on room creation on quick HSes

Recents: Avoid to open a room twice

---

Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/TabBar/MasterTabBarController.h
Riot/Modules/TabBar/MasterTabBarController.m

Fix user interaction disabled in master view of UISplitViewContoller when selecting a room 

---

CHANGES.rst
Riot/Modules/BugReport/BugReportViewController.m
Riot/Modules/Room/DataSources/RoomDataSource.m

Lazy-Loading: Fix missing read receipts

---

Riot/Model/Room/RoomPreviewData.m

Require https://github.com/matrix-org/matrix-ios-sdk/pull/563

RoomPreviewData: Make a full usage of MXPeekingRoom.summary

---

CHANGES.rst
Riot/Modules/Room/Settings/RoomSettingsViewController.m

Room settings: Anyone can now set a room alias

---

CHANGES.rst
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Utils/Tools.h
Riot/Utils/Tools.m

BF: Weird text color when selecting a message

---

Riot/Assets/bg.lproj/Vector.strings
Riot/Assets/ca.lproj/Vector.strings
Riot/Assets/de.lproj/Vector.strings
Riot/Assets/es.lproj/Vector.strings
Riot/Assets/eu.lproj/Vector.strings
Riot/Assets/fr.lproj/Vector.strings
Riot/Assets/is.lproj/Vector.strings
Riot/Assets/nl.lproj/Vector.strings
Riot/Assets/ru.lproj/Vector.strings
Riot/Assets/sq.lproj/Vector.strings
Riot/Assets/vi.lproj/Vector.strings
Riot/Assets/zh_Hans.lproj/Vector.strings
Riot/Assets/zh_Hant.lproj/Vector.strings

As promised at https://github.com/vector-im/riot-ios/pull/2043
Work with https://github.com/matrix-org/matrix-ios-kit/pull/475

Matrix room summaries: Move i18n strings from Riot to MatrixKit

---

Riot/Assets/en.lproj/Vector.strings

Signed-off-by: Aaron Raimist <aaron@raim.ist>

Reword English settings_sign_out_e2e_warn

---

Riot/AppDelegate.m
Riot/Managers/Widgets/WidgetManager.m
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Settings/SettingsViewController.m

Remove all calls of [NSUserDefaults synchronize] (#1924)

---

Podfile
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/Views/AuthInputsView.h
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Authentication/Views/AuthInputsView.xib
Riot/Modules/Authentication/Views/TermsView.swift
Riot/Modules/Authentication/Views/TermsView.xib
Riot/SupportingFiles/Riot-Bridging-Header.h

fixes #1939
Video:
https://matrix.org/_matrix/media/v1/download/matrix.org/BJMLVdjeRahKivWjKUMXmbSk

 Login flow: Make User Agreement part of the registration flow

---

CHANGES.rst
Riot/Modules/Authentication/Views/AuthInputsView.h
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Authentication/Views/AuthInputsView.xib

fixes #2119
Requires https://github.com/matrix-org/matrix-ios-kit/pull/500

Registration: reCAPTCHA does not work anymore on iOS 10

---

CHANGES.rst
RiotShareExtension/Managers/ShareExtensionManager.h
RiotShareExtension/Managers/ShareExtensionManager.m

Share Extension: Improve image sharing performance and fix screenshot sharing

---

CHANGES.rst
Podfile
Podfile.lock
Riot.xcodeproj/project.pbxproj
Riot/Generated/Images.swift
Riot/Generated/RiotDefaults.swift
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Tools/SwiftGen/swiftgen-config.yml

Add SwiftGen pod in order to generate Swift constants for assets (strings, images, storyboards, etc.)

---

CHANGES.rst
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/Views/AuthInputsView.m

Fixes #2184 and probably #2165.

Registration screen improvements

---

Riot/Managers/Theme/Theme.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift

Update Theme protocol, set placeholder color non optional and add commodity methods

---

CHANGES.rst
Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

Fixes #679.
Instead of the infinite spinner, we now display this error:

BF: Infinite loading wheel when taping on a fake room alias

---

Riot.xcodeproj/project.pbxproj
Riot/Managers/Theme/ThemeService.m
Riot/Managers/Theme/Themes/BlackTheme.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift

Fixes #2175
The only difference is the background color which is a pure black.
Black theme:
Dark theme:

reskin: Create a black theme from the dark theme  

---

CHANGES.rst
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Communities/GroupsViewController.m
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Rooms/DirectoryPicker/DirectoryServerPickerViewController.m
Riot/Modules/Settings/SettingsViewController.m

BF: Ban and kick reasons are silently discarded

---

Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Authentication/Views/ForgotPasswordInputsView.m
Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
Riot/Modules/Room/Settings/RoomSettingsViewController.m
Riot/Modules/Settings/SettingsViewController.m

Fixes part of #2174:
- kill dead code around placeholderTextColor (introduced by #2187)
- riot-ios does use unreadRoomIndentColor

Fix iOS side of #2174

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/BubbleCells/RoomPredecessorBubbleCell.m
Riot/Utils/EventFormatter.m

Enhance tap on room predecessor cell used to go back to the old version of the room (Fix issue #2179)

---

CHANGES.rst
RiotShareExtension/Managers/ShareExtensionManager.m

BF: Share extension: Fail to send screenshot

---

Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m
Riot/Modules/Settings/KeyBackup/SettingsKeyBackupViewModel.swift

when opening the home or the settings screen in order to display the right banner and settings.
Require https://github.com/matrix-org/matrix-ios-sdk/pull/627

Key backup: Check backup update on the homeserver

---

CHANGES.rst
RiotShareExtension/Managers/ShareExtensionManager.m
RiotShareExtension/SupportingFiles/Info.plist

BF: [Share Extension] Handle rich item sharing (image + text + URL)

---

CHANGES.rst
Riot/Modules/Room/RoomViewController.m

RoomVC: Remove the beta warning modal when opening an e2e room

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/SettingsViewController.m
Riot/Modules/Settings/SignOut/SignOutAlertPresenter.swift

Key backup: logout warning

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Modules/Room/RoomViewController.m

1 commit per fix:
* Fixes #2218 
* Fixes #2251

Reskin: 2 fixes

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

Fixes #2230.
**NOTE**: The settings button is not yet mapped. This is an UX issue but this is better to display that modal rather than nothing.

Key backup: new recover method detected

---

Riot/AppDelegate.m
Riot/Managers/Theme/Theme.swift
Riot/Managers/Theme/ThemeService.m
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift
Riot/Modules/TabBar/MasterTabBarController.m

Reskin: Update Dark theme colors

---

Riot/Modules/Room/RoomViewController.m

Reskin: Fix room expanded header color

---

Riot/Modules/Room/RoomViewController.h
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/RoomViewController.xib

Reskin: Update jump to last unread banner separator color in RoomViewController

---

Riot/Assets/Riot-Defaults.plist

Remove Pusher App Ids as Push Notifications are handled with PushKit.

Remove Pusher App Ids

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/Settings/RoomSettingsViewController.m

Fixes #2239 for real.
Hard to screenshot a removed thing.

RoomVC: Remove the beta warning modal when enabling e2e in a room

---

CHANGES.rst
Riot/Modules/Settings/SettingsViewController.m

Fix crash in Settings in 0.8.1

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Categories/UIApplication.swift
Riot/Generated/Strings.swift
Riot/Modules/GlobalSearch/Messages/Views/MessagesSearchResultTextMsgBubbleCell.xib
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomIncomingEncryptedTextMsgBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomIncomingEncryptedTextMsgWithPaginationTitleBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomIncomingEncryptedTextMsgWithPaginationTitleWithoutSenderNameBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomIncomingEncryptedTextMsgWithoutSenderInfoBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomIncomingEncryptedTextMsgWithoutSenderNameBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomOutgoingEncryptedTextMsgBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomOutgoingEncryptedTextMsgWithPaginationTitleBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomOutgoingEncryptedTextMsgWithPaginationTitleWithoutSenderNameBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomOutgoingEncryptedTextMsgWithoutSenderInfoBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomOutgoingEncryptedTextMsgWithoutSenderNameBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgWithPaginationTitleBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgWithPaginationTitleWithoutSenderNameBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgWithoutSenderInfoBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgWithoutSenderNameBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithPaginationTitleBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithPaginationTitleWithoutSenderNameBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithoutSenderInfoBubbleCell.xib
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgWithoutSenderNameBubbleCell.xib

Fix #728 
Requires matrix-org/matrix-ios-kit#525

BF: Quickly tapping on a URL in a message highlights the message rather than opening the URL

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/Views/AuthInputsView.h
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Authentication/Views/AuthInputsView.xib

This is hacky. I would have preferred to create a new MXKAuthenticationTypeSSO but that would imply a lot of changes (and regressions) in the kit.
Fixes https://github.com/vector-im/riot-ios/issues/2306
Requires  https://github.com/matrix-org/matrix-ios-sdk/pull/641 & https://github.com/matrix-org/matrix-ios-kit/pull/524.

Authentication: support SSO by using the fallback URL

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Categories/Character.swift
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.h
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
Riot/Categories/String.swift
Riot/Managers/Theme/Theme.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift
Riot/Modules/GlobalSearch/Messages/Views/MessagesSearchResultAttachmentBubbleCell.m
Riot/Modules/GlobalSearch/Messages/Views/MessagesSearchResultTextMsgBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomIncomingAttachmentBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomIncomingAttachmentWithPaginationTitleBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomIncomingTextMsgWithPaginationTitleBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingAttachmentBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingAttachmentWithPaginationTitleBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomOutgoingTextMsgBubbleCell.m
Riot/Utils/UserNameColorGenerator.swift

Reskin: colorise users displaynames

---

CHANGES.rst
Riot/Assets/Riot-Defaults.plist
Riot/Generated/RiotDefaults.swift
Riot/Managers/Widgets/Widget.m
Riot/Managers/Widgets/WidgetManager.h
Riot/Managers/Widgets/WidgetManager.m
Riot/Modules/Integrations/IntegrationManagerViewController.m
Riot/Modules/Integrations/Widgets/WidgetViewController.m

and pass scalar_token only when required.
Fixes #2326.

Widgets: Attempt to re-register for a scalar token if ours is invalid

---

Riot/Assets/en.lproj/Vector.strings

I assume some script needs to be run to generate the other string files, but if you want to just do that yourselves and take the text in this PR I'm totally fine with that.

Fix grammar in registration text

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Generated/Storyboards.swift
Tools/SwiftGen/swiftgen-config.yml
Tools/Templates/README.md
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinator.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorBridgePresenter.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinator.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinatorType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewAction.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewController.storyboard
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewController.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModel.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModelType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewState.swift
Tools/Templates/createRootCoordinator.sh
Tools/Templates/createScreen.sh

and `createScreen.sh`
It generates this minimalistic screen:

Productivity: Create templates for screens and flow root coordinators

---

Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/GlobalSearch/Rooms/DirectoryViewController.m
Riot/Modules/Rooms/RoomsViewController.m

Use one external entry point on AppDelegate to navigate to a room

---

CHANGES.rst
RiotShareExtension/Modules/Share/DataSources/ShareDataSource.m

Upgraded rooms show up in the share extension twice

---

Riot/Assets/ja.lproj/Localizable.strings
Riot/Assets/ja.lproj/Vector.strings
Riot/Assets/zh_Hans.lproj/Vector.strings
Riot/Assets/zh_Hant.lproj/Vector.strings

I feel that this should be self-explanatory enough to not warrant as much scrutiny as normal, but feel free to tell me otherwise :)
Signed-off-by: Jeremy O'Brien <neutral@fastmail.com>

Fix remaining full-width '%' symbols in strings

---

Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/Assets/de.lproj/Vector.strings
Riot/Assets/en.lproj/Vector.strings
Riot/Assets/nl.lproj/Vector.strings
Riot/Assets/pr.lproj/Vector.strings
Riot/Assets/vi.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Authentication/AuthenticationViewController.xib
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Communities/Home/GroupHomeViewController.m

First part of #2345 
This probably doesn't need to be included in CHANGES.rst.

home server -> homeserver (#2345)

---

Tools/Release/buildRelease.sh

For internal usage, in order to make release.
It basically does what Jenkins did but on your machine.

 Build: Add a sh build script

---

README.rst

Signed-off-by: Fridtjof Mund 2780577+fridtjof@users.noreply.github.com

Readme: 'pod update' should be 'pod setup' for updating CocoaPods repos

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m

because message editing (#2404) is coming.
And made this change: When replying, use a "Reply" button instead of "Send"

RoomInputToolbarView: Turn the boolean replyToEnabled into an enum: sendMode

---

Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuViewModel.swift

Closes #2398.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/663 & https://github.com/matrix-org/matrix-ios-kit/pull/552

Reactions: Reactions menu: plug unreact

---

Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuViewModel.swift
Riot/Modules/Room/ContextualMenu/RoomContextualMenuPresenter.swift

only if the server does not have the aggregation API yet.
I made a fix in Reactions menu to highlight reactions only our user has made.

Hack reaction sending like riot-web and riot-android

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Settings/SettingsViewController.m

closes #2441.
Requires https://github.com/matrix-org/matrix-ios-kit/pull/553.

Reactions: Add a labs setting

---

CHANGES.rst
Podfile
Riot.xcodeproj/project.pbxproj
Riot/Managers/Theme/Theme.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift
Riot/Modules/Common/CollectionView/AutosizedCollectionView.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionViewCell.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionViewCell.xib
Riot/Modules/Room/BubbleReactions/BubbleReactionViewData.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionsView.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionsView.xib
Riot/Modules/Room/BubbleReactions/BubbleReactionsViewModel.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionsViewModelType.swift
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/DataSources/RoomDataSource.m

#2396
Requires matrix-org/matrix-ios-kit/pull/555

Reactions: Display existing reactions below the message

---

Riot/Assets/third_party_licenses.html

Update third-party licences

---

Riot.xcodeproj/project.pbxproj
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
Riot/Categories/UITouch.swift
Riot/Modules/Room/CellData/RoomBubbleCellData.h
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/ContextualMenu/RoomContextualMenuViewController.swift
Riot/Modules/Room/RoomViewController.m
Riot/Utils/EventFormatter.m

Menu actions: Display message time

---

CHANGES.rst
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.h
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
Riot/Modules/Room/RoomViewController.m

Reactions Menu: Fix position

---

CHANGES.rst
Riot/Modules/Authentication/Views/AuthInputsView.m

BF: Registration with an email is broken

---

CHANGES.rst
Riot/Modules/Room/ContextualMenu/ContextualMenuItemView.swift
Riot/Modules/Room/ContextualMenu/ContextualMenuItemView.xib
Riot/Modules/Room/ContextualMenu/RoomContextualMenuToolbarView.swift

Context menu polish

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.h
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomBubbleCellLayout.swift

Fix #2462
Requires matrix-org/matrix-ios-kit/pull/559

BF: Reactions: Bad position

---

CHANGES.rst
Riot/Modules/Room/RoomViewController.m

BF Reactions: It lets you react to join/leave events

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/RoomViewController.m
Riot/Utils/EventFormatter.h
Riot/Utils/EventFormatter.m

Message Editing: Annotate edited messages in timeline

---

CHANGES.rst
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m

Message Editing: Editing in the timeline

---

Riot/Modules/Room/ContextualMenu/ReactionsMenu/ReactionsMenuViewModel.swift
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/RoomViewController.m

Part of vector-im/riot-ios#2453.
Requires matrix-org/matrix-ios-sdk#673.

Local echo for reactions

---

Riot/Modules/Room/CellData/RoomBubbleCellData.m

e2e room message: Fix padlock position on last message with sender name

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

Fixes #2526
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/678.

Device Verification: Name for 🔒 is "Lock"

---

Riot/Modules/Room/BubbleReactions/BubbleReactionViewCell.xib

BF: Reactions: Frames bottoms are clipped

---

Riot.xcodeproj/project.pbxproj
Riot/Generated/Storyboards.swift
Riot/Modules/Room/EditHistory/EditHistoryCoordinator.swift
Riot/Modules/Room/EditHistory/EditHistoryCoordinatorBridgePresenter.swift
Riot/Modules/Room/EditHistory/EditHistoryCoordinatorType.swift
Riot/Modules/Room/EditHistory/EditHistoryMessage.swift
Riot/Modules/Room/EditHistory/EditHistoryViewAction.swift
Riot/Modules/Room/EditHistory/EditHistoryViewController.storyboard
Riot/Modules/Room/EditHistory/EditHistoryViewController.swift
Riot/Modules/Room/EditHistory/EditHistoryViewModel.swift
Riot/Modules/Room/EditHistory/EditHistoryViewModelType.swift
Riot/Modules/Room/EditHistory/EditHistoryViewState.swift
Riot/SupportingFiles/Riot-Bridging-Header.h
Riot/Utils/EventFormatter.h
Riot/Utils/EventFormatter.m

Part of #2401
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/684
`EditHistoryViewModel` should have everything to implement the expected UI.

Edits history: view model 

---

CHANGES.rst
Riot/Modules/Room/RoomViewController.m

#2492
Requires matrix-org/matrix-ios-sdk/pull/688 and matrix-org/matrix-ios-kit/pull/575

Message Editing: Handle reply edition

---

Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionActionViewCell.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionActionViewCell.xib
Riot/Modules/Room/BubbleReactions/BubbleReactionsView.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionsViewModel.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionsViewModelType.swift
Riot/Modules/Room/CellData/RoomBubbleCellData.h
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/DataSources/RoomDataSource.m

Reactions: Show at most 8 reactions

---

Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/EditHistory/EditHistoryCell.swift
Riot/Modules/Room/EditHistory/EditHistoryCell.xib
Riot/Modules/Room/EditHistory/EditHistoryCoordinatorBridgePresenter.swift
Riot/Modules/Room/EditHistory/EditHistoryHeaderView.swift
Riot/Modules/Room/EditHistory/EditHistoryHeaderView.xib
Riot/Modules/Room/EditHistory/EditHistorySection.swift
Riot/Modules/Room/EditHistory/EditHistoryViewController.storyboard
Riot/Modules/Room/EditHistory/EditHistoryViewController.swift
Riot/Modules/Room/EditHistory/EditHistoryViewModel.swift
Riot/Modules/Room/EditHistory/EditHistoryViewModelType.swift
Riot/Modules/Room/EditHistory/EditHistoryViewState.swift
Riot/Modules/Room/RoomViewController.m

Message Editing: View edit history (UI)

---

Riot/Modules/Room/EditHistory/EditHistoryCoordinator.swift
Riot/Modules/Room/EditHistory/EditHistoryCoordinatorBridgePresenter.swift
Riot/Modules/Room/EditHistory/EditHistoryViewModel.swift

Message editing: Handle encrypted message edits history

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Model/Room/RoomPreviewData.h
Riot/Modules/Common/Recents/RecentsViewController.m
Riot/Modules/Room/RoomViewController.m

Part of #2547.
Closes #2550.
Requires https://github.com/matrix-org/matrix-ios-kit/pull/576 and matrix-org/matrix-ios-sdk#690.

 Join Room: Support via parameters to better handle federation

---

Riot/Modules/Room/BubbleReactions/BubbleReactionsView.swift

BF: Reactions: Unexpected padding after event selection

---

Riot/Categories/MXKRoomBubbleTableViewCell+Riot.h
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
Riot/Modules/Room/CellData/RoomBubbleCellData.h
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/RoomViewController.m

BF: Quick reactions menu hide time and user display name

---

Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Settings/SettingsViewController.m

LABS: Remove reaction settings

---

Riot/Modules/Room/BubbleReactions/BubbleReactionViewCell.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionViewCell.xib

Reactions: Reinstate the ability to react with non-unicode keys

---

CHANGES.rst
Podfile
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Room/DataSources/RoomDataSource.h
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m

Handle #2019 & #2530
Requires https://github.com/matrix-org/matrix-ios-kit/pull/581

Ability to send files via the iOS11+ file manager

---

CHANGES.rst
Tools/Logs/filterCryptoLogs.sh

Tools: Create filterCryptoLogs.sh to filter logs related to e2ee from Riot logs

---

Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Authentication/AuthenticationViewController.xib
Riot/Modules/Authentication/Views/AuthInputsView.xib

Requires https://github.com/matrix-org/matrix-ios-kit/pull/585
All client side part of https://github.com/vector-im/riot-ios/issues/2597

 Soft logout: SSO support

---

CHANGES.rst
Riot/Assets/Riot-Defaults.plist

Widgets: Whitelist https://scalar-staging.vector.im/api

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.h
Riot/Categories/MXKRoomBubbleTableViewCell+Riot.m
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionsView.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionsViewModel.swift
Riot/Modules/Room/BubbleReactions/BubbleReactionsViewModelType.swift
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/EditHistory/EditHistoryCoordinatorBridgePresenter.swift
Riot/Modules/Room/EditHistory/EditHistoryViewModel.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryBridgeCoordinatorPresenter.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryCoordinator.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryCoordinatorType.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewAction.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewCell.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewCell.xib
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewController.storyboard
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewController.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewData.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewModel.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewModelType.swift
Riot/Modules/Room/ReactionHistory/ReactionHistoryViewState.swift
Riot/Modules/Room/RoomViewController.m

Reactions: Show who reacted

---

CHANGES.rst
Riot/Categories/UISearchBar.swift
Riot/Modules/Communities/Members/GroupParticipantsViewController.m
Riot/Modules/Communities/Rooms/GroupRoomsViewController.m
Riot/Modules/Room/Members/RoomParticipantsViewController.m
Riot/Modules/StartChat/StartChatViewController.m

BF: Fix crash for search bar customisation in iOS13

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Assets/Riot-Defaults.plist
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/RiotDefaults.swift
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Call/CallViewController.h
Riot/Modules/Call/CallViewController.m
Riot/Modules/Settings/SettingsViewController.m

VoIP: Fallback to matrix.org STUN server with a confirmation dialog

---

CHANGES.rst
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Settings/SettingsViewController.m

 Privacy: Remove the bind true flag from 3PID calls

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Authentication/Views/ForgotPasswordInputsView.m

Closes #2658
Display an error if IS is required but empty
Requires https://github.com/matrix-org/matrix-ios-kit/pull/600
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/715

Privacy: Allow password reset when no IS

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/SettingsViewController.m

#2659
And display an error if an IS is required.
Requires matrix-org/matrix-ios-sdk#715

Privacy: Settings: Allow adding 3pids when no IS

---

Riot/Modules/Authentication/Views/ForgotPasswordInputsView.m
Riot/Modules/Settings/SettingsViewController.m

Settings: Update the screen if IS is changed from another device

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Authentication/AuthenticationViewController.h
Riot/Modules/Authentication/AuthenticationViewController.m

Support Riot configuration link to customise HS and IS

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Riot/Modules/Common/ActivityIndicator/ActivityIndicatorPresenter.swift
Riot/Modules/ServiceTerms/Modal/ServiceTermsModalCoordinatorBridgePresenter.swift
Riot/Modules/Settings/Discovery/SettingsDiscoveryTableViewSection.swift
Riot/Modules/Settings/Discovery/SettingsDiscoveryViewAction.swift
Riot/Modules/Settings/Discovery/SettingsDiscoveryViewModel.swift
Riot/Modules/Settings/Discovery/SettingsDiscoveryViewModelType.swift
Riot/Modules/Settings/Discovery/SettingsDiscoveryViewState.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsCoordinator.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsCoordinatorBridgePresenter.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsCoordinatorType.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewAction.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewController.storyboard
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewController.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewModel.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewModelType.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewState.swift
Riot/Modules/Settings/SettingsViewController.m
Riot/SupportingFiles/Riot-Bridging-Header.h

#2606
Requires matrix-org/matrix-ios-sdk/pull/719

Settings: Add a Discovery section

---

Riot/Modules/Authentication/Views/AuthInputsView.m

Closes #2682
Only the registration has been updated. Adding a MSISDN from settings was already protected.

Send IS for adding MSISDNs only when required by HS

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Home/Fallback/AuthFallBackViewController.h
Riot/Modules/Home/Fallback/AuthFallBackViewController.m

Authentication: Improve the webview used for SSO

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Integrations/WidgetPicker/WidgetPickerViewController.m
Riot/Modules/Room/CellData/RoomBubbleCellData.h
Riot/Modules/Room/CellData/RoomBubbleCellData.m
Riot/Modules/Room/ContextualMenu/ContextualMenuItemView.swift
Riot/Modules/Room/ContextualMenu/RoomContextualMenuViewController.swift
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/Activities/RoomActivitiesView.m
Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.m

Fix some issues with VoiceOver

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Riot/Managers/Theme/Themes/DarkTheme.swift
Riot/Managers/Theme/Themes/DefaultTheme.swift
Riot/Modules/Authentication/Views/AuthInputsView.m
Riot/Modules/Common/ActivityIndicator/ActivityIndicatorPresenter.swift
Riot/Modules/Settings/Discovery/SettingsDiscoveryViewModel.swift
Riot/Modules/Settings/Discovery/ThreePidDetails/SettingsDiscoveryThreePidDetailsViewController.swift
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerCoordinator.swift
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerCoordinatorBridgePresenter.swift
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerCoordinatorType.swift
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewAction.swift
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewController.storyboard
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewController.swift
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewModel.swift
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewModelType.swift
Riot/Modules/Settings/IdentityServer/SettingsIdentityServerViewState.swift
Riot/Modules/Settings/SettingsViewController.m

Fixes #2604. 
Fixes #2649.
Fixes #2734.
Fixes #2736.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/724.
There is a TODO that will be managed after #2713.

Privacy: Add/Change/Remove IS from settings

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewController.swift
Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewModel.swift
Riot/Modules/ServiceTerms/Modal/Modal/ServiceTermsModalScreenViewModelType.swift

Add more context for the user.

Terms: Display the URL of the service

---

CHANGES.rst
Riot/Modules/Common/Recents/RecentsViewController.m

BF: Room cell: The states of direct chat and favorite buttons are reversed in the menu

---

CHANGES.rst
Riot/Modules/Room/EmojiPicker/EmojiPickerHeaderView.swift
Riot/Modules/Room/EmojiPicker/EmojiPickerViewCell.swift
Riot/Modules/Room/EmojiPicker/EmojiPickerViewController.swift

BF: Emoji Picker: Background color is not white

---

Riot/Modules/Room/RoomViewController.m

Fix #2687
Requires matrix-org/matrix-ios-kit/pull/625

BF: Timestamps are sometimes hidden by the overlay

---

CHANGES.rst
Riot/AppDelegate.m

Requires matrix-org/matrix-ios-kit/pull/627

Improve UIApplication background task management

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Serialization/SerializationService.swift
Riot/Managers/Serialization/SerializationServiceType.swift
Riot/Managers/Settings/Shared/JSONModels/RiotSettingAllowedWidgets.swift
Riot/Managers/Settings/Shared/RiotSharedSettings.swift
Riot/Modules/Integrations/IntegrationManagerViewController.m
Riot/Modules/Integrations/Widgets/WidgetViewController.m

Closes #2832
I left one TODO for the implementation of the final design (#2833).

Widgets: Check user permission before opening a widget (Data side)

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/Shared/JSONModels/RiotSettingIntegrationProvisioning.swift
Riot/Managers/Settings/Shared/RiotSharedSettings.swift
Riot/Managers/Widgets/WidgetManager.h
Riot/Managers/Widgets/WidgetManager.m
Riot/Modules/Integrations/IntegrationManagerViewController.m
Riot/Modules/Settings/SettingsViewController.m

Settings: Add an option for disabling use of the integration manager 

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Managers/Settings/Shared/JSONModels/RiotSettingAllowedWidgets.swift
Riot/Managers/Settings/Shared/RiotSharedSettings.swift
Riot/Modules/Integrations/Widgets/Jitsi/JitsiService.swift
Riot/Modules/Integrations/Widgets/Jitsi/JitsiViewController.m
Riot/Modules/Integrations/Widgets/WidgetViewController.m

Data part of #2842 
This PR also fixes data displayed in the jitsi conference screen.

Widgets: Check user permission before opening a widget (data part)

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Managers/RoomMessageLinkParser/RoomMessageURLParser.swift
Riot/Modules/Room/RoomViewController.m

Close #2803 and #2804 
Requires matrix-org/matrix-ios-kit/pull/633

BF: Tapping on location links gives 'unable to open link'

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Settings/SettingsViewController.m

ON/OFF Cross-signing development in a Lab setting

---

Riot/AppDelegate.m
Riot/Assets/en.lproj/Localizable.strings
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

#2852
Incoming request in foreground:

Verifications in DM: E2E Notices/Toast management

---

Riot/AppDelegate.m
Riot/Managers/OnBoarding/OnBoardingManager.swift
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/Contacts/Details/ContactDetailsViewController.m
Riot/Modules/StartChat/StartChatViewController.m

Required by https://github.com/matrix-org/matrix-ios-sdk/pull/768.

Room creation: Follow SDK changes

---

Riot/Modules/Room/Views/BubbleCells/Encryption/RoomEncryptedDataBubbleCell.m

Message decoration: Do not decorate state events

---

Riot/Modules/Room/DataSources/RoomDataSource.m

Commits can be read separately.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/771.
Fixes https://github.com/vector-im/riot-ios/issues/2956

Fix shields

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Categories/MXRoomSummary+Riot.h
Riot/Categories/MXRoomSummary+Riot.m
Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
Riot/Modules/Home/Views/RoomCollectionViewCell.m
Riot/Modules/Room/DataSources/RoomDataSource.h
Riot/Modules/Room/DataSources/RoomDataSource.m
RiotShareExtension/Modules/Share/Listing/Views/RecentRoomTableViewCell.m

Closes #2906.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/772

Room decoration: Use shields instead of padlocks

---

Riot/Modules/Common/Recents/Views/RecentTableViewCell.xib
Riot/Modules/Home/Views/RoomCollectionViewCell.xib

Room decoration: Make shields bigger

---

Riot/Modules/Settings/Security/ManageSession/ManageSessionViewController.m
Riot/Modules/UserVerification/SessionStatus/UserVerificationSessionStatusViewController.swift
Riot/Modules/UserVerification/UserVerificationCoordinator.swift
Riot/Modules/UserVerification/UserVerificationCoordinatorBridgePresenter.swift

Settings: Add session verification screens

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Modules/Settings/SettingsViewController.m

E2E: Do not warn anymore for unknown devices

---

Riot/Categories/MXRoom+Riot.h
Riot/Categories/MXRoom+Riot.m
Riot/Modules/Contacts/Views/ContactTableViewCell.h
Riot/Modules/Contacts/Views/ContactTableViewCell.m
Riot/Modules/Contacts/Views/ContactTableViewCell.xib
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m

Decoration: Display shields in room members list

---

Riot/Modules/Room/Views/BubbleCells/Encryption/RoomEncryptedDataBubbleCell.m

Message decoration: No shield by default

---

CHANGES.rst
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomEncryptedDataBubbleCell.h
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomEncryptedDataBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomIncomingEncryptedAttachmentBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomIncomingEncryptedAttachmentWithPaginationTitleBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomIncomingEncryptedAttachmentWithoutSenderInfoBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomOutgoingEncryptedAttachmentBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomOutgoingEncryptedAttachmentWithPaginationTitleBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/Encryption/RoomOutgoingEncryptedAttachmentWithoutSenderInfoBubbleCell.m
Riot/Modules/Room/Views/BubbleCells/RoomSelectedStickerBubbleCell.m

#2978 
Requires matrix-org/matrix-ios-kit/pull/642

Room decoration: Remove horizontal empty space when there is no decoration badge to set on room message

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift

Localization: Make sure "Session" replaces "Device" everywhere

---

Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/Security/SecurityViewController.m

Settings > Security: Missing loading state for getting devices

---

Riot/AppDelegate.m
Riot/Modules/DeviceVerification/DeviceVerificationCoordinator.swift
Riot/Modules/DeviceVerification/Loading/DeviceVerificationDataLoadingCoordinator.swift
Riot/Modules/DeviceVerification/Loading/DeviceVerificationDataLoadingViewModel.swift

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/781
Note: There is some TODOs where to insert the code that will manage choice between QR code & emoji.

Key Verification: Support m.key.verification.ready event with new SDK API

---

CHANGES.rst
Riot/Managers/Widgets/WidgetManager.m

Fix crash due to malformed widget

---

CHANGES.rst
Riot/AppDelegate.m

This may fix vector-im/riot-ios#3017.

Push notifications: Avoid any automatic deactivation

---

Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift

#3040
The screen was stuck on the request step in case of self verification (to_device events)

BF: Self verification is broken

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartCoordinator.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartCoordinatorType.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewAction.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewController.storyboard
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewController.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewModel.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewModelType.swift
Riot/Modules/KeyVerification/Device/SelfVerifyStart/KeyVerificationSelfVerifyStartViewState.swift
Riot/Modules/KeyVerification/User/Start/UserVerificationStartCoordinator.swift
Riot/Modules/KeyVerification/User/Start/UserVerificationStartCoordinatorType.swift
Riot/Modules/KeyVerification/User/Start/UserVerificationStartViewModelType.swift

Cross-Signing: Detect and expose new sign-ins

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinatorBridgePresenter.swift
Riot/Modules/KeyVerification/Common/KeyVerificationFlow.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinator.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinatorType.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewAction.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.storyboard
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModelType.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewState.swift
Riot/Modules/KeyVerification/User/UserVerificationCoordinator.swift

Cross-signing: Complete security at the end of sign in process

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Model/Room/RoomPowerLevel.swift
Riot/Modules/Communities/Members/GroupParticipantsViewController.m
Riot/Modules/Contacts/Views/ContactTableViewCell.h
Riot/Modules/Contacts/Views/ContactTableViewCell.m
Riot/Modules/Contacts/Views/ContactTableViewCell.xib
Riot/Modules/Home/Views/RoomCollectionViewCell.m
Riot/Modules/Home/Views/RoomCollectionViewCell.xib
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.xib
Riot/Modules/Room/Members/Detail/Views/RoomMemberTitleView.h
Riot/Modules/Room/Members/Detail/Views/RoomMemberTitleView.xib
Riot/Modules/Room/Members/RoomParticipantsViewController.m
Riot/Modules/Room/RoomViewController.m
Riot/Modules/Room/Views/Title/Expanded/ExpandedRoomTitleView.xib
Riot/Modules/Room/Views/Title/RoomTitleView.h
Riot/Modules/Room/Views/Title/RoomTitleView.m
Riot/Modules/Room/Views/Title/RoomTitleView.xib
Riot/Utils/EncryptionTrustLevelBadgeImageHelper.swift

Make decoration uniform

---

Riot.xcodeproj/project.pbxproj
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Storyboards.swift
Riot/Generated/Strings.swift
Riot/Modules/KeyBackup/Recover/KeyBackupRecoverCoordinator.swift
Riot/Modules/KeyBackup/Recover/Loading/KeyBackupRecoverDataLoadingViewModelType.swift
Riot/Modules/KeyBackup/Recover/PrivateKey/KeyBackupRecoverFromPrivateKeyCoordinator.swift
Riot/Modules/KeyBackup/Recover/PrivateKey/KeyBackupRecoverFromPrivateKeyCoordinatorType.swift
Riot/Modules/KeyBackup/Recover/PrivateKey/KeyBackupRecoverFromPrivateKeyViewAction.swift
Riot/Modules/KeyBackup/Recover/PrivateKey/KeyBackupRecoverFromPrivateKeyViewController.storyboard
Riot/Modules/KeyBackup/Recover/PrivateKey/KeyBackupRecoverFromPrivateKeyViewController.swift
Riot/Modules/KeyBackup/Recover/PrivateKey/KeyBackupRecoverFromPrivateKeyViewModel.swift
Riot/Modules/KeyBackup/Recover/PrivateKey/KeyBackupRecoverFromPrivateKeyViewModelType.swift
Riot/Modules/KeyBackup/Recover/PrivateKey/KeyBackupRecoverFromPrivateKeyViewState.swift
Riot/Modules/KeyBackup/Recover/Success/KeyBackupRecoverSuccessViewController.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinator.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorBridgePresenter.swift
Tools/Templates/buildable/FlowCoordinatorTemplate/FlowTemplateCoordinatorType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinator.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenCoordinatorType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewAction.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewController.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModel.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewModelType.swift
Tools/Templates/buildable/ScreenTemplate/TemplateScreenViewState.swift
Tools/Templates/buildable/SimpleScreenTemplate/SimpleScreenTemplateViewController.swift

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/816
Fixes #3053

Key Backup: Use private key if we have it

---

Riot/AppDelegate.m
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/EncryptionInfo/EncryptionInfoView.m
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinatorBridgePresenter.swift
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinatorType.swift
Riot/Modules/KeyVerification/User/UserVerificationCoordinator.swift
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Riot/Modules/RoomKeyRequest/RoomKeyRequestViewController.m
Riot/Modules/UserDevices/UsersDevicesViewController.m

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/820
Fixes #3089

New Sign-in: Do not send key requests before completing the "security"

---

Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Managers/Settings/RiotSettings.swift
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m
Riot/Modules/Settings/SettingsViewController.m

Fixes https://github.com/vector-im/riot-ios/issues/3103

Remove LABS > Enable Cross-signing

---

Riot/Categories/MXRoom+Riot.h
Riot/Categories/MXRoom+Riot.m
Riot/Modules/Contacts/Views/ContactTableViewCell.m
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m

Badges: Make Riot build again

---

Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
Riot/Modules/QRCode/Reader/QRCodeReaderViewController.swift

BF: Self-verification: Crash after scanning with success

---

Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewAction.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewController.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewModel.swift
Riot/Modules/KeyVerification/Common/Verify/Scanning/KeyVerificationVerifyByScanningViewState.swift

QR code verification: Remove other scan my code alert

---

CHANGES.rst
Riot/AppDelegate.m
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/SupportingFiles/Info.plist
RiotShareExtension/SupportingFiles/Info.plist
SiriIntents/Info.plist

Fixes #3139.
The copy is similar in web and in iOS:

Cross-signing: Allow incoming device verification request from other user

---

Riot/AppDelegate.h
Riot/AppDelegate.m
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Authentication/AuthenticationViewController.m
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift
Riot/Modules/KeyVerification/Common/KeyVerificationCoordinatorBridgePresenter.swift
Riot/Modules/KeyVerification/Common/KeyVerificationFlow.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinator.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewController.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewState.swift
Riot/Modules/Room/Members/Detail/RoomMemberDetailsViewController.m

RoomMemberDetailsViewController: For current user present complete security when device is not trusted

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/Security/SecurityViewController.m

BF: Settings - Security: My device is not trusted

---

CHANGES.rst
Riot.xcodeproj/project.pbxproj
Riot/Managers/Widgets/JSONModels/JitsiWidgetData.h
Riot/Managers/Widgets/JSONModels/JitsiWidgetData.m
Riot/Managers/Widgets/WidgetManager.h
Riot/Managers/Widgets/WidgetManager.m
Riot/Modules/Integrations/WidgetPicker/WidgetPickerViewController.m
Riot/Modules/Integrations/Widgets/Jitsi/JitsiViewController.m
Riot/Modules/Room/DataSources/RoomDataSource.m
Riot/Modules/Room/RoomViewController.m
Riot/Utils/EventFormatter.m

This allows to use any Jitsi server 
Fix #3150.
Commits can be reviewed one by one.

Make Jitsi widgets compatible with Matrix Widget API v2

---

CHANGES.rst
Riot/Assets/en.lproj/Vector.strings
Riot/Generated/Strings.swift
Riot/Modules/Settings/Security/SecurityViewController.m

Security settings: Do not ask to complete security if there is no cross-signing
